// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Chapter Tactics", text: "When selecting your kill team, select a primary and secondary CHAPTER TACTIC for friendly ANGEL OF DEATH operatives to gain for the battle. Multiple instances of the same CHAPTER TACTIC aren’t cumulative.\nDesigner’s Note: If you’re playing a series of games, i.e. a campaign or tournament, you must select the same primary and secondary CHAPTER TACTIC for every battle (you can still change the secondary with the Adaptive Tactics strategy ploy)." },
  { kind: 'faction', name: "Chapter Tactics 1. Aggressive", text: "This operative’s melee weapons have the Rending weapon rule.\n2. DUELLER Whenever this operative is fighting or retaliating, each of your normal successes can block one unresolved critical success (unless the enemy operative’s weapon has the Brutal weapon rule).\n3. RESOLUTE You can ignore any changes to this operative’s APL stat and it isn’t affected by enemy operatives’ Shock weapon rule." },
  { kind: 'faction', name: "Astartes", text: "During each friendly ANGEL OF DEATH operative’s activation, it can perform either two Shoot actions or two Fight actions. If it’s two Shoot actions, a bolt weapon must be selected for at least one of them, and if it’s a bolt sniper rifle or heavy bolter, 1 additional AP must be spent for the second action if both actions are using that weapon.\nEach friendly ANGEL OF DEATH operative can counteract regardless of its order." },
  { kind: 'strategy', name: "Combat Doctrine", text: "Select one COMBAT DOCTRINE from those presented below. Whenever a friendly ANGEL OF DEATH operative is x, its weapons have the Balanced weapon rule. X is the COMBAT DOCTRINE you selected.\n• Devastator Doctrine: Shooting an operative more than 6\" from it.\n• Tactical Doctrine: Shooting an operative within 6\" of it.\n• Assault Doctrine: Fighting or retaliating." },
  { kind: 'strategy', name: "And They Shall Know No Fear", text: "You can ignore any changes to the stats of friendly ANGEL OF DEATH operatives from being injured (including their weapons’ stats)." },
  { kind: 'strategy', name: "Indomitus", text: "Whenever an operative is shooting a friendly ANGEL OF DEATH operative, if you roll two or more fails, you can discard one of them to retain another as a normal success instead." },
  { kind: 'strategy', name: "Adaptive Tactics", text: "Change your secondary CHAPTER TACTIC. Note this ploy only lasts until the end of the turning point, at which point your original secondary CHAPTER TACTIC returns." },
  { kind: 'firefight', name: "Adjust Doctrine", text: "Use this firefight ploy during a friendly ANGEL OF DEATH operative’s activation, before or after it performs an action. If you’ve used the Combat Doctrine strategy ploy during this turning point, change the COMBAT DOCTRINE you selected." },
  { kind: 'firefight', name: "Transhuman Physiology", text: "Use this firefight ploy when an operative is shooting a friendly ANGEL OF DEATH operative, in the Roll Defence Dice step. You can retain one of your normal successes as a critical success instead." },
  { kind: 'firefight', name: "Wrath of Vengeance", text: "Use this firefight ploy when a friendly ANGEL OF DEATH operative is counteracting. It can perform an additional 1AP action for free during that counteraction, but both actions must be different." },
  { kind: 'firefight', name: "Shock Assault", text: "Use this firefight ploy when a friendly ANGEL OF DEATH operative is performing the Fight action during an activation in which it performed the Charge action, at the start of the Resolve Attack Dice step. Until the end of that action:\n• Its melee weapon has the Shock weapon rule.\n• The first time you strike during that sequence, inflict 1 additional damage (to a maximum of 7)." },
  { kind: 'equipment', name: "Purity Seals", text: "Once per turning point, when a friendly ANGEL OF DEATH operative is shooting, fighting or retaliating, if you roll two or more fails, you can discard one of them to retain another as a normal success instead." },
  { kind: 'equipment', name: "Chapter Reliquaries", text: "You can use the Wrath of Vengeance firefight ploy for 0CP if the specified friendly operative has an Engage order." },
  { kind: 'equipment', name: "Auspex", text: "Once per turning point, when a friendly ANGEL OF DEATH operative performs the Shoot action and you’re selecting a valid target, you can use this rule. If you do, until the end of the activation/ counteraction, enemy operatives within 8\" of that friendly operative cannot be obscured." },
  { kind: 'equipment', name: "Tilting Shields", text: "Once per turning point, when a friendly ANGEL OF DEATH operative is fighting or retaliating, after your opponent rolls their attack dice, but before re-rolls, you can use this rule. If you do, your opponent cannot retain attack dice results of less than 6 as critical successes during that sequence (e.g. as a result of the Lethal, Rending or Severe weapon rules).\nNOTES:" },
]

export const operatives: Operative[] = [
  { id: "aod:space-marine-captain", name: "Space Marine Captain", apl: 3, move: "6\"", save: "3+", w: 15 },
  { id: "aod:assault-intercessor-sergeant", name: "Assault Intercessor Sergeant", apl: 3, move: "6\"", save: "3+", w: 15 },
  { id: "aod:intercessor-sergeant", name: "Intercessor Sergeant", apl: 3, move: "6\"", save: "3+", w: 15 },
  { id: "aod:assault-intercessor-grenadier", name: "Assault Intercessor Grenadier", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "aod:assault-intercessor-warrior", name: "Assault Intercessor Warrior", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "aod:heavy-intercessor-gunner", name: "Heavy Intercessor Gunner", apl: 3, move: "5\"", save: "3+", w: 18 },
  { id: "aod:intercessor-gunner", name: "Intercessor Gunner", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "aod:intercessor-warrior", name: "Intercessor Warrior", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "aod:eliminator-sniper", name: "Eliminator Sniper", apl: 3, move: "7\"", save: "3+", w: 12 },
]

export const datacards: Datacard[] = [
  {"name": "Space Marine Captain", "weapons": [{"name": "Plasma pistol (standard)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Piercing 1"}, {"name": "Plasma pistol (supercharge)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Hot, Lethal 5+, Piercing 1"}, {"name": "Power fist", "atk": 5, "hit": "3+", "dmg": "5/7", "wr": "Brutal"}], "abilities": [{"name": "Heroic Leader", "text": "Once per turning point, you can do one of the following:\n• Use a firefight ploy for 0CP if this is the specified ANGEL OF DEATH operative (excluding Command Re-roll). • Use the Combat Doctrine strategy ploy when you activate a friendly ANGEL OF DEATH operative if this operative is in the killzone and isn’t within control range of enemy operatives (pay its CP cost as normal). Note that you cannot do so if you’ve already used that ploy during this turning point. • Use the Adjust Doctrine firefight ploy for 0CP if this operative is in the killzone and isn’t within control range of enemy operatives."}, {"name": "Iron Halo", "text": "Once per battle, when an attack dice inflicts Normal Dmg on this operative, you can ignore that inflicted damage."}], "actions": [], "keywords": ["ANGEL OF DEATH", "IMPERIUM", "ADEPTUS ASTARTES", "LEADER", "SPACE MARINE CAPTAIN"], "img": "/ops/aod/space-marine-captain.webp"},
  {"name": "Assault Intercessor Sergeant", "weapons": [{"name": "Hand flamer", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 6\", Saturate, Torrent 1\""}, {"name": "Heavy bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Piercing Crits 1"}, {"name": "Plasma pistol (standard)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Piercing 1"}, {"name": "Plasma pistol (supercharge)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Hot, Lethal 5+, Piercing 1"}, {"name": "Chainsword", "atk": 5, "hit": "3+", "dmg": "4/5"}, {"name": "Power fist", "atk": 5, "hit": "4+", "dmg": "5/7", "wr": "Brutal"}, {"name": "Power weapon", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}, {"name": "Thunder hammer", "atk": 5, "hit": "4+", "dmg": "5/6", "wr": "Shock, Stun"}], "abilities": [{"name": "Doctrine Warfare", "text": "You can do each of the following once per battle:\n• Whenever you would use the Combat Doctrine strategy ploy and then select Assault, if this operative is in the killzone, it costs you 0CP. • Whenever you would use the Combat Doctrine strategy ploy and then select Tactical, if this operative is in the killzone, it costs you 0CP."}, {"name": "Chapter Veteran", "text": "At the end of the Select Operatives step, if this operative is selected for deployment, select one additional CHAPTER TACTIC for it to have for the battle. Unlike primary and secondary CHAPTER TACTICS, you don’t have to select the same one for each battle in a campaign or tournament."}], "actions": [], "keywords": ["ANGEL OF DEATH", "IMPERIUM", "ADEPTUS ASTARTES", "LEADER", "ASSAULT INTERCESSOR", "SERGEANT"], "img": "/ops/aod/assault-intercessor-sergeant.webp"},
  {"name": "Intercessor Sergeant", "weapons": [{"name": "Auto bolt rifle", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Torrent 1\""}, {"name": "Bolt rifle", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Piercing Crits 1"}, {"name": "Stalker bolt rifle (heavy)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Heavy (Dash only), Lethal 5+, Piercing Crits 1"}, {"name": "Stalker bolt rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Chainsword", "atk": 4, "hit": "3+", "dmg": "4/5"}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Power fist", "atk": 4, "hit": "4+", "dmg": "5/7", "wr": "Brutal"}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}, {"name": "Thunder hammer", "atk": 4, "hit": "4+", "dmg": "5/6", "wr": "Shock, Stun"}], "abilities": [{"name": "Doctrine Warfare", "text": "You can do each of the following once per battle:\n• Whenever you would use the Combat Doctrine strategy ploy and then select Devastator, if this operative is in the killzone, it costs you 0CP. • Whenever you would use the Combat Doctrine strategy ploy and then select Tactical, if this operative is in the killzone, it costs you 0CP."}, {"name": "Chapter Veteran", "text": "At the end of the Select Operatives step, if this operative is selected for deployment, select one additional CHAPTER TACTIC for it to have for the battle. Unlike primary and secondary CHAPTER TACTICS, you don’t have to select the same one for each battle in a campaign or tournament."}], "actions": [], "keywords": ["ANGEL OF DEATH", "IMPERIUM", "APEPTUS ASTARTES", "LEADER", "INTERCESSOR", "SERGEANT"], "img": "/ops/aod/intercessor-sergeant.webp"},
  {"name": "Assault Intercessor Grenadier", "weapons": [{"name": "Heavy bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Piercing Crits 1"}, {"name": "Chainsword", "atk": 5, "hit": "3+", "dmg": "4/5"}], "abilities": [{"name": "Grenadier", "text": "This operative can use frag and krak grenades (see universal equipment). Doing so doesn’t count towards any limited uses you have (i.e. if you also select those grenades from equipment for other operatives). Whenever it’s doing so, improve the Hit stat of that weapon by 1."}], "actions": [], "keywords": ["ANGEL OF DEATH", "IMPERIUM", "ADEPTUS ASTARTES", "ASSAULT INTERCESSOR", "GRENADIER"], "img": "/ops/aod/assault-intercessor-grenadier.webp"},
  {"name": "Assault Intercessor Warrior", "weapons": [{"name": "Heavy bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Piercing Crits 1"}, {"name": "Chainsword", "atk": 5, "hit": "3+", "dmg": "4/5"}], "abilities": [], "actions": [], "keywords": ["ANGEL OF DEATH", "IMPERIUM", "ADEPTUS ASTARTES", "ASSAULT INTERCESSOR", "WARRIOR"], "img": "/ops/aod/assault-intercessor-warrior.webp"},
  {"name": "Heavy Intercessor Gunner", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Heavy bolter (focused)", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Piercing Crits 1"}, {"name": "Heavy bolter (sweeping)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Piercing Crits 1, Torrent 1\""}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["ANGEL OF DEATH", "IMPERIUM", "ADEPTUS ASTARTES", "HEAVY INTERCESSOR", "GUNNER"], "img": "/ops/aod/heavy-intercessor-gunner.webp"},
  {"name": "Intercessor Gunner", "weapons": [{"name": "Auto bolt rifle", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Torrent 1\""}, {"name": "Auxiliary grenade launcher (frag)", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Blast 2\""}, {"name": "Auxiliary grenade launcher (krak)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Piercing 1"}, {"name": "Bolt rifle", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Piercing Crits 1"}, {"name": "Stalker bolt rifle (heavy)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Heavy (Dash only), Lethal 5+, Piercing Crits 1"}, {"name": "Stalker bolt rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["ANGEL OF DEATH", "IMPERIUM", "ADEPTUS ASTARTES", "INTERCESSOR", "GUNNER"], "img": "/ops/aod/intercessor-gunner.webp"},
  {"name": "Intercessor Warrior", "weapons": [{"name": "Auto bolt rifle", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Torrent 1\""}, {"name": "Bolt rifle", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Piercing Crits 1"}, {"name": "Stalker bolt rifle (heavy)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Heavy (Dash only), Lethal 5+, Piercing Crits 1"}, {"name": "Stalker bolt rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["ANGEL OF DEATH", "IMPERIUM", "ADEPTUS ASTARTES", "INTERCESSOR", "WARRIOR"], "img": "/ops/aod/intercessor-warrior.webp"},
  {"name": "Eliminator Sniper", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Bolt sniper rifle (executioner)", "atk": 4, "hit": "2+", "dmg": "3/4", "wr": "Heavy (Dash only), Saturate, Seek Light, Silent"}, {"name": "Bolt sniper rifle (hyperfrag)", "atk": 4, "hit": "2+", "dmg": "2/4", "wr": "Blast 1\", Heavy (Dash only), Silent"}, {"name": "Bolt sniper rifle (mortis)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy (Dash only), Piercing 1, Silent"}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [{"name": "Camo Cloak", "text": "Whenever an operative is shooting this operative, ignore the Saturate weapon rule. This operative has the Stealthy\nCHAPTER TACTIC. If you selected that CHAPTER TACTIC,\nyou can do both of its options (i.e. retain two cover saves – one normal and one critical success)."}], "actions": [{"name": "Optics", "ap": 1, "text": "Until the start of this operative’s next activation, whenever\nit’s shooting, enemy operatives cannot be obscured.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["ANGEL OF DEATH", "IMPERIUM", "ADEPTUS ASTARTES", "ELIMINATOR", "SNIPER"], "img": "/ops/aod/eliminator-sniper.webp"},
]
