// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Noospheric Network", text: "Once during each friendly BATTLECLADE SERVITOR operative’s activation, before or after it performs an action, you can spend 1AP to TRANSFER POWER. After that activation, you can NETWORK COUNTERACT with one other friendly BATTLECLADE SERVITOR operative before your opponent activates. Whenever you NETWORK COUNTERACT with a friendly operative, first select its order. It can then perform a 1AP action for free, but cannot move more than 2\" during that action. Once it’s done so, your opponent then activates as normal." },
  { kind: 'strategy', name: "Duty of Reclamation", text: "Once per action, you can use the Command Re- roll firefight ploy for 0CP if the attack or defence dice was rolled for a friendly BATTLECLADE operative that contests an objective marker or one of your mission markers." },
  { kind: 'strategy', name: "Noospheric Possession", text: "SUPPORT. Whenever a friendly BATTLECLADE SERVITOR operative is within 6\" of a friendly BATTLECLADE AUTO-PROXY or BATTLECLADE SERVITOR UNDERSEER operative, that friendly SERVITOR operative’s weapons have the Accurate 1 weapon rule. For the purposes of the Comms Device universal equipment, the operative the distance is being determined from must control your Comms Device marker to add 3\" to its distance requirement for this rule." },
  { kind: 'strategy', name: "Incantation of the Iron Soul", text: "Whenever an attack dice inflicts damage of 3 or more on a friendly BATTLECLADE operative, roll one D6: on a 4+, subtract 1 from that inflicted damage." },
  { kind: 'strategy', name: "Prioritised Acquisition", text: "Select one objective marker or one of your mission markers.\n• Whenever determining control of that marker, treat the total APL stat of friendly\nBATTLECLADE operatives that contest it as 1 higher if at least one friendly BATTLECLADE operative contests that marker. Note this isn’t a change to the APL stat, so any changes are cumulative with this.\n• Whenever a friendly BATTLECLADE operative is within 3\" of that marker, add 1 to the Atk stat of its melee weapons (to a maximum of 4)." },
  { kind: 'firefight', name: "Remote Access", text: "Use this firefight ploy during a friendly BATTLECLADE TECH-PRIEST operative’s activation. Once during that activation, you can use one of the following rules:\n• That operative doesn’t require a marker to be within its control range to perform a mission action that usually requires this (this takes precedence over that action’s conditions). Instead, the marker must be within 4\" of it and no enemy operatives can contest that marker. However, you can ignore enemy operatives within control range of other friendly BATTLECLADE operatives when determining this.\n• That operative doesn’t require a hatchway’s access point to be within its control range to perform an Operate Hatch action. Instead, that access point must be within 4\" of it." },
  { kind: 'firefight', name: "System Exorcism", text: "Use this firefight ploy when you would activate a friendly BATTLECLADE operative. Remove one rules effect or stat change your opponent has applied to it (e.g. Poison token, -1APL, cannot be activated or perform actions, etc.), then activate it. This ploy cannot allow it to regain lost wounds, ignore the effects of being injured or remove mission pack rules." },
  { kind: 'firefight', name: "Auto-ferric Supplication", text: "Use this firefight ploy when an operative is shooting a friendly BATTLECLADE TECH-PRIEST operative, at the start of the Roll Attack Dice step. Until the end of the sequence, ignore the Piercing weapon rule." },
  { kind: 'firefight', name: "Servile Surrogacy", text: "Use this firefight ploy when a friendly BATTLECLADE TECH-PRIEST operative is selected as the valid target of a Shoot action or to fight against during the Fight action. Select one friendly BATTLECLADE SERVITOR operative visible to and within 3\" of that first friendly operative to become the valid target or to be fought against (as appropriate) instead (even if it wouldn’t normally be valid for this). If it’s the Fight action, treat that SERVITOR operative as being within the fighting operative’s control range for the duration of that action. If it’s the Shoot action, that SERVITOR operative is only in cover or obscured if the original target was. This ploy has no effect if it’s the Shoot action and the ranged weapon has the Blast or Torrent weapon rule." },
  { kind: 'equipment', name: "Electromantic Capacitors", text: "Friendly BATTLECLADE operatives’ melee weapons have the Shock weapon rule. Whenever a friendly BATTLECLADE operative is retaliating, its melee weapons also have the Severe weapon rule." },
  { kind: 'equipment', name: "Covert Guises", text: "After revealing this equipment option, roll one D3. As a STRATEGIC GAMBIT in the first turning point, a number of friendly BATTLECLADE operatives equal to the result that are wholly within your drop zone can immediately perform a free Reposition action, but must end that move wholly within 3\" of your drop zone. Your TECHNOARCHEOLOGIST operative cannot perform more than one Reposition action in the Strategy phase of the first turning point (i.e. as a result of the Seeker of Divine Arcana rule as well)." },
  { kind: 'equipment', name: "Concealed Apparatus", text: "Once per battle, one COMBAT SERVITOR or\nGUN SERVITOR operative can use another weapon option on its datacard it didn’t select for the battle." },
  { kind: 'equipment', name: "Neurocyclic Reserve Cells", text: "Once per turning point, whenever you TRANSFER POWER, you can use this rule. If you do, you can TRANSFER POWER for 0AP (this takes precedence over the normal Noospheric Network rules)." },
]

export const operatives: Operative[] = [
  { id: "battleclade:battleclade-technoarcheologist", name: "Battleclade Technoarcheologist", apl: 3, move: "6\"", save: "3+", w: 9 },
  { id: "battleclade:battleclade-auto-proxy-servitor", name: "Battleclade Auto-proxy Servitor", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "battleclade:battleclade-breacher-servitor", name: "Battleclade Breacher Servitor", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "battleclade:battleclade-combat-servitor", name: "Battleclade Combat Servitor", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "battleclade:battleclade-gun-servitor", name: "Battleclade Gun Servitor", apl: 2, move: "5\"", save: "4+", w: 11 },
  { id: "battleclade:battleclade-servitor-underseer", name: "Battleclade Servitor Underseer", apl: 3, move: "6\"", save: "3+", w: 9 },
  { id: "battleclade:battleclade-technomedic-servitor", name: "Battleclade Technomedic Servitor", apl: 2, move: "5\"", save: "4+", w: 8 },
]

export const datacards: Datacard[] = [
  {"name": "Battleclade Technoarcheologist", "weapons": [{"name": "Eradication pistol", "atk": 4, "hit": "3+", "dmg": "4/2", "wr": "Range 8\", 1\" Devastating 3, Lethal 5+"}, {"name": "Servo-arc claw", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Severe, Shock"}], "abilities": [{"name": "Seeker of Divine Arcana", "text": "STRATEGIC GAMBIT. You can immediately change this operative’s order and/or it can\nimmediately perform a free Omniscanner, Fall Back, Place\nMarker, Pick Up Marker, Reposition or mission action.\nIf it’s the Fall Back or Reposition action and this operative\nisn’t carrying a marker, it must end that move either within your\ndrop zone (if this isn’t possible, then as close as possible to it), or\nwith an objective marker or one of your mission markers within its control range."}], "actions": [{"name": "Omniscanner", "ap": 1, "text": "Select one enemy operative visible to or within 8\" of this\noperative to gain one of your Omniscanner tokens. Whenever\na friendly BATTLECLADE operative is shooting against,\nfighting against or retaliating against an enemy operative that\nhas one of your Omniscanner tokens, that friendly operative’s\nweapons have the Ceaseless weapon rule.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["BATTLECLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "TECH-PRIEST", "LEADER", "TECHNOARCHEOLOGIST"], "img": "/ops/battleclade/battleclade-technoarcheologist.webp"},
  {"name": "Battleclade Auto-proxy Servitor", "weapons": [{"name": "Taser goad", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Lethal 5+, Shock"}], "abilities": [{"name": "Achillan Eye", "text": "Whenever a friendly BATTLECLADE operative is\nshooting an enemy operative visible to\nthis operative, that friendly operative’s\nranged weapons have the Saturate weapon rule. This rule has no effect if this operative is within control range of an enemy operative."}], "actions": [{"name": "Gaze of the Omnissiah", "ap": 1, "text": "Select one enemy operative visible to this operative. Until the end of the turning\npoint, whenever a friendly BATTLECLADE operative is shooting that enemy\noperative, you can use this effect. If you do:\n• That friendly operative’s ranged weapons have the Seek Light weapon rule. • That enemy operative cannot be obscured.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["BATTLECLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "AUTO-PROXY", "SERVITOR"], "img": "/ops/battleclade/battleclade-auto-proxy-servitor.webp"},
  {"name": "Battleclade Breacher Servitor", "weapons": [{"name": "Lascutter (close range)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 2\", Lethal 5+, Piercing 2"}, {"name": "Lascutter (short range)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 6\", Lethal 5+"}, {"name": "Hydraulic pincer & lascutter", "atk": 4, "hit": "4+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [], "actions": [{"name": "Breach", "ap": 1, "text": "Place one of your Breach markers within this operative’s                 This operative cannot perform this action while within control control range as close as possible to a terrain feature within           range of an enemy operative, or if a terrain feature isn’t control range of it. Whenever an operative is within 1\" of that          within its control range. marker, it treats parts of that terrain feature that are no more than 1\" thick as Accessible terrain."}], "keywords": ["BATTLECLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "BREACHER", "SERVITOR"], "img": "/ops/battleclade/battleclade-breacher-servitor.webp"},
  {"name": "Battleclade Combat Servitor", "weapons": [{"name": "Incendine igniter", "atk": 4, "hit": "2+", "dmg": "4/4", "wr": "Range 6\", Saturate, Torrent 1\""}, {"name": "Meltagun", "atk": 4, "hit": "4+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Phosphor blaster", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Blast 1\", Severe"}, {"name": "Servo-claw", "atk": 3, "hit": "4+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["BATTLECLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "COMBAT", "SERVITOR"], "img": "/ops/battleclade/battleclade-combat-servitor.webp"},
  {"name": "Battleclade Gun Servitor", "weapons": [{"name": "Heavy arc rifle", "atk": 5, "hit": "4+", "dmg": "4/6", "wr": "Heavy (Dash only), Piercing 1, Stun"}, {"name": "Heavy bolter (focused)", "atk": 5, "hit": "4+", "dmg": "4/5", "wr": "Heavy (Dash only), Piercing Crits 1"}, {"name": "Heavy bolter (sweeping)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Heavy (Dash only), Piercing Crits 1, Torrent 1\""}, {"name": "Augmetic claw", "atk": 3, "hit": "4+", "dmg": "4/5", "wr": "Brutal"}], "abilities": [], "actions": [], "keywords": ["BATTLECLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "GUN", "SERVITOR"], "img": "/ops/battleclade/battleclade-gun-servitor.webp"},
  {"name": "Battleclade Servitor Underseer", "weapons": [{"name": "Master-crafted radium pistol", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Range 8\", Balanced, Rending"}, {"name": "Dataspikes", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [], "actions": [{"name": "Datacoronal Accumulator", "ap": 1, "text": "SUPPORT. Determine the friendly BATTLECLADE operatives within 6\" of this operative and/or a friendly BATTLECLADE AUTO-PROXY operative, then roll one D3. If the result is equal to or less than the number of objective markers those friendly operatives contest, you gain 1CP. For the purposes of the Comms Device universal equipment, the operative the distance is being determined from must control your Comms Device marker to add 3\" to its distance requirement for this rule.\nThis operative cannot perform this action while within control range of an enemy operative."}, {"name": "Network Override", "ap": 1, "text": "SUPPORT. Select one friendly BATTLECLADE SERVITOR operative within 6\" of either this operative or a friendly BATTLECLADE AUTO-PROXY operative to immediately NETWORK COUNTERACT (you don’t have to TRANSFER POWER to do so) or perform a free Dash action. Continue this operative’s activation after doing so. For the purposes of the Comms Device universal equipment, the operative the distance is being determined from must control that marker.\nThis operative can perform this action twice during its activation, but it must select a different friendly operative each time and it cannot perform this action while within control range of an enemy operative."}], "keywords": ["BATTLECLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "TECH-PRIEST", "SERVITOR UNDERSEER"], "img": "/ops/battleclade/battleclade-servitor-underseer.webp"},
  {"name": "Battleclade Technomedic Servitor", "weapons": [{"name": "Servo-chirurgic claw", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Rending"}], "abilities": [{"name": "Mechanosuture Array", "text": "Once per turning point, when another friendly BATTLECLADE operative would be incapacitated while visible to and within 3\" of this operative, you can use this rule, providing neither this nor that operative is within control range of an enemy operative. If you do, that friendly operative isn’t incapacitated, has 1 wound remaining and cannot be incapacitated for the remainder of the action. After that action, that friendly operative can immediately perform a free Dash action, but must end that move within this operative’s control range. If this rule was used during that friendly operative’s activation, that activation ends. You cannot use this rule if this operative is incapacitated, or if it’s a Shoot action and this operative would be a primary or secondary target."}], "actions": [{"name": "Expedient Repair", "ap": 1, "text": "Select one friendly BATTLECLADE operative within this operative’s control range to regain up to D3+3 lost wounds. It cannot be an operative that the Mechanosuture Array rule was used on during this turning point.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["BATTLECLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "MEDIC", "TECHNOMEDIC", "SERVITOR"], "img": "/ops/battleclade/battleclade-technomedic-servitor.webp"},
]
