// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Noospheric Network", text: "Once during each friendly BATTLECLADE SERVITOR operative’s activation, before or after it performs an action, you can spend 1AP to TRANSFER POWER. After that activation, you can NETWORK COUNTERACT with one other friendly BATTLECLADE SERVITOR operative before your opponent activates. Whenever you NETWORK COUNTERACT with a friendly operative, first select its order. It can then perform a 1AP action for free, but cannot move more than 2\" during that action. Once it’s done so, your opponent then activates as normal." },
  { kind: 'strategy', name: "Duty of Reclamation", text: "Once per action, you can use the Command Re- roll firefight ploy for 0CP if the attack or defence dice was rolled for a friendly BATTLECLADE operative that contests an objective marker or one of your mission markers." },
  { kind: 'strategy', name: "Noospheric Possession", text: "SUPPORT. Whenever a friendly BATTLECLADE SERVITOR operative is within 6\" of a friendly BATTLECLADE AUTO-PROXY or BATTLECLADE SERVITOR UNDERSEER operative, that friendly SERVITOR operative’s weapons have the Accurate 1 weapon rule. For the purposes of the Comms Device universal equipment, the operative the distance is being determined from must control your Comms Device marker to add 3\" to its distance requirement for this rule." },
  { kind: 'strategy', name: "Incantation of the Iron Soul", text: "Whenever an attack dice inflicts damage of 3 or more on a friendly BATTLECLADE operative, roll one D6: on a 4+, subtract 1 from that inflicted damage." },
  { kind: 'strategy', name: "Prioritised Acquisition", text: "Select one objective marker or one of your mission markers.\n• Whenever determining control of that marker, treat the total APL stat of friendly\nBATTLECLADE operatives that contest it as 1 higher if at least one friendly BATTLECLADE operative contests that marker. Note this isn’t a change to the APL stat, so any changes are cumulative with this.\n• Whenever a friendly BATTLECLADE operative is within 3\" of that marker, add 1 to the Atk stat of its melee weapons (to a maximum of 4)." },
  { kind: 'firefight', name: "Remote Access", text: "Use this firefight ploy during a friendly BATTLECLADE TECH-PRIEST operative’s activation. Once during that activation, you can use one of the following rules:\n• That operative doesn’t require a marker to be within its control range to perform a mission action that usually requires this (this takes precedence over that action’s conditions). Instead, the marker must be within 4\" of it and no enemy operatives can contest that marker. However, you can ignore enemy operatives within control range of other friendly BATTLECLADE operatives when determining this.\n• That operative doesn’t require a hatchway’s access point to be within its control range to perform an Operate Hatch action. Instead, that access point must be within 4\" of it." },
  { kind: 'firefight', name: "System Exorcism", text: "Use this firefight ploy when you would activate a friendly BATTLECLADE operative. Remove one rules effect or stat change your opponent has applied to it (e.g. Poison token, -1APL, cannot be activated or perform actions, etc.), then activate it. This ploy cannot allow it to regain lost wounds, ignore the effects of being injured or remove mission pack rules." },
  { kind: 'firefight', name: "Auto-ferric Supplication", text: "Use this firefight ploy when an operative is shooting a friendly BATTLECLADE TECH-PRIEST operative, at the start of the Roll Attack Dice step. Until the end of the sequence, ignore the Piercing weapon rule." },
  { kind: 'firefight', name: "Servile Surrogacy", text: "Use this firefight ploy when a friendly BATTLECLADE TECH-PRIEST operative is selected as the valid target of a Shoot action or to fight against during the Fight action. Select one friendly BATTLECLADE SERVITOR operative visible to and within 3\" of that first friendly operative to become the valid target or to be fought against (as appropriate) instead (even if it wouldn’t normally be valid for this). If it’s the Fight action, treat that SERVITOR operative as being within the fighting operative’s control range for the duration of that action. If it’s the Shoot action, that SERVITOR operative is only in cover or obscured if the original target was. This ploy has no effect if it’s the Shoot action and the ranged weapon has the Blast or Torrent weapon rule." },
  { kind: 'equipment', name: "Electromantic Capacitors", text: "Friendly BATTLECLADE operatives’ melee weapons have the Shock weapon rule. Whenever a friendly BATTLECLADE operative is retaliating, its melee weapons also have the Severe weapon rule." },
  { kind: 'equipment', name: "Covert Guises", text: "After revealing this equipment option, roll one D3. As a STRATEGIC GAMBIT in the first turning point, a number of friendly BATTLECLADE operatives equal to the result that are wholly within your drop zone can immediately perform a free Reposition action, but must end that move wholly within 3\" of your drop zone. Your TECHNOARCHEOLOGIST operative cannot perform more than one Reposition action in the Strategy phase of the first turning point (i.e. as a result of the Seeker of Divine Arcana rule as well)." },
  { kind: 'equipment', name: "Concealed Apparatus", text: "Once per battle, one COMBAT SERVITOR or\nGUN SERVITOR operative can use another weapon option on its datacard it didn’t select for the battle." },
  { kind: 'equipment', name: "Neurocyclic Reserve Cells", text: "Once per turning point, whenever you TRANSFER POWER, you can use this rule. If you do, you can TRANSFER POWER for 0AP (this takes precedence over the normal Noospheric Network rules)." },
]

export const operatives: Operative[] = [
  { id: "battleclade:battleclade-technoarcheologist", name: "Battleclade Technoarcheologist", apl: 3, move: "6\"", save: "3+", w: 9 },
  { id: "battleclade:battleclade-auto-proxy-servitor", name: "Battleclade Auto-proxy Servitor", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "battleclade:battleclade-breacher-servitor", name: "Battleclade Breacher Servitor", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "battleclade:battleclade-combat-servitor", name: "Battleclade Combat Servitor", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "battleclade:battleclade-gun-servitor", name: "Battleclade Gun Servitor", apl: 2, move: "5\"", save: "4+", w: 11 },
  { id: "battleclade:battleclade-servitor-underseer", name: "Battleclade Servitor Underseer", apl: 3, move: "6\"", save: "3+", w: 9 },
  { id: "battleclade:battleclade-technomedic-servitor", name: "Battleclade Technomedic Servitor", apl: 2, move: "5\"", save: "4+", w: 8 },
]
