// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Aspect Techniques", text: "Each ASPECT TECHNIQUE is in a category: Dire Avenger, Howling Banshee and Striking Scorpion. Each ASPECT TECHNIQUE can only be used with a friendly operative that has the matching Aspect keyword, and each will specify when it can be used and what its effects are. In addition:\n• You cannot use more than one ASPECT TECHNIQUE per activation or counteraction.\n• You cannot use each ASPECT TECHNIQUE more than once per turning point.\n• If every friendly BLADES OF KHAINE operative selected for deployment has the same Aspect keyword (e.g. STRIKING SCORPION), you cannot use each ASPECT TECHNIQUE more than twice per turning point (instead of once)." },
  { kind: 'faction', name: "Howling Banshee Aspect Technique", text: "THE WOE Howling Banshees are woe given form. Emitting sonic screeches from their helms, they hurl themselves into the stunned foe, the lightning speed of their swordplay cutting through the enemy before a blow can be landed in return. Use this ASPECT TECHNIQUE during a friendly HOWLING BANSHEE operative’s activation, after it’s performed the Charge action and incapacitated an enemy operative during the Fight action, and is no longer within control range of enemy operatives. That friendly operative can immediately perform a free Charge action using any remaining move distance it had from that first Charge action. That operative can perform two Charge actions during its activation to do so. The operative cannot have performed any other actions during this activation (but can do so after resolving this ASPECT TECHNIQUE)." },
  { kind: 'faction', name: "Howling Banshee Aspect Technique Rain of Tears", text: "Use this ASPECT TECHNIQUE when a friendly HOWLING BANSHEE operative is fighting, after you strike with a critical success, if the enemy operative isn’t incapacitated. End that sequence (any remaining attack dice are discarded) and immediately perform a free Fall Back action up to 3\" with that operative (then the Fight action ends). That operative can do so even if it’s performed an action that prevents it from performing the Fall Back action." },
  { kind: 'faction', name: "Howling Banshee Aspect Technique Scream-that-steals", text: "Use this ASPECT TECHNIQUE when a friendly HOWLING BANSHEE operative is fighting or retaliating, at the start of the Resolve Attack Dice step. You can resolve one of your successes before the normal order. If you do, that success must be used to block." },
  { kind: 'faction', name: "Howling Banshee Aspect Technique Acrobatic", text: "Use this ASPECT TECHNIQUE when a friendly HOWLING BANSHEE operative performs an action in which it moves. Until the end of the action, that operative:\n• Can ignore all vertical distances whenever it drops and climbs.\n• Can move through enemy operatives, move within control range of them, and during the Charge action can leave their control range (it must still end the move following all requirements for that move).\n• Cannot move more than its Move stat if it’s the Charge action." },
  { kind: 'faction', name: "Howling Banshee Aspect Technique Shriek-that-kills", text: "Use this ASPECT TECHNIQUE when a friendly HOWLING BANSHEE operative is performing the Shoot action. Until the end of that action, that operative can use the following ranged weapon — Shriek-that-kills: ATK 5, HIT 3+, DMG 1/2.\nWR Range 6\", Saturate, Seek Light, Stun, Torrent 1\"" },
  { kind: 'faction', name: "Dire Avenger Aspect Technique the Slicing Hurricane", text: "Use this ASPECT TECHNIQUE when a friendly DIRE AVENGER operative is performing the Reposition action. That operative can perform the Shoot action during that action (it must do so in a location it can be placed, and any remaining move distance it had from that Reposition action can be used after it does so). You must select its shuriken catapult, shuriken pistol or twin shuriken catapult for that Shoot action." },
  { kind: 'faction', name: "Dire Avenger Aspect Technique Vigilance of the Avenger", text: "Use this ASPECT TECHNIQUE when a friendly\nDIRE AVENGER operative is performing the Shoot action and you select a shuriken catapult or twin shuriken catapult. Until the end of that action, that weapon has the Lethal 5+ weapon rule." },
  { kind: 'faction', name: "Dire Avenger Aspect Technique Death of a Thousand Blades", text: "Use this ASPECT TECHNIQUE when a friendly DIRE AVENGER operative is performing the Shoot action and you select a shuriken catapult or twin shuriken catapult. Until the end of that action, that weapon has the Torrent 2\" weapon rule, but you cannot select more than one secondary target." },
  { kind: 'faction', name: "Dire Avenger Aspect Technique Unstinting, Immovable", text: "Use this ASPECT TECHNIQUE when an operative is shooting a friendly DIRE AVENGER operative, and you’ve rolled two or more fails. You can discard one of them to retain the other as a normal success instead." },
  { kind: 'faction', name: "Dire Avenger Aspect Technique Raging Heat of the Dying Flame", text: "Use this ASPECT TECHNIQUE during a friendly DIRE AVENGER operative’s activation. Until the start of that operative’s next activation, you can ignore any changes to its stats from being injured (including its weapons’ stats)." },
  { kind: 'faction', name: "Striking Scorpion Aspect Technique Strike and Fade", text: "Use this ASPECT TECHNIQUE when a friendly STRIKING SCORPION operative incapacitates an enemy operative while fighting or retaliating, and is no longer within 3\" of enemy operatives. Change that friendly operative’s order to Conceal and it can immediately perform a free Dash action, even if it’s performed an action that prevents it from performing the Dash action." },
  { kind: 'faction', name: "Striking Scorpion Aspect Technique Patient Stalk, Sudden Blow", text: "Use this ASPECT TECHNIQUE when a friendly STRIKING SCORPION operative that has a Conceal order performs the Reposition action. During that action, that operative can move within control range of enemy operatives (it cannot end the move there), and you can inflict D3+2 damage on one enemy operative it moved within control range of after it’s moved." },
  { kind: 'faction', name: "Striking Scorpion Aspect Technique Scorpion’s Eye", text: "Use this ASPECT TECHNIQUE when a friendly STRIKING SCORPION operative is performing the Shoot action and you select a shuriken pistol. Until the end of that action, that weapon has the Seek Light weapon rule." },
  { kind: 'faction', name: "Striking Scorpion Aspect Technique Merciless Strikes", text: "Use this ASPECT TECHNIQUE when a friendly STRIKING SCORPION operative is fighting, the first time you strike with a critical success during that sequence. Until the end of that sequence, that operative’s melee weapon has the Shock weapon rule." },
  { kind: 'faction', name: "Striking Scorpion Aspect Technique One with the Gloom", text: "Use this ASPECT TECHNIQUE during a friendly STRIKING SCORPION operative’s activation. Until the start of its next activation, while that operative has a Conceal order and is in cover, it cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2\"." },
  { kind: 'strategy', name: "Forewarned", text: "Whenever an operative is shooting a ready friendly BLADES OF KHAINE operative, you can re-roll any of your defence dice results of one result (e.g. results of 2)." },
  { kind: 'strategy', name: "Ruthless Poise", text: "Whenever a friendly BLADES OF KHAINE operative is fighting a ready enemy operative, that friendly operative’s melee weapons have the Ceaseless weapon rule." },
  { kind: 'strategy', name: "Dance of Death", text: "Select two friendly BLADES OF KHAINE operatives visible to and within 6\" of each other. Remove them both from the killzone and set them back up in each other’s previous locations (in other words, swap their positions)." },
  { kind: 'strategy', name: "Khaine’s Vengeance", text: "Whenever a friendly BLADES OF KHAINE operative is shooting an expended enemy operative, that friendly operative’s ranged weapons have the Ceaseless weapon rule." },
  { kind: 'firefight', name: "Bladewind", text: "Use this firefight ploy during a friendly BLADES OF KHAINE operative’s activation. During that activation, that operative can perform two Fight actions." },
  { kind: 'firefight', name: "Starfall", text: "Use this firefight ploy during a friendly BLADES OF KHAINE operative’s activation. During that activation, that operative can perform two Shoot actions." },
  { kind: 'firefight', name: "Contempt", text: "Use this firefight ploy when a friendly BLADES OF KHAINE operative is retaliating or an enemy operative is shooting it, after your opponent rolls their attack dice, but before re-rolls. Until the end of the sequence, your opponent cannot re-roll their attack dice (if your opponent declared the use of any firefight ploys during that sequence that would allow them to re-roll, that ploy is cancelled and the CP spent on it is refunded)." },
  { kind: 'firefight', name: "Fading Light", text: "Use this firefight ploy during a friendly BLADES OF KHAINE operative’s activation, before or after it performs an action. During that activation, that operative can perform the Fall Back action for 1 less AP." },
  { kind: 'equipment', name: "Rune of Prophecy", text: "Once per battle, after rolling off to decide initiative, you can add D3 to, or subtract D3 from, your result." },
  { kind: 'equipment', name: "Rune of Shielding", text: "Once per battle, when an attack dice inflicts Normal Dmg on a friendly BLADES OF KHAINE operative, you can ignore that inflicted damage." },
  { kind: 'equipment', name: "Wraithbone Talisman", text: "Once per turning point, when a friendly BLADES OF KHAINE operative is shooting, fighting or retaliating, if you roll two or more fails, you can discard one of them to retain another as a normal success instead." },
  { kind: 'equipment', name: "Rune of Foresight", text: "When this equipment is revealed, roll one D3. In the Strategy phase of the turning point equal to the result, you gain 1 additional CP.\nNOTES:" },
]

export const operatives: Operative[] = [
  { id: "blades-of-khaine:dire-avenger-exarch", name: "Dire Avenger Exarch", apl: 3, move: "7\"", save: "3+", w: 9 },
  { id: "blades-of-khaine:dire-avenger-warrior", name: "Dire Avenger Warrior", apl: 3, move: "7\"", save: "4+", w: 8 },
  { id: "blades-of-khaine:howling-banshee-exarch", name: "Howling Banshee Exarch", apl: 3, move: "7\"", save: "3+", w: 9 },
  { id: "blades-of-khaine:howling-banshee-warrior", name: "Howling Banshee Warrior", apl: 3, move: "7\"", save: "4+", w: 8 },
  { id: "blades-of-khaine:striking-scorpion-exarch", name: "Striking Scorpion Exarch", apl: 3, move: "7\"", save: "3+", w: 9 },
  { id: "blades-of-khaine:striking-scorpion-warrior", name: "Striking Scorpion Warrior", apl: 3, move: "7\"", save: "3+", w: 8 },
]

export const datacards: Datacard[] = [
  {"name": "Dire Avenger Exarch", "weapons": [{"name": "Shuriken catapult", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Rending"}, {"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Twin shuriken catapult", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Ceaseless, Rending"}, {"name": "Diresword", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Lethal 5+, Rending"}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "2/4"}, {"name": "Gun butts", "atk": 3, "hit": "4+", "dmg": "2/3"}, {"name": "Power weapon", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Defence Tactics", "text": "Whenever this operative contests an objective marker or one of your mission markers, or whenever it’s shooting an enemy operative that does, this operative’s weapons have the Balanced weapon rule."}, {"name": "Exarch", "text": "This operative can perform two Shoot or two Fight actions during its activation."}, {"name": "Shimmershield", "text": "Whenever an operative is shooting a friendly BLADES OF KHAINE operative that’s visible to and within 2\" of this operative, ignore the Piercing weapon rule. This operative only has this rule if you select the shimmershield weapon option."}], "actions": [], "keywords": ["BLADES OF KHAINE", "AELDARI", "ASURYANI", "LEADER", "DIRE AVENGER", "EXARCH"]},
  {"name": "Dire Avenger Warrior", "weapons": [{"name": "Shuriken catapult", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Rending"}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "2/4"}], "abilities": [{"name": "Defence Tactics", "text": "Whenever this operative contests an objective marker or one of your mission markers, or whenever it's shooting an enemy operative that does, this operative’s weapons have the Balanced weapon rule."}], "actions": [], "keywords": ["BLADES OF KHAINE", "AELDARI", "ASURYANI", "DIRE AVENGER", "WARRIOR"]},
  {"name": "Howling Banshee Exarch", "weapons": [{"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Triskele (throw)", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Range 8\", Rending, Torrent 2\""}, {"name": "Executioner", "atk": 5, "hit": "3+", "dmg": "3/7", "wr": "Lethal 5+"}, {"name": "Mirrorswords", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Ceaseless, Lethal 5+"}, {"name": "Power weapon", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}, {"name": "Triskele (slice)", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Rending"}], "abilities": [{"name": "Banshee Mask", "text": "Whenever this operative is fighting, worsen the Hit stat of the enemy operative’s melee weapons by 1. This isn’t cumulative with being injured."}, {"name": "Exarch", "text": "This operative can perform two Shoot or two Fight actions during its activation."}], "actions": [], "keywords": ["BLADES OF KHAINE", "AELDARI", "ASURYANI", "LEADER", "HOWLING BANSHEE", "EXARCH"]},
  {"name": "Howling Banshee Warrior", "weapons": [{"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Banshee Mask", "text": "Whenever this operative is fighting, worsen the Hit stat of the enemy operative’s melee weapons by 1. This isn’t cumulative with being injured."}], "actions": [], "keywords": ["BLADES OF KHAINE", "AELDARI", "ASURYANI", "HOWLING BANSHEE", "WARRIOR"]},
  {"name": "Striking Scorpion Exarch", "weapons": [{"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Twin shuriken pistols", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Range 8\", Ceaseless, Rending"}, {"name": "Biting blade", "atk": 5, "hit": "3+", "dmg": "5/6", "wr": "Rending"}, {"name": "Scorpion’s claw and chainsword", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Brutal, Lethal 5+"}, {"name": "Twin chainswords", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Ceaseless, Rending"}], "abilities": [{"name": "Mandiblasters", "text": "Whenever this operative performs the Fight action, at the start of the Roll Attack Dice step, you can use this rule. If you do, inflict 2 damage on the enemy operative in that sequence."}, {"name": "Exarch", "text": "This operative can perform two Shoot or two Fight actions during its activation."}], "actions": [], "keywords": ["BLADES OF KHAINE", "AELDARI", "ASURYANI", "LEADER", "STRIKING SCORPION", "EXARCH"]},
  {"name": "Striking Scorpion Warrior", "weapons": [{"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Chainsword", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Rending"}], "abilities": [{"name": "Mandiblasters", "text": "Whenever this operative performs the Fight action, at the start of the Roll Attack Dice step, you can use this rule. If you do, inflict 2 damage on the enemy operative in that sequence."}], "actions": [], "keywords": ["BLADES OF KHAINE", "AELDARI", "ASURYANI", "STRIKING SCORPION", "WARRIOR"]},
]
