// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Blooded", text: "• In the Ready step of each Strategy phase.\n• The first time an enemy operative is incapacitated during each turning point.\n• The first time a friendly operative is incapacitated within 6\" of an enemy operative during each turning point." },
  { kind: 'strategy', name: "Reckless Aspirant", text: "Whenever a friendly BLOODED operative that’s wholly within your opponent’s territory and doesn’t have one of your Blooded tokens is shooting or fighting, its weapons have the Accurate 1 weapon rule.\nWhenever a friendly BLOODED operative that has one of your Blooded tokens is wholly within your opponent’s territory, its weapons have the Punishing weapon rule." },
  { kind: 'strategy', name: "Glory Kill", text: "Select one enemy operative. Until the end of the turning point, whenever a friendly BLOODED operative is shooting against, fighting against or retaliating against that enemy operative, that shooting, fighting or retaliating operative’s weapons have the Ceaseless weapon rule, or Relentless if it has one of your Blooded tokens." },
  { kind: 'strategy', name: "Malevolent Grit", text: "Whenever an operative is shooting a friendly BLOODED operative that has one of your Blooded tokens or is wholly within your opponent’s territory, you can re-roll one of your defence dice." },
  { kind: 'strategy', name: "Bitter Demise", text: "Whenever a friendly BLOODED operative is incapacitated, before it’s removed from the killzone, roll one D3: on a 3 (or 2+ if that friendly operative has one of your Blooded tokens), inflict damage equal to the result on one enemy operative visible to and within 2\" of that friendly operative." },
  { kind: 'firefight', name: "Moment of Repute", text: "Use this firefight ploy during the activation of a friendly BLOODED operative that’s under the GAZE OF THE GODS, before or after it performs an action. Until the end of that operative’s activation, add 1 to its APL stat." },
  { kind: 'firefight', name: "Callous Disregard", text: "Use this firefight ploy when a friendly BLOODED operative performs the Shoot action and you’re selecting a valid target. Having other friendly BLOODED operatives within an enemy operative’s control range doesn’t prevent that enemy operative from being selected. Until the end of that action, whenever you discard an attack dice as a fail, inflict damage equal to the dice result on one friendly operative of your choice within control range of the target." },
  { kind: 'firefight', name: "Reward Earned", text: "Use this firefight ploy when an enemy operative is incapacitated by a friendly BLOODED operative within 2\" of it that has one of your Blooded tokens. You gain one Blooded token." },
  { kind: 'firefight', name: "Dark Favour", text: "Use this firefight ploy when a friendly BLOODED operative that has one of your Blooded tokens is selected as the valid target of a Shoot action or to fight against during the Fight action. Select one other friendly BLOODED operative visible to and within 3\" of that first friendly operative to become the valid target or to be fought against (as appropriate) instead (even if it wouldn’t normally be valid for this). If it’s the Fight action, treat that other operative as being within the fighting operative’s control range for the duration of that action. If it’s the Shoot action, that other operative is only in cover or obscured if the original target was. This ploy has no effect if it’s the Shoot action and the ranged weapon has the Blast or Torrent weapon rule." },
  { kind: 'equipment', name: "Sinister Trophies", text: "Whenever an enemy operative is shooting against, fighting against or retaliating against a friendly BLOODED operative that has one of your Blooded tokens and is within 2\" of it, your opponent cannot re-roll their attack dice results of 1." },
  { kind: 'equipment', name: "Chaos Sigil", text: "The disquieting sigils carried by the Blooded bend reality and thin the veil between realspace and the ever-shifting tides of the warp.\nThe Reward Earned firefight ploy costs you 0CP." },
  { kind: 'equipment', name: "Symbols of Bloody Worship", text: "Whenever a friendly BLOODED operative ends an action, if it wasn’t incapacitated but inflicted damage on any enemy operatives during that action, it regains 1 lost wound." },
  { kind: 'equipment', name: "Wicked Blades", text: "Add 1 to both Dmg stats of each friendly BLOODED operative’s bayonet, bayonet & shield and improvised blade for the battle." },
]

export const operatives: Operative[] = [
  { id: "blooded:traitor-chieftain", name: "Traitor Chieftain", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "blooded:traitor-brimstone-grenadier", name: "Traitor Brimstone Grenadier", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "blooded:traitor-butcher", name: "Traitor Butcher", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "blooded:traitor-corpseman", name: "Traitor Corpseman", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "blooded:traitor-commsman", name: "Traitor Commsman", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "blooded:traitor-enforcer", name: "Traitor Enforcer", apl: 2, move: "6\"", save: "4+", w: 9 },
  { id: "blooded:traitor-flenser", name: "Traitor Flenser", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "blooded:traitor-gunner", name: "Traitor Gunner", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "blooded:traitor-ogryn", name: "Traitor Ogryn", apl: 2, move: "6\"", save: "5+", w: 16 },
  { id: "blooded:traitor-sharpshooter", name: "Traitor Sharpshooter", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "blooded:traitor-thug", name: "Traitor Thug", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "blooded:traitor-trench-sweeper", name: "Traitor Trench Sweeper", apl: 2, move: "6\"", save: "4+", w: 9 },
  { id: "blooded:traitor-trooper", name: "Traitor Trooper", apl: 2, move: "6\"", save: "5+", w: 7 },
]

export const datacards: Datacard[] = [
  {"name": "Traitor Chieftain", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Boltgun", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Laspistol", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Plasma pistol (standard)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Piercing 1"}, {"name": "Plasma pistol (supercharge)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Hot, Lethal 5+, Piercing 1"}, {"name": "Bayonet", "atk": 3, "hit": "3+", "dmg": "2/3"}, {"name": "Chainsword", "atk": 4, "hit": "3+", "dmg": "4/5"}, {"name": "Improvised blade", "atk": 4, "hit": "3+", "dmg": "2/3"}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Blooded Icon", "text": "Once per turning point, when a friendly                       Lead With Strength: Whenever this operative has one of your BLOODED operative that has one of your Blooded tokens is                    Blooded tokens or is wholly within your opponent’s territory, incapacitated, if this operative is within 6\" of it, you can regain         treat it as if it’s under the GAZE OF THE GODS. that token."}], "actions": [], "keywords": ["BLOODED", "CHAOS", "LEADER", "CHIEFTAIN"]},
  {"name": "Traitor Brimstone Grenadier", "weapons": [{"name": "Diabolyk bomb", "atk": 4, "hit": "3+", "dmg": "4/3", "wr": "Range 6\", Blast 2\", Devastating 2, Limited 1,"}], "abilities": [{"name": "Grenadier", "text": "This operative can use frag and krak grenades (see universal equipment). Doing so doesn’t count towards any limited uses you have (i.e. if you also select those grenades from equipment for other operatives). Whenever it’s doing so, improve the Hit stat of that weapon by 1."}, {"name": "Explosive Demise", "text": "If this operative is incapacitated, before it’s removed from the killzone, you can use this rule. If you do, roll two D6, or one D6 if this operative is within control range of an enemy operative. If any result is a 4+, inflict D3+2 damage on each operative visible to and within 2\" of this operative (roll separately for each). If this operative hasn’t used its diabolyk bomb during the battle, inflict D6+2 damage instead."}], "actions": [], "keywords": ["BLOODED", "CHAOS", "BRIMSTONE GRENADIER"]},
  {"name": "Traitor Butcher", "weapons": [{"name": "Power weapon & cleaver", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Ceaseless, Lethal 5+, Blood Offering*"}], "abilities": [{"name": "Unholy Sustenance", "text": "Whenever this operative is fighting or                   *Blood Offering: Whenever this operative is fighting or retaliating retaliating, if it incapacitates the enemy operative in that                with this weapon, the first time you strike with a critical success sequence, it regains up to D3 lost wounds. This is cumulative               during that sequence, you gain one Blooded token. with the Symbols of Bloody Worship equipment."}], "actions": [], "keywords": ["BLOODED", "CHAOS", "BUTCHER"]},
  {"name": "Traitor Corpseman", "weapons": [{"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}, {"name": "Stimm needle", "atk": 3, "hit": "5+", "dmg": "1/4", "wr": "Lethal 5+"}], "abilities": [{"name": "Regular Dosage", "text": "At the end of the Select Operatives step, if this operative is selected for deployment, you can select one other friendly BLOODED operative to gain one STIMM rule for the battle (excluding Rejuvenated)."}], "actions": [{"name": "Stimms", "ap": 1, "text": "Select one friendly BLOODED operative within this operative’s control range, then select the Rejuvenated STIMM rule, or one other STIMM rule for that operative to have for the battle. You cannot select each STIMM rule for each operative more than once per battle.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["BLOODED", "CHAOS", "CORPSEMAN"]},
  {"name": "Traitor Commsman", "weapons": [{"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [{"name": "Signal", "ap": 1, "text": "SUPPORT. Select one other friendly BLOODED operative (excluding OGRYN) visible to and within 6\" of this operative. Until the end of that operative’s next activation, add 1 to its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative."}, {"name": "Sacrilegious Actuation", "ap": 1, "text": "You gain one Blooded token.\nThis operative cannot perform this action while within control range of an enemy operative, or if it doesn’t have one of your Blooded tokens."}], "keywords": ["BLOODED", "CHAOS", "COMMSMAN"]},
  {"name": "Traitor Enforcer", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Power fist", "atk": 4, "hit": "4+", "dmg": "5/7", "wr": "Brutal"}], "abilities": [{"name": "Gruelling Disciplinarian", "text": "• Whenever a friendly BLOODED operative is within 6\" of this operative, you can ignore any changes to that operative’s stats from being injured (including its weapons’ stats). • Whenever a friendly BLOODED operative is activated within 6\" of this operative, you can ignore any changes to that operative’s stats from being injured until the end of its activation (including its weapons’ stats)."}], "actions": [{"name": "Enforce", "ap": 1, "text": "Select one other friendly BLOODED operative visible to and within 3\" of this operative. That operative can immediately perform a 1AP action for free, but it cannot move more than 2\" during that action. If the selected friendly operative is a COMMSMAN, it cannot perform the Sacrilegious Actuation or Signal actions.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["BLOODED", "CHAOS", "ENFORCER"]},
  {"name": "Traitor Flenser", "weapons": [{"name": "Skinning blades", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Ceaseless, Stalk*"}], "abilities": [], "actions": [], "keywords": ["BLOODED", "CHAOS", "FLENSER"]},
  {"name": "Traitor Gunner", "weapons": [{"name": "Flamer", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 8\", Saturate, Torrent 2\""}, {"name": "Grenade launcher (frag)", "atk": 4, "hit": "4+", "dmg": "2/4", "wr": "Blast 2\""}, {"name": "Grenade launcher (krak)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Piercing 1"}, {"name": "Meltagun", "atk": 4, "hit": "4+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Plasma gun (standard)", "atk": 4, "hit": "4+", "dmg": "4/6", "wr": "Piercing 1"}, {"name": "Plasma gun (supercharge)", "atk": 4, "hit": "4+", "dmg": "5/6", "wr": "Hot, Lethal 5+, Piercing 1"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [], "keywords": ["BLOODED", "CHAOS", "GUNNER"]},
  {"name": "Traitor Ogryn", "weapons": [{"name": "Power maul & mutant claw", "atk": 4, "hit": "3+", "dmg": "5/6", "wr": "Rending, Shock"}], "abilities": [{"name": "Avalanche of Muscle", "text": "Whenever this operative ends its move during the Charge action, you can inflict D3 damage on one enemy operative within its control range."}, {"name": "Chem-enhanced", "text": "You can ignore any changes to this operative’s APL stat and it’s not affected by enemy operatives’ Shock and Stun weapon rules."}, {"name": "Brute", "text": "Whenever your opponent is selecting a valid target, if this operative has a Conceal order, it cannot use Light terrain for cover. While this can allow this operative to be targeted (assuming it’s visible), it doesn’t remove its cover save (if any)."}, {"name": "Slow-witted", "text": "You must spend 1 additional AP for this operative to perform the Pick Up Marker and mission actions (excluding Operate Hatch)."}], "actions": [], "keywords": ["BLOODED", "CHAOS", "OGRYN"]},
  {"name": "Traitor Sharpshooter", "weapons": [{"name": "Long-las (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Long-las (stationary)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 1, Heavy (Dash only), Silent"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Camo Cloak", "text": "Whenever an operative is shooting this operative,            A Name Whispered In Blood: STRATEGIC GAMBIT in the if you can retain any cover saves, you can retain one additional         first turning point. Select one enemy operative. Whenever this cover save. This isn’t cumulative with improved cover saves from         operative is shooting that enemy operative, treat this operative Vantage terrain.                                                         as if it has one of your Blooded tokens and is under the GAZE OF THE GODS."}], "actions": [], "keywords": ["BLOODED", "CHAOS", "SHARPSHOOTER"]},
  {"name": "Traitor Thug", "weapons": [{"name": "Heavy club", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Brutal"}], "abilities": [{"name": "Tough", "text": "Whenever this operative is fighting or retaliating, or an operative is shooting it, Normal Dmg of 3 or more inflicts 1 less damage on it."}], "actions": [], "keywords": ["BLOODED", "CHAOS", "THUG"]},
  {"name": "Traitor Trench Sweeper", "weapons": [{"name": "Shotgun", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Range 6\""}, {"name": "Bayonet & shield", "atk": 3, "hit": "3+", "dmg": "2/3", "wr": "Shield*"}], "abilities": [{"name": "Shielding", "text": "Whenever this operative is activated, you can use this rule. If you do, until the start of this operative’s next activation:\n• Subtract 2\" from its Move stat. • Whenever an operative is shooting this operative, you can re-roll any of your defence dice."}], "actions": [], "keywords": ["BLOODED", "CHAOS", "TRENCH SWEEPER"]},
  {"name": "Traitor Trooper", "weapons": [{"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Group Activation", "text": "Whenever this operative is expended, you must then activate one other ready friendly BLOODED TROOPER operative (if able) before your opponent activates. When that other operative is expended, your opponent then activates as normal (in other words, you cannot activate more than two operatives in succession with this rule).\nNOTES:"}], "actions": [], "keywords": ["BLOODED", "CHAOS", "TROOPER"]},
]
