// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Crossfire", text: "Whenever a friendly BROOD BROTHER operative is shooting against or fighting against an enemy operative, after resolving all of your attack dice, if that enemy operative isn’t incapacitated it gains one of your Crossfire tokens. Whenever a friendly BROOD BROTHER operative is shooting against, fighting against or retaliating against an enemy operative that has any of your Crossfire tokens, you can remove any of those tokens. For each that you do, you can re-roll one of your attack dice." },
  { kind: 'strategy', name: "Pervasive", text: "During each friendly BROOD BROTHER operative’s activation, you can ignore the first vertical distance of 2\" they move during one climb up." },
  { kind: 'strategy', name: "Embedded", text: "Whenever an enemy operative is shooting a friendly BROOD BROTHER operative, if you can retain any cover saves as a result of Heavy terrain, you can retain one additional cover save." },
  { kind: 'strategy', name: "Uprising", text: "The first time each friendly BROOD BROTHER operative performs either the Shoot or Fight action during each of its activations, if its order was changed from Conceal to Engage at the start of that activation, the enemy operative selected as the valid target or to fight against gains one of your Crossfire tokens as soon as it’s selected (instead of after resolving your attack dice). This ploy has no effect if that friendly operative was activated within control range of an enemy operative. Note this ploy cannot come into effect more than once per activation (you cannot use it during both the Shoot and Fight action in the same activation)." },
  { kind: 'strategy', name: "Cult Devotion", text: "Whenever a friendly BROOD BROTHER operative (excluding PATRIARCH) is incapacitated while fighting or retaliating, if you have any unresolved successes, you can roll one D6: if the result is a success as if it were the Roll Attack Dice step of that sequence (i.e. using the same weapon, but with no re-rolls), you can strike the enemy operative in that sequence with one of your unresolved normal successes, or any of your successes instead if the D6 result is a critical success. In either case, that friendly operative is removed from the killzone afterwards." },
  { kind: 'firefight', name: "Ruthless Coordination", text: "Use this firefight ploy when selecting a valid target for a friendly BROOD BROTHER operative. Until the end of the action, determine visibility as normal, but you can instead determine intervening (for cover and obscured) from another friendly BROOD BROTHER operative that both that friendly operative and the potential valid target are visible to, but that isn’t itself within control range of enemy operatives. Note the friendly operative doesn’t gain the additional benefits of Vantage terrain if the other friendly operative is on it (e.g. to target an enemy operative that has a Conceal order that’s in cover provided only by Light terrain)." },
  { kind: 'firefight', name: "Unquestioning Loyalty", text: "Use this firefight ploy when a friendly BROOD BROTHER LEADER operative is selected as the valid target of a Shoot action or to fight against during the Fight action. Select one other friendly BROOD BROTHER BROODGUARD operative (excluding LEADER) visible to and within 3\" of that LEADER operative to become the valid target or to be fought against (as appropriate) instead (even if it wouldn’t normally be valid for this). If it’s the Fight action, treat that other operative as being within the fighting operative’s control range for the duration of that action. If it’s the Shoot action, that other operative is only in cover or obscured if the original target was. This ploy has no effect if it’s the Shoot action and the ranged weapon has the Blast or Torrent weapon rule." },
  { kind: 'firefight', name: "Idolisation", text: "Use this firefight ploy when a friendly BROOD BROTHER operative (excluding LEADER) within 6\" of a friendly BROOD BROTHER LEADER or BROOD BROTHER ICONWARD operative is shooting, fighting or retaliating, in the Roll Attack Dice step. You can retain one of your fails as a normal success instead of discarding it, or retain one of your normal successes as a critical success instead." },
  { kind: 'firefight', name: "Insidious", text: "Use this firefight ploy after an activation. Before the next activation, one friendly BROOD BROTHER operative can perform a free Dash action, as long as it’s not a valid target for enemy operatives when it starts and ends that action. You cannot use this ploy during the first turning point." },
  { kind: 'equipment', name: "Covert Guises", text: "After revealing this equipment option, roll one D3. As a STRATEGIC GAMBIT in the first turning point, a number of friendly BROOD BROTHER BROODGUARD operatives equal to the result that are wholly within your drop zone can immediately perform a free Reposition action, but must end that move wholly within 3\" of your drop zone." },
  { kind: 'equipment', name: "Cult Talisman", text: "Once per turning point, when an operative is shooting a friendly BROOD BROTHER operative (excluding PATRIARCH), in the Roll Defence Dice step, you can retain one of your normal successes as a critical success instead." },
  { kind: 'equipment', name: "Cult Knives", text: "Friendly BROOD BROTHER BROODGUARD operatives have the following melee weapon — Cult knife: ATK 3, HIT 4+, DMG 3/4." },
  { kind: 'equipment', name: "Lookout", text: "STRATEGIC GAMBIT. Select one enemy operative visible to a friendly BROOD BROTHER operative to gain one of your Crossfire tokens." },
]

export const operatives: Operative[] = [
  { id: "brood-brothers:brood-brother-commander", name: "Brood Brother Commander", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "brood-brothers:brood-brother-agitator", name: "Brood Brother Agitator", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "brood-brothers:brood-brother-gunner", name: "Brood Brother Gunner", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "brood-brothers:brood-brother-iconward", name: "Brood Brother Iconward", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "brood-brothers:brood-brother-knife-fighter", name: "Brood Brother Knife Fighter", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "brood-brothers:brood-brother-medic", name: "Brood Brother Medic", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "brood-brothers:brood-brother-sapper", name: "Brood Brother Sapper", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "brood-brothers:brood-brother-sniper", name: "Brood Brother Sniper", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "brood-brothers:brood-brother-trooper", name: "Brood Brother Trooper", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "brood-brothers:brood-brother-veteran", name: "Brood Brother Veteran", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "brood-brothers:brood-brother-vox-operator", name: "Brood Brother Vox-operator", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "brood-brothers:magus", name: "Magus", apl: 3, move: "6\"", save: "4+", w: 9 },
  { id: "brood-brothers:patriarch", name: "Patriarch", apl: 4, move: "6\"", save: "4+", w: 21 },
  { id: "brood-brothers:psychic-familiar", name: "Psychic Familiar", apl: 2, move: "6\"", save: "5+", w: 3 },
  { id: "brood-brothers:primus", name: "Primus", apl: 3, move: "6\"", save: "4+", w: 9 },
]

export const datacards: Datacard[] = [
  {"name": "Brood Brother Commander", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Drum-fed autogun", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Ceaseless"}, {"name": "Laspistol", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Bayonet", "atk": 3, "hit": "3+", "dmg": "2/3"}, {"name": "Chainsword and claw", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Balanced, Rending"}, {"name": "Power weapon and claw", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Balanced, Lethal 5+"}], "abilities": [{"name": "Coordinate", "text": "STRATEGIC GAMBIT if this operative is in the killzone. Select one enemy operative to gain one of your Crossfire tokens."}], "actions": [], "keywords": ["BROOD BROTHER", "TYRANID", "GENESTEALER CULT", "BROODGUARD", "LEADER", "COMMANDER"], "img": "/ops/brood-brothers/brood-brother-commander.webp"},
  {"name": "Brood Brother Agitator", "weapons": [{"name": "Shock maul", "atk": 4, "hit": "4+", "dmg": "4/4", "wr": "Shock"}], "abilities": [{"name": "Devoted", "text": "Once per turning point, when this operative is fighting or retaliating, in the Resolve Attack Dice step, you can ignore the damage inflicted on it from one normal success."}, {"name": "Psiren Caster", "text": "Whenever a friendly BROOD BROTHER operative is shooting against, fighting against or retaliating against an enemy operative within 6\" of this operative, you can re-roll one of your attack dice."}], "actions": [], "keywords": ["BROOD BROTHER", "TYRANID", "GENESTEALER CULT", "BROODGUARD", "AGITATOR"], "img": "/ops/brood-brothers/brood-brother-agitator.webp"},
  {"name": "Brood Brother Gunner", "weapons": [{"name": "Flamer", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 8\", Saturate, Torrent 2\""}, {"name": "Grenade launcher (frag)", "atk": 4, "hit": "4+", "dmg": "2/4", "wr": "Blast 2\""}, {"name": "Grenade launcher (krak)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Piercing 1"}, {"name": "Meltagun", "atk": 4, "hit": "4+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Plasma gun (standard)", "atk": 4, "hit": "4+", "dmg": "4/6", "wr": "Piercing 1"}, {"name": "Plasma gun (supercharge)", "atk": 4, "hit": "4+", "dmg": "5/6", "wr": "Hot, Lethal 5+, Piercing 1"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [], "keywords": ["BROOD BROTHER", "TYRANID", "GENESTEALER CULT", "BROODGUARD", "GUNNER"], "img": "/ops/brood-brothers/brood-brother-gunner.webp"},
  {"name": "Brood Brother Iconward", "weapons": [{"name": "Large knife", "atk": 4, "hit": "4+", "dmg": "3/5"}], "abilities": [{"name": "Cult Icon", "text": "Whenever determining control of a marker within 4\" of this operative, treat the total APL stat of friendly BROOD BROTHER operatives that contest it as 1 higher if at least one friendly BROOD BROTHER operative contests that marker. Note this isn’t a change to the APL stat, so any changes are cumulative with this."}, {"name": "Broodmind Devotion", "text": "Once per turning point, when a ready friendly BROOD BROTHER BROODGUARD operative is incapacitated while visible to and within 6\" of this operative, you can use this rule. If you do, before that operative is removed from the killzone, it can perform a 1AP action for free (excluding Fight and Explosives), and you can change its order to do so. It’s then removed from the killzone as normal. You cannot use this rule and the Medic! rule (see MEDIC) on the same operative at the same time."}], "actions": [], "keywords": ["BROOD BROTHER", "TYRANID", "GENESTEALER CULT", "BROODGUARD", "ICONWARD"], "img": "/ops/brood-brothers/brood-brother-iconward.webp"},
  {"name": "Brood Brother Knife Fighter", "weapons": [{"name": "Poisoned fighting knives", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Ceaseless, Lethal 5+"}], "abilities": [{"name": "Assassin", "text": "This operative can perform the Charge action while it has a Conceal order."}, {"name": "Counterattack", "text": "Whenever this operative is fighting or retaliating, whenever your opponent resolves a normal success, inflict 1 damage on the enemy operative in that sequence."}], "actions": [], "keywords": ["BROOD BROTHER", "TYRANID", "GENESTEALER CULT", "BROODGUARD", "KNIFE FIGHTER"], "img": "/ops/brood-brothers/brood-brother-knife-fighter.webp"},
  {"name": "Brood Brother Medic", "weapons": [{"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}, {"name": "Gene-needler", "atk": 1, "hit": "4+", "dmg": "5/7", "wr": "Lethal 5+, Limited 1"}], "abilities": [{"name": "Medic!", "text": "The first time during each turning point that another friendly BROOD BROTHER operative (excluding PATRIARCH) would be incapacitated while visible to and within 3\" of this operative, you can use this rule, providing neither this nor that operative is within control range of an enemy operative. If you do, that friendly operative isn’t incapacitated, has 1 wound remaining and cannot be incapacitated for the remainder of the action. After that action, that friendly operative can immediately perform a free Dash action, but must end that move within this operative’s control range. Subtract 1 from this and that operative’s APL stats until the end of their next activations respectively, and if this rule was used during that friendly operative’s activation, that activation ends. You cannot use this rule if this operative is incapacitated, or if it’s a Shoot action and this operative would be a primary or secondary target."}], "actions": [{"name": "Medikit", "ap": 1, "text": "Select one friendly BROOD BROTHER operative (excluding PATRIARCH) within this operative’s control range to regain up to 2D3 lost wounds. It cannot be an operative that the Medic! rule was used on during this turning point.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["BROOD BROTHER", "TYRANID", "GENESTEALER CULT", "BROODGUARD", "MEDIC"], "img": "/ops/brood-brothers/brood-brother-medic.webp"},
  {"name": "Brood Brother Sapper", "weapons": [{"name": "Demolition charge", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Range 3\", Blast 2\", Heavy (Reposition only), Limited 1, Piercing 1, Saturate"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Final Defiance", "text": "If this operative is incapacitated, it can perform a free Explosives unique action before it’s removed from the killzone."}, {"name": "Grenadier", "text": "This operative can use frag and krak grenades (see universal equipment). Doing so doesn’t count towards any limited uses you have (i.e. if you also select those grenades from equipment for other operatives). Whenever it’s doing so, improve the Hit stat of that weapon by 1."}], "actions": [{"name": "Explosives", "ap": 1, "text": "The first time this operative performs this action during the battle, place your Explosives marker within its control range. The second time this operative performs this action during the battle, inflict 2D6 damage on each operative within 2\" of that marker (roll separately for each) unless Heavy terrain is wholly intervening between that operative and that marker.\nThis operative cannot perform this action more than twice per battle, while within control range of an enemy operative, or during an activation in which it performed the Charge, Dash or Fall Back action (or vice versa)."}], "keywords": ["BROOD BROTHER", "TYRANID", "GENESTEALER CULT", "BROODGUARD", "SAPPER"], "img": "/ops/brood-brothers/brood-brother-sapper.webp"},
  {"name": "Brood Brother Sniper", "weapons": [{"name": "Sniper rifle (concealed)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy, Silent, Concealed Position*"}, {"name": "Sniper rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Sniper rifle (stationary)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Concealed Position", "text": "This operative can only use this weapon the first time it’s performing the Shoot action during the battle."}], "actions": [], "keywords": ["BROOD BROTHER", "TYRANID", "GENESTEALER CULT", "BROODGUARD", "SNIPER"], "img": "/ops/brood-brothers/brood-brother-sniper.webp"},
  {"name": "Brood Brother Trooper", "weapons": [{"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Group Activation", "text": "Whenever this operative is expended, you must then activate one other ready friendly BROOD BROTHER TROOPER operative (if able) before your opponent activates. When that other operative is expended, your opponent then activates as normal (in other words, you cannot activate more than two operatives in succession with this rule)."}], "actions": [], "keywords": ["BROOD BROTHER", "TYRANID", "GENESTEALER CULT", "BROODGUARD", "TROOPER"], "img": "/ops/brood-brothers/brood-brother-trooper.webp"},
  {"name": "Brood Brother Veteran", "weapons": [{"name": "Combat shotgun (close range)", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Range 6\""}, {"name": "Combat shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "2/2"}, {"name": "Bayonet & claw", "atk": 3, "hit": "4+", "dmg": "2/3", "wr": "Balanced"}], "abilities": [{"name": "Resilient", "text": "Normal Dmg of 3 or more inflicts 1 less damage on this operative."}, {"name": "Bodyguard", "text": "You can use the Unquestioning Loyalty firefight ploy for 0CP if this is the specified friendly BROODGUARD operative."}], "actions": [], "keywords": ["BROOD BROTHER", "TYRANID", "GENESTEALER CULT", "BROODGUARD", "VETERAN"], "img": "/ops/brood-brothers/brood-brother-veteran.webp"},
  {"name": "Brood Brother Vox-operator", "weapons": [{"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [{"name": "Signal", "ap": 1, "text": "SUPPORT. Select one other friendly BROOD                                 This operative cannot perform this action while within control BROTHER BROODGUARD operative visible to and                              range of an enemy operative. within 6\" of this operative. Until the end of that operative’s next activation, add 1 to its APL stat."}], "keywords": ["BROOD BROTHER", "TYRANID", "GENESTEALER CULT", "BROODGUARD", "VOX-OPERATOR"], "img": "/ops/brood-brothers/brood-brother-vox-operator.webp"},
  {"name": "Magus", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Bio dagger", "atk": 2, "hit": "4+", "dmg": "3/6", "wr": "Lethal 4+"}, {"name": "Force stave", "atk": 4, "hit": "4+", "dmg": "4/6", "wr": "PSYCHIC, Shock"}], "abilities": [{"name": "Spiritual Leader", "text": "STRATEGIC GAMBIT if this operative is in the killzone. Select one of the following for friendly BROOD BROTHER operatives to have until the end of the turning point or until this operative is incapacitated (whichever comes first):\n• Whenever an operative is shooting a friendly BROOD BROTHER operative, ignore the Piercing weapon rule. • You can ignore any changes to friendly BROOD BROTHER operatives’ stats from being injured (including their weapons’ stats). • You can ignore any changes to the APL stat of friendly BROOD BROTHER operatives."}], "actions": [{"name": "Telepathic Overload", "ap": 1, "text": "PSYCHIC. Select one enemy operative that’s a valid target for this operative. Until the end of that operative’s next activation, subtract 1 from its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative."}, {"name": "Mental Onslaught", "ap": 1, "text": "PSYCHIC. Select one enemy operative that’s a valid target for this operative. Inflict 2 damage on it, or 4 damage instead if it’s within 6\" of this operative. Then roll one D6: if the result is higher than that enemy operative’s APL stat, inflict an additional 2 damage on it, or 4 damage instead if it’s within 6\" of this operative. Keep rolling one D6 in this manner until you roll equal to or less than that enemy operative’s APL stat, until it’s incapacitated, or until you inflict 8 damage on it during this action (whichever comes first).\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["BROOD BROTHER", "TYRANID", "GENESTEALER CULT", "BROODCOVEN", "PSYKER", "LEADER", "MAGUS"], "img": "/ops/brood-brothers/magus.webp"},
  {"name": "Patriarch", "weapons": [{"name": "Claws", "atk": 5, "hit": "3+", "dmg": "5/6", "wr": "Relentless, Rending"}], "abilities": [{"name": "Alpha Predator", "text": "Whenever an operative is shooting this operative, ignore the\nPiercing weapon rule. You can activate this operative twice during the turning point as long as it has AP to spend (it stays ready while it can still be activated a second time). Per turning point, it cannot move more than 9\" and you cannot spend more than 4AP in total for it."}, {"name": "Monster", "text": "This operative cannot use any            INTO SHADOW                          1AP weapons that aren’t on its datacard, Change this operative’s order. or perform unique actions (excluding Into Shadow and Mind Control).                       This operative cannot perform this Whenever your opponent is selecting a                action while within control range of an valid target, if this operative has a Conceal        enemy operative. order, it cannot use Light terrain for cover. While this can allow this operative to be targeted (assuming it’s visible), it doesn’t remove its cover save (if any)."}], "actions": [{"name": "Mind Control", "ap": 2, "text": "PSYCHIC. Select one enemy                        Until the end of the activation,                 This operative cannot perform this operative visible to and within 2\"               that enemy operative is a friendly               action while within control range of of this operative. Both players roll             operative (an enemy operative for                an enemy operative, unless the only one D6 and add their respective                  your opponent), you can change its               enemy operative it’s within control operative’s APL stat to their result.            order, and it can immediately perform            range of is selected for this action. If your total is higher than your                one free action. It cannot perform an opponent’s, you can resolve this                 action in which it moves other than action’s second effect.                          Dash (in which case specify the location for your opponent to move the operative to). You can only resolve this action’s second effect once per battle."}], "keywords": ["BROOD BROTHER", "TYRANID", "GENESTEALER CULT", "BROODCOVEN", "PSYKER", "LEADER", "PATRIARCH"], "img": "/ops/brood-brothers/patriarch.webp"},
  {"name": "Psychic Familiar", "weapons": [{"name": "Claws", "atk": 3, "hit": "4+", "dmg": "2/3", "wr": "Rending"}], "abilities": [{"name": "Small", "text": "This operative cannot use any weapons that aren’t on its datacard, or perform unique actions. Whenever this operative has a Conceal order and is in cover, it cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2\". This operative can perform the Fall Back action for 1 less AP."}, {"name": "Group Activation", "text": "Whenever this operative is expended, you must then activate one other ready friendly BROOD BROTHER PSYCHIC FAMILIAR operative (if able) before your opponent activates. When that other operative is expended, your opponent then activates as normal."}, {"name": "Elusive", "text": "This operative can perform mission actions while within control range of an enemy operative (this takes precedence over those actions’ normal conditions). It can move through enemy operatives, move within control range of them, and during the Charge action can leave their control range (it must still end the move following all requirements for that move).\n."}], "actions": [], "keywords": ["BROOD BROTHER", "TYRANID", "GENESTEALER CULT", "PSYCHIC FAMILIAR"], "img": "/ops/brood-brothers/psychic-familiar.webp"},
  {"name": "Primus", "weapons": [{"name": "Scoped needle pistol (short range)", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Range 8\", Lethal 5+, Silent"}, {"name": "Scoped needle pistol (long range)", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Silent"}, {"name": "Bonesword and toxin injector claw", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Lethal 5+, Rending"}], "abilities": [{"name": "Fist of the Patriarch", "text": "This operative can either perform two Shoot or two Fight actions during its activation."}, {"name": "Mastermind", "text": "Once per turning point, after rolling off to determine initiative, if this operative is in the killzone, you can do one of the following (you cannot select each option more than once per battle):\n• Add 1 to your dice result. • If you didn’t have initiative in the previous turning point, re-roll your dice."}], "actions": [{"name": "Conspire", "ap": 1, "text": "You gain 1CP.\nThis operative cannot perform this action while within control range of an enemy operative, or more than once per turning point."}], "keywords": ["BROOD BROTHER", "TYRANID", "GENESTEALER CULT", "BROODCOVEN", "LEADER", "PRIMUS"], "img": "/ops/brood-brothers/primus.webp"},
]
