// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Obelisk Node Matrix", text: "As a STRATEGIC GAMBIT in the first turning point, place your three OBELISK NODE markers wholly within your territory. As a STRATEGIC GAMBIT in each turning point after the first, you can move each of your OBELISK NODE markers up to\n3\" horizontally.\nYour OBELISK NODE markers control other markers within 1\" of them that no enemy operatives contest (treat your OBELISK NODE markers as friendly operatives for this purpose).\nIf more than one player would use their OBELISK\nNODE markers to control the same marker, no OBELISK NODE markers control it." },
  { kind: 'strategy', name: "Hypershielding", text: "Whenever an operative is shooting a friendly CANOPTEK CIRCLE operative, if your OBELISK NODE MATRIX is intervening, or that friendly operative is within your OBELISK NODE MATRIX, you can re-roll any of your defence dice results of one result (e.g. results of 2)." },
  { kind: 'strategy', name: "Cryptogravitic Repulsion", text: "Once per action, the first time an enemy operative would move within your OBELISK NODE MATRIX, the distance is treated as an additional 1\". Note this means if that enemy operative doesn’t have sufficient move distance (e.g. it’s at the end of its move), that operative cannot move within your OBELISK NODE MATRIX." },
  { kind: 'strategy', name: "Transdynamic Amplification", text: "Whenever a friendly CANOPTEK CIRCLE operative is shooting, if your OBELISK NODE MATRIX is intervening, or the target is within your OBELISK NODE MATRIX, that friendly operative’s weapons have the Ceaseless weapon rule." },
  { kind: 'strategy', name: "Souldrain", text: "Whenever an enemy operative is within your OBELISK NODE MATRIX, or whenever it’s fighting or retaliating against a friendly CANOPTEK CIRCLE operative that’s within your OBELISK NODE MATRIX, subtract 1 from both Dmg stats of that enemy operative’s melee weapons (to a minimum of 2) until the end of the activation/ counteraction. Note this means if the enemy operative moves through your OBELISK NODE MATRIX, apply this change at the end of that move action until the end of the activation/ counteraction." },
  { kind: 'firefight', name: "Shield Flare", text: "Use this firefight ploy when an attack dice inflicts Normal Dmg on a friendly CANOPTEK CIRCLE operative. If your OBELISK NODE MATRIX is intervening, or that friendly operative is within your OBELISK NODE MATRIX, ignore that inflicted damage. Note your opponent determines intervening (i.e. where on their operative’s base to draw the targeting lines from)." },
  { kind: 'firefight', name: "Nodal Response", text: "Use this firefight ploy during a friendly CANOPTEK CIRCLE operative’s activation, before or after it performs an action. You can either change one of the strategy ploys you used during this turning point (only pay additional CP if that ploy costs more), or use a strategy ploy now (pay its CP cost as normal)." },
  { kind: 'firefight', name: "Animate Obelisk Nodes", text: "Use this firefight ploy when it’s your turn to activate or counteract with a friendly operative.\nMove any number of your OBELISK NODE markers instead. They can move up to 6\" horizontally combined, and distances are always rounded up to the nearest inch (so if you move a marker 1.5\", it’s treated as moving it 2\"). For example, you could move one marker 6\", three markers 1\" each, or any combination that doesn’t exceed 6\" in total. You can also move them 0\" (to effectively skip an activation). In any case, your opponent activates as normal afterwards." },
  { kind: 'firefight', name: "Sacrificial Thrall", text: "Use this firefight ploy when a friendly CANOPTEK CIRCLE GEOMANCER operative is selected as the valid target of a Shoot action or to fight against during the Fight action. Select one other friendly CANOPTEK CIRCLE CANOPTEK operative visible to and within 3\" of that first friendly operative to become the valid target or to be fought against (as appropriate) instead (even if it wouldn’t normally be valid for this). If it’s the Fight action, treat that other operative as being within the fighting operative’s control range for the duration of that action. If it’s the Shoot action, that other operative is only in cover or obscured if the original target was. This ploy has no effect if it’s the Shoot action and the ranged weapon has the Blast or Torrent weapon rule." },
  { kind: 'equipment', name: "Matrix Manipulator", text: "Once per battle, during a friendly CANOPTEK CIRCLE operative’s activation or counteraction, you can use this rule. If you do, until the end of that activation/counteraction, a friendly CANOPTEK CIRCLE GEOMANCER operative is treated as your fourth OBELISK NODE marker." },
  { kind: 'equipment', name: "Nanoscarab Caskets", text: "Whenever a friendly CANOPTEK CIRCLE operative is activated, it regains up to D3 lost wounds." },
  { kind: 'equipment', name: "Awakened Obelisk Nodes", text: "After revealing this equipment option, roll one D3. You can use the Animate Obelisk Nodes firefight ploy for 0CP a number of times during the battle equal to the result." },
  { kind: 'equipment', name: "Phase Shifter", text: "Once per turning point, when an operative is shooting a friendly CANOPTEK CIRCLE GEOMANCER operative, at the start of the Roll Defence Dice step, you can use this rule. If you do, worsen the x of the Piercing weapon rule by 1 (if any) until the end of that sequence. Note that Piercing 1 would therefore be ignored." },
]

export const operatives: Operative[] = [
  { id: "canoptek-circle:geomancer", name: "Geomancer", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "canoptek-circle:canoptek-macrocyte-accelerator", name: "Canoptek Macrocyte Accelerator", apl: 2, move: "7\"", save: "4+", w: 7 },
  { id: "canoptek-circle:canoptek-macrocyte-reanimator", name: "Canoptek Macrocyte Reanimator", apl: 2, move: "7\"", save: "4+", w: 7 },
  { id: "canoptek-circle:canoptek-macrocyte-warrior", name: "Canoptek Macrocyte Warrior", apl: 2, move: "7\"", save: "4+", w: 7 },
  { id: "canoptek-circle:canoptek-tomb-crawler", name: "Canoptek Tomb Crawler", apl: 2, move: "5\"", save: "3+", w: 18 },
]
