// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Benedictions", text: "BENEDICTION EFFECT Until the end of the battle, add 1 to that operative’s Ardour APL stat. You cannot select this BENEDICTION for a SUPERIOR operative. Until the end of the battle, weapons on that operative’s Wrath datacard have the Ceaseless weapon rule.\nThat operative regains up to Restoration D3+2 lost wounds.\nThat operative can immediately perform a free Charge or Dash action (for the former, it cannot Exigence move more than 3\"), but must end that move closer to that incapacitated INSPIRING operative." },
  { kind: 'faction', name: "Martyrdom", text: "Whenever an INSPIRING friendly CELESTIAN INSIDIANT operative is incapacitated, before it’s removed from the killzone, select one other friendly CELESTIAN INSIDIANT operative that operative is visible to or within 6\" of.\nThen, that selected operative gains one\nBENEDICTION (incapacitated operatives cannot be selected for a BENEDICTION)." },
  { kind: 'faction', name: "Weapons of the Witch Hunters", text: "PSYCHIC ranged weapons cannot inflict damage on friendly CELESTIAN INSIDIANT operatives. For the effects of PSYCHIC actions, friendly CELESTIAN INSIDIANT operatives cannot be selected and are never treated as being within those actions’ required distances. Whenever an operative is within 3\" of a friendly CELESTIAN INSIDIANT operative:\n• That operative cannot perform PSYCHIC actions or use PSYCHIC additional rules.\n• That operative cannot use PSYCHIC ranged weapons.\n• PSYCHIC melee weapons have no weapon rules and cannot have Dmg stats higher than 3/4." },
  { kind: 'faction', name: "Inspiration", text: "Whenever a friendly CELESTIAN INSIDIANT operative:\n• Incapacitates an enemy operative that has a Wounds stat of 6 or more, that friendly operative becomes INSPIRING.\n• Performs the Charge action, before it moves, it becomes INSPIRING. Whenever a friendly CELESTIAN INSIDIANT operative is INSPIRING, weapons on its datacard have the Severe weapon rule." },
  { kind: 'strategy', name: "Suspect & Eliminate", text: "Select one enemy operative or marker. If you select an enemy operative, that operative and each other enemy operative visible to and within 2\" of it gains one of your Suspicion tokens until the end of the turning point. If you selected a marker, each enemy operative contesting that marker gains one of your Suspicion tokens until the end of the turning point. Whenever a friendly CELESTIAN INSIDIANT operative is shooting against or fighting against an operative that has one of your Suspicion tokens, that friendly operative's weapons have the Punishing weapon rule." },
  { kind: 'strategy', name: "Suffering & Sacrifice", text: "Whenever a wounded friendly CELESTIAN INSIDIANT operative is shooting against, fighting against or retaliating against an enemy operative, its weapons have the Balanced weapon rule." },
  { kind: 'strategy', name: "Wrathful Determination", text: "Whenever an operative is shooting a friendly CELESTIAN INSIDIANT operative that has an Engage order, you can re-roll one of your defence dice." },
  { kind: 'strategy', name: "Holy Resilience", text: "Whenever an INSPIRING friendly CELESTIAN INSIDIANT operative is fighting or retaliating, Normal and Critical Dmg of 4 or more inflicts 1 less damage on that friendly operative." },
  { kind: 'firefight', name: "Glory to the Martyrs", text: "Use this firefight ploy when a friendly CELESTIAN INSIDIANT operative is incapacitated while fighting or retaliating. You can strike the enemy operative in that sequence with one of your unresolved successes before it’s removed from the killzone. If that enemy operative is incapacitated as a result, that friendly operative becomes INSPIRING before it’s removed from the killzone and you can resolve the Martyrdom faction rule." },
  { kind: 'firefight', name: "Unshakeable Pursuit", text: "Use this firefight ploy during a friendly CELESTIAN INSIDIANT operative’s activation, before or after it performs an action. Until the end of that operative’s activation, you can ignore any changes to its Move stat. If that operative is INSPIRING, add 1\" to its Move stat until the end of that activation. If that operative becomes INSPIRING by performing the Charge action, you can use this ploy before it moves to gain the additional movement (this takes precedence over stats not changing during an action)." },
  { kind: 'firefight', name: "Faith & Fury", text: "Use this firefight ploy when a friendly CELESTIAN INSIDIANT operative is fighting and you strike the enemy operative in that sequence with a critical success. After resolving that strike, also inflict D3 damage on each other enemy operative visible to and within 2\" of that friendly operative in an order of your choice (roll separately for each). Note that the friendly operative would become INSPIRING if any enemy operatives with a Wounds stat of 6 or more are incapacitated as a result of this damage." },
  { kind: 'firefight', name: "Fervent Hate", text: "Use this firefight ploy after rolling your attack dice for a friendly CELESTIAN INSIDIANT operative, if it’s shooting against, fighting against or retaliating against an enemy operative that doesn’t have the IMPERIUM keyword. That friendly operative’s weapons have the Ceaseless weapon rule until the end of that sequence; if that enemy operative also has the CHAOS and/or PSYKER keyword, that friendly operative’s weapons have the Relentless weapon rule until the end of that sequence instead." },
  { kind: 'equipment', name: "Psyk-out Grenades", text: "If you also select that equipment as normal, you cannot select any stun grenades (i.e. to give you more than two). Whenever an operative takes a stun test as a result of a friendly CELESTIAN INSIDIANT operative performing the Stun Grenade action, if the result is a 3+, also inflict damage on it equal to the dice result halved (rounding up). If that first operative has the PSYKER keyword, inflict damage on it equal to the dice result instead." },
  { kind: 'equipment', name: "Saintly Relics", text: "Whenever an attack dice would inflict damage on a friendly CELESTIAN INSIDIANT operative, you can use this rule. If you do, roll one D6, or two D6 if that operative is INSPIRING: if any result is a 6, ignore the damage inflicted from that attack dice. You cannot ignore more than one attack dice per action and two attack dice per battle this way." },
  { kind: 'equipment', name: "Vocifera Mortis", text: "Once per battle, when an INSPIRING friendly CELESTIAN INSIDIANT operative is incapacitated, you can use this rule. If you do, for the Martyrdom faction rule, the other friendly CELESTIAN INSIDIANT operative you select can be one that isn’t visible to or within 6\" of that operative." },
  { kind: 'equipment', name: "Auto-flagellator", text: "Whenever a friendly CELESTIAN INSIDIANT operative is activated, you can use this rule. If you do, roll one D6 and inflict damage on that operative equal to half the result (rounding up); on a 4+, that operative also becomes INSPIRING. You cannot make more than one friendly operative INSPIRING using this rule per turning point." },
]

export const operatives: Operative[] = [
  { id: "celestian-insidiants:insidiant-superior", name: "Insidiant Superior", apl: 3, move: "6\"", save: "3+", w: 10 },
  { id: "celestian-insidiants:insidiant-abjuror", name: "Insidiant Abjuror", apl: 2, move: "6\"", save: "2+", w: 11 },
  { id: "celestian-insidiants:insidiant-censor", name: "Insidiant Censor", apl: 2, move: "6\"", save: "3+", w: 9 },
  { id: "celestian-insidiants:insidiant-cremator", name: "Insidiant Cremator", apl: 2, move: "6\"", save: "3+", w: 9 },
  { id: "celestian-insidiants:insidiant-denuncia", name: "Insidiant Denuncia", apl: 2, move: "6\"", save: "3+", w: 9 },
  { id: "celestian-insidiants:insidiant-mortisanctus", name: "Insidiant Mortisanctus", apl: 2, move: "6\"", save: "3+", w: 9 },
  { id: "celestian-insidiants:insidiant-reliquarius", name: "Insidiant Reliquarius", apl: 2, move: "6\"", save: "3+", w: 9 },
  { id: "celestian-insidiants:insidiant-warrior", name: "Insidiant Warrior", apl: 2, move: "6\"", save: "3+", w: 9 },
]

export const datacards: Datacard[] = [
  {"name": "Insidiant Superior", "weapons": [{"name": "Inferno pistol", "atk": 4, "hit": "3+", "dmg": "4/2", "wr": "Range 3\", Devastating 3, Piercing 2"}, {"name": "Relic bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Lethal 5+"}, {"name": "Relic condemnor stakethrower", "atk": 4, "hit": "3+", "dmg": "2/2", "wr": "Devastating 2, Lethal 5+, Piercing Crits 1, Silent,"}], "abilities": [{"name": "Holy Example", "text": "Once per turning point, if this operative is INSPIRING, you can use a firefight ploy for 0CP if this is the specified CELESTIAN INSIDIANT operative (including Command Re-roll if the attack or defence dice was rolled for this operative)."}], "actions": [{"name": "Spiritual Mentor", "ap": 1, "text": "SUPPORT. Select one friendly CELESTIAN INSIDIANT operative visible to and within 6\" of this operative. That operative becomes INSPIRING.\nThis operative cannot perform this action while within control range of an enemy operative, or more than once per turning point."}], "keywords": ["CELESTIAN INSIDIANT", "IMPERIUM", "ADEPTA SORORITAS", "LEADER", "SUPERIOR"]},
  {"name": "Insidiant Abjuror", "weapons": [{"name": "Blessed sword & praesidium", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Shield*"}], "abilities": [{"name": "Holy Defender", "text": "Once per turning point, when a friendly CELESTIAN INSIDIANT operative visible to and within 2\" of this operative is selected as the valid target of a Shoot action or to fight against during the Fight action, you can use this rule. If you do, this operative becomes the valid target or is fought against (as appropriate) instead (even if it wouldn’t normally be valid for this). If it’s the Fight action, treat this operative as being within the fighting operative’s control range for the duration of that action. If it’s the Shoot action, this operative is only in cover or obscured if the original target was.\nThis rule has no effect if it’s the Shoot action and the ranged weapon has the Blast or Torrent weapon rule."}], "actions": [], "keywords": ["CELESTIAN INSIDIANT", "IMPERIUM", "ADEPTA SORORITAS", "ABJUROR"]},
  {"name": "Insidiant Censor", "weapons": [{"name": "Virge of admonition", "atk": 4, "hit": "4+", "dmg": "5/5", "wr": "Brutal, Shock, Anti-PSYKER*"}], "abilities": [{"name": "Virge of Admonition Icon Bearer", "text": "Whenever determining control of a marker, treat this operative’s APL stat as 1 higher. Note this\nisn't a change to its APL stat, so any changes are cumulative\nwith this."}, {"name": "Null Field", "text": "This operative starts the battle with a null range of 1\". Whenever an enemy operative is within null range of this operative, subtract 2\" from the Move stat of that enemy operative and worsen the Hit stat of its weapons by 1 (this isn’t cumulative with being injured)."}], "actions": [{"name": "Nullifying Ritual", "ap": 1, "text": "Add 1 to this operative’s null range (to a maximum of 5\").\nNullification tokens in the marker/token guide are numbered,\nso use the numbered token equal to this operative’s null range.\nThis operative cannot perform this action while within control range of an enemy operative, or more than once per turning point."}], "keywords": ["CELESTIAN INSIDIANT", "IMPERIUM", "ADEPTA SORORITAS", "CENSOR"]},
  {"name": "Insidiant Cremator", "weapons": [{"name": "Hand flamer (standard)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 6”, Saturate, Torrent 1”"}, {"name": "Hand flamer (deluge)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 4\", Saturate, Seek Light, Torrent 0\"1"}, {"name": "Null mace", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Shock, Anti-PSYKER*"}], "abilities": [{"name": "Inspirational Pyre", "text": "Once per turning point, when this operative\ninflicts damage on an enemy operative with either profile of its hand flamer but doesn’t incapacitate it, you can use this rule. If you do, you can select one friendly CELESTIAN INSIDIANT operative within 6\" of this operative to become INSPIRING."}], "actions": [], "keywords": ["CELESTIAN INSIDIANT", "IMPERIUM", "ADEPTA SORORITAS", "CREMATOR"]},
  {"name": "Insidiant Denuncia", "weapons": [{"name": "Voice of condemnation", "atk": 5, "hit": "3+", "dmg": "1/1", "wr": "Range 6\", Seek, Stun"}, {"name": "Staff of declamation", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Shock"}], "abilities": [{"name": "Accusing Exorcist", "text": "Whenever this operative is INSPIRING, the Suspect & Eliminate strategy ploy costs you 0CP if the enemy operative or marker you select is visible to or within 6\" of this operative."}], "actions": [{"name": "Speak of Her Deeds", "ap": 1, "text": "SUPPORT. Select an INSPIRING friendly CELESTIAN INSIDIANT operative visible to and within 6\" of this operative. That operative is no longer INSPIRING. Then, select another friendly CELESTIAN INSIDIANT operative visible to and within 6\" of this operative. Resolve one BENEDICTION from the Martyrdom faction rule on that operative (excluding Exigence).\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["CELESTIAN INSIDIANT", "IMPERIUM", "ADEPTA SORORITAS", "DENUNCIA"]},
  {"name": "Insidiant Mortisanctus", "weapons": [{"name": "Blessed broadsword", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+, Brutal"}], "abilities": [{"name": "Zealous Ultimatum", "text": "Once per battle STRATEGIC GAMBIT. Select one enemy operative within 8\" of this operative and issue an ultimatum to it. Your opponent must accept or decline that ultimatum (if it's a non-player operative, roll one D6: on a 4+, the ultimatum is accepted, otherwise it’s declined).\nIf the ultimatum is accepted, whenever this operative is fighting against or retaliating against that enemy operative, add 1 to the Atk stat of this operative's blessed broadsword. The first time this operative incapacitates that enemy operative while fighting or retaliating during the battle, add 1 to the Atk stat of this operative’s blessed broadsword until the end of the battle. In either case, this is to a maximum of 5.\nIf the ultimatum is declined, whenever that enemy operative is fighting against or retaliating against a friendly CELESTIAN INSIDIANT operative, subtract 1 from the Atk stat of that enemy operative’s weapons."}, {"name": "Bladed Stance", "text": "Whenever this operative is fighting or retaliating, you can resolve one of your successes before the normal order. If you do, that success must be used to block."}], "actions": [], "keywords": ["CELESTIAN INSIDIANT", "IMPERIUM", "ADEPTA SORORITAS", "MORTISANCTUS"]},
  {"name": "Insidiant Reliquarius", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Condemnor stakethrower", "atk": 4, "hit": "3+", "dmg": "2/2", "wr": "Devastating 1, Piercing Crits 1, Silent,"}], "abilities": [{"name": "Simulacrum Nullificatus Icon Bearer", "text": "Whenever determining control of a marker, treat the total APL stat of enemy operatives that contest it as 1 lower if at least one of those enemy operatives is within 3\" of this operative. Note this isn’t a change to the APL stat, so any changes are cumulative with this."}, {"name": "Devotion", "text": "At the end of each of this operative’s activations, if it’s INSPIRING and it controls an objective marker or one of your mission markers, one friendly CELESTIAN INSIDIANT operative this operative is visible to and within 6\" of becomes INSPIRING."}], "actions": [], "keywords": ["CELESTIAN INSIDIANT", "IMPERIUM", "ADEPTA SORORITAS", "RELIQUARIUS"]},
  {"name": "Insidiant Warrior", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Condemnor stakethrower", "atk": 4, "hit": "3+", "dmg": "2/2", "wr": "Devastating 1, Piercing Crits 1, Silent,"}], "abilities": [{"name": "Inspired Strikes", "text": "Whenever this operative is INSPIRING, add 1 to the Critical Dmg stat of weapons on its datacard."}], "actions": [], "keywords": ["CELESTIAN INSIDIANT", "IMPERIUM", "ADEPTA SORORITAS", "WARRIOR"]},
]
