// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Benedictions", text: "BENEDICTION EFFECT Until the end of the battle, add 1 to that operative’s Ardour APL stat. You cannot select this BENEDICTION for a SUPERIOR operative. Until the end of the battle, weapons on that operative’s Wrath datacard have the Ceaseless weapon rule.\nThat operative regains up to Restoration D3+2 lost wounds.\nThat operative can immediately perform a free Charge or Dash action (for the former, it cannot Exigence move more than 3\"), but must end that move closer to that incapacitated INSPIRING operative." },
  { kind: 'faction', name: "Martyrdom", text: "Whenever an INSPIRING friendly CELESTIAN INSIDIANT operative is incapacitated, before it’s removed from the killzone, select one other friendly CELESTIAN INSIDIANT operative that operative is visible to or within 6\" of.\nThen, that selected operative gains one\nBENEDICTION (incapacitated operatives cannot be selected for a BENEDICTION)." },
  { kind: 'faction', name: "Weapons of the Witch Hunters", text: "PSYCHIC ranged weapons cannot inflict damage on friendly CELESTIAN INSIDIANT operatives. For the effects of PSYCHIC actions, friendly CELESTIAN INSIDIANT operatives cannot be selected and are never treated as being within those actions’ required distances. Whenever an operative is within 3\" of a friendly CELESTIAN INSIDIANT operative:\n• That operative cannot perform PSYCHIC actions or use PSYCHIC additional rules.\n• That operative cannot use PSYCHIC ranged weapons.\n• PSYCHIC melee weapons have no weapon rules and cannot have Dmg stats higher than 3/4." },
  { kind: 'faction', name: "Inspiration", text: "Whenever a friendly CELESTIAN INSIDIANT operative:\n• Incapacitates an enemy operative that has a Wounds stat of 6 or more, that friendly operative becomes INSPIRING.\n• Performs the Charge action, before it moves, it becomes INSPIRING. Whenever a friendly CELESTIAN INSIDIANT operative is INSPIRING, weapons on its datacard have the Severe weapon rule." },
  { kind: 'strategy', name: "Suspect & Eliminate", text: "Select one enemy operative or marker. If you select an enemy operative, that operative and each other enemy operative visible to and within 2\" of it gains one of your Suspicion tokens until the end of the turning point. If you selected a marker, each enemy operative contesting that marker gains one of your Suspicion tokens until the end of the turning point. Whenever a friendly CELESTIAN INSIDIANT operative is shooting against or fighting against an operative that has one of your Suspicion tokens, that friendly operative's weapons have the Punishing weapon rule." },
  { kind: 'strategy', name: "Suffering & Sacrifice", text: "Whenever a wounded friendly CELESTIAN INSIDIANT operative is shooting against, fighting against or retaliating against an enemy operative, its weapons have the Balanced weapon rule." },
  { kind: 'strategy', name: "Wrathful Determination", text: "Whenever an operative is shooting a friendly CELESTIAN INSIDIANT operative that has an Engage order, you can re-roll one of your defence dice." },
  { kind: 'strategy', name: "Holy Resilience", text: "Whenever an INSPIRING friendly CELESTIAN INSIDIANT operative is fighting or retaliating, Normal and Critical Dmg of 4 or more inflicts 1 less damage on that friendly operative." },
  { kind: 'firefight', name: "Glory to the Martyrs", text: "Use this firefight ploy when a friendly CELESTIAN INSIDIANT operative is incapacitated while fighting or retaliating. You can strike the enemy operative in that sequence with one of your unresolved successes before it’s removed from the killzone. If that enemy operative is incapacitated as a result, that friendly operative becomes INSPIRING before it’s removed from the killzone and you can resolve the Martyrdom faction rule." },
  { kind: 'firefight', name: "Unshakeable Pursuit", text: "Use this firefight ploy during a friendly CELESTIAN INSIDIANT operative’s activation, before or after it performs an action. Until the end of that operative’s activation, you can ignore any changes to its Move stat. If that operative is INSPIRING, add 1\" to its Move stat until the end of that activation. If that operative becomes INSPIRING by performing the Charge action, you can use this ploy before it moves to gain the additional movement (this takes precedence over stats not changing during an action)." },
  { kind: 'firefight', name: "Faith & Fury", text: "Use this firefight ploy when a friendly CELESTIAN INSIDIANT operative is fighting and you strike the enemy operative in that sequence with a critical success. After resolving that strike, also inflict D3 damage on each other enemy operative visible to and within 2\" of that friendly operative in an order of your choice (roll separately for each). Note that the friendly operative would become INSPIRING if any enemy operatives with a Wounds stat of 6 or more are incapacitated as a result of this damage." },
  { kind: 'firefight', name: "Fervent Hate", text: "Use this firefight ploy after rolling your attack dice for a friendly CELESTIAN INSIDIANT operative, if it’s shooting against, fighting against or retaliating against an enemy operative that doesn’t have the IMPERIUM keyword. That friendly operative’s weapons have the Ceaseless weapon rule until the end of that sequence; if that enemy operative also has the CHAOS and/or PSYKER keyword, that friendly operative’s weapons have the Relentless weapon rule until the end of that sequence instead." },
  { kind: 'equipment', name: "Psyk-out Grenades", text: "If you also select that equipment as normal, you cannot select any stun grenades (i.e. to give you more than two). Whenever an operative takes a stun test as a result of a friendly CELESTIAN INSIDIANT operative performing the Stun Grenade action, if the result is a 3+, also inflict damage on it equal to the dice result halved (rounding up). If that first operative has the PSYKER keyword, inflict damage on it equal to the dice result instead." },
  { kind: 'equipment', name: "Saintly Relics", text: "Whenever an attack dice would inflict damage on a friendly CELESTIAN INSIDIANT operative, you can use this rule. If you do, roll one D6, or two D6 if that operative is INSPIRING: if any result is a 6, ignore the damage inflicted from that attack dice. You cannot ignore more than one attack dice per action and two attack dice per battle this way." },
  { kind: 'equipment', name: "Vocifera Mortis", text: "Once per battle, when an INSPIRING friendly CELESTIAN INSIDIANT operative is incapacitated, you can use this rule. If you do, for the Martyrdom faction rule, the other friendly CELESTIAN INSIDIANT operative you select can be one that isn’t visible to or within 6\" of that operative." },
  { kind: 'equipment', name: "Auto-flagellator", text: "Whenever a friendly CELESTIAN INSIDIANT operative is activated, you can use this rule. If you do, roll one D6 and inflict damage on that operative equal to half the result (rounding up); on a 4+, that operative also becomes INSPIRING. You cannot make more than one friendly operative INSPIRING using this rule per turning point." },
]

export const operatives: Operative[] = [
  { id: "celestian-insidiants:insidiant-superior", name: "Insidiant Superior", apl: 3, move: "6\"", save: "3+", w: 10 },
  { id: "celestian-insidiants:insidiant-abjuror", name: "Insidiant Abjuror", apl: 2, move: "6\"", save: "2+", w: 11 },
  { id: "celestian-insidiants:insidiant-censor", name: "Insidiant Censor", apl: 2, move: "6\"", save: "3+", w: 9 },
  { id: "celestian-insidiants:insidiant-cremator", name: "Insidiant Cremator", apl: 2, move: "6\"", save: "3+", w: 9 },
  { id: "celestian-insidiants:insidiant-denuncia", name: "Insidiant Denuncia", apl: 2, move: "6\"", save: "3+", w: 9 },
  { id: "celestian-insidiants:insidiant-mortisanctus", name: "Insidiant Mortisanctus", apl: 2, move: "6\"", save: "3+", w: 9 },
  { id: "celestian-insidiants:insidiant-reliquarius", name: "Insidiant Reliquarius", apl: 2, move: "6\"", save: "3+", w: 9 },
  { id: "celestian-insidiants:insidiant-warrior", name: "Insidiant Warrior", apl: 2, move: "6\"", save: "3+", w: 9 },
]
