// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Accursed Gifts", text: "Whenever this operative is climbing up, you can treat the vertical distance as 2\" (regardless of how far the operative actually moves vertically). Whenever this operative is dropping, ignore the vertical distance.\nACCURSED GIFTS are rules that friendly CHAOS CULT operatives gain when they turn into another operative type (see Mutation faction rule). The first time a friendly DEVOTEE operative turns into a MUTANT operative during the battle, select your primary ACCURSED GIFT. The first time a friendly MUTANT operative turns into a TORMENT operative during the battle, select your secondary ACCURSED GIFT. All friendly MUTANT operatives have your primary ACCURSED GIFT, and all friendly TORMENT operatives have your primary and secondary ACCURSED GIFTS. You cannot select the same ACCURSED GIFT more than once per battle.\nACCURSED GIFT OPTIONS ARE PRESENTED ON THEIR OWN CARDS\nAdd 1\" to this operative’s Move stat.\n3. Chitinous Hardened plates formed of chitinous, daemonic material erupt from angry, swollen flesh, lending the accursed unholy resilience and turning lasbolts, bullets and blades aside.\nImprove this operative’s Save stat by 1.\nYou can ignore any changes to the Hit stat of this operative’s melee weapons from being injured.\nThis operative’s melee weapons have the Brutal weapon rule.\nWhenever this operative ends its move during the Charge action, you can inflict 1 damage on one enemy operative within its control range, or D3 damage instead if this operative is a TORMENT.\nWhenever this operative is fighting or retaliating:\n• Enemy operatives cannot assist.\n• The first time you strike during that sequence, also inflict 1 damage on each other enemy operative within this operative’s control range, or D3 damage instead if this operative is a TORMENT (roll separately for each)." },
  { kind: 'faction', name: "Mutation", text: "During the battle, friendly CHAOS CULT operatives can MUTATE as follows:\n• As a STRATEGIC GAMBIT, you can MUTATE a number of friendly CHAOS CULT operatives based on the turning point as follows: TP1 = 2, TP2 = 2, TP3 = 3, TP4+ = 4.\n• Whenever a friendly DEVOTEE operative incapacitates an enemy operative within its control range, it can MUTATE.\n• Each operative cannot MUTATE more than once per turning point." },
  { kind: 'strategy', name: "Exaltation in Pain", text: "You can ignore any changes to the Hit stat of friendly CHAOS CULT operatives’ weapons from being injured. Whenever an operative is shooting a friendly CHAOS CULT operative that’s wounded, you can re-roll one of your defence dice." },
  { kind: 'strategy', name: "Fervent Onslaught", text: "Friendly CHAOS CULT operatives’ melee weapons have the Accurate 1 weapon rule, or the Accurate 2 weapon rule if that friendly operative is a MUTANT or TORMENT operative." },
  { kind: 'strategy', name: "Creatures of Nightmare", text: "Whenever determining control of a marker, treat the total APL stat of enemy operatives that contest it as 1 lower if at least one of those enemy operatives is within 2\" of friendly CHAOS CULT MUTANT or CHAOS CULT TORMENT operatives. Note this isn’t a change to the APL stat, so any changes are cumulative with this." },
  { kind: 'firefight', name: "Faithful Follower", text: "Use this firefight ploy when a friendly CHAOS CULT DARK COMMUNE operative is selected as the valid target of a Shoot action or to fight against during the Fight action. Select one other friendly CHAOS CULT operative (excluding DARK COMMUNE) visible to and within 3\" of that DARK COMMUNE operative to become the valid target or to be fought against (as appropriate) instead (even if it wouldn’t normally be valid for this). If it’s the Fight action, treat that other operative as being within the fighting operative’s control range for the duration of that action. If it’s the Shoot action, that other operative is only in cover or obscured if the original target was. This ploy has no effect if it’s the Shoot action and the ranged weapon has the Blast or Torrent weapon rule." },
  { kind: 'strategy', name: "Sickening Aura", text: "Whenever an enemy operative is within 2\" of friendly CHAOS CULT MUTANT or CHAOS CULT TORMENT operatives, worsen the Hit stat of that enemy operative’s weapons by 1. This isn’t cumulative with being injured." },
  { kind: 'firefight', name: "Abhorrent Mutation", text: "In the midst of battle, when violence and emotion run rampant, the Ruinous Powers bestow upon their underlings their accursed gifts. Use this firefight ploy when a friendly CHAOS CULT operative (excluding DARK COMMUNE) is activated. Select an ACCURSED GIFT for that operative to gain. This is in addition to any ACCURSED GIFTS it already has. Each friendly operative cannot be selected for this ploy more than once per battle, and if that operative turns into a different one (see Mutation faction rule), it still has that ACCURSED GIFT." },
  { kind: 'firefight', name: "Frenzied Demise", text: "Use this firefight ploy when a friendly CHAOS CULT MUTANT or CHAOS CULT TORMENT operative is incapacitated, before it’s removed from the killzone. Inflict D3 damage (or D6 damage instead if that friendly operative is a TORMENT) on one enemy operative visible to and within 2\" of that friendly operative." },
  { kind: 'equipment', name: "Baleful Script", text: "Once per battle STRATEGIC GAMBIT. Change one of your ACCURSED GIFTS. Note that if it's an ACCURSED GIFT an operative has from the Abhorrent Mutation firefight ploy, only that operative benefits from this." },
  { kind: 'firefight', name: "Unleash the Daemon", text: "Use this firefight ploy during a friendly CHAOS CULT MUTANT or CHAOS CULT TORMENT operative’s activation, before or after it performs an action. During that activation, that operative can perform two Fight actions, and one of them can be free." },
  { kind: 'equipment', name: "Covert Guises", text: "After revealing this equipment option, roll one D3. As a STRATEGIC GAMBIT in the first turning point, a number of friendly CHAOS CULT DEVOTEE operatives equal to the result that are wholly within your drop zone can immediately perform a free Reposition action, but must end that move wholly within 3\" of your drop zone." },
  { kind: 'equipment', name: "Unholy Talisman", text: "Once per turning point, when an operative is shooting a friendly CHAOS CULT operative, in the Roll Defence Dice step, you can retain one of your normal successes as a critical success instead." },
  { kind: 'equipment', name: "Vile Blessing", text: "Once per battle, when an attack dice inflicts Normal Dmg on a friendly CHAOS CULT operative (excluding DEVOTEE), you can ignore that inflicted damage. If that friendly operative is a MUTANT or TORMENT operative, you cannot roll for the Unnatural Regeneration rule for that attack dice then decide to use this rule on the same dice – you must use one or the other." },
]

export const operatives: Operative[] = [
  { id: "chaos-cult:cult-demagogue", name: "Cult Demagogue", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "chaos-cult:blessed-blade", name: "Blessed Blade", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "chaos-cult:iconarch", name: "Iconarch", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "chaos-cult:mindwitch", name: "Mindwitch", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "chaos-cult:chaos-devotee", name: "Chaos Devotee", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "chaos-cult:chaos-mutant", name: "Chaos Mutant", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "chaos-cult:chaos-torment", name: "Chaos Torment", apl: 2, move: "6\"", save: "5+", w: 13 },
]

export const datacards: Datacard[] = [
  {"name": "Cult Demagogue", "weapons": [{"name": "Diabolical stave (ranged)", "atk": 4, "hit": "4+", "dmg": "3/6", "wr": "Range 2\", Stun"}, {"name": "Pistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Diabolical stave (melee)", "atk": 4, "hit": "4+", "dmg": "3/6", "wr": "Shock, Stun"}], "abilities": [], "actions": [{"name": "Incite Slaughter", "ap": 1, "text": "SUPPORT. One other friendly CHAOS CULT operative visible to and within 9\" of this operative can immediately perform a free Fight action.\nThis operative cannot perform this action while within control range of an enemy operative."}, {"name": "Incite Urgency", "ap": 1, "text": "SUPPORT. One other friendly CHAOS CULT operative visible to and within 9\" of this operative can immediately perform a free Charge or Dash action (for the former, it cannot move more than 3\").\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["CHAOS CULT", "CHAOS", "LEADER", "DARK COMMUNE", "CULT DEMAGOGUE"], "img": "/ops/chaos-cult/cult-demagogue.webp"},
  {"name": "Blessed Blade", "weapons": [{"name": "Commune blade", "atk": 4, "hit": "4+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Cut Them Down", "text": "Whenever an enemy operative performs the Fall Back action while within control range of this operative, you can use this rule. If you do, inflict D3+1 damage on that enemy operative before it moves. If that enemy operative is within control range of two of these operatives, inflict 2D3+2 damage instead."}, {"name": "Attuned In Purpose", "text": "Whenever this operative is activated, you can activate another ready friendly BLESSED BLADE operative within 6\" of it at the same time. Complete their activations action by action in any order."}], "actions": [], "keywords": ["CHAOS CULT", "CHAOS", "DARK COMMUNE", "BLESSED BLADE"], "img": "/ops/chaos-cult/blessed-blade.webp"},
  {"name": "Iconarch", "weapons": [{"name": "Burning censer", "atk": 4, "hit": "2+", "dmg": "4/4", "wr": "Range 5\", Saturate, Torrent 2\""}, {"name": "Pistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Crude melee weapon", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Icon Bearer", "text": "Whenever determining control of a marker, treat this operative’s APL stat as 1 higher. Note this isn’t a change to its APL stat, so any changes are cumulative with this."}], "actions": [{"name": "Ruinous Icon", "ap": 1, "text": "PSYCHIC. Select one of the following effects to last                         This operative cannot perform this action while within control until the start of this operative’s next activation, until                   range of an enemy operative. it’s incapacitated or until it performs this action again (whichever comes first):\n• Invigoration: PSYCHIC. Whenever a friendly CHAOS CULT operative is within 4\" of this operative, Normal and Critical Dmg of 4 or more inflicts 1 less damage on that operative. • Deterioration: PSYCHIC. Whenever an enemy operative is within 4\" of this operative, Normal and Critical Dmg inflicts 1 more damage on that operative."}], "keywords": ["CHAOS CULT", "CHAOS", "DARK COMMUNE", "PSYKER", "ICONARCH"], "img": "/ops/chaos-cult/iconarch.webp"},
  {"name": "Mindwitch", "weapons": [{"name": "Infernal gaze", "atk": 5, "hit": "3+", "dmg": "0/0", "wr": "PSYCHIC, Range 6\", Devastating 2, Lethal 3+"}, {"name": "Fists", "atk": 3, "hit": "5+", "dmg": "1/2"}], "abilities": [], "actions": [{"name": "Heinous Deluge", "ap": 1, "text": "PSYCHIC. Select one enemy operative that's a valid target for this operative. Until the end of that operative’s next activation, subtract 1 from its APL stat. This operative cannot perform this action while within control range of an enemy operative."}, {"name": "Malefic Vortex", "ap": 1, "text": "PSYCHIC. Remove your Malefic Vortex marker from the killzone (if any). Then place your Malefic Vortex marker visible to this operative, or on Vantage terrain of a terrain feature that’s visible to this operative. Inflict 1 damage on each enemy operative within 2\" of that marker. In addition, in the Ready step of each Strategy phase, inflict 1 damage on each enemy operative within 2\" of that marker.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["CHAOS CULT", "CHAOS", "DARK COMMUNE", "PSYKER", "MINDWITCH"], "img": "/ops/chaos-cult/mindwitch.webp"},
  {"name": "Chaos Devotee", "weapons": [{"name": "Pistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Crude melee weapon", "atk": 4, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Group Activation", "text": "Whenever this operative is expended, you must then activate one other ready friendly CHAOS CULT DEVOTEE operative (if able) before your opponent activates. When that other operative is expended, your opponent then activates as normal (in other words, you cannot activate more than two operatives in succession with this rule)."}], "actions": [], "keywords": ["CHAOS CULT", "CHAOS", "DEVOTEE"], "img": "/ops/chaos-cult/chaos-devotee.webp"},
  {"name": "Chaos Mutant", "weapons": [{"name": "Blasphemous appendages", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless, Rending"}], "abilities": [{"name": "Accursed Mutant", "text": "This operative cannot perform unique actions. You must spend 1 additional AP for this operative to perform the Pick Up Marker and mission actions (excluding Operate Hatch)."}, {"name": "Unnatural Regeneration", "text": "Whenever an attack dice inflicts damage of 3 or more on this operative, roll one D6: on a 5+, subtract 1 from that inflicted damage."}], "actions": [], "keywords": ["CHAOS CULT", "CHAOS", "MUTANT"], "img": "/ops/chaos-cult/chaos-mutant.webp"},
  {"name": "Chaos Torment", "weapons": [{"name": "Hideous mutations", "atk": 5, "hit": "4+", "dmg": "4/5", "wr": "Ceaseless, Rending"}], "abilities": [{"name": "Accursed Torment", "text": "This operative cannot use any weapons that aren’t on its datacard, or perform the Pick Up Marker, unique or mission actions (excluding Operate Hatch)."}, {"name": "Brute", "text": "Whenever your opponent is selecting a valid target, if this operative has a Conceal order, it cannot use Light terrain for cover. While this can allow this operative to be targeted (assuming it’s visible), it doesn’t remove its cover save (if any)."}, {"name": "Unnatural Regeneration", "text": "Whenever an attack dice inflicts damage of 3 or more on this operative, roll one D6: on a 5+, subtract 1 from that inflicted damage."}], "actions": [], "keywords": ["CHAOS CULT", "CHAOS", "TORMENT"], "img": "/ops/chaos-cult/chaos-torment.webp"},
]
