// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Rifles", text: "Whenever a friendly CORSAIR VOIDSCARRED operative is shooting with a shuriken rifle or ranger long rifle during an activation in which it hasn’t performed the Charge, Fall Back or Reposition action, that weapon has the Accurate 1 weapon rule. Note that operative isn’t restricted from performing those actions after shooting." },
  { kind: 'faction', name: "Aeldari Raiders", text: "Each friendly CORSAIR VOIDSCARRED operative can perform a free Dash action during their activation." },
  { kind: 'strategy', name: "Piratical Profiteers", text: "Whenever a friendly CORSAIR VOIDSCARRED operative is shooting, fighting or retaliating, if it or the enemy operative in that sequence contests an objective marker or one of your mission markers, that friendly operative’s weapons have the Balanced weapon rule." },
  { kind: 'strategy', name: "Plunderers", text: "Up to D3 friendly CORSAIR VOIDSCARRED operatives can immediately perform a free Dash action in an order of your choice. This turning point, each that does so cannot perform the Dash action during their activation. You cannot use this ploy during the first turning point." },
  { kind: 'strategy', name: "Mobile Engagement", text: "Whenever an operative is shooting a friendly CORSAIR VOIDSCARRED operative that performed an action in which it moved during this turning point, you can re-roll one of your defence dice." },
  { kind: 'strategy', name: "Outcasts", text: "Whenever a friendly CORSAIR VOIDSCARRED operative is more than 5\" from other friendly operatives, its weapons have the Punishing weapon rule." },
  { kind: 'firefight', name: "Light Fingers", text: "Use this firefight ploy during a friendly CORSAIR VOIDSCARRED operative’s activation. Until the end of that activation, having an enemy operative within its control range doesn’t prevent that friendly operative from performing the Pick Up Marker or mission actions." },
  { kind: 'firefight', name: "Opportunistic Fighters", text: "Use this firefight ploy when an enemy operative performs the Fall Back action. Before it moves, inflict 2D3 damage on that operative for each friendly CORSAIR VOIDSCARRED operative within its control range." },
  { kind: 'firefight', name: "Capricious Flight", text: "Use this firefight ploy during a friendly CORSAIR VOIDSCARRED operative’s activation, before or after it performs an action. During that activation, that operative can perform the Fall Back action for 1 less AP." },
  { kind: 'firefight', name: "Contemptuous Adventurer", text: "Use this firefight ploy when the first friendly\nCORSAIR VOIDSCARRED operative is activated during the turning point, if it’s more than 5\" from other friendly operatives. The first time that operative performs either the Shoot or Fight action during that activation, its weapons have the Relentless weapon rule. Note this ploy cannot come into effect more than once per activation (you cannot use it during both the Shoot and Fight action in the same activation)." },
  { kind: 'equipment', name: "Mistfield", text: "Once per turning point, when an operative is shooting a friendly CORSAIR VOIDSCARRED operative more than 3\" from it, at the start of the Roll Defence Dice step, you can use this rule. If you do, worsen the x of the Piercing weapon rule by 1 (if any) until the end of that sequence. Note that Piercing 1 would therefore be ignored." },
  { kind: 'equipment', name: "Diuturnal Mantles", text: "Whenever an operative is shooting a friendly\nCORSAIR VOIDSCARRED operative, if the ranged weapon in that sequence has the Blast or Torrent weapon rule, you can re-roll one of your defence dice. In addition, friendly CORSAIR VOIDSCARRED operatives aren’t affected by the x\" Devastating x weapon rule (i.e. Devastating with a distance) unless they are the target during that sequence." },
  { kind: 'equipment', name: "Runes of Guidance", text: "Once per turning point, when a friendly CORSAIR VOIDSCARRED WAY SEEKER or CORSAIR VOIDSCARRED SOUL WEAVER operative is performing a PSYCHIC unique action (excluding Warp Fold), you can use this rule. If you do, until the end of that action, add 3\" to its distance requirement. Note this has no effect on PSYCHIC weapons (e.g. the Devastating distance requirement of lightning strike)." },
  { kind: 'equipment', name: "Star Charts", text: "STRATEGIC GAMBIT. Roll one D3: if the result is higher than the number of the current turning point, you gain 1CP and cannot use this STRATEGIC GAMBIT for the rest of the battle." },
]

export const operatives: Operative[] = [
  { id: "corsair-voidscarred:voidscarred-felarch", name: "Voidscarred Felarch", apl: 2, move: "7\"", save: "4+", w: 9 },
  { id: "corsair-voidscarred:voidscarred-fate-dealer", name: "Voidscarred Fate Dealer", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "corsair-voidscarred:voidscarred-gunner", name: "Voidscarred Gunner", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "corsair-voidscarred:voidscarred-heavy-gunner", name: "Voidscarred Heavy Gunner", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "corsair-voidscarred:voidscarred-kurnathi", name: "Voidscarred Kurnathi", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "corsair-voidscarred:voidscarred-kurnite-hunter", name: "Voidscarred Kurnite Hunter", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "corsair-voidscarred:voidscarred-shade-runner", name: "Voidscarred Shade Runner", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "corsair-voidscarred:voidscarred-soul-weaver", name: "Voidscarred Soul Weaver", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "corsair-voidscarred:voidscarred-starstorm-duellist", name: "Voidscarred Starstorm Duellist", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "corsair-voidscarred:voidscarred-warrior", name: "Voidscarred Warrior", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "corsair-voidscarred:voidscarred-way-seeker", name: "Voidscarred Way Seeker", apl: 2, move: "7\"", save: "4+", w: 8 },
]

export const datacards: Datacard[] = [
  {"name": "Voidscarred Felarch", "weapons": [{"name": "Neuro disruptor", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Piercing 1, Stun"}, {"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Shuriken rifle", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Rending"}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Veteran Raider", "text": "This operative    One Step Ahead: Once per battle, after an enemy operative performs an action, if this operative is can perform a 1AP action for      ready, you can use this rule. If you do, roll one D6: if the result is higher than that enemy operative’s free during their activation      APL stat, you can interrupt and immediately perform either a free Shoot or a free Fight action with as a result of the Aeldari        this operative, but you cannot select any other enemy operative as a valid target or to fight against Raiders rule (instead of the      during that action (note that secondary targets from the Blast weapon rule can still be targeted). After Dash action).                     you perform that action, subtract 1 from this operative’s APL stat until the end of its next activation."}], "actions": [], "keywords": ["CORSAIR VOIDSCARRED", "AELDARI", "ANHRATHE", "LEADER", "FELARCH"]},
  {"name": "Voidscarred Fate Dealer", "weapons": [{"name": "Ranger long rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Ranger long rifle (stationary)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy, Silent"}, {"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Fists", "atk": 3, "hit": "3+", "dmg": "2/3"}], "abilities": [{"name": "Camo Cloak", "text": "Whenever an operative is shooting this operative:\n• Ignore the Saturate weapon rule. • If you can retain any cover saves, you can retain one additional cover save, or you can retain one cover save as a critical success instead. This isn’t cumulative with improved cover saves from Vantage terrain."}], "actions": [], "keywords": ["CORSAIR VOIDSCARRED", "AELDARI", "ANHRATHE", "FATE DEALER"]},
  {"name": "Voidscarred Gunner", "weapons": [{"name": "Blaster", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Piercing 2"}, {"name": "Shredder", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Rending, Torrent 2\""}, {"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Fists", "atk": 3, "hit": "3+", "dmg": "2/3"}], "abilities": [], "actions": [], "keywords": ["CORSAIR VOIDSCARRED", "AELDARI", "ANHRATHE", "GUNNER"]},
  {"name": "Voidscarred Heavy Gunner", "weapons": [{"name": "Shuriken cannon (focused)", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Heavy (Dash only), Rending"}, {"name": "Shuriken cannon (sweeping)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Heavy (Dash only), Rending, Torrent 1\""}, {"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Wraithcannon", "atk": 4, "hit": "3+", "dmg": "6/3", "wr": "Devastating 4, Heavy (Dash only), Piercing 2"}, {"name": "Fists", "atk": 3, "hit": "3+", "dmg": "2/3"}], "abilities": [], "actions": [], "keywords": ["CORSAIR VOIDSCARRED", "AELDARI", "ANHRATHE", "HEAVY GUNNER"]},
  {"name": "Voidscarred Kurnathi", "weapons": [{"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Dual power weapons", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Ceaseless, Lethal 5+"}], "abilities": [{"name": "Blademaster", "text": "This operative can perform the Dash action during an activation in which it performed the Charge action, but can only use any remaining move distance it had from that Charge action (to a maximum of 3\")."}, {"name": "Bladed Stance", "text": "Whenever this operative is fighting or retaliating, you can resolve one of your successes before the normal order. If you do, that success must be used to block."}], "actions": [], "keywords": ["CORSAIR VOIDSCARRED", "AELDARI", "ANHRATHE", "KURNATHI"]},
  {"name": "Voidscarred Kurnite Hunter", "weapons": [{"name": "Faolchú", "atk": 4, "hit": "3+", "dmg": "1/2", "wr": "Rending, Saturate, Seek Light, Silent"}, {"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Faolchú’s Bond", "text": "The first time during each turning point that this operative is retaliating, if it’s ready, in the Resolve Attack Dice step of that sequence, you resolve the first attack dice (i.e. defender instead of attacker)."}, {"name": "Erudite Hunter", "text": "STRATEGIC GAMBIT. Select one enemy operative within 9\" of this operative. Once during this turning point, after that enemy operative performs an action in which it moves, you can interrupt to use this rule. If you do, this operative can immediately perform either a free Reposition action (it cannot end that move further away from that enemy operative), or a free Charge action (you can change its order to do so, and it must end that move within control range of that enemy operative). In a killzone that uses the close quarters rules (e.g. Killzone: Tomb World), ignore Wall terrain when determining further away."}], "actions": [], "keywords": ["CORSAIR VOIDSCARRED", "AELDARI", "ANHRATHE", "KURNITE HUNTER"]},
  {"name": "Voidscarred Shade Runner", "weapons": [{"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Throwing blades", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Range 6\", Silent"}, {"name": "Hekatarii blades", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Ceaseless, Lethal 5+"}], "abilities": [{"name": "Blink Pack", "text": "Whenever this operative performs the Charge, Fall Back or Reposition action, it can warp jump. If it does, don’t move it. Instead, remove it from the killzone and set it back up wholly within 7\" horizontally of its original location (in a killzone that uses the close quarters rules, e.g. Killzone: Tomb World, this distance can be measured through Wall terrain). It must be set up in a location it can be placed, and unless it’s the Charge action, it cannot be set up within control range of an enemy operative."}, {"name": "Slicing Attack", "text": "Whenever this operative performs the Reposition action with a warp jump (see other side of card),\nyou can use this rule. If you do, after it moves, draw an imaginary\nline 1mm in diameter and up to 7\" long between it and its previous location. Note this doesn’t have to be a straight line. Inflict D3+2 damage on one enemy operative that line crosses. You cannot inflict damage on an enemy operative that was not visible to this operative at the start of that action. A 28mm round marker can be temporarily placed underneath this operative before it moves to help determine this."}], "actions": [], "keywords": ["CORSAIR VOIDSCARRED", "AELDARI", "ANHRATHE", "SHADE RUNNER"]},
  {"name": "Voidscarred Soul Weaver", "weapons": [{"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [], "actions": [{"name": "Soul Channel", "ap": 1, "text": "PSYCHIC. Select one other friendly CORSAIR VOIDSCARRED operative visible to and within 6\" of this operative. Until the end of that operative’s next activation, add 1 to its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative."}, {"name": "Soul Heal", "ap": 1, "text": "PSYCHIC. Select one friendly CORSAIR VOIDSCARRED operative visible to and within 6\" of this operative. That operative regains up to 2D3 lost wounds.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["CORSAIR VOIDSCARRED", "AELDARI", "ANHRATHE", "PSYKER", "MEDIC", "SOUL WEAVER"]},
  {"name": "Voidscarred Starstorm Duellist", "weapons": [{"name": "Fusion pistol", "atk": 4, "hit": "3+", "dmg": "5/3", "wr": "Range 3\", Devastating 3, Piercing 2"}, {"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Fists", "atk": 3, "hit": "3+", "dmg": "2/3"}], "abilities": [{"name": "Quick on the Trigger", "text": "This operative can perform the Shoot action while within control range of an enemy operative. If it\ndoes, when selecting a valid target, you can only select an\nenemy operative within this operative’s control range, and can\ndo so even if other friendly operatives are within that enemy\noperative’s control range."}], "actions": [{"name": "Pistol Barrage", "ap": 1, "text": "Perform two free Shoot actions with this operative (this\ntakes precedence over action restrictions). You must select\nits fusion pistol for one action and its shuriken pistol for the\nother (in any order).\nThis operative cannot perform this action while it has a Conceal order, or during an activation in which it performed the Shoot action (or vice versa)."}], "keywords": ["CORSAIR VOIDSCARRED", "AELDARI", "ANHRATHE", "STARSTORM DUELLIST"]},
  {"name": "Voidscarred Warrior", "weapons": [{"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Shuriken rifle", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Rending"}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}, {"name": "Fists", "atk": 3, "hit": "3+", "dmg": "2/3"}], "abilities": [{"name": "Prowling Raiders", "text": "You can use the Capricious Flight and Light Fingers firefight ploys for 0CP each if a friendly WARRIOR operative is the specified CORSAIR VOIDSCARRED operative."}], "actions": [], "keywords": ["CORSAIR VOIDSCARRED", "AELDARI", "ANHRATHE", "WARRIOR"]},
  {"name": "Voidscarred Way Seeker", "weapons": [{"name": "Freezing grasp", "atk": 4, "hit": "3+", "dmg": "1/2", "wr": "PSYCHIC, Severe, Silent, Stun"}, {"name": "Lightning strike", "atk": 4, "hit": "3+", "dmg": "4/3", "wr": "PSYCHIC, 2\" Devastating 2"}, {"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Witch staff", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "PSYCHIC, Shock"}], "abilities": [], "actions": [{"name": "Warp Fold", "ap": 1, "text": "PSYCHIC. Select two friendly CORSAIR VOIDSCARRED operatives visible to and within 5\" of this operative. Remove them both from the killzone and set them back up in each other’s previous locations (in other words, swap their positions). If one of them performed the Charge, Fall Back or Reposition action during this turning point and the other is ready, the other cannot perform any of those actions in its activation during this turning point.\nThis operative cannot perform this action while within control range of an enemy operative."}, {"name": "Warding Shield", "ap": 1, "text": "PSYCHIC. Select one friendly CORSAIR VOIDSCARRED operative visible to and within 6\" of this operative. Until the start of this operative’s next activation, until it’s incapacitated or until it performs this action again (whichever comes first), the first time an attack dice inflicts Normal Dmg on that friendly operative, ignore that inflicted damage.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["CORSAIR VOIDSCARRED", "AELDARI", "ANHRATHE", "PSYKER", "WAY SEEKER"]},
]
