// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Guardsmen Orders", text: "STRATEGIC GAMBIT and SUPPORT. A friendly\nDEATH KORPS WATCHMASTER operative can issue a GUARDSMAN ORDER. Whenever it does, select one GUARDSMAN ORDER for all friendly DEATH KORPS operatives within 6\" of it to receive. Whenever a friendly operative receives a\nGUARDSMAN ORDER, apply its rules until the end of the turning point. Operatives cannot benefit from more than one GUARDSMAN ORDER at once; they only benefit from the most recent order they received during the turning point.\nTake Aim! Outfitted and trained for attritional infantry combat, the soldiers of Krieg have undertaken endless hours of lasgun drills.\nRanged weapons of operatives that received this order (excluding mortar barrage and remote detonator) have the Ceaseless weapon rule.\nFix Bayonets! The kind of warfare undertaken by the Death Korps of Krieg requires their troopers to be well versed in close-quarters fighting and trench clearance. Melee weapons of operatives that received this order have the Ceaseless weapon rule.\nWhenever an operative is shooting a friendly operative that’s received this order, if you can retain any cover saves, you can re-roll any of your defence dice results of one result (e.g. results of 2).\nMove! Move! Move! Responding to a barked order from their Watchmaster, the soldiers of Krieg pick up the pace and hustle towards their next objective. Whenever an operative that’s received this order is performing the Reposition action, add 1\" to its Move stat." },
  { kind: 'strategy', name: "Siege Warfare", text: "Friendly DEATH KORPS operatives’ ranged weapons have the Saturate and Accurate 1 weapon rules." },
  { kind: 'strategy', name: "Take Cover", text: "Whenever an operative is shooting a friendly DEATH KORPS operative, if you can retain any cover saves, improve that friendly operative’s Save stat by 1." },
  { kind: 'strategy', name: "Clear the Line", text: "Friendly DEATH KORPS operatives’ melee weapons have the Accurate 1 weapon rule. Whenever a friendly DEATH KORPS operative is fighting wholly within your territory, or whenever it’s retaliating, its melee weapons also have the Severe weapon rule." },
  { kind: 'firefight', name: "Inspirational Leadership", text: "SUPPORT. Use this firefight ploy during a friendly DEATH KORPS WATCHMASTER or DEATH KORPS CONFIDANT operative’s activation, before or after it performs an action. It issues a" },
  { kind: 'strategy', name: "Regroup", text: "SUPPORT. Select one friendly DEATH KORPS operative that’s more than 3\" from enemy operatives. Each other friendly DEATH KORPS operative within 5\" of that operative and not within control range of enemy operatives can immediately perform a free Dash action in an order of your choice, but each that does so must end that move closer to that operative. Note that a Comms Device from universal equipment only affects the second distance of this rule. You cannot use this ploy and the Chronometer faction equipment STRATEGIC GAMBIT during the same turning point." },
  { kind: 'firefight', name: "Combined Arms", text: "Use this firefight ploy after rolling your attack dice for a friendly DEATH KORPS operative, if it’s shooting an enemy operative that’s been shot by another friendly DEATH KORPS operative during this turning point. You can re-roll any of your attack dice." },
  { kind: 'firefight', name: "In Life, Shame", text: "Use this firefight ploy when a friendly DEATH KORPS operative is activated and given an Engage order. It receives every GUARDSMAN ORDER. This takes precedence over the normal rule that operatives cannot benefit from more than one GUARDSMAN ORDER at once." },
  { kind: 'equipment', name: "Chronometer", text: "Once per battle STRATEGIC GAMBIT in the first or second turning point. Each friendly DEATH KORPS operative wholly within your territory can immediately perform a free Dash action in an order of your choice, but each that does so must end that move closer to an opponent’s drop zone or killzone edge. You cannot use this STRATEGIC GAMBIT and the Regroup strategy ploy during the same turning point." },
  { kind: 'firefight', name: "In Death, Atonement", text: "Use this firefight ploy when a ready friendly DEATH KORPS operative is incapacitated, if it isn’t within control range of enemy operatives. Before it’s removed from the killzone, it can immediately perform one free action and you can change its order to do so. Note that friendly operative is injured for the duration of that action." },
  { kind: 'equipment', name: "Comm-beads", text: "Whenever a friendly DEATH KORPS WATCHMASTER or friendly DEATH KORPS CONFIDANT operative issues a GUARDSMAN ORDER, you can use this rule. If you do, instead of each friendly DEATH KORPS operative within 6\" of it receiving that order, you can select one friendly DEATH KORPS operative to receive that order." },
  { kind: 'equipment', name: "Hand Axes", text: "Friendly DEATH KORPS operatives have the following melee weapon — Hand axe: ATK 3, HIT 4+, DMG 3/4." },
  { kind: 'equipment', name: "Gas Bombardment", text: "Once per battle STRATEGIC GAMBIT. Place your Gas marker in the killzone; it cannot be placed underneath Vantage terrain. Whenever an operative is within 3\" of that marker, subtract 1 from its APL stat. In the Ready step of the next Strategy phase, remove that marker. Note that an operative’s APL stat is only changed while it’s within 3\" of that marker. If it moves more than 3\" from that marker, its APL stat is no longer changed by this rule." },
]

export const operatives: Operative[] = [
  { id: "death-korps:death-korps-watchmaster", name: "Death Korps Watchmaster", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "death-korps:death-korps-bruiser", name: "Death Korps Bruiser", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-confidant", name: "Death Korps Confidant", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-gunner", name: "Death Korps Gunner", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-medic", name: "Death Korps Medic", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-sapper", name: "Death Korps Sapper", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-sniper", name: "Death Korps Sniper", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-spotter", name: "Death Korps Spotter", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-trooper", name: "Death Korps Trooper", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-veteran", name: "Death Korps Veteran", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-vox-operator", name: "Death Korps Vox-operator", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-zealot", name: "Death Korps Zealot", apl: 2, move: "6\"", save: "5+", w: 7 },
]
