// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Guardsmen Orders", text: "STRATEGIC GAMBIT and SUPPORT. A friendly\nDEATH KORPS WATCHMASTER operative can issue a GUARDSMAN ORDER. Whenever it does, select one GUARDSMAN ORDER for all friendly DEATH KORPS operatives within 6\" of it to receive. Whenever a friendly operative receives a\nGUARDSMAN ORDER, apply its rules until the end of the turning point. Operatives cannot benefit from more than one GUARDSMAN ORDER at once; they only benefit from the most recent order they received during the turning point.\nTake Aim! Outfitted and trained for attritional infantry combat, the soldiers of Krieg have undertaken endless hours of lasgun drills.\nRanged weapons of operatives that received this order (excluding mortar barrage and remote detonator) have the Ceaseless weapon rule.\nFix Bayonets! The kind of warfare undertaken by the Death Korps of Krieg requires their troopers to be well versed in close-quarters fighting and trench clearance. Melee weapons of operatives that received this order have the Ceaseless weapon rule.\nWhenever an operative is shooting a friendly operative that’s received this order, if you can retain any cover saves, you can re-roll any of your defence dice results of one result (e.g. results of 2).\nMove! Move! Move! Responding to a barked order from their Watchmaster, the soldiers of Krieg pick up the pace and hustle towards their next objective. Whenever an operative that’s received this order is performing the Reposition action, add 1\" to its Move stat." },
  { kind: 'strategy', name: "Siege Warfare", text: "Friendly DEATH KORPS operatives’ ranged weapons have the Saturate and Accurate 1 weapon rules." },
  { kind: 'strategy', name: "Take Cover", text: "Whenever an operative is shooting a friendly DEATH KORPS operative, if you can retain any cover saves, improve that friendly operative’s Save stat by 1." },
  { kind: 'strategy', name: "Clear the Line", text: "Friendly DEATH KORPS operatives’ melee weapons have the Accurate 1 weapon rule. Whenever a friendly DEATH KORPS operative is fighting wholly within your territory, or whenever it’s retaliating, its melee weapons also have the Severe weapon rule." },
  { kind: 'firefight', name: "Inspirational Leadership", text: "SUPPORT. Use this firefight ploy during a friendly DEATH KORPS WATCHMASTER or DEATH KORPS CONFIDANT operative’s activation, before or after it performs an action. It issues a" },
  { kind: 'strategy', name: "Regroup", text: "SUPPORT. Select one friendly DEATH KORPS operative that’s more than 3\" from enemy operatives. Each other friendly DEATH KORPS operative within 5\" of that operative and not within control range of enemy operatives can immediately perform a free Dash action in an order of your choice, but each that does so must end that move closer to that operative. Note that a Comms Device from universal equipment only affects the second distance of this rule. You cannot use this ploy and the Chronometer faction equipment STRATEGIC GAMBIT during the same turning point." },
  { kind: 'firefight', name: "Combined Arms", text: "Use this firefight ploy after rolling your attack dice for a friendly DEATH KORPS operative, if it’s shooting an enemy operative that’s been shot by another friendly DEATH KORPS operative during this turning point. You can re-roll any of your attack dice." },
  { kind: 'firefight', name: "In Life, Shame", text: "Use this firefight ploy when a friendly DEATH KORPS operative is activated and given an Engage order. It receives every GUARDSMAN ORDER. This takes precedence over the normal rule that operatives cannot benefit from more than one GUARDSMAN ORDER at once." },
  { kind: 'equipment', name: "Chronometer", text: "Once per battle STRATEGIC GAMBIT in the first or second turning point. Each friendly DEATH KORPS operative wholly within your territory can immediately perform a free Dash action in an order of your choice, but each that does so must end that move closer to an opponent’s drop zone or killzone edge. You cannot use this STRATEGIC GAMBIT and the Regroup strategy ploy during the same turning point." },
  { kind: 'firefight', name: "In Death, Atonement", text: "Use this firefight ploy when a ready friendly DEATH KORPS operative is incapacitated, if it isn’t within control range of enemy operatives. Before it’s removed from the killzone, it can immediately perform one free action and you can change its order to do so. Note that friendly operative is injured for the duration of that action." },
  { kind: 'equipment', name: "Comm-beads", text: "Whenever a friendly DEATH KORPS WATCHMASTER or friendly DEATH KORPS CONFIDANT operative issues a GUARDSMAN ORDER, you can use this rule. If you do, instead of each friendly DEATH KORPS operative within 6\" of it receiving that order, you can select one friendly DEATH KORPS operative to receive that order." },
  { kind: 'equipment', name: "Hand Axes", text: "Friendly DEATH KORPS operatives have the following melee weapon — Hand axe: ATK 3, HIT 4+, DMG 3/4." },
  { kind: 'equipment', name: "Gas Bombardment", text: "Once per battle STRATEGIC GAMBIT. Place your Gas marker in the killzone; it cannot be placed underneath Vantage terrain. Whenever an operative is within 3\" of that marker, subtract 1 from its APL stat. In the Ready step of the next Strategy phase, remove that marker. Note that an operative’s APL stat is only changed while it’s within 3\" of that marker. If it moves more than 3\" from that marker, its APL stat is no longer changed by this rule." },
]

export const operatives: Operative[] = [
  { id: "death-korps:death-korps-watchmaster", name: "Death Korps Watchmaster", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "death-korps:death-korps-bruiser", name: "Death Korps Bruiser", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-confidant", name: "Death Korps Confidant", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-gunner", name: "Death Korps Gunner", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-medic", name: "Death Korps Medic", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-sapper", name: "Death Korps Sapper", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-sniper", name: "Death Korps Sniper", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-spotter", name: "Death Korps Spotter", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-trooper", name: "Death Korps Trooper", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-veteran", name: "Death Korps Veteran", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-vox-operator", name: "Death Korps Vox-operator", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "death-korps:death-korps-zealot", name: "Death Korps Zealot", apl: 2, move: "6\"", save: "5+", w: 7 },
]

export const datacards: Datacard[] = [
  {"name": "Death Korps Watchmaster", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Boltgun", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Plasma pistol (standard)", "atk": 4, "hit": "4+", "dmg": "3/5", "wr": "Range 8\", Piercing 1"}, {"name": "Plasma pistol (supercharge)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Range 8\", Hot, Lethal 5+, Piercing 1"}, {"name": "Relic laspistol", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Range 8\", Lethal 5+"}, {"name": "Bayonet", "atk": 4, "hit": "3+", "dmg": "2/3"}, {"name": "Chainsword", "atk": 4, "hit": "3+", "dmg": "4/5"}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Adaptive Orders", "text": "If this operative doesn’t issue a GUARDSMAN ORDER as a STRATEGIC GAMBIT, you can use the Inspirational Leadership firefight ploy for 0CP during this operative’s activation."}, {"name": "Bring it Down!", "text": "STRATEGIC GAMBIT if this operative is in the killzone. Select one enemy operative. Whenever a friendly DEATH KORPS operative is shooting against, fighting against or retaliating against that enemy operative, that friendly operative’s weapons have the Punishing weapon rule."}], "actions": [], "keywords": ["DEATH KORPS", "IMPERIUM", "ASTRA MILITARUM", "LEADER", "WATCHMASTER"], "img": "/ops/death-korps/death-korps-watchmaster.webp"},
  {"name": "Death Korps Bruiser", "weapons": [{"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Trench club", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Shock"}], "abilities": [{"name": "Bruiser", "text": "Once per turning point, when this operative is fighting or retaliating, in the Resolve Attack Dice step, you can ignore the damage inflicted on it from one normal success. If this operative is incapacitated during the Fight action, you can strike the enemy operative in that sequence with one of your unresolved successes before this operative is removed from the killzone."}], "actions": [], "keywords": ["DEATH KORPS", "IMPERIUM", "ASTRA MILITARUM", "BRUISER"], "img": "/ops/death-korps/death-korps-bruiser.webp"},
  {"name": "Death Korps Confidant", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Boltgun", "atk": 4, "hit": "4+", "dmg": "3/4"}, {"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Relic laspistol", "atk": 4, "hit": "4+", "dmg": "2/4", "wr": "Range 8\", Lethal 5+"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}, {"name": "Chainsword", "atk": 4, "hit": "4+", "dmg": "4/5"}], "abilities": [{"name": "Second in Command", "text": "If a friendly WATCHMASTER operative is incapacitated and removed from the killzone, you can use this rule. If you do, until the end of the battle, this operative can issue a GUARDSMAN ORDER as a STRATEGIC GAMBIT (even though it's not a WATCHMASTER operative)."}, {"name": "Directive", "text": "Whenever this operative is activated, if you haven’t used the Second in Command rule during the battle, you can select one other ready friendly DEATH KORPS operative visible to and within 6\" of it. When this operative is expended, activate that other friendly operative before your opponent activates (if that operative is a TROOPER, ignore its Group Activation rule)."}], "actions": [], "keywords": ["DEATH KORPS", "IMPERIUM", "ASTRA MILITARUM", "CONFIDANT"], "img": "/ops/death-korps/death-korps-confidant.webp"},
  {"name": "Death Korps Gunner", "weapons": [{"name": "Flamer", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 8\", Saturate, Torrent 2\""}, {"name": "Grenade launcher (frag)", "atk": 4, "hit": "4+", "dmg": "2/4", "wr": "Blast 2\""}, {"name": "Grenade launcher (krak)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Piercing 1"}, {"name": "Meltagun", "atk": 4, "hit": "4+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Plasma gun (standard)", "atk": 4, "hit": "4+", "dmg": "4/6", "wr": "Piercing 1"}, {"name": "Plasma gun (supercharge)", "atk": 4, "hit": "4+", "dmg": "5/6", "wr": "Hot, Lethal 5+, Piercing 1"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [], "keywords": ["DEATH KORPS", "IMPERIUM", "ASTRA MILITARUM", "GUNNER"], "img": "/ops/death-korps/death-korps-gunner.webp"},
  {"name": "Death Korps Medic", "weapons": [{"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Medic!", "text": "The first time during each turning point that another friendly DEATH KORPS operative would be incapacitated while visible to and within 3\" of this operative, you can use this rule, providing neither this nor that operative is within control range of an enemy operative. If you do, that friendly operative isn’t incapacitated, has 1 wound remaining and cannot be incapacitated for the remainder of the action. After that action, that friendly operative can immediately perform a free Dash action, but must end that move within this operative’s control range. Subtract 1 from this and that operative’s APL stats until the end of their next activations respectively, and if this rule was used during that friendly operative’s activation, that activation ends. You cannot use this rule if this operative is incapacitated, or if it’s a Shoot action and this operative would be a primary or secondary target."}], "actions": [{"name": "Medikit", "ap": 1, "text": "Select one friendly DEATH KORPS operative within this operative’s control range to regain up to 2D3 lost wounds. It cannot be an operative that the Medic! rule was used on during this turning point.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["DEATH KORPS", "IMPERIUM", "ASTRA MILITARUM", "MEDIC"], "img": "/ops/death-korps/death-korps-medic.webp"},
  {"name": "Death Korps Sapper", "weapons": [{"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Remote detonator", "atk": 4, "hit": "2+", "dmg": "5/6", "wr": "Heavy (Dash only), Limited 1, Piercing 1, Silent, Detonate*"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Mine Layer", "text": "This operative is carrying your Mine marker. It can perform the Pick Up Marker action on that marker, and whenever it performs the Place Marker action on that marker, it can immediately perform a free Dash action."}, {"name": "Detonate", "text": "Don’t select a valid target. Instead, shoot against each operative within 2\" of your Mine marker, unless Heavy terrain is wholly intervening between that operative and that marker. Each of those operatives cannot be in cover or obscured. Roll each sequence separately in an order of your choice. This weapon cannot be selected if your Mine marker isn’t in the killzone. At the end of the action, remove your Mine marker from the killzone. In a killzone that uses the close quarters rules (e.g. Killzone: Tomb World), this weapon has the Lethal 5+ weapon rule."}], "actions": [], "keywords": ["DEATH KORPS", "IMPERIUM", "ASTRA MILITARUM", "SAPPER"], "img": "/ops/death-korps/death-korps-sapper.webp"},
  {"name": "Death Korps Sniper", "weapons": [{"name": "Long-las (concealed)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy, Silent, Concealed Position*"}, {"name": "Long-las (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Long-las (stationary)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Concealed Position", "text": "This operative can only use this weapon the first time it’s performing the Shoot action during the battle."}], "actions": [], "keywords": ["DEATH KORPS", "IMPERIUM", "ASTRA MILITARUM", "SNIPER"], "img": "/ops/death-korps/death-korps-sniper.webp"},
  {"name": "Death Korps Spotter", "weapons": [{"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Mortar barrage", "atk": 4, "hit": "4+", "dmg": "3/5", "wr": "Blast 2\", Heavy (Dash only), Silent"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [{"name": "Spot", "ap": 1, "text": "SUPPORT. Select one enemy operative visible to this operative. Until the end of               This operative cannot perform this the turning point, whenever a friendly DEATH KORPS operative within 3\" of this                action while within control range of an operative is shooting that enemy operative, you can use this effect. If you do:               enemy operative.\n• That friendly operative’s ranged weapons have the Seek Light weapon rule. • That enemy operative cannot be obscured."}], "keywords": ["DEATH KORPS", "IMPERIUM", "ASTRA MILITARUM", "SPOTTER"], "img": "/ops/death-korps/death-korps-spotter.webp"},
  {"name": "Death Korps Trooper", "weapons": [{"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Group Activation", "text": "Whenever this operative is expended, you must then activate one other ready friendly DEATH KORPS TROOPER operative (if able) before your opponent activates. When that other operative is expended, your opponent then activates as normal (in other words, you cannot activate more than two operatives in succession with this rule)."}], "actions": [], "keywords": ["DEATH KORPS", "IMPERIUM", "ASTRA MILITARUM", "TROOPER"], "img": "/ops/death-korps/death-korps-trooper.webp"},
  {"name": "Death Korps Veteran", "weapons": [{"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Bionic arm", "atk": 3, "hit": "4+", "dmg": "4/5"}], "abilities": [{"name": "Veteran Guardsman", "text": "Whenever this operative is activated, it can      Bionics: Normal Dmg of 3 or more inflicts 1 less damage on receive one GUARDSMAN ORDER.                                         this operative."}], "actions": [], "keywords": ["DEATH KORPS", "IMPERIUM", "ASTRA MILITARUM", "VETERAN"], "img": "/ops/death-korps/death-korps-veteran.webp"},
  {"name": "Death Korps Vox-operator", "weapons": [{"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Relay Orders", "text": "Once per turning point, when this operative receives a GUARDSMAN ORDER, if it’s not within control\nrange of enemy operatives, it can relay that order. Whenever an\norder is relayed, all friendly DEATH KORPS operatives in the\nkillzone receive that order, then subtract 1 from this operative’s APL stat until the end of its next activation."}], "actions": [{"name": "Signal", "ap": 1, "text": "SUPPORT. Select one other friendly DEATH KORPS\noperative visible to and within 6\" of this operative. Until the\nend of that operative’s next activation, add 1 to its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["DEATH KORPS", "IMPERIUM", "ASTRA MILITARUM", "VOX-OPERATOR"], "img": "/ops/death-korps/death-korps-vox-operator.webp"},
  {"name": "Death Korps Zealot", "weapons": [{"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Bayonet", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "The Emperor Protects", "text": "Whenever an operative is shooting this operative, you can re-roll any of your defence dice."}, {"name": "Uplifting Primer", "text": "SUPPORT. Whenever a friendly DEATH KORPS operative is within 3\" of this operative, that friendly operative’s weapons have the Severe weapon rule."}], "actions": [], "keywords": ["DEATH KORPS", "IMPERIUM", "ASTRA MILITARUM", "ZEALOT"], "img": "/ops/death-korps/death-korps-zealot.webp"},
]
