// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Special Issue Ammunition", text: "Once per turning point, when a friendly DEATHWATCH operative is performing the Shoot action, in the Select Weapon step, you can use this rule. If you do, select one of the following weapon rules for that operative’s ranged weapons to have until the end of the action. This rule cannot be used with explosive grenades (see universal equipment) or melta bombs.\n• Blast 1\" (you cannot select this if the weapon profile being used has the Torrent weapon rule)\n• Devastating 1\n• Lethal 5+\n• Piercing Crits 1\n• Saturate\n• Severe" },
  { kind: 'faction', name: "Veteran Astartes", text: "During each friendly DEATHWATCH operative’s activation, it can perform either two Shoot actions or two Fight actions. If it’s two Shoot actions and an auxiliary grenade launcher, frag cannon, heavy plasma incinerator, infernus heavy bolter, plasma pistol or stalker bolt rifle is selected for both, or if a melta bomb is selected for either, 1 additional AP must be spent for the second action.\nEach friendly DEATHWATCH operative can counteract regardless of its order. Whenever it does, it can perform an additional 1AP action for free during that counteraction, but both actions must be different and you cannot perform a Fight and Shoot action during the same counteraction." },
  { kind: 'strategy', name: "Mission Tactics", text: "Select Conceal or Engage. Whenever a friendly DEATHWATCH operative is shooting against, fighting against, or retaliating against an enemy operative that has that order, that friendly operative’s weapons have the Balanced weapon rule." },
  { kind: 'strategy', name: "The Shield That Slays", text: "Whenever a friendly DEATHWATCH operative is wholly within your opponent’s territory, Normal Dmg of 4 or more inflicts 1 less damage on it." },
  { kind: 'strategy', name: "The Long Vigil", text: "Whenever an operative is shooting a friendly DEATHWATCH operative that’s wholly within your territory, you can re-roll one of your defence dice." },
  { kind: 'strategy', name: "And They Shall Know No Fear", text: "You can ignore any changes to the stats of friendly DEATHWATCH operatives from being injured (including their weapons’ stats)." },
  { kind: 'firefight', name: "Suffer Not the Alien", text: "Use this firefight ploy after rolling your attack dice for a friendly DEATHWATCH operative, if it’s shooting against, fighting against, or retaliating against an operative that doesn’t have the CHAOS or IMPERIUM keyword. You can re-roll any of your attack dice." },
  { kind: 'firefight', name: "Advanced Auspex Scan", text: "Use this firefight ploy when a friendly DEATHWATCH operative performs the Shoot action. Until the end of the activation/ counteraction, its ranged weapons have the Saturate weapon rule and enemy operatives cannot be obscured." },
  { kind: 'firefight', name: "Auspicator Tracking", text: "Use this firefight ploy when a friendly DEATHWATCH operative is counteracting, before it performs any actions. You can change its order." },
  { kind: 'firefight', name: "Transhuman Physiology", text: "Use this firefight ploy when an operative is shooting a friendly DEATHWATCH operative, in the Roll Defence Dice step. You can retain one of your normal successes as a critical success instead." },
  { kind: 'equipment', name: "Digital Weapons", text: "Once per turning point, when a friendly\nDEATHWATCH operative performs the Fight action, at the start of the Roll Attack Dice step, you can use this rule. If you do, inflict 1 damage on the enemy operative in that sequence." },
  { kind: 'equipment', name: "Sanctus-v Bioscryer Cuffs", text: "Once during each friendly DEATHWATCH operative’s activation, before or after it performs an action, if it’s not within control range of enemy operatives, you can use this rule. If you do, select one of the following:\n• That friendly operative regains up to D3 lost wounds.\n• Remove any changes to that friendly operative’s APL stat.\n• Remove one of the following tokens that friendly operative has (before that token’s activation effects are resolved, if relevant): Neutron Fragment, Poison, Terrorchem." },
  { kind: 'equipment', name: "Scrutavore Servo-thrall", text: "Once per turning point, during a friendly DEATHWATCH operative’s activation, you can use this rule. If you do, during that activation, that operative can perform a mission action for 1 less AP. Having an enemy operative within its control range doesn’t prevent that friendly operative from performing that mission action. However, in such an instance, after it does so, you and your opponent roll-off. If your opponent wins, you cannot use this equipment for the rest of the battle." },
  { kind: 'equipment', name: "Ammunition Reserve", text: "Once per battle, you can use the Special Issue Ammunition faction rule for up to two Shoot actions during one turning point, but you must select different weapon rules for both uses. This takes precedence over the normal Special Issue Ammunition rules." },
]

export const operatives: Operative[] = [
  { id: "dw:deathwatch-watch-sergeant", name: "Deathwatch Watch Sergeant", apl: 3, move: "6\"", save: "3+", w: 15 },
  { id: "dw:deathwatch-aegis-veteran", name: "Deathwatch Aegis Veteran", apl: 3, move: "6\"", save: "2+", w: 15 },
  { id: "dw:deathwatch-blademaster-veteran", name: "Deathwatch Blademaster Veteran", apl: 3, move: "6\"", save: "3+", w: 15 },
  { id: "dw:deathwatch-bombard-veteran", name: "Deathwatch Bombard Veteran", apl: 3, move: "5\"", save: "3+", w: 18 },
  { id: "dw:deathwatch-breacher-veteran", name: "Deathwatch Breacher Veteran", apl: 3, move: "5\"", save: "3+", w: 18 },
  { id: "dw:deathwatch-demolisher-veteran", name: "Deathwatch Demolisher Veteran", apl: 3, move: "6\"", save: "3+", w: 15 },
  { id: "dw:deathwatch-disruptor-veteran", name: "Deathwatch Disruptor Veteran", apl: 3, move: "7\"", save: "3+", w: 13 },
  { id: "dw:deathwatch-gunner-veteran", name: "Deathwatch Gunner Veteran", apl: 3, move: "6\"", save: "3+", w: 15 },
  { id: "dw:deathwatch-headtaker-veteran", name: "Deathwatch Headtaker Veteran", apl: 3, move: "7\"", save: "3+", w: 13 },
  { id: "dw:deathwatch-horde-slayer-veteran", name: "Deathwatch Horde-slayer Veteran", apl: 3, move: "5\"", save: "3+", w: 18 },
  { id: "dw:deathwatch-marksman-veteran", name: "Deathwatch Marksman Veteran", apl: 3, move: "6\"", save: "3+", w: 15 },
]

export const datacards: Datacard[] = [
  {"name": "Deathwatch Watch Sergeant", "weapons": [{"name": "Plasma pistol (standard)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Piercing 1"}, {"name": "Plasma pistol (supercharge)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Hot, Lethal 5+, Piercing 1"}, {"name": "Power weapon", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Adaptable Armoury", "text": "You can select one additional equipment option."}, {"name": "Strategic Command", "text": "You can do each of the following once per battle if this operative is in the killzone:\n• Use a DEATHWATCH strategy ploy for 0CP. • Use a DEATHWATCH firefight ploy for 0CP."}], "actions": [], "keywords": ["DEATHWATCH", "IMPERIUM", "ADEPTUS ASTARTES", "LEADER", "WATCH SERGEANT"]},
  {"name": "Deathwatch Aegis Veteran", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Power maul & storm shield", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Shock, Shield*"}], "abilities": [{"name": "Shield", "text": "Whenever this operative is fighting or retaliating with this weapon, each of your blocks can be allocated to block two unresolved successes (instead of one)."}, {"name": "Storm Shield", "text": "Whenever an operative is shooting this operative, worsen the x of the Piercing weapon rule by 1 (if any). Note that Piercing 1 would therefore be ignored."}], "actions": [], "keywords": ["DEATHWATCH", "IMPERIUM", "ADEPTUS ASTARTES", "AEGIS"]},
  {"name": "Deathwatch Blademaster Veteran", "weapons": [{"name": "Special issue bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Piercing 1"}, {"name": "Xenophase blade (duel)", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Brutal, Lethal 5+"}, {"name": "Xenophase blade (phase sweep)", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Brutal, Lethal 5+, Phase Sweep*"}], "abilities": [{"name": "Adaptive Swordsmanship", "text": "You can ignore any changes to the Hit stat of this operative’s xenophase blade. Whenever this operative is fighting or retaliating, you can resolve one of your successes before the normal order. If you do, that success must be used to block."}, {"name": "Phase Sweep", "text": "Whenever this operative performs the Fight action with this weapon profile, if it isn't incapacitated, it can immediately perform a free Fight action afterwards, but you must select this weapon profile and it can only fight against each enemy operative within its control range once per activation or counteraction using this weapon profile. This takes precedence over action restrictions, and you can continue to perform free Fight actions until this operative is incapacitated or has fought against every enemy operative within its control range."}], "actions": [], "keywords": ["DEATHWATCH", "IMPERIUM", "ADEPTUS ASTARTES", "BLADEMASTER"]},
  {"name": "Deathwatch Bombard Veteran", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Frag cannon (shell)", "atk": 4, "hit": "3+", "dmg": "5/7", "wr": "Piercing 1"}, {"name": "Frag cannon (shrapnel)", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Torrent 2\""}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["DEATHWATCH", "IMPERIUM", "ADEPTUS ASTARTES", "GRAVIS", "BOMBARD"]},
  {"name": "Deathwatch Breacher Veteran", "weapons": [{"name": "Auxiliary grenade launcher (frag)", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Blast 2\""}, {"name": "Auxiliary grenade launcher (krak)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Piercing 1"}, {"name": "Hellstorm bolt rifle", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Torrent 1\""}, {"name": "Melta bomb", "atk": 4, "hit": "3+", "dmg": "5/3", "wr": "Range 3\", Devastating 3, Heavy (Reposition only), Limited 1, Piercing 2"}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["DEATHWATCH", "IMPERIUM", "ADEPTUS ASTARTES", "GRAVIS", "BREACHER"]},
  {"name": "Deathwatch Demolisher Veteran", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Heavy thunder hammer", "atk": 5, "hit": "4+", "dmg": "6/7", "wr": "Shock, Stun"}], "abilities": [{"name": "Brutal Assault", "text": "Whenever this operative is fighting, its heavy thunder hammer has the Brutal weapon rule. Whenever this operative performs the Charge action, its heavy thunder hammer has the Ceaseless weapon rule until the end of the activation/counteraction."}, {"name": "Aggressive Force", "text": "Whenever this operative is fighting or retaliating, Normal and Critical Dmg of 3 or more inflicts 1 less damage on it. This isn’t cumulative with the Shield that Slays strategy ploy."}], "actions": [], "keywords": ["DEATHWATCH", "IMPERIUM", "ADEPTUS ASTARTES", "DEMOLISHER"]},
  {"name": "Deathwatch Disruptor Veteran", "weapons": [{"name": "Marksman bolt carbine", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Lethal 5+"}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [{"name": "Advanced Omni-Scrambler", "text": "STRATEGIC GAMBIT. Select one enemy operative visible to or within 6\" of this operative, then roll one D6. In the Firefight phase of this turning point, that enemy operative cannot be activated or perform actions until one of the following is true:\n• Your opponent has activated a number of enemy operatives equal to the result of the D6. • It’s the last enemy operative to be activated."}, {"name": "Auspex Triangulation", "text": "The Advanced Auspex Scan firefight ploy costs you 0CP when both of the following are true:\n• This operative isn’t within control range of enemy operatives. • The target of that Shoot action (primary target, if relevant) is visible to this operative.\nNote that it doesn’t have to be this operative performing the Shoot action, and that any subsequent Shoot actions during that activation/counteraction must meet these same requirements (or that ploy has no effect on those subsequent Shoot actions)."}], "actions": [], "keywords": ["DEATHWATCH", "IMPERIUM", "ADEPTUS ASTARTES", "DISRUPTOR"]},
  {"name": "Deathwatch Gunner Veteran", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Heavy plasma incinerator (standard)", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Piercing 1"}, {"name": "Heavy plasma incinerator (supercharge)", "atk": 5, "hit": "3+", "dmg": "5/6", "wr": "Hot, Lethal 5+, Piercing 1"}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["DEATHWATCH", "IMPERIUM", "ADEPTUS ASTARTES", "GUNNER"]},
  {"name": "Deathwatch Headtaker Veteran", "weapons": [{"name": "Special issue bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Piercing 1"}, {"name": "Combat knives", "atk": 5, "hit": "3+", "dmg": "4/5"}], "abilities": [{"name": "Grav-chute and Grapnel Launcher", "text": "Whenever this operative is climbing, treat the vertical distance as 2\" (regardless of how far the operative actually moves vertically). Whenever this operative is dropping, ignore the vertical distance."}, {"name": "Clandestine Headtaker", "text": "This operative can perform the Charge action while it has a Conceal order. Whenever this operative is fighting against an operative it wasn’t visible to at the start of the activation/counteraction, the first time you strike during that sequence, you can immediately resolve another of your successes as a strike (before your opponent)."}], "actions": [], "keywords": ["DEATHWATCH", "IMPERIUM", "ADEPTUS ASTARTES", "HEADTAKER"]},
  {"name": "Deathwatch Horde-slayer Veteran", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Infernus heavy bolter (flame)", "atk": 5, "hit": "2+", "dmg": "3/3", "wr": "Range 8\", Saturate, Torrent 2\""}, {"name": "Infernus heavy bolter (focused bolt)", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Piercing Crits 1"}, {"name": "Infernus heavy bolter (sweeping bolt)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Piercing Crits 1, Torrent 1\""}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["DEATHWATCH", "IMPERIUM", "ADEPTUS ASTARTES", "GRAVIS", "HORDE-SLAYER"]},
  {"name": "Deathwatch Marksman Veteran", "weapons": [{"name": "Stalker bolt rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Stalker bolt rifle (heavy)", "atk": 4, "hit": "2+", "dmg": "3/5", "wr": "Heavy (Dash only), Lethal 5+, Piercing Crits 1"}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [{"name": "Vigilant Marksman", "text": "This operative can perform the Guard action during its activation regardless of the killzone (see close quarters rules, Kill Team: Tomb World).\nWhen using the close quarters rules, once per turning point, after this operative performs a free Shoot action on guard, it can immediately perform a free Guard action. However, if it does, it cannot counteract during that turning point (nor Guard twice if it’s counteracted)."}], "actions": [], "keywords": ["DEATHWATCH", "IMPERIUM", "ADEPTUS ASTARTES", "MARKSMAN"]},
]
