// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Warrant of Trade", text: "Up to four times per battle, you can use a WARRANT OF TRADE rule (below). Each one specifies when it can be used, and you cannot use the same WARRANT OF TRADE rule more than once per battle.\nConsideration When: In the Select Operatives step, after revealing your equipment options. Effect: Select one additional equipment option. It cannot be an option you have previously selected." },
  { kind: 'faction', name: "Privateer Support Assets", text: "Once per Firefight phase, when a friendly ELUCIDIAN STARSTRIDER NAVIS or ELUCIDIAN STARSTRIDER ELUCIA VHANE operative performs the Shoot action, you can select one of the following PRIVATEER SUPPORT ASSET ranged weapons for it to use. You cannot use each PRIVATEER SUPPORT ASSET more than once per battle.\nWhenever a friendly ELUCIDIAN STARSTRIDER operative is using a PRIVATEER SUPPORT ASSET, determine cover saves differently. Instead, the target has a cover save if any part of its base is underneath Vantage terrain. Note that while this can affect the target’s cover save, you must still select a valid target as normal. In other words, the shot is guided by an operative in the killzone, but it comes from above." },
  { kind: 'strategy', name: "Lethal Proximity", text: "Whenever a friendly ELUCIDIAN STARSTRIDER operative is shooting an operative within 6\" of it, that friendly operative's ranged weapons (excluding PRIVATEER SUPPORT ASSET weapons) have the Balanced weapon rule." },
  { kind: 'strategy', name: "Stake Claim", text: "Place your Claim marker in the killzone. Whenever a friendly ELUCIDIAN STARSTRIDER operative is shooting against, fighting against or retaliating against an enemy operative that’s within 3\" of that marker, in the Roll Attack Dice step, you can retain one of your fails as a normal success instead of discarding it, or retain one of your normal successes as a critical success instead. At the end of the turning point, remove your Claim marker from the killzone." },
  { kind: 'strategy', name: "Undaunted Explorers", text: "The first time an attack dice inflicts damage on each friendly ELUCIDIAN STARSTRIDER operative during the turning point in the Resolve Attack Dice step, you can halve that inflicted damage (rounding up, to a minimum of 2)." },
  { kind: 'firefight', name: "Combined Arms", text: "Use this firefight ploy after rolling your attack dice for a friendly ELUCIDIAN STARSTRIDER operative, if it’s shooting an enemy operative that’s been shot by another friendly ELUCIDIAN STARSTRIDER operative during this turning point. You can re-roll any of your attack dice. You cannot use this ploy while shooting with a" },
  { kind: 'strategy', name: "Quick March", text: "Whenever a friendly ELUCIDIAN STARSTRIDER operative performs the Reposition action during its activation, you can use this rule. If you do, add 1\" to its Move stat until the end of that activation, but it must end that move closer to your opponent’s drop zone and cannot use a PRIVATEER SUPPORT ASSET during that activation." },
  { kind: 'firefight', name: "Survivalist", text: "Use this firefight ploy when a friendly ELUCIDIAN STARSTRIDER operative is activated. That friendly operative regains up to D3+2 lost wounds and during that activation you can ignore any changes to its APL stat." },
  { kind: 'firefight', name: "Great Endurance", text: "Use this firefight ploy during a friendly ELUCIDIAN STARSTRIDER NAVIS operative’s activation. Until the end of the activation, add 1 to its APL stat." },
  { kind: 'equipment', name: "Armoured Undersuit", text: "Whenever an operative is shooting a friendly ELUCIDIAN STARSTRIDER operative (excluding CANID) that has a 5+ Save stat, you can retain one of your defence dice results of 4 as a normal success." },
  { kind: 'firefight', name: "Well-drilled", text: "Use this firefight ploy when a friendly ELUCIDIAN STARSTRIDER NAVIS operative is activated. Select one other ready friendly ELUCIDIAN STARSTRIDER NAVIS operative visible to and within 3\" of that operative. When that first friendly operative is expended, you can activate that other friendly operative before your opponent activates. When that other operative is expended, your opponent then activates as normal." },
  { kind: 'equipment', name: "Hot Shot Capacitor Packs", text: "Up to twice per turning point, whenever a friendly ELUCIDIAN STARSTRIDER operative is performing the Shoot action and you select a laspistol, lasgun or relic laspistol, you can use this rule. If you do, until the end of the turning point, add 1 to both Dmg stats of that weapon and it has the Hot and Piercing Crits 1 weapon rules." },
  { kind: 'equipment', name: "Improved Coordinates Uplink", text: "Whenever a friendly ELUCIDIAN STARSTRIDER operative is using a PRIVATEER SUPPORT ASSET, if the target is within 6\" of a friendly ELUCIDIAN STARSTRIDER NAVIS operative, the target cannot be obscured and that weapon has the Saturate weapon rule." },
  { kind: 'equipment', name: "Rapid Gunnery", text: "Once per battle, when selecting a PRIVATEER SUPPORT ASSET, you can select one that's already been used during the battle. This takes precedence over the normal PRIVATEER SUPPORT ASSET rules." },
]

export const operatives: Operative[] = [
  { id: "elucidian-starstriders:elucia-vhane", name: "Elucia Vhane", apl: 3, move: "6\"", save: "4+", w: 8 },
  { id: "elucidian-starstriders:canid", name: "Canid", apl: 2, move: "8\"", save: "5+", w: 7 },
  { id: "elucidian-starstriders:death-cult-executioner", name: "Death Cult Executioner", apl: 3, move: "6\"", save: "5+", w: 8 },
  { id: "elucidian-starstriders:lectro-maester", name: "Lectro-maester", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "elucidian-starstriders:rejuvenat-adept", name: "Rejuvenat Adept", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "elucidian-starstriders:voidmaster", name: "Voidmaster", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "elucidian-starstriders:voidsman", name: "Voidsman", apl: 2, move: "6\"", save: "5+", w: 7 },
]

export const datacards: Datacard[] = [
  {"name": "Elucia Vhane", "weapons": [{"name": "Heirloom relic pistol", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Piercing Crits 1, Seek Light"}, {"name": "Monomolecular cane-rapier", "atk": 4, "hit": "3+", "dmg": "3/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Digital Lasers", "text": "Whenever this operative performs the Fight action, at the start of the Roll Attack Dice step, you can use this rule. If you do, inflict 1 damage on the enemy operative in that sequence."}, {"name": "Merciless", "text": "Whenever this operative is shooting against, fighting against or retaliating against an enemy operative that was already wounded when the action started, this operative's weapons have the Balanced weapon rule; if the weapon already has that weapon rule, it has the Ceaseless weapon rule instead of Balanced."}, {"name": "Disruption Field", "text": "Whenever an operative is shooting this operative, ignore the Piercing weapon rule."}, {"name": "Reputation to Maintain", "text": "The first time this operative incapacitates an enemy operative during the battle, you can either gain 1 additional CP or use an additional WARRANT OF TRADE rule (up to four uses per battle, instead of three). Note that you still cannot use the same WARRANT OF TRADE rule more than once per battle."}], "actions": [], "keywords": ["ELUCIDIAN STARSTRIDER", "IMPERIUM", "LEADER", "ELUCIA VHANE"]},
  {"name": "Canid", "weapons": [{"name": "Vicious bite", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Rending"}], "abilities": [{"name": "Beast", "text": "This operative cannot perform any actions other than Charge, Dash, Fall Back, Fight, Gather, Guard, Reposition, Pick Up Marker and Place Marker. It cannot use any weapons that aren’t on its datacard. Loyal Companion: Whenever an enemy operative performs the Fight action, if this operative is a valid operative to fight against, you can force them to select this operative to fight against instead. Whenever an enemy operative ends the Charge action within control range of another friendly ELUCIDIAN STARSTRIDER operative within 3\" of this operative, if this operative isn’t within control range of enemy operatives, this"}], "actions": [{"name": "Gather", "ap": 1, "text": "Perform a free Dash or Reposition action with this operative. During that move, it can perform a free Pick Up Marker or Place Marker action (you can determine control during that action to do so), and any remaining move distance it had from the Dash or Reposition action can be used after it does so."}], "keywords": ["ELUCIDIAN STARSTRIDER", "IMPERIUM", "CANID"]},
  {"name": "Death Cult Executioner", "weapons": [{"name": "Dartmask", "atk": 4, "hit": "3+", "dmg": "1/1", "wr": "Range 6\", Lethal 5+, Silent, Stun"}, {"name": "Power weapon", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Rapid Reflexes", "text": "Whenever an operative is shooting this operative, ignore the Piercing weapon rule."}, {"name": "Bladed Stance", "text": "Whenever this operative is fighting or retaliating, you can resolve one of your successes before the normal order. If you do, that success must be used to block."}, {"name": "Zealot", "text": "If this operative is incapacitated during the Fight action, you can strike the enemy operative in that sequence with one of your unresolved successes before this operative is removed from the killzone."}], "actions": [{"name": "Trained Assassin", "ap": 1, "text": "Change this operative’s order.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["ELUCIDIAN STARSTRIDER", "IMPERIUM", "DEATH CULT EXECUTIONER"]},
  {"name": "Lectro-maester", "weapons": [{"name": "Voltaic pistol", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Range 8\", 1\" Devastating 1, Rending"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Missionary of the Martian Creed", "text": "Once during each of this operative’s activations, it can perform the Pick Up Marker, Place Marker or a mission action for 1 less AP."}, {"name": "Voltaghiest Array", "text": "Whenever an operative is shooting a friendly ELUCIDIAN STARSTRIDER operative that’s within 4\" of this operative, you can re-roll one of your defence dice."}], "actions": [{"name": "Calibrate Voltagheist", "ap": 0, "text": "Select one of the following effects to last until the start of this operative’s next activation, until it’s incapacitated or until it performs this action again (whichever comes first):\n• Charge: This operative’s voltaic pistol has the Lethal 4+ weapon rule. • Field: Whenever an enemy operative ends the Charge, Dash, Fall Back or Reposition action visible to and within 4\" of this operative, inflict D6 damage on that enemy operative. This operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["ELUCIDIAN STARSTRIDER", "IMPERIUM", "LECTRO-MAESTER"]},
  {"name": "Rejuvenat Adept", "weapons": [{"name": "Laspistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Scalpel claw", "atk": 3, "hit": "4+", "dmg": "3/4", "wr": "Rending"}], "abilities": [{"name": "Medic!", "text": "The first time during each turning point that another friendly ELUCIDIAN STARSTRIDER operative would be incapacitated while visible to and within 3\" of this operative, you can use this rule, providing neither this nor that operative is within control range of an enemy operative. If you do, that friendly operative isn’t incapacitated, has 3 wounds remaining and cannot be incapacitated for the remainder of the action. After that action, that friendly operative can immediately perform a free Dash action, but must end that move within"}, {"name": "Normaliser Helm", "text": "Whenever a friendly ELUCIDIAN STARSTRIDER operative is within 6\" of this operative, you can ignore any changes to that operative’s stats from being injured (including its weapons’ stats)."}], "actions": [{"name": "Healing Serum", "ap": 1, "text": "Select one friendly ELUCIDIAN STARSTRIDER operative within this operative’s control range to regain up to D3+3 lost wounds. It cannot be an operative that the Medic! rule was used on during this turning point.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["ELUCIDIAN STARSTRIDER", "IMPERIUM", "MEDIC", "REJUVENAT ADEPT"]},
  {"name": "Voidmaster", "weapons": [{"name": "Artificer shotgun (close range)", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Range 6\""}, {"name": "Artificer shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "2/2"}, {"name": "Relic laspistol", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Range 8\", Lethal 5+"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Disciplinarian", "text": "SUPPORT. Whenever another friendly ELUCIDIAN STARSTRIDER NAVIS operative is within 3\" of this operative, that friendly operative’s ranged weapons (excluding PRIVATEER SUPPORT ASSET weapons) have the Balanced weapon rule; if the weapon already has that weapon rule, it has the Ceaseless weapon rule instead of Balanced."}, {"name": "Hardy", "text": "Once per battle, when an attack dice inflicts Normal Dmg on this operative, you can ignore that inflicted damage."}], "actions": [{"name": "Uncompromising Fire", "ap": 1, "text": "Perform two free Shoot actions with this operative (this takes precedence over action restrictions). You must select its relic laspistol for one action and its artificer shotgun (close range) for the other (in any order).\nThis operative cannot perform this action while it has a Conceal order, or during an activation in which it performed the Shoot action (or vice versa)."}], "keywords": ["ELUCIDIAN STARSTRIDER", "IMPERIUM", "NAVIS", "VOIDMASTER"]},
  {"name": "Voidsman", "weapons": [{"name": "Lasgun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Rotor cannon (focused)", "atk": 5, "hit": "4+", "dmg": "4/5", "wr": "Heavy (Dash only), Rending"}, {"name": "Rotor cannon (sweeping)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Heavy (Dash only), Rending, Torrent 1\""}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Crewmen", "text": "Once per turning point, whenever you would counteract, if you haven't used a PRIVATEER SUPPORT ASSET during this turning point, you can use this rule. If you do, you can counteract with one friendly ELUCIDIAN STARSTRIDER VOIDSMAN operative that has a Conceal order, but during that counteraction you cannot perform any actions other than Shoot, and you must use a PRIVATEER SUPPORT ASSET to do so."}], "actions": [], "keywords": ["ELUCIDIAN STARSTRIDER", "IMPERIUM", "NAVIS", "VOIDSMAN"]},
]
