// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Ruthless Efficiency", text: "Whenever a friendly EXACTION SQUAD operative is shooting (excluding with frag or krak grenades) and you’re selecting a valid target, you can use this rule. If you do, having other friendly EXACTION SQUAD operatives within an enemy operative’s control range doesn’t prevent that enemy operative from being selected." },
  { kind: 'faction', name: "Marked for Justice", text: "STRATEGIC GAMBIT. Select one enemy operative to be your mark for the turning point. Whenever a friendly EXACTION SQUAD operative is shooting against, fighting against or retaliating against your mark, that friendly operative's weapons have the Punishing weapon rule. Whenever your mark is incapacitated, you can select a new enemy operative to be your mark for the turning point (and can continue to do so during this turning point)." },
  { kind: 'faction', name: "Repress", text: "• Each of your blocks can be allocated to block two unresolved successes (instead of one).\n• If this operative is retaliating, you resolve the first attack dice (i.e. defender instead of attacker)." },
  { kind: 'strategy', name: "Guilt Reveals Itself", text: "Whenever you’re selecting a valid target for a friendly EXACTION SQUAD operative, enemy operatives within 4\" of it cannot be in cover (instead of 2\"). While this can allow such operatives to be targeted (assuming they’re visible), it doesn’t remove their cover save (if any), unless the friendly EXACTION SQUAD operative is within 2\" as normal." },
  { kind: 'strategy', name: "Inviolate Jurisdiction", text: "Whenever an operative is shooting a friendly EXACTION SQUAD operative that’s within 2\" of an objective marker or an enemy operative, you can re-roll one of your defence dice." },
  { kind: 'strategy', name: "Dispense Justice", text: "Whenever a friendly EXACTION SQUAD operative is fighting or retaliating, if it hasn’t moved more than its Move stat during the activation, or if it's a counteraction, its melee weapons have the Ceaseless weapon rule." },
  { kind: 'firefight', name: "Long Arm of the Emperor's Law", text: "Use this firefight ploy when a friendly EXACTION SQUAD operative is performing the Shoot action and you select a weapon with the Range x weapon rule (excluding frag or krak grenade). Until the end of that action, add 3\" to x." },
  { kind: 'strategy', name: "Terminal Decree", text: "Whenever a friendly EXACTION SQUAD operative is shooting an enemy operative within 6\" of it, or whenever a friendly EXACTION SQUAD GUNNER operative is shooting, that friendly operative’s ranged weapons have the Balanced weapon rule." },
  { kind: 'firefight', name: "Exact Punishment", text: "Use this firefight ploy after an enemy operative shoots against or fights against a friendly EXACTION SQUAD operative within 6\" of it, and that friendly operative isn’t incapacitated as a result. That friendly operative can immediately perform either a free Shoot or a free Fight action, but you cannot select any other enemy operative as a valid target or to fight against during that action (note that secondary targets from the Blast weapon rule can still be targeted)." },
  { kind: 'firefight', name: "Brutal Backup", text: "Use this firefight ploy during a friendly EXACTION SQUAD operative’s activation, before or after it performs an action. Select one enemy operative within its control range. One other friendly EXACTION SQUAD operative can immediately perform a free Fight action, but you cannot select any other enemy operative to fight against during that action." },
  { kind: 'equipment', name: "Reinforced Mirror-visor", text: "You can ignore any changes to the APL stat of friendly EXACTION SQUAD operatives, and they aren’t affected by enemy operatives’ Shock weapon rule." },
  { kind: 'firefight', name: "Execution Order", text: "Use this firefight ploy when an enemy operative performs a mission action (excluding Operate Hatch). Alternatively, use it at the end of the Firefight phase and select one enemy operative that controls an objective marker.\nIn either case, the next time your opponent would activate that enemy operative, you can interrupt that activation and activate a ready friendly EXACTION SQUAD operative. If you do, during that activation, that friendly operative must shoot against or fight against that enemy operative, and cannot do so against any other enemy operatives until it does (if this isn’t possible, that friendly operative’s activation is cancelled). After completing that friendly operative’s activation, continue that enemy operative’s activation (if possible). You cannot use this ploy again until that enemy operative is activated or incapacitated." },
  { kind: 'equipment', name: "Manacles", text: "Whenever an enemy operative would perform the Fall Back action while within control range of a friendly EXACTION SQUAD operative, if no other enemy operatives are within that friendly operative’s control range, you can use this rule. If you do, roll two D6, or one D6 if that enemy operative has a higher Wounds stat than that friendly operative. If any result is a 4+, that enemy operative cannot perform that action during that activation/counteraction (no AP are spent on it), and you cannot use this rule again during this turning point." },
  { kind: 'equipment', name: "Strobing Phosphor-lumen", text: "Whenever an enemy operative is shooting against, fighting against or retaliating against a friendly EXACTION SQUAD operative within 2\" of it, your opponent cannot re-roll their attack dice results of 1." },
  { kind: 'equipment', name: "Special Issue Shells", text: "Up to twice per turning point, when a friendly EXACTION SQUAD operative is performing the Shoot action and you select a combat shotgun, executioner shotgun, scoped shotpistol or shotpistol, you can use this rule. If you do, select one of the following weapon rules for that weapon to have until the end of that action:\n• Saturate.\n• Piercing 1, but only if the target has a Save stat of 3+ or better.\n• Torrent 1\", but you cannot select more than one secondary target." },
]

export const operatives: Operative[] = [
  { id: "exaction-squad:arbites-proctor-exactant", name: "Arbites Proctor-exactant", apl: 2, move: "6\"", save: "4+", w: 9 },
  { id: "exaction-squad:arbites-chirurgant", name: "Arbites Chirurgant", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-leashmaster", name: "Arbites Leashmaster", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:r-vr-cyber-mastiff", name: "R-vr Cyber-mastiff", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-castigator", name: "Arbites Castigator", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-gunner", name: "Arbites Gunner", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-malocator", name: "Arbites Malocator", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-marksman", name: "Arbites Marksman", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-revelatum", name: "Arbites Revelatum", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-subductor", name: "Arbites Subductor", apl: 2, move: "6\"", save: "3+", w: 8 },
  { id: "exaction-squad:arbites-vigilant", name: "Arbites Vigilant", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-vox-signifier", name: "Arbites Vox-signifier", apl: 2, move: "6\"", save: "4+", w: 8 },
]
