// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Ruthless Efficiency", text: "Whenever a friendly EXACTION SQUAD operative is shooting (excluding with frag or krak grenades) and you’re selecting a valid target, you can use this rule. If you do, having other friendly EXACTION SQUAD operatives within an enemy operative’s control range doesn’t prevent that enemy operative from being selected." },
  { kind: 'faction', name: "Marked for Justice", text: "STRATEGIC GAMBIT. Select one enemy operative to be your mark for the turning point. Whenever a friendly EXACTION SQUAD operative is shooting against, fighting against or retaliating against your mark, that friendly operative's weapons have the Punishing weapon rule. Whenever your mark is incapacitated, you can select a new enemy operative to be your mark for the turning point (and can continue to do so during this turning point)." },
  { kind: 'faction', name: "Repress", text: "• Each of your blocks can be allocated to block two unresolved successes (instead of one).\n• If this operative is retaliating, you resolve the first attack dice (i.e. defender instead of attacker)." },
  { kind: 'strategy', name: "Guilt Reveals Itself", text: "Whenever you’re selecting a valid target for a friendly EXACTION SQUAD operative, enemy operatives within 4\" of it cannot be in cover (instead of 2\"). While this can allow such operatives to be targeted (assuming they’re visible), it doesn’t remove their cover save (if any), unless the friendly EXACTION SQUAD operative is within 2\" as normal." },
  { kind: 'strategy', name: "Inviolate Jurisdiction", text: "Whenever an operative is shooting a friendly EXACTION SQUAD operative that’s within 2\" of an objective marker or an enemy operative, you can re-roll one of your defence dice." },
  { kind: 'strategy', name: "Dispense Justice", text: "Whenever a friendly EXACTION SQUAD operative is fighting or retaliating, if it hasn’t moved more than its Move stat during the activation, or if it's a counteraction, its melee weapons have the Ceaseless weapon rule." },
  { kind: 'firefight', name: "Long Arm of the Emperor's Law", text: "Use this firefight ploy when a friendly EXACTION SQUAD operative is performing the Shoot action and you select a weapon with the Range x weapon rule (excluding frag or krak grenade). Until the end of that action, add 3\" to x." },
  { kind: 'strategy', name: "Terminal Decree", text: "Whenever a friendly EXACTION SQUAD operative is shooting an enemy operative within 6\" of it, or whenever a friendly EXACTION SQUAD GUNNER operative is shooting, that friendly operative’s ranged weapons have the Balanced weapon rule." },
  { kind: 'firefight', name: "Exact Punishment", text: "Use this firefight ploy after an enemy operative shoots against or fights against a friendly EXACTION SQUAD operative within 6\" of it, and that friendly operative isn’t incapacitated as a result. That friendly operative can immediately perform either a free Shoot or a free Fight action, but you cannot select any other enemy operative as a valid target or to fight against during that action (note that secondary targets from the Blast weapon rule can still be targeted)." },
  { kind: 'firefight', name: "Brutal Backup", text: "Use this firefight ploy during a friendly EXACTION SQUAD operative’s activation, before or after it performs an action. Select one enemy operative within its control range. One other friendly EXACTION SQUAD operative can immediately perform a free Fight action, but you cannot select any other enemy operative to fight against during that action." },
  { kind: 'equipment', name: "Reinforced Mirror-visor", text: "You can ignore any changes to the APL stat of friendly EXACTION SQUAD operatives, and they aren’t affected by enemy operatives’ Shock weapon rule." },
  { kind: 'firefight', name: "Execution Order", text: "Use this firefight ploy when an enemy operative performs a mission action (excluding Operate Hatch). Alternatively, use it at the end of the Firefight phase and select one enemy operative that controls an objective marker.\nIn either case, the next time your opponent would activate that enemy operative, you can interrupt that activation and activate a ready friendly EXACTION SQUAD operative. If you do, during that activation, that friendly operative must shoot against or fight against that enemy operative, and cannot do so against any other enemy operatives until it does (if this isn’t possible, that friendly operative’s activation is cancelled). After completing that friendly operative’s activation, continue that enemy operative’s activation (if possible). You cannot use this ploy again until that enemy operative is activated or incapacitated." },
  { kind: 'equipment', name: "Manacles", text: "Whenever an enemy operative would perform the Fall Back action while within control range of a friendly EXACTION SQUAD operative, if no other enemy operatives are within that friendly operative’s control range, you can use this rule. If you do, roll two D6, or one D6 if that enemy operative has a higher Wounds stat than that friendly operative. If any result is a 4+, that enemy operative cannot perform that action during that activation/counteraction (no AP are spent on it), and you cannot use this rule again during this turning point." },
  { kind: 'equipment', name: "Strobing Phosphor-lumen", text: "Whenever an enemy operative is shooting against, fighting against or retaliating against a friendly EXACTION SQUAD operative within 2\" of it, your opponent cannot re-roll their attack dice results of 1." },
  { kind: 'equipment', name: "Special Issue Shells", text: "Up to twice per turning point, when a friendly EXACTION SQUAD operative is performing the Shoot action and you select a combat shotgun, executioner shotgun, scoped shotpistol or shotpistol, you can use this rule. If you do, select one of the following weapon rules for that weapon to have until the end of that action:\n• Saturate.\n• Piercing 1, but only if the target has a Save stat of 3+ or better.\n• Torrent 1\", but you cannot select more than one secondary target." },
]

export const operatives: Operative[] = [
  { id: "exaction-squad:arbites-proctor-exactant", name: "Arbites Proctor-exactant", apl: 2, move: "6\"", save: "4+", w: 9 },
  { id: "exaction-squad:arbites-chirurgant", name: "Arbites Chirurgant", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-leashmaster", name: "Arbites Leashmaster", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:r-vr-cyber-mastiff", name: "R-vr Cyber-mastiff", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-castigator", name: "Arbites Castigator", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-gunner", name: "Arbites Gunner", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-malocator", name: "Arbites Malocator", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-marksman", name: "Arbites Marksman", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-revelatum", name: "Arbites Revelatum", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-subductor", name: "Arbites Subductor", apl: 2, move: "6\"", save: "3+", w: 8 },
  { id: "exaction-squad:arbites-vigilant", name: "Arbites Vigilant", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "exaction-squad:arbites-vox-signifier", name: "Arbites Vox-signifier", apl: 2, move: "6\"", save: "4+", w: 8 },
]

export const datacards: Datacard[] = [
  {"name": "Arbites Proctor-exactant", "weapons": [{"name": "Combat shotgun (close range)", "atk": 4, "hit": "2+", "dmg": "4/4", "wr": "Range 6\""}, {"name": "Combat shotgun (long range)", "atk": 4, "hit": "4+", "dmg": "2/2"}, {"name": "Shotpistol", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Range 8\""}, {"name": "Dominator maul & assault shield", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Lethal 5+, Shock, Repress*"}, {"name": "Repression baton", "atk": 3, "hit": "3+", "dmg": "2/3"}], "abilities": [{"name": "Assault Shield", "text": "If this operative has a dominator maul & assault shield, it has a 3+ Save stat."}, {"name": "Nuncio-aquila", "text": "• Whenever an enemy operative is within 3\" of your Nuncio-aquila marker (or this operative if your Nuncio-aquila marker isn’t in the killzone), your opponent must spend 1 additional AP for that enemy operative to perform the Pick Up Marker and mission actions. • Whenever determining control of a marker, treat the total APL stat of enemy operatives that contest it as 1 lower if at least one of those enemy operatives is within 3\" of your Nuncio-aquila marker (or this operative if your Nuncio-aquila marker isn’t in the killzone). Note this isn’t a change to the APL stat, so any changes are cumulative with this."}], "actions": [{"name": "Deploy Nuncio-aquila", "ap": 0, "text": "If your Nuncio-aquila marker isn’t in the killzone, place it within 6\" horizontally of this operative; otherwise, move your Nuncio-aquila marker up to 6\" horizontally. If this operative is removed from the killzone, remove your Nuncio-aquila marker from the killzone.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["EXACTION SQUAD", "IMPERIUM", "ADEPTUS ARBITES", "LEADER", "PROCTOR-EXACTANT"], "img": "/ops/exaction-squad/arbites-proctor-exactant.webp"},
  {"name": "Arbites Chirurgant", "weapons": [{"name": "Combat shotgun (close range)", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Range 6\""}, {"name": "Combat shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "2/2"}, {"name": "Repression baton", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Medic!", "text": "The first time during each turning point that another friendly EXACTION SQUAD operative would be incapacitated while visible to and within 3\" of this operative, you can use this rule, providing neither this nor that operative is within control range of an enemy operative. If you do, that friendly operative isn’t incapacitated, has 1 wound remaining and cannot be incapacitated for the remainder of the action. After that action, that friendly operative can immediately perform a free Dash action, but must end that move within this operative’s control range. Subtract 1 from this and that operative’s APL stats until the end of their next activations respectively, and if this rule was used during that friendly operative’s activation, that activation ends. You cannot use this rule if this operative is incapacitated, or if it’s a Shoot action and this operative would be a primary or secondary target."}], "actions": [{"name": "Medikit", "ap": 1, "text": "Select one friendly EXACTION SQUAD operative within this operative’s control range to regain up to 2D3 lost wounds. It cannot be an operative that the Medic! rule was used on during this turning point.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["EXACTION SQUAD", "IMPERIUM", "ADEPTUS ARBITES", "MEDIC", "CHIRURGANT"], "img": "/ops/exaction-squad/arbites-chirurgant.webp"},
  {"name": "Arbites Leashmaster", "weapons": [{"name": "Combat shotgun (close range)", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Range 6\""}, {"name": "Combat shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "2/2"}, {"name": "Shotpistol", "atk": 4, "hit": "4+", "dmg": "3/3", "wr": "Range 8”"}, {"name": "Repression baton", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Handler", "text": "Whenever this operative is activated, you can activate a ready friendly EXACTION SQUAD R-VR CYBER-MASTIFF operative at the same time. Complete their activations action by action in any order."}, {"name": "Attack Pattern", "text": "STRATEGIC GAMBIT in the first turning point. Select two of the following attack patterns for a friendly EXACTION SQUAD R-VR CYBER-MASTIFF operative to have for the battle:\n• Aggressive: Its melee weapons have the Relentless weapon rule. • Swift: Add 2\" to its Move stat. • Defensive: Improve its Save stat by 1."}], "actions": [{"name": "R-vr Command", "ap": 0, "text": "Select one friendly EXACTION SQUAD R-VR CYBER-MASTIFF operative and change one of its attack patterns."}], "keywords": ["EXACTION SQUAD", "IMPERIUM", "ADEPTUS ARBITES", "LEASHMASTER"], "img": "/ops/exaction-squad/arbites-leashmaster.webp"},
  {"name": "R-vr Cyber-mastiff", "weapons": [{"name": "Mechanical bite", "atk": 4, "hit": "4+", "dmg": "3/5", "wr": "Lethal 5+"}], "abilities": [{"name": "Beast", "text": "This operative cannot perform any actions other than Apprehend,\nCharge, Dash, Fall Back, Fight,\nGuard, Reposition, Pick Up\nMarker and Place Marker. It\ncannot use any weapons that aren’t on\nits datacard."}], "actions": [{"name": "Apprehend", "ap": 0, "text": "Select one enemy operative within this operative’s control range. Until that enemy\noperative is no longer within this operative’s control range, or until this operative\nperforms this action again (whichever comes first), worsen the Hit stat of that\nenemy operative’s weapons by 1 (this isn’t cumulative with being injured); in\naddition, that enemy operative cannot perform the Fall Back action.\nThis operative cannot perform this action unless an enemy operative is within its control range."}], "keywords": ["EXACTION SQUAD", "IMPERIUM", "ADEPTUS ARBITES", "R-VR CYBER-MASTIFF"], "img": "/ops/exaction-squad/r-vr-cyber-mastiff.webp"},
  {"name": "Arbites Castigator", "weapons": [{"name": "Combat shotgun (close range)", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Range 6\""}, {"name": "Combat shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "2/2"}, {"name": "Excruciator maul", "atk": 4, "hit": "3+", "dmg": "5/5", "wr": "Rending, Shock"}], "abilities": [{"name": "Engendered Focus", "text": "You can ignore any changes to this operative’s stats (including its weapons’ stats, but excluding its Save stat)."}, {"name": "Zealous Dedication", "text": "Whenever an attack dice inflicts damage of 3 or more on this operative, roll one D6: on a 5+, subtract 1 from that inflicted damage."}, {"name": "Castigator’s Arrest", "text": "Whenever an enemy operative is within control range of this operative, if no other enemy operatives are within this operative’s control range, that enemy operative cannot perform the Fall Back action."}], "actions": [], "keywords": ["EXACTION SQUAD", "IMPERIUM", "ADEPTUS ARBITES", "CASTIGATOR"], "img": "/ops/exaction-squad/arbites-castigator.webp"},
  {"name": "Arbites Gunner", "weapons": [{"name": "Grenade launcher", "atk": 5, "hit": "4+", "dmg": "4/5", "wr": "Piercing 1"}, {"name": "Heavy stubber (focused)", "atk": 5, "hit": "4+", "dmg": "4/5", "wr": "Heavy (Dash Only)"}, {"name": "Heavy stubber (sweeping)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Heavy (Dash Only), Torrent 1\""}, {"name": "Webber", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 12\", Severe, Stun"}, {"name": "Repression baton", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [], "keywords": ["EXACTION SQUAD", "IMPERIUM", "ADEPTUS ARBITES", "GUNNER"], "img": "/ops/exaction-squad/arbites-gunner.webp"},
  {"name": "Arbites Malocator", "weapons": [{"name": "Combat shotgun (close range)", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Range 6\""}, {"name": "Combat shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "2/2"}, {"name": "Repression baton", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Acute Focus", "text": "Once during           VERISCANT                                                                                          1AP each of this operative’s Select one enemy operative visible to this operative. Until the start of this operative’s next activations, it can perform the activation, until it’s incapacitated or until it performs this action again (whichever comes first), Pick Up Marker, Place whenever a friendly EXACTION SQUAD operative is shooting against, fighting against or Marker, Veriscant or a retaliating against that enemy operative, that friendly operative’s weapons have the Lethal 5+ mission action for 1 less AP. and Severe weapon rules.\nThis operative cannot perform this action while within control range of an enemy operative."}], "actions": [], "keywords": ["EXACTION SQUAD", "IMPERIUM", "ADEPTUS ARBITES", "MALOCATOR"], "img": "/ops/exaction-squad/arbites-malocator.webp"},
  {"name": "Arbites Marksman", "weapons": [{"name": "Executioner shotgun (concealed)", "atk": 4, "hit": "2+", "dmg": "4/0", "wr": "Devastating 4, Heavy, Silent, Concealed Position*"}, {"name": "Executioner shotgun (mobile)", "atk": 4, "hit": "3+", "dmg": "4/4"}, {"name": "Executioner shotgun (stationary)", "atk": 4, "hit": "2+", "dmg": "4/0", "wr": "Devastating 4, Heavy"}, {"name": "Repression baton", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Concealed Position", "text": "This operative can only use this weapon the first time it’s performing the Shoot action during the battle."}], "actions": [{"name": "Optics", "ap": 1, "text": "Until the start of this operative’s next activation: • The concealed and stationary profiles of its executioner shotgun have the Lethal 5+ weapon rule. • Whenever it’s shooting with its executioner shotgun, enemy operatives cannot be obscured. This operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["EXACTION SQUAD", "IMPERIUM", "ADEPTUS ARBITES", "MARKSMAN"], "img": "/ops/exaction-squad/arbites-marksman.webp"},
  {"name": "Arbites Revelatum", "weapons": [{"name": "Scoped shotpistol (short range)", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Range 8\", Lethal 5+"}, {"name": "Scoped shotpistol (long range)", "atk": 4, "hit": "3+", "dmg": "3/3"}, {"name": "Repression baton", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "First in the Field", "text": "SPOT                                                                                               1AP STRATEGIC GAMBIT Select one enemy operative visible to and within 8\" of this operative. Until the end of the turning in the first turning point. point, whenever a friendly EXACTION SQUAD operative is shooting that enemy operative, If this operative is wholly you can use this effect. If you do: within your drop zone, it can immediately perform a free        • That friendly operative’s ranged weapons have the Seek Light weapon rule. Reposition action.                • That enemy operative cannot be obscured.\nThis operative cannot perform this action while within control range of an enemy operative."}], "actions": [], "keywords": ["EXACTION SQUAD", "IMPERIUM", "ADEPTUS ARBITES", "REVELATUM"], "img": "/ops/exaction-squad/arbites-revelatum.webp"},
  {"name": "Arbites Subductor", "weapons": [{"name": "Shotpistol", "atk": 4, "hit": "4+", "dmg": "3/3", "wr": "Range 8\""}, {"name": "Shock maul & assault shield", "atk": 4, "hit": "4+", "dmg": "4/4", "wr": "Shock, Repress*"}], "abilities": [{"name": "Stubborn Subjugator", "text": "You can ignore any changes to the Hit stat of this operative’s melee weapons."}], "actions": [], "keywords": ["EXACTION SQUAD", "IMPERIUM", "ADEPTUS ARBITES", "SUBDUCTOR"], "img": "/ops/exaction-squad/arbites-subductor.webp"},
  {"name": "Arbites Vigilant", "weapons": [{"name": "Combat shotgun (close range)", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Range 6\""}, {"name": "Combat shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "2/2"}, {"name": "Repression baton", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Close Quarters Vigilance", "text": "This operative can perform the Shoot action (excluding Guard) while within control range of an enemy operative, but only if it hasn’t performed the Charge action during the activation, or if it’s a counteraction. Note this operative isn’t restricted from performing the Charge action after performing the Shoot action."}], "actions": [], "keywords": ["EXACTION SQUAD", "IMPERIUM", "ADEPTUS ARBITES", "VIGILANT"], "img": "/ops/exaction-squad/arbites-vigilant.webp"},
  {"name": "Arbites Vox-signifier", "weapons": [{"name": "Combat shotgun (close range)", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Range 6\""}, {"name": "Combat shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "2/2"}, {"name": "Repression baton", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [{"name": "Signal", "ap": 1, "text": "SUPPORT. Select one other friendly EXACTION SQUAD operative visible to this operative. Until the end of that operative’s next activation, add 1 to its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["EXACTION SQUAD", "IMPERIUM", "ADEPTUS ARBITES", "VOX-SIGNIFIER"], "img": "/ops/exaction-squad/arbites-vox-signifier.webp"},
]
