// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Drakesteed Agility", text: "EXODITE DRAGON MASTER MOUNTED operatives cannot perform the Charge, Dash, Fall Back or Reposition actions; instead they can perform the Sprint and Turn unique actions.\nSPRINT (0AP): Move the active operative to a location it can be placed. This must be directly forwards or backwards in one or more straight-line increments, and increments are always rounded up to the nearest inch. It cannot move more than 9\" forwards or 3\" backwards per activation, and it cannot move more than 12\" per turning point. Before or after one of the increments, you can pivot the active operative up to 45°. This doesn’t use any of its movement allowance, and it can then continue its movement with any remaining move distance. RULE CONTINUES ON OTHER SIDE" },
  { kind: 'faction', name: "Draconic Cavalry Tactics", text: "When setting up an EXODITE DRAGON MASTER kill team before the battle, the first third of your kill team must be friendly DRAKOLITHE operatives set up as normal. Each friendly EXODITE DRAGON MASTER MOUNTED operative thereafter must be set up in reserve: place it to one side instead of in the killzone.\nIn the first Firefight phase, each friendly EXODITE DRAGON MASTER MOUNTED operative set up in reserve is activated as normal. When it is, set it up in a location it can be placed on the killzone floor with its base touching your killzone edge (it’s no longer in reserve). The operative is treated as performing the Turn action (spend the AP accordingly), then continue its activation as normal." },
  { kind: 'faction', name: "Mercurial Speed", text: "Each friendly EXODITE DRAGON MASTER operative has a SPEED that has three levels: SPEED 3-, SPEED 4+ and SPEED 7+. An operative can only have one SPEED level at a time, and it starts the battle with SPEED 3-. An EXODITE DRAGON MASTER MOUNTED operative has SPEED 3- if either of the following are true:\n• It ends the Sprint action and it either moved backwards or less than 4\" forwards.\n• It ends its activation without performing the Sprint action. An EXODITE DRAGON MASTER MOUNTED operative has SPEED 4+ if it ends the Sprint action and moved 4\" or more during that action, or SPEED 7+ instead if it moved 7\" or more during that action.\nEXODITE DRAGON MASTER\nCLANBLADE UPGRADE\nMOONSONG CULL\nThe mythic weapons after which moonblades are named were said to sing louder with every soul thread they severed. Some Clanblades emulate this haunting dirge, surging from prey to prey with the screams and arterial sprays of their foes ever in their wake. Once during each of this operative’s activations, after it’s performed the Sprint action forwards and incapacitated an enemy operative during the Fight action, if it’s no longer within control range of enemy operatives, you can use this rule. If you do, it can immediately perform a free Sprint action forwards using any remaining move distance it had from that first Sprint action, but it cannot pivot during that free action. That operative can perform two Sprint actions during its activation to do so, and its SPEED is measured by the distance moved during both Sprint actions combined. The operative cannot have performed any other actions between those actions." },
  { kind: 'strategy', name: "Draconic Fury", text: "Whenever a friendly EXODITE DRAGON MASTER operative is fighting:\n• If it has SPEED 4+, its melee weapons have the\nBalanced weapon rule.\n• If it has SPEED 7+, its melee weapons have the\nCeaseless weapon rule." },
  { kind: 'strategy', name: "Wind-swift Precision", text: "Whenever a friendly EXODITE DRAGON MASTER operative is shooting, if it has SPEED 4+, its ranged weapons have the Balanced weapon rule." },
  { kind: 'strategy', name: "Sinuous Flux", text: "Whenever an enemy operative is shooting a friendly EXODITE DRAGON MASTER operative more than 6\" from it, if that friendly operative has\nSPEED 4+ or SPEED 7+, your opponent cannot re-roll their attack dice." },
  { kind: 'strategy', name: "Ride Them Down", text: "Once during each friendly EXODITE DRAGON MASTER MOUNTED operative’s activation, whenever it ends its move during the Sprint action:\n• If it moved 4\" or more during that action, you can inflict 1 damage on one enemy operative within its control range.\n• If it moved 7\" or more during that action, or it's a CLANBLADE operative, you can inflict D3 damage on one enemy operative within its control range instead." },
  { kind: 'firefight', name: "Leap", text: "Use this firefight ploy when a friendly EXODITE DRAGON MASTER MOUNTED operative performs the Sprint action. Instead of moving that operative, remove it from the killzone and set it back up in a location it can be placed within 1\" horizontally of its original location. This distance cannot be measured through terrain features more than 2\" tall, and that operative cannot be set up on Vantage terrain higher than 2\" from the killzone floor. That operative is treated as having moved 3\" for the purposes of its movement allowance and has SPEED 3-." },
  { kind: 'firefight', name: "Survivalist Spirit", text: "Use this firefight ploy during a friendly EXODITE DRAGON MASTER MOUNTED operative’s activation or counteraction, before or after it performs an action. Until the start of its next activation, you can ignore any changes to that operative's weapon stats from being injured." },
  { kind: 'firefight', name: "Feral Hunger", text: "Use this firefight ploy after rolling your attack dice for a friendly EXODITE DRAGON MASTER operative, if it’s fighting against a wounded enemy operative with its Drakesteed fangs & talons or fangs & talons. You can re-roll any of your attack dice." },
  { kind: 'firefight', name: "Riding Mastery", text: "Use this firefight ploy when a friendly EXODITE DRAGON MASTER MOUNTED operative performs the Sprint action during its activation. During that action, that operative can perform the Pick Up Marker, Place Marker or a mission action (you can determine control during that action to do so), and any remaining move distance it had from that Sprint action can be used after it does so." },
  { kind: 'equipment', name: "Clan Talismans", text: "Once per turning point, when a friendly EXODITE DRAGON MASTER MOUNTED operative is shooting, fighting or retaliating, if you roll two or more fails, you can discard one of them to retain another as a normal success instead." },
  { kind: 'equipment', name: "Dragonscale Mesh", text: "Once per turning point, when an operative is shooting a friendly EXODITE DRAGON MASTER MOUNTED operative, in the Roll Defence Dice step, you can retain one of your normal successes as a critical success instead." },
  { kind: 'equipment', name: "Lileathan Crystal Matrices", text: "Once per turning point, when a friendly EXODITE DRAGON MASTER operative is performing the Shoot action and you select a solar carbine or a profile of its long rifle, you can use this rule. If you do, until the end of that activation, that weapon has the Piercing 1 weapon rule." },
  { kind: 'equipment', name: "Spirit Stones", text: "Whenever a friendly EXODITE DRAGON MASTER MOUNTED operative is incapacitated, you gain 1CP." },
]

export const operatives: Operative[] = [
  { id: "exodite-dragon-masters:dragon-master-clanblade", name: "Dragon Master Clanblade", apl: 4, move: "12\"", save: "3+", w: 24 },
  { id: "exodite-dragon-masters:dragon-master-leystalker", name: "Dragon Master Leystalker", apl: 4, move: "12\"", save: "3+", w: 24 },
  { id: "exodite-dragon-masters:dragon-master-stonesinger", name: "Dragon Master Stonesinger", apl: 4, move: "12\"", save: "3+", w: 24 },
  { id: "exodite-dragon-masters:drakolithe", name: "Drakolithe", apl: 2, move: "8\"", save: "5+", w: 7 },
]

export const datacards: Datacard[] = [
  {"name": "Dragon Master Clanblade", "weapons": [{"name": "Solar carbine", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Devastating 1"}, {"name": "Drakesteed fangs & talons", "atk": 6, "hit": "3+", "dmg": "3/5", "wr": "Brutal"}, {"name": "Moonblades", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Scaleshield", "text": "Whenever an operative is shooting this operative,            Clanblade Upgrades: When this operative is selected for the and no attack dice are retained as critical successes, worsen the         battle, select up to two different Clanblade Upgrade rules (see x of the Piercing weapon rule by 1 (if any). Note that Piercing 1         Faction Rules) to be added to its datacard for the battle. would therefore be ignored.\nEXODITE DRAGON MASTER , AELDARI, MOUNTED, CLANBLADE                                                                                  75x42"}], "actions": []},
  {"name": "Dragon Master Leystalker", "weapons": [{"name": "Long rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Devastating 1"}, {"name": "Long rifle (stationary)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Aimed*"}, {"name": "Drakesteed fangs & talons", "atk": 6, "hit": "3+", "dmg": "3/5", "wr": "Brutal"}, {"name": "Hunting blade", "atk": 3, "hit": "3+", "dmg": "3/5", "wr": "Lethal 5+"}], "abilities": [{"name": "Implacable Darkscale", "text": "You can ignore any changes to this operative’s drakesteed fangs & talons weapon’s Hit stat from being injured."}, {"name": "Leystalker Upgrades", "text": "When this operative is selected for the battle, select up to two different Leystalker Upgrade rules (see Faction Rules) to be added to its datacard for the battle.\n75x42"}], "actions": []},
  {"name": "Dragon Master Stonesinger", "weapons": [{"name": "Solar carbine", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Devastating 1"}, {"name": "Venomcrest spit", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Severe, Torrent 2\""}, {"name": "Drakesteed fangs & talons", "atk": 6, "hit": "3+", "dmg": "3/5", "wr": "Brutal"}, {"name": "Stone stave", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "PSYCHIC, Lethal 5+, Shock, Stun"}], "abilities": [{"name": "Stonesinger Upgrades", "text": "When this operative is selected for the battle, select up to two different Stonesinger Upgrade rules (see Faction Rules) to be added to its datacard for the battle.\nEXODITE DRAGON MASTER , AELDARI, MOUNTED, PSYKER, STONESINGER                                                                        75x42"}], "actions": [{"name": "Song of Renewal", "ap": 1, "text": "PSYCHIC. Select one friendly EXODITE DRAGON MASTER operative visible to this operative. That operative regains up to 2D3 lost wounds.\nPSYCHIC. Alternatively, each friendly EXODITE DRAGON MASTER operative can regain up to D3 lost wounds.\nThis operative cannot perform this action while within control range of an enemy operative, or more than once per turning point."}]},
  {"name": "Drakolithe", "weapons": [{"name": "Fangs & talons", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Rending"}], "abilities": [{"name": "Preternatural Evasion", "text": "Whenever this operative performs the Charge, Fall Back or Reposition action, if it ends that action more than 2\" from its previous location, it has SPEED 4+; if it ends more than 5\" from its previous location, it has SPEED 7+ instead. Whenever this operative ends its activation, if it didn't gain SPEED 4+ or SPEED 7+ during that activation, it has SPEED 3-. Note that it's the distance from the previous location, not the distance moved (in other words it cannot just circle back to its previous location and gain high SPEED).\nNOTES:\nNOTES:\nNOTES:"}, {"name": "Beast", "text": "This operative cannot perform any actions other than Charge, Dash, Fall Back, Fight, Guard, Pick Up Marker, Place Marker, Reposition and mission actions. This operative cannot perform the Pick Up Marker, Place Marker or mission actions unless there's a friendly LEYSTALKER operative that isn't incapacitated. It cannot use any weapons that aren’t on its datacard."}], "actions": [], "keywords": ["EXODITE DRAGON MASTER", "AELDARI", "DRAKOLITHE"]},
]
