// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Farstalker", text: "In the Ready step of each Strategy phase, you can change the order of up to three friendly FARSTALKER KINBAND operatives that are not within control range of enemy operatives. Whenever it’s your turn to counteract, you can change the order of one friendly FARSTALKER KINBAND operative that’s not within control range of enemy operatives instead. This still counts as you counteracting (so activation alternates back to your opponent afterwards), but doesn’t count as that friendly operative’s counteraction for this turning point." },
  { kind: 'strategy', name: "Cut-throats", text: "Add 1 to the Atk stat of friendly FARSTALKER KINBAND operatives’ melee weapons (to a maximum of 5)." },
  { kind: 'strategy', name: "Prey", text: "When a Kroot Farstalker has selected their target, the hunter’s focus is directed fully towards bringing down their chosen prey.\nWhenever a friendly FARSTALKER KINBAND operative is shooting during an activation in which it hasn’t performed the Charge, Fall Back or Reposition action, its ranged weapons have the Balanced and Severe weapon rules; if the weapon already has the Balanced weapon rule, it has the Ceaseless and Severe weapon rules instead. Note that operative isn’t restricted from performing those actions after shooting." },
  { kind: 'strategy', name: "Rogue", text: "Whenever an operative is shooting a friendly FARSTALKER KINBAND operative:\n• Ignore the Saturate weapon rule.\n• If you can retain any cover saves, you can retain one additional cover save, or you can retain one cover save as a critical success instead. This isn’t cumulative with improved cover saves from Vantage terrain." },
  { kind: 'strategy', name: "Bound", text: "During each friendly FARSTALKER KINBAND operative’s activation, you can ignore the first vertical distance of 2\" they move during one climb up." },
  { kind: 'firefight', name: "Savage Ambush", text: "Use this firefight ploy during the Fight action when a ready friendly FARSTALKER KINBAND operative that has Light or Heavy terrain within its control range is selected to fight against. In the Resolve Attack Dice step of that sequence, you resolve the first attack dice (i.e. defender instead of attacker)." },
  { kind: 'firefight', name: "Poach", text: "Use this firefight ploy during a friendly FARSTALKER KINBAND operative’s activation. Until the end of that activation, that operative doesn’t have to control a marker to perform the Pick Up Marker or mission actions that usually require this (this takes precedence over that action’s conditions – it only needs to contest the marker)." },
  { kind: 'firefight', name: "Slip Away", text: "Use this firefight ploy during a friendly FARSTALKER KINBAND operative's activation, before or after it performs an action. During that activation, that operative can perform the Fall Back action for 1 less AP." },
  { kind: 'firefight', name: "Vengeance for the Kinband", text: "Use this firefight ploy when a friendly FARSTALKER KINBAND operative is incapacitated by an enemy operative. Until the end of the battle, whenever another friendly FARSTALKER KINBAND operative is shooting against, fighting against or retaliating against that enemy operative, that other friendly operative's weapons have the Relentless weapon rule. You cannot use this ploy again during the battle until that enemy operative is incapacitated." },
  { kind: 'equipment', name: "Piercing Shot", text: "Once per turning point, when a friendly FARSTALKER KINBAND operative is performing the Shoot action and you select a Kroot rifle, Kroot scattergun or dual Kroot pistols (focused), you can use this rule. If you do, until the end of that action, that weapon has the Piercing 1 weapon rule. You cannot use the Piercing Shot and Toxin Shot rule during the same action." },
  { kind: 'equipment', name: "Meat", text: "Once per turning point, when a friendly FARSTALKER KINBAND operative (excluding HOUND) is activated, if it’s not within control range of enemy operatives, you can use this rule. If you do, that friendly operative regains up to D3+1 lost wounds." },
  { kind: 'equipment', name: "Toxin Shot", text: "Once per turning point, when a friendly FARSTALKER KINBAND operative is performing the Shoot action and you select a Kroot rifle, Kroot scattergun or dual Kroot pistols (focused), you can use this rule. If you do, until the end of that action, that weapon has the Lethal 5+ and Stun weapon rules. You cannot use the Piercing Shot and Toxin Shot rule during the same action." },
  { kind: 'equipment', name: "Trophy", text: "Once per battle, during a friendly FARSTALKER KINBAND operative’s activation (excluding HOUND), before or after it performs an action, if it’s not within control range of enemy operatives, you can use this rule. If you do, add 1 to that friendly operative’s APL stat until the end of its activation." },
]

export const operatives: Operative[] = [
  { id: "farstalker-kinband:kroot-kill-broker", name: "Kroot Kill-broker", apl: 2, move: "6\"", save: "5+", w: 9 },
  { id: "farstalker-kinband:kroot-bow-hunter", name: "Kroot Bow-hunter", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "farstalker-kinband:kroot-cold-blood", name: "Kroot Cold-blood", apl: 2, move: "6\"", save: "5+", w: 9 },
  { id: "farstalker-kinband:kroot-cut-skin", name: "Kroot Cut-skin", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "farstalker-kinband:kroot-heavy-gunner", name: "Kroot Heavy Gunner", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "farstalker-kinband:kroot-hound", name: "Kroot Hound", apl: 2, move: "8\"", save: "5+", w: 7 },
  { id: "farstalker-kinband:kroot-long-sight", name: "Kroot Long-sight", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "farstalker-kinband:kroot-pistolier", name: "Kroot Pistolier", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "farstalker-kinband:kroot-stalker", name: "Kroot Stalker", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "farstalker-kinband:kroot-tracker", name: "Kroot Tracker", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "farstalker-kinband:kroot-warrior", name: "Kroot Warrior", apl: 2, move: "6\"", save: "5+", w: 8 },
]

export const datacards: Datacard[] = [
  {"name": "Kroot Kill-broker", "weapons": [{"name": "Kroot rifle", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Pulse weapon", "atk": 4, "hit": "4+", "dmg": "4/5"}, {"name": "Ritual blade", "atk": 4, "hit": "3+", "dmg": "4/5"}], "abilities": [{"name": "Call The Kill", "text": "STRATEGIC GAMBIT if this operative is in the killzone. Select one enemy operative to be your mark for the turning point. Whenever a friendly FARSTALKER KINBAND operative is shooting against, fighting against or retaliating against your mark, that friendly operative's weapons have the Balanced weapon rule. Whenever your mark is incapacitated, you can select a new enemy operative to be your mark for the turning point (and can continue to do so during this turning point)."}, {"name": "Victory Shriek", "text": "Whenever your mark is incapacitated, you can select one friendly FARSTALKER KINBAND operative within 6\" of this operative. Until the end of the battle, that operative’s weapons have the Balanced weapon rule. Each friendly operative can only be selected for this rule once per battle."}], "actions": [], "keywords": ["FARSTALKER KINBAND", "T’AU EMPIRE", "LEADER", "KROOT", "KILL-BROKER"], "img": "/ops/farstalker-kinband/kroot-kill-broker.webp"},
  {"name": "Kroot Bow-hunter", "weapons": [{"name": "Accelerator bow (fused arrow)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Piercing 1"}, {"name": "Accelerator bow (glide arrow)", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Silent"}, {"name": "Accelerator bow (voltaic arrow)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Blast 1\""}, {"name": "Blade", "atk": 3, "hit": "3+", "dmg": "3/5"}], "abilities": [], "actions": [{"name": "Energise", "ap": 1, "text": "Until the end of the turning point or until this operative                  This operative cannot perform this action while within control has shot with its accelerator bow (whichever comes first),                  range of an enemy operative. all profiles of its accelerator bow have the Lethal 5+ weapon rule."}], "keywords": ["FARSTALKER KINBAND", "T’AU EMPIRE", "KROOT", "BOW-HUNTER"], "img": "/ops/farstalker-kinband/kroot-bow-hunter.webp"},
  {"name": "Kroot Cold-blood", "weapons": [{"name": "Kroot rifle", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Blade", "atk": 3, "hit": "3+", "dmg": "3/5"}], "abilities": [{"name": "Hardy", "text": "Whenever an attack dice would inflict Critical Dmg on this operative, you can choose for that attack dice to inflict Normal Dmg instead."}, {"name": "Cold-blooded", "text": "Whenever this operative is shooting against, fighting against or retaliating against a wounded enemy operative, this operative’s weapons have the Lethal 5+ weapon rule; if that enemy operative is also injured, this operative’s weapons also have the Rending weapon rule."}], "actions": [], "keywords": ["FARSTALKER KINBAND", "T’AU EMPIRE", "KROOT", "COLD-BLOOD"], "img": "/ops/farstalker-kinband/kroot-cold-blood.webp"},
  {"name": "Kroot Cut-skin", "weapons": [{"name": "Cut-skin's blades", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Ceaseless, Lethal 5+"}], "abilities": [{"name": "Vicious Duellist", "text": "Whenever this operative is fighting or retaliating, for each attack dice your opponent discards as a fail, inflict 1 damage on the enemy operative in that sequence."}, {"name": "Savage Assault", "text": "The first time this operative performs the Fight action during each of its activations, if neither it nor the enemy operative in that sequence is incapacitated, this operative can immediately perform a free Fight action afterwards, but you cannot select any other enemy operative to fight against during that action (and only if it’s still valid to fight against). This takes precedence over action restrictions."}], "actions": [], "keywords": ["FARSTALKER KINBAND", "T’AU EMPIRE", "KROOT", "CUT-SKIN"], "img": "/ops/farstalker-kinband/kroot-cut-skin.webp"},
  {"name": "Kroot Heavy Gunner", "weapons": [{"name": "Dvorgite skinner", "atk": 5, "hit": "2+", "dmg": "3/3", "wr": "Range 6\", Heavy (Reposition only), Piercing 2, Torrent 2\""}, {"name": "Londaxi tribalest", "atk": 5, "hit": "4+", "dmg": "4/5", "wr": "Heavy (Reposition only), Piercing 1, Rending"}, {"name": "Blade", "atk": 3, "hit": "3+", "dmg": "3/5"}], "abilities": [], "actions": [], "keywords": ["FARSTALKER KINBAND", "T’AU EMPIRE", "KROOT", "HEAVY GUNNER"], "img": "/ops/farstalker-kinband/kroot-heavy-gunner.webp"},
  {"name": "Kroot Hound", "weapons": [{"name": "Ripping fangs", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Rending"}], "abilities": [{"name": "Beast", "text": "This operative cannot perform any actions other than Charge, Dash, Fall Back, Fight, Gather, Guard, Reposition, Pick Up Marker and\nPlace Marker. It cannot use any weapons that aren’t on its datacard."}, {"name": "Bad-tempered", "text": "Whenever an enemy operative performs the Fight action, if this operative is a valid operative to fight against, you can force them to select this operative to fight against instead. Whenever an enemy operative ends the Charge action within control range of another friendly FARSTALKER KINBAND operative within 3\" of this operative, if this operative isn’t within control range of enemy operatives, this operative can immediately perform a free Charge action (you can change its order to Engage to do so), but must end that move within control range of that enemy operative."}], "actions": [{"name": "Gather", "ap": 1, "text": "Perform a free Dash or Reposition action\nwith this operative. During that move, it can perform a free Pick Up Marker or Place Marker action (you can determine control during that action to do so), and any remaining move distance it had from the Dash or Reposition action can be used after it does so."}], "keywords": ["FARSTALKER KINBAND", "T’AU EMPIRE", "KROOT", "HOUND"], "img": "/ops/farstalker-kinband/kroot-hound.webp"},
  {"name": "Kroot Long-sight", "weapons": [{"name": "Kroot hunting rifle (concealed)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Heavy, Devastating 3, Silent, Concealed Position*"}, {"name": "Kroot hunting rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Kroot hunting rifle (stationary)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Heavy, Devastating 3"}, {"name": "Blade", "atk": 3, "hit": "3+", "dmg": "3/5"}], "abilities": [{"name": "Concealed Position", "text": "This operative can only use this weapon the first time it’s performing the Shoot action during the battle."}], "actions": [{"name": "Long-sight", "ap": 1, "text": "Until the start of this operative’s next activation:\n• The concealed and stationary profiles of its Kroot hunting rifle have the Lethal 5+ weapon rule. • Whenever it’s shooting with its Kroot hunting rifle, enemy operatives cannot be obscured.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["FARSTALKER KINBAND", "T’AU EMPIRE", "KROOT", "LONG-SIGHT"], "img": "/ops/farstalker-kinband/kroot-long-sight.webp"},
  {"name": "Kroot Pistolier", "weapons": [{"name": "Dual Kroot pistols (focused)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Ceaseless, Lethal 5+"}, {"name": "Dual Kroot pistols (salvo)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Salvo*"}, {"name": "Blade", "atk": 3, "hit": "3+", "dmg": "3/5"}], "abilities": [{"name": "Quick Draw", "text": "Once per turning point, when an enemy operative is performing the Shoot              *Salvo: Select up to two different action and this operative is selected as the valid target (or if it will be a secondary target   valid targets that aren’t within control from the Blast weapon rule), if this operative is ready, you can interrupt that action to        range of friendly operatives. Shoot use this rule. If you do, this operative can immediately perform a free Shoot action with        with this weapon against both of them its dual Kroot pistols (focused) against that enemy operative (you can change its order          in an order of your choice (roll each to Engage to do so), but that enemy operative must be a valid target.                            sequence separately)."}], "actions": [], "keywords": ["FARSTALKER KINBAND", "T’AU EMPIRE", "KROOT", "PISTOLIER"], "img": "/ops/farstalker-kinband/kroot-pistolier.webp"},
  {"name": "Kroot Stalker", "weapons": [{"name": "Kroot scattergun", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Range 6\""}, {"name": "Stalker's blade", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Balanced, Rending"}], "abilities": [{"name": "Stalker", "text": "This operative can          STEALTH ATTACK                                                                                     2AP perform the Charge action Perform a free Charge action with this operative, but don’t exceed its Move stat (i.e. don’t add while it has a Conceal order. 2\"). Then immediately perform a free Fight action with this operative. The first time you strike during that action, you can immediately resolve another of your successes as a strike (before your opponent).\nThis operative cannot perform this action while it has an Engage order, while within control range of an enemy operative, or if it isn’t within 1\" of Light or Heavy terrain."}], "actions": [], "keywords": ["FARSTALKER KINBAND", "T’AU EMPIRE", "KROOT", "STALKER"], "img": "/ops/farstalker-kinband/kroot-stalker.webp"},
  {"name": "Kroot Tracker", "weapons": [{"name": "Kroot rifle", "atk": 4, "hit": "4+", "dmg": "3/4"}, {"name": "Blade", "atk": 3, "hit": "3+", "dmg": "3/5"}], "abilities": [], "actions": [{"name": "Marked for the Hunt", "ap": 1, "text": "Remove your Pech’ra marker from the killzone (if any).                   At the start of this operative’s next activation or if it’s Then place your Pech’ra marker visible to this operative, or             removed from the killzone (whichever comes first), remove on Vantage terrain of a terrain feature that’s visible to this           your Pech’ra marker from the killzone. operative. Whenever a friendly FARSTALKER KINBAND operative is shooting an enemy operative that has that marker            This operative cannot perform this action while within control within its control range, that friendly operative’s ranged               range of an enemy operative. weapons have the Seek Light weapon rule."}, {"name": "From the Eye Above", "ap": 1, "text": "SUPPORT. Select one other friendly FARSTALKER KINBAND operative visible to and within 6\" of this operative. Until the end of that operative’s next activation, add 1 to its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["FARSTALKER KINBAND", "T’AU EMPIRE", "KROOT", "TRACKER"], "img": "/ops/farstalker-kinband/kroot-tracker.webp"},
  {"name": "Kroot Warrior", "weapons": [{"name": "Kroot rifle", "atk": 4, "hit": "4+", "dmg": "3/4"}, {"name": "Kroot scattergun", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Range 6\""}, {"name": "Blade", "atk": 3, "hit": "3+", "dmg": "3/5"}], "abilities": [{"name": "Ready for Anything", "text": "Once per turning point, during a friendly WARRIOR operative’s activation, you can use the Meat, Piercing Shot or Toxin Shot rule (see faction equipment) for that operative. Doing so doesn’t count for its once per turning point limit."}], "actions": [], "keywords": ["FARSTALKER KINBAND", "T’AU EMPIRE", "KROOT", "WARRIOR"], "img": "/ops/farstalker-kinband/kroot-warrior.webp"},
]
