// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Frenzy", text: "Whenever a friendly FELLGOR RAVAGER operative that doesn’t have one of your Frenzy tokens would be incapacitated during the battle, it’s not incapacitated and it gains one of your Frenzy tokens. All remaining attack dice are discarded (including yours if this operative is fighting or retaliating). If it has a Conceal order, change it to Engage.\nWhenever a friendly FELLGOR RAVAGER operative has one of your Frenzy tokens:\n• It’s only incapacitated as detailed overleaf.\n• It cannot have a Conceal order.\n• It’s injured.\n• It cannot perform the Pick Up Marker, unique\n(excluding Sweeping Blow, see VANDAL) or mission actions (excluding Operate Hatch).\n• For the purpose of determining control of markers and areas of the killzone, treat its\nAPL stat as 1. This takes precedence over any stat changes." },
  { kind: 'strategy', name: "Violent Temperament", text: "Whenever a friendly FELLGOR RAVAGER operative is fighting or retaliating, after rolling your attack dice, you can use this rule. If you do, you must re-roll all of your attack dice (you cannot only re-roll some)." },
  { kind: 'strategy', name: "Pelting Firepower", text: "Whenever a friendly FELLGOR RAVAGER operative is shooting an enemy operative that’s been shot by another friendly FELLGOR RAVAGER operative during this turning point, that first friendly operative’s ranged weapons have the Ceaseless weapon rule; if the enemy operative has been shot by more than one other friendly FELLGOR RAVAGER operative during this turning point, that first friendly operative’s ranged weapons have the Relentless weapon rule instead." },
  { kind: 'strategy', name: "Ambush", text: "Whenever a friendly FELLGOR RAVAGER operative is activated, if its order is changed from Conceal to Engage, it’s ambushing for that activation. Whenever a friendly FELLGOR RAVAGER operative that’s ambushing is fighting, you can retain one of your normal successes as a critical success instead. Note that an operative that has one of your Frenzy tokens cannot ambush." },
  { kind: 'strategy', name: "Reckless Determination", text: "Whenever an enemy operative is shooting an expended friendly FELLGOR RAVAGER operative, if you cannot retain any cover saves, you can retain one of your defence dice as a normal success without rolling it." },
  { kind: 'firefight', name: "Ruthless Rampage", text: "Use this firefight ploy after a friendly FELLGOR RAVAGER operative performs the Fight action, if it's no longer within control range of enemy operatives. That friendly operative can immediately perform a free Charge action (even if it’s already performed the Charge action during that activation), but cannot move more than 3\" during that action." },
  { kind: 'firefight', name: "Animalistic Fury", text: "Use this firefight ploy when a friendly FELLGOR RAVAGER operative is fighting or retaliating and you strike with a critical success. Inflict 1 additional damage with that strike." },
  { kind: 'firefight', name: "Wild Rage", text: "Use this firefight ploy when a friendly FELLGOR RAVAGER operative is activated. Until the end of that operative’s activation, add 1\" to its Move stat." },
  { kind: 'firefight', name: "Bloodsense", text: "Use this firefight ploy during a friendly FELLGOR RAVAGER operative’s activation, when it incapacitates an enemy operative within its control range. Select one other ready friendly FELLGOR RAVAGER operative that’s visible to and within 3\" of the incapacitated enemy operative. When that first friendly operative is expended, you can activate that other friendly operative before your opponent activates. When that other operative is expended, your opponent then activates as normal." },
  { kind: 'equipment', name: "Brass Adornments", text: "Once per battle, you can use the Animalistic Fury and Wild Rage firefight ploys for 0CP each." },
  { kind: 'equipment', name: "Chaos Sigil", text: "Once per turning point, when an operative is shooting a friendly FELLGOR RAVAGER operative, at the start of the Roll Defence Dice step, you can use this rule. If you do, worsen the x of the Piercing weapon rule by 1 (if any) until the end of that sequence. Note that Piercing 1 would therefore be ignored." },
  { kind: 'equipment', name: "Gore Marks", text: "Once per turning point, when a friendly FELLGOR RAVAGER operative is fighting or retaliating, you can use this rule. If you do, inflict 1 damage on that friendly operative and re-roll one of your attack dice. If the result is a fail, inflict 1 additional damage on that friendly operative." },
  { kind: 'equipment', name: "War Paint", text: "You can ignore any changes to the Move stat of friendly FELLGOR RAVAGER operatives from being injured." },
]

export const operatives: Operative[] = [
  { id: "fellgor-ravagers:fellgor-ironhorn", name: "Fellgor Ironhorn", apl: 2, move: "6\"", save: "5+", w: 11 },
  { id: "fellgor-ravagers:fellgor-deathknell", name: "Fellgor Deathknell", apl: 2, move: "6\"", save: "4+", w: 10 },
  { id: "fellgor-ravagers:fellgor-fluxbray", name: "Fellgor Fluxbray", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "fellgor-ravagers:fellgor-gnarlscar", name: "Fellgor Gnarlscar", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "fellgor-ravagers:fellgor-gorehorn", name: "Fellgor Gorehorn", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "fellgor-ravagers:fellgor-herd-goad", name: "Fellgor Herd-goad", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "fellgor-ravagers:fellgor-mangler", name: "Fellgor Mangler", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "fellgor-ravagers:fellgor-shaman", name: "Fellgor Shaman", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "fellgor-ravagers:fellgor-toxhorn", name: "Fellgor Toxhorn", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "fellgor-ravagers:fellgor-vandal", name: "Fellgor Vandal", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "fellgor-ravagers:fellgor-warrior", name: "Fellgor Warrior", apl: 2, move: "6\"", save: "5+", w: 10 },
]

export const datacards: Datacard[] = [
  {"name": "Fellgor Ironhorn", "weapons": [{"name": "Corrupted pistol", "atk": 4, "hit": "4+", "dmg": "3/5", "wr": "Range 8\", Rending"}, {"name": "Plasma pistol (standard)", "atk": 4, "hit": "4+", "dmg": "3/5", "wr": "Range 8\", Piercing 1"}, {"name": "Plasma pistol (supercharge)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Range 8\", Hot, Lethal 5+, Piercing 1"}, {"name": "Bludgeon", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Brutal"}, {"name": "Corrupted chainsword", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Rending"}], "abilities": [{"name": "Call the Attack", "text": "STRATEGIC GAMBIT if this operative doesn’t have one of your Frenzy tokens. Select one friendly FELLGOR RAVAGER operative visible to and within 6\" of this operative. That selected operative, and each other friendly FELLGOR RAVAGER operative visible to and within 2\" of it, can immediately perform a free Dash action in an order of your choice."}], "actions": [], "keywords": ["FELLGOR RAVAGER", "CHAOS", "LEADER", "IRONHORN"], "img": "/ops/fellgor-ravagers/fellgor-ironhorn.webp"},
  {"name": "Fellgor Deathknell", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Bludgeon", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Brutal"}], "abilities": [{"name": "Icon Bearer", "text": "This operative isn’t affected by the marker control bullet point of the Frenzy faction rule. Whenever determining\ncontrol of a marker, treat this operative’s APL stat as 1 higher.\nNote this isn’t a change to its APL stat, so any changes are\ncumulative with this."}, {"name": "War Gong", "text": "Whenever an attack dice would inflict Critical Dmg on a friendly FELLGOR RAVAGER operative within 3\" of this operative, if this operative doesn’t have one of your Frenzy tokens, you can choose for that attack dice to inflict Normal Dmg instead."}], "actions": [{"name": "Gong Knell", "ap": 1, "text": "Until the start of this operative’s next activation or until\nthis operative is incapacitated (whichever comes first),\nwhenever an operative is shooting this operative, improve\nthis operative’s Save stat by 1."}], "keywords": ["FELLGOR RAVAGER", "CHAOS", "DEATHKNELL"], "img": "/ops/fellgor-ravagers/fellgor-deathknell.webp"},
  {"name": "Fellgor Fluxbray", "weapons": [{"name": "Triple cleavers", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Ceaseless"}], "abilities": [{"name": "Blade Whirl", "text": "Whenever this operative is fighting or retaliating, if it doesn’t have\none of your Frenzy tokens, you can resolve\none of your successes before the normal\norder. If you do, that success must be\nused to block."}], "actions": [{"name": "Cleaver Flurry", "ap": 2, "text": "Perform a free Reposition action with this operative. During that action, it can\nmove an additional 2\", and can move within control range of enemy operatives (it\ncannot begin or end the move there). Inflict D3+1 damage on each enemy operative\nit moved within control range of (roll separately for each after it’s moved, in the\norder it moved within control range of them).\nThis operative cannot perform this action while it has a Conceal order."}], "keywords": ["FELLGOR RAVAGER", "CHAOS", "FLUXBRAY"], "img": "/ops/fellgor-ravagers/fellgor-fluxbray.webp"},
  {"name": "Fellgor Gnarlscar", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Bionic fist", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Brutal"}], "abilities": [{"name": "Sagacious", "text": "At the end of this operative’s activation, you can change its order."}], "actions": [{"name": "Uncompromising Attack", "ap": 1, "text": "Perform a free Fight action with this operative, then perform a free Shoot action with this operative (or vice versa). This operative can perform that Shoot action while within control range of an enemy operative, but if it does, it can and must target an enemy operative within its control range (even if other friendly operatives are within that enemy operative’s control range). You can only select an autopistol for that Shoot action."}], "keywords": ["FELLGOR RAVAGER", "CHAOS", "GNARLSCAR"], "img": "/ops/fellgor-ravagers/fellgor-gnarlscar.webp"},
  {"name": "Fellgor Gorehorn", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Skullcleaver", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Lethal 5+, Headtaker*"}], "abilities": [{"name": "Champion", "text": "This operative can perform two Fight actions during its activation."}, {"name": "Headtaker", "text": "Whenever this operative incapacitates an operative with this weapon, roll one D3:\n• This operative regains a number of lost wounds equal to the result (unless it has a Frenzy token). • Until the end of the battle, add the result to the Critical Dmg stat of this operative’s skullcleaver (to a maximum of 8)."}], "actions": [], "keywords": ["FELLGOR RAVAGER", "CHAOS", "GOREHORN"], "img": "/ops/fellgor-ravagers/fellgor-gorehorn.webp"},
  {"name": "Fellgor Herd-goad", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Crackthorn whip (ranged)", "atk": 4, "hit": "2+", "dmg": "2/3", "wr": "Range 3\", Lethal 4+, Stun"}, {"name": "Crackthorn whip (melee)", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Lethal 4+, Shock"}], "abilities": [{"name": "Whip Control", "text": "Whenever an enemy operative is visible to and within 3\" of this operative, if this operative isn’t within control\nrange of any other enemy operatives:\n• Subtract 1 from the Atk stat of that enemy operative’s melee weapons (to a minimum of 1). • Your opponent must spend 1 additional AP for that enemy operative to perform the Fall Back action."}], "actions": [{"name": "Incite Fury", "ap": 1, "text": "Select one other friendly FELLGOR RAVAGER operative\n(excluding SHAMAN or IRONHORN) visible to and within 3\" of this operative. Until the end of that operative’s next activation, add 1 to its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["FELLGOR RAVAGER", "CHAOS", "HERD-GOAD"], "img": "/ops/fellgor-ravagers/fellgor-herd-goad.webp"},
  {"name": "Fellgor Mangler", "weapons": [{"name": "Vicious claws", "atk": 4, "hit": "4+", "dmg": "4/6", "wr": "Ceaseless, Tactual Hunter*"}], "abilities": [{"name": "Tactual Hunter", "text": "Whenever this operative is fighting with this weapon against an expended operative, the first time you strike with a critical success during that sequence, you can immediately resolve another of your successes as a strike (before your opponent)."}, {"name": "Berserker", "text": "This operative cannot perform the Shoot action (other than Guard, but cannot then perform a free Shoot action during the interruption). You must spend 1 additional AP for this operative to perform the Pick Up Marker and mission actions (excluding Operate Hatch)."}, {"name": "Savage", "text": "The first time this operative performs the Fight action during each of its activations, if it isn’t incapacitated, it can immediately perform a free Fight action afterwards (you don't have to select the same enemy operative to fight against). This takes precedence over action restrictions, and you cannot use the Ruthless Rampage firefight ploy between those two Fight actions."}], "actions": [], "keywords": ["FELLGOR RAVAGER", "CHAOS", "MANGLER"], "img": "/ops/fellgor-ravagers/fellgor-mangler.webp"},
  {"name": "Fellgor Shaman", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Tech-curse", "atk": 4, "hit": "3+", "dmg": "1/3", "wr": "PSYCHIC, Rending, Saturate, Seek Light"}, {"name": "Braystave", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Shock"}], "abilities": [], "actions": [{"name": "Apoplectic Rejuvenation", "ap": 1, "text": "Select one friendly FELLGOR RAVAGER operative that doesn’t have one of your Frenzy tokens and is visible to and within 6\" of this operative. That friendly operative regains up to 2D3 lost wounds; if that operative has incapacitated an enemy operative while fighting or retaliating during the battle, it regains up to 6 lost wounds instead.\nThis operative cannot perform this action while within control range of an enemy operative."}, {"name": "Mantle of Darkness", "ap": 1, "text": "PSYCHIC. Until the start of this operative’s next activation or until it’s incapacitated (whichever comes first), whenever a friendly FELLGOR RAVAGER operative is visible to and within 3\" of this operative, has a Conceal order and is in cover, that friendly operative cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2\".\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["FELLGOR RAVAGER", "CHAOS", "PSYKER", "SHAMAN"], "img": "/ops/fellgor-ravagers/fellgor-shaman.webp"},
  {"name": "Fellgor Toxhorn", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Cleaver", "atk": 4, "hit": "3+", "dmg": "4/5"}], "abilities": [{"name": "Toxic Blessings", "text": "You can ignore any changes to this operative’s APL stat and it’s not affected by enemy operatives’ Shock weapon rule. Whenever an attack dice inflicts Normal Dmg of 3 or more on this operative, roll one D6: on a 5+, subtract 1 from that inflicted damage."}, {"name": "Pox Bomb", "text": "This operative can use stun grenades (see universal equipment). Doing so doesn’t count towards any limited uses you have (i.e. if you also select that grenade from equipment for other operatives). Whenever an enemy operative takes a stun test as a result of this operative performing the Stun Grenade action, if the result is a 3+, also inflict damage on that enemy operative equal to the dice result halved (rounding up)."}], "actions": [], "keywords": ["FELLGOR RAVAGER", "CHAOS", "TOXHORN"], "img": "/ops/fellgor-ravagers/fellgor-toxhorn.webp"},
  {"name": "Fellgor Vandal", "weapons": [{"name": "Mancrusher", "atk": 4, "hit": "4+", "dmg": "5/5", "wr": "Brutal, Vicious Blows*"}], "abilities": [{"name": "Vicious Blows", "text": "Whenever this operative is fighting, this weapon has the Ceaseless weapon rule."}], "actions": [{"name": "Sweeping Blow", "ap": 1, "text": "Inflict D3+1 damage on each other operative visible to and within 2\" of this operative in an order of your choice (roll separately for each).\nThis operative cannot perform this action while it has a Conceal order."}], "keywords": ["FELLGOR RAVAGER", "CHAOS", "VANDAL"], "img": "/ops/fellgor-ravagers/fellgor-vandal.webp"},
  {"name": "Fellgor Warrior", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Bludgeon", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Brutal"}, {"name": "Cleaver", "atk": 4, "hit": "3+", "dmg": "4/5"}], "abilities": [{"name": "Warrior Frenzy", "text": "Whenever this operative has one of your Frenzy tokens, it cannot be injured. This takes precedence over the normal Frenzy rules."}], "actions": [], "keywords": ["FELLGOR RAVAGER", "CHAOS", "WARRIOR"], "img": "/ops/fellgor-ravagers/fellgor-warrior.webp"},
]
