// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Techno-curse", text: "At the end of the Select Operatives step, select one TECHNO-CURSE for friendly GELLERPOX INFECTED operatives to gain for the battle. Whenever an enemy operative is within your selected TECHNO-CURSE’s infection range, that enemy operative is affected by the symptom of the selected TECHNO-CURSE. Each TECHNO-CURSE, its infection range and its symptom is listed below:" },
  { kind: 'faction', name: "Mutoid Vermin", text: "MUTOID VERMIN operatives cannot perform any actions other than Charge, Dash, Fall Back, Fight, Reposition and Shoot, or use any weapons that aren’t on their datacard. They can perform the Fall Back action for 1 less AP. MUTOID VERMIN operatives cannot contest markers or areas of the killzone, and are ignored for your opponent’s kill/elimination op (when they're incapacitated, and when determining your starting number of operatives). They're also ignored for victory conditions and scoring VPs if either require operatives to ‘escape’, ‘survive’ or be incapacitated by enemy operatives (if they escape/survive/are incapacitated, determining how many operatives must escape/survive/be incapacitated, etc.)." },
  { kind: 'faction', name: "Nightmare Hulks", text: "Whenever your opponent is selecting a valid target, friendly GELLERPOX INFECTED NIGHTMARE HULK operatives cannot use Light terrain for cover. While this can allow such operatives to be targeted (assuming they’re visible), it doesn’t remove their cover save (if any). Friendly GELLERPOX INFECTED NIGHTMARE HULK operatives cannot perform unique actions. You must spend 1 additional AP for friendly GELLERPOX INFECTED NIGHTMARE HULK operatives (excluding VULGRAR THRICECURSED) to perform the Pick Up Marker and mission actions (excluding Operate Hatch)." },
  { kind: 'faction', name: "Revoltingly Resilient", text: "Whenever an attack dice inflicts damage of 3 or more on a friendly GELLERPOX INFECTED NIGHTMARE HULK or GELLERPOX INFECTED MUTANT operative, roll one D6: on a 4+, subtract 1 from that inflicted damage." },
  { kind: 'strategy', name: "Plagueridden Determination", text: "Whenever an operative is shooting a friendly GELLERPOX INFECTED operative (excluding MUTOID VERMIN) that has an Engage order, you can re-roll one of your defence dice." },
  { kind: 'strategy', name: "Drawn to the Hum", text: "Select one objective marker. Whenever a friendly GELLERPOX INFECTED operative performs the Reposition or Charge action during its activation, you can use this rule. If you do, add 1\" to its Move stat until the end of that activation, but it must end that move within 2\" of that objective marker." },
  { kind: 'strategy', name: "Blessings of Infection", text: "Whenever a friendly GELLERPOX INFECTED operative is fighting or retaliating, you can do one of the following:\n• If you roll three or more fails, you can discard one of them to retain another as a normal success instead.\n• If you roll three or more successes, you can discard one of your fails to retain one of your normal successes as a critical success instead." },
  { kind: 'strategy', name: "Rust Emanations", text: "Whenever a friendly GELLERPOX INFECTED operative (excluding MUTOID VERMIN) is fighting or retaliating, your opponent cannot retain results of 3 as successes." },
  { kind: 'firefight', name: "Revolting Technology", text: "Use this firefight ploy when an enemy operative is shooting a friendly GELLERPOX INFECTED operative. That operative’s ranged weapons have the Hot weapon rule until the end of that sequence; if the weapon already has that weapon rule, when your opponent rolls one D6 for that weapon rule, you can add or subtract 1 from the result. Note that for the latter you can see the result of your opponent’s roll for the Hot weapon rule before deciding to use this ploy." },
  { kind: 'firefight', name: "Putrescent Demise", text: "Use this firefight ploy when a friendly GELLERPOX INFECTED operative (excluding MUTOID VERMIN) is incapacitated, before it’s removed from the killzone. Inflict 1 damage (or D3 damage instead if that friendly operative is a NIGHTMARE HULK) on each enemy operative visible to and within 2\" of that friendly operative." },
  { kind: 'firefight', name: "Barge", text: "Use this firefight ploy during a friendly GELLERPOX INFECTED NIGHTMARE HULK operative’s activation or counteraction, before or after it performs an action. During that activation/ counteraction:\n• It can move through enemy operatives and within control range of them.\n• It can perform the Charge and Reposition actions while within control range of an enemy operative, and can leave that operative’s control range to do so (but then normal requirements for that move apply)." },
  { kind: 'firefight', name: "Frightening Onslaught", text: "Use this firefight ploy after a friendly GELLERPOX INFECTED NIGHTMARE HULK operative performs the Fight action, if it isn't incapacitated. It can immediately perform a free Fight action (you don't have to select the same enemy operative to fight against). This takes precedence over action restrictions." },
  { kind: 'equipment', name: "Mutoid Vermin", text: "After revealing this equipment option, add four GELLERPOX INFECTED MUTOID VERMIN operatives to your kill team for the battle." },
  { kind: 'equipment', name: "Mutated Symptoms", text: "Once per battle, when you activate a friendly GELLERPOX INFECTED operative, you can select one additional TECHNO-CURSE for that operative to gain until the end of the turning point (it must be different from your existing TECHNO-CURSE). Note that if a rule refers to an enemy operative being affected by your selected TECHNO-CURSE rule (e.g. VULGRAR THRICE-CURSED operative’s Spread the Glorious Gifts rule), it’s affected by your additional TECHNO-CURSE rule too." },
  { kind: 'equipment', name: "Polluted Stockpile", text: "After revealing this equipment option, roll 2D6: on a 7+, remove one of your opponent’s selected equipment options; otherwise, that player removes one of their own selected equipment options. They cannot select that equipment again during the game sequence (e.g. in the Scouting step of Approved Ops). You cannot select this equipment option after the Select Operatives step." },
  { kind: 'equipment', name: "Plague Bellows", text: "Whenever an operative is shooting a friendly GELLERPOX INFECTED NIGHTMARE HULK operative that’s more than 6\" from it, you can retain one of your defence dice results of 3 as a normal success instead of discarding it." },
]

export const operatives: Operative[] = [
  { id: "gellerpox-infected:vulgrar-thrice-cursed", name: "Vulgrar Thrice-cursed", apl: 2, move: "5\"", save: "5+", w: 21 },
  { id: "gellerpox-infected:bloatspawn", name: "Bloatspawn", apl: 2, move: "5\"", save: "5+", w: 20 },
  { id: "gellerpox-infected:fleshscreamer", name: "Fleshscreamer", apl: 2, move: "5\"", save: "5+", w: 20 },
  { id: "gellerpox-infected:lumberghast", name: "Lumberghast", apl: 2, move: "5\"", save: "5+", w: 20 },
  { id: "gellerpox-infected:mutant", name: "Mutant", apl: 2, move: "5\"", save: "5+", w: 7 },
  { id: "gellerpox-infected:glitchling", name: "Glitchling", apl: 2, move: "6\"", save: "6+", w: 3 },
  { id: "gellerpox-infected:cursemite", name: "Cursemite", apl: 2, move: "6\"", save: "6+", w: 2 },
  { id: "gellerpox-infected:eyestinger-swarm", name: "Eyestinger Swarm", apl: 2, move: "6\"", save: "6+", w: 2 },
  { id: "gellerpox-infected:sludge-grub", name: "Sludge-grub", apl: 2, move: "4\"", save: "6+", w: 2 },
]
