// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Techno-curse", text: "At the end of the Select Operatives step, select one TECHNO-CURSE for friendly GELLERPOX INFECTED operatives to gain for the battle. Whenever an enemy operative is within your selected TECHNO-CURSE’s infection range, that enemy operative is affected by the symptom of the selected TECHNO-CURSE. Each TECHNO-CURSE, its infection range and its symptom is listed below:" },
  { kind: 'faction', name: "Mutoid Vermin", text: "MUTOID VERMIN operatives cannot perform any actions other than Charge, Dash, Fall Back, Fight, Reposition and Shoot, or use any weapons that aren’t on their datacard. They can perform the Fall Back action for 1 less AP. MUTOID VERMIN operatives cannot contest markers or areas of the killzone, and are ignored for your opponent’s kill/elimination op (when they're incapacitated, and when determining your starting number of operatives). They're also ignored for victory conditions and scoring VPs if either require operatives to ‘escape’, ‘survive’ or be incapacitated by enemy operatives (if they escape/survive/are incapacitated, determining how many operatives must escape/survive/be incapacitated, etc.)." },
  { kind: 'faction', name: "Nightmare Hulks", text: "Whenever your opponent is selecting a valid target, friendly GELLERPOX INFECTED NIGHTMARE HULK operatives cannot use Light terrain for cover. While this can allow such operatives to be targeted (assuming they’re visible), it doesn’t remove their cover save (if any). Friendly GELLERPOX INFECTED NIGHTMARE HULK operatives cannot perform unique actions. You must spend 1 additional AP for friendly GELLERPOX INFECTED NIGHTMARE HULK operatives (excluding VULGRAR THRICECURSED) to perform the Pick Up Marker and mission actions (excluding Operate Hatch)." },
  { kind: 'faction', name: "Revoltingly Resilient", text: "Whenever an attack dice inflicts damage of 3 or more on a friendly GELLERPOX INFECTED NIGHTMARE HULK or GELLERPOX INFECTED MUTANT operative, roll one D6: on a 4+, subtract 1 from that inflicted damage." },
  { kind: 'strategy', name: "Plagueridden Determination", text: "Whenever an operative is shooting a friendly GELLERPOX INFECTED operative (excluding MUTOID VERMIN) that has an Engage order, you can re-roll one of your defence dice." },
  { kind: 'strategy', name: "Drawn to the Hum", text: "Select one objective marker. Whenever a friendly GELLERPOX INFECTED operative performs the Reposition or Charge action during its activation, you can use this rule. If you do, add 1\" to its Move stat until the end of that activation, but it must end that move within 2\" of that objective marker." },
  { kind: 'strategy', name: "Blessings of Infection", text: "Whenever a friendly GELLERPOX INFECTED operative is fighting or retaliating, you can do one of the following:\n• If you roll three or more fails, you can discard one of them to retain another as a normal success instead.\n• If you roll three or more successes, you can discard one of your fails to retain one of your normal successes as a critical success instead." },
  { kind: 'strategy', name: "Rust Emanations", text: "Whenever a friendly GELLERPOX INFECTED operative (excluding MUTOID VERMIN) is fighting or retaliating, your opponent cannot retain results of 3 as successes." },
  { kind: 'firefight', name: "Revolting Technology", text: "Use this firefight ploy when an enemy operative is shooting a friendly GELLERPOX INFECTED operative. That operative’s ranged weapons have the Hot weapon rule until the end of that sequence; if the weapon already has that weapon rule, when your opponent rolls one D6 for that weapon rule, you can add or subtract 1 from the result. Note that for the latter you can see the result of your opponent’s roll for the Hot weapon rule before deciding to use this ploy." },
  { kind: 'firefight', name: "Putrescent Demise", text: "Use this firefight ploy when a friendly GELLERPOX INFECTED operative (excluding MUTOID VERMIN) is incapacitated, before it’s removed from the killzone. Inflict 1 damage (or D3 damage instead if that friendly operative is a NIGHTMARE HULK) on each enemy operative visible to and within 2\" of that friendly operative." },
  { kind: 'firefight', name: "Barge", text: "Use this firefight ploy during a friendly GELLERPOX INFECTED NIGHTMARE HULK operative’s activation or counteraction, before or after it performs an action. During that activation/ counteraction:\n• It can move through enemy operatives and within control range of them.\n• It can perform the Charge and Reposition actions while within control range of an enemy operative, and can leave that operative’s control range to do so (but then normal requirements for that move apply)." },
  { kind: 'firefight', name: "Frightening Onslaught", text: "Use this firefight ploy after a friendly GELLERPOX INFECTED NIGHTMARE HULK operative performs the Fight action, if it isn't incapacitated. It can immediately perform a free Fight action (you don't have to select the same enemy operative to fight against). This takes precedence over action restrictions." },
  { kind: 'equipment', name: "Mutoid Vermin", text: "After revealing this equipment option, add four GELLERPOX INFECTED MUTOID VERMIN operatives to your kill team for the battle." },
  { kind: 'equipment', name: "Mutated Symptoms", text: "Once per battle, when you activate a friendly GELLERPOX INFECTED operative, you can select one additional TECHNO-CURSE for that operative to gain until the end of the turning point (it must be different from your existing TECHNO-CURSE). Note that if a rule refers to an enemy operative being affected by your selected TECHNO-CURSE rule (e.g. VULGRAR THRICE-CURSED operative’s Spread the Glorious Gifts rule), it’s affected by your additional TECHNO-CURSE rule too." },
  { kind: 'equipment', name: "Polluted Stockpile", text: "After revealing this equipment option, roll 2D6: on a 7+, remove one of your opponent’s selected equipment options; otherwise, that player removes one of their own selected equipment options. They cannot select that equipment again during the game sequence (e.g. in the Scouting step of Approved Ops). You cannot select this equipment option after the Select Operatives step." },
  { kind: 'equipment', name: "Plague Bellows", text: "Whenever an operative is shooting a friendly GELLERPOX INFECTED NIGHTMARE HULK operative that’s more than 6\" from it, you can retain one of your defence dice results of 3 as a normal success instead of discarding it." },
]

export const operatives: Operative[] = [
  { id: "gellerpox-infected:vulgrar-thrice-cursed", name: "Vulgrar Thrice-cursed", apl: 2, move: "5\"", save: "5+", w: 21 },
  { id: "gellerpox-infected:bloatspawn", name: "Bloatspawn", apl: 2, move: "5\"", save: "5+", w: 20 },
  { id: "gellerpox-infected:fleshscreamer", name: "Fleshscreamer", apl: 2, move: "5\"", save: "5+", w: 20 },
  { id: "gellerpox-infected:lumberghast", name: "Lumberghast", apl: 2, move: "5\"", save: "5+", w: 20 },
  { id: "gellerpox-infected:mutant", name: "Mutant", apl: 2, move: "5\"", save: "5+", w: 7 },
  { id: "gellerpox-infected:glitchling", name: "Glitchling", apl: 2, move: "6\"", save: "6+", w: 3 },
  { id: "gellerpox-infected:cursemite", name: "Cursemite", apl: 2, move: "6\"", save: "6+", w: 2 },
  { id: "gellerpox-infected:eyestinger-swarm", name: "Eyestinger Swarm", apl: 2, move: "6\"", save: "6+", w: 2 },
  { id: "gellerpox-infected:sludge-grub", name: "Sludge-grub", apl: 2, move: "4\"", save: "6+", w: 2 },
]

export const datacards: Datacard[] = [
  {"name": "Vulgrar Thrice-cursed", "weapons": [{"name": "Pyregut (standard)", "atk": 5, "hit": "2+", "dmg": "3/3", "wr": "Range 6”, Saturate, Torrent 2”"}, {"name": "Pyregut (deluge)", "atk": 5, "hit": "2+", "dmg": "3/3", "wr": "Range 4”, Saturate, Seek Light"}, {"name": "Fleshmelded weapons", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Engineered*"}], "abilities": [{"name": "Spread the Glorious Gifts", "text": "Once per battle STRATEGIC GAMBIT. Select one objective marker this operative controls to gain one of your Techno-curse tokens. It cannot be an objective marker within control range of an enemy operative. Whenever that objective marker is within control range of an enemy operative, that operative is affected by your selected TECHNO-CURSE rule and an additional rule determined by your TECHNO-CURSE, as shown opposite. You cannot use this"}, {"name": "Engineered", "text": "At the end of the Select Operatives step, if this operative is selected for deployment, select up to two of the following improvements or weapon rules for this weapon to have for the battle: Add 1 to the Normal Dmg stat, add 1 to the Critical Dmg stat, Balanced, Brutal, Lethal 5+, Rending."}], "actions": [], "keywords": ["GELLERPOX INFECTED", "CHAOS", "NIGHTMARE HULK", "LEADER", "VULGRAR THRICE-CURSED"]},
  {"name": "Bloatspawn", "weapons": [{"name": "Mutant tentacles", "atk": 5, "hit": "4+", "dmg": "3/4", "wr": "Range 3\", Torrent 1\""}, {"name": "Mutant claw & tentacles (slashing)", "atk": 6, "hit": "4+", "dmg": "3/4"}, {"name": "Mutant claw & tentacles (swiping)", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Swipe*"}], "abilities": [{"name": "Swipe", "text": "Whenever this operative performs the Fight action and you select this weapon profile, if it isn't incapacitated, it can immediately perform a free Fight action afterwards, but you must select this weapon profile and it can only fight against each enemy operative within its control range once per activation or counteraction using this weapon profile. This takes precedence over action restrictions, and you can continue to perform free Fight actions until this operative is incapacitated or has fought against every enemy operative within its control range."}, {"name": "Tentacled Grasp", "text": "Whenever an enemy operative would perform the Fall Back action while within control range of this operative, you can use this rule. If you do, roll one D6, adding 1 to the result if that enemy operative has a Wounds stat of 8 or less: on a 4+, that enemy operative cannot perform that action during that activation/counteraction (the AP spent on it isn’t refunded)."}], "actions": [], "keywords": ["GELLERPOX INFECTED", "CHAOS", "NIGHTMARE HULK", "BLOATSPAWN"]},
  {"name": "Fleshscreamer", "weapons": [{"name": "Mutant fist and cleaver (lopping blow)", "atk": 1, "hit": "3+", "dmg": "8/9", "wr": "Lethal 5+"}, {"name": "Mutant fist and cleaver (slashing)", "atk": 5, "hit": "4+", "dmg": "5/6"}], "abilities": [{"name": "Horrifying Shrieking", "text": "Whenever an enemy operative is within 3\" of this operative, your opponent must spend 1 additional AP for that enemy operative to perform the Pick Up Marker and mission actions.\nWhenever determining control of a marker, treat the total APL stat of enemy operatives that contest it as 1 lower if at least one of those enemy operatives is within 3\" of this operative. Note this isn’t a change to the APL stat, so any changes are cumulative with this."}], "actions": [], "keywords": ["GELLERPOX INFECTED", "CHAOS", "NIGHTMARE HULK", "FLESHSCREAMER"]},
  {"name": "Lumberghast", "weapons": [{"name": "Mutant claw", "atk": 4, "hit": "4+", "dmg": "6/7", "wr": "Brutal"}], "abilities": [{"name": "Spiked Charger", "text": "Whenever this operative finishes moving during the Charge action, you can inflict D3 damage on each enemy operative within its control range (roll separately for each)."}], "actions": [], "keywords": ["GELLERPOX INFECTED", "CHAOS", "NIGHTMARE HULK", "LUMBERGHAST"]},
  {"name": "Mutant", "weapons": [{"name": "Frag grenade", "atk": 4, "hit": "4+", "dmg": "2/4", "wr": "Range 6\", Blast 2\", Limited 1, Saturate"}, {"name": "Heavy axe", "atk": 3, "hit": "4+", "dmg": "4/5", "wr": "Brutal"}, {"name": "Improvised weapon", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless"}], "abilities": [{"name": "Group Activation", "text": "Whenever this operative is expended, you must then activate one other ready friendly GELLERPOX INFECTED MUTANT operative (if able) before your opponent activates. When that other operative is expended, your opponent then activates as normal (in other words, you cannot activate more than two operatives in succession with this rule)."}, {"name": "Gellercaust Masks", "text": "Whenever an attack dice would inflict Critical Dmg on this operative, you can choose for that attack dice to inflict Normal Dmg instead."}], "actions": [], "keywords": ["GELLERPOX INFECTED", "CHAOS", "MUTANT"]},
  {"name": "Glitchling", "weapons": [{"name": "Diseased effluence", "atk": 4, "hit": "4+", "dmg": "2/2", "wr": "Range 6\""}, {"name": "Diseased nippers", "atk": 3, "hit": "4+", "dmg": "1/2"}], "abilities": [{"name": "Daemonic", "text": "Whenever an operative is shooting this operative, ignore the Piercing weapon rule."}, {"name": "Small", "text": "This operative cannot use any weapons that aren’t on its datacard, or perform unique actions. Whenever this operative has a Conceal order and is in cover, it cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2”."}, {"name": "Group Activation", "text": "Whenever this operative is expended, you must then activate one other ready friendly GELLERPOX INFECTED GLITCHLING operative (if able) before your opponent activates. When that other operative is expended, your opponent then activates as normal (in other words, you cannot activate more than two operatives in succession with this rule)."}], "actions": [], "keywords": ["GELLERPOX INFECTED", "CHAOS", "GLITCHLING"]},
  {"name": "Cursemite", "weapons": [{"name": "Bloodsucking proboscis", "atk": 2, "hit": "4+", "dmg": "2/3", "wr": "Rending, Feast*"}], "abilities": [{"name": "Feast", "text": "Whenever this operative is using this weapon against a wounded operative, add 1 to the Atk stat of this weapon and it has the Lethal 5+ weapon rule."}, {"name": "Group Activation", "text": "Whenever this operative is expended, you must then activate one other ready friendly GELLERPOX INFECTED MUTOID VERMIN operative (if able) before your opponent activates. When that other operative is expended, your opponent then activates as normal (in other words, you cannot activate more than two operatives in succession with this rule)."}], "actions": [], "keywords": ["GELLERPOX INFECTED", "CHAOS", "MUTOID VERMIN", "CURSEMITE"]},
  {"name": "Eyestinger Swarm", "weapons": [{"name": "Swarm", "atk": 5, "hit": "6+", "dmg": "0/0", "wr": "Range 6\", Stun"}, {"name": "Sting", "atk": 5, "hit": "5+", "dmg": "1/2", "wr": "Shock"}], "abilities": [{"name": "Group Activation", "text": "Whenever this operative is expended, you must then activate one other ready friendly GELLERPOX INFECTED MUTOID VERMIN operative (if able) before your opponent activates. When that other operative is expended, your opponent then activates as normal (in other words, you cannot activate more than two operatives in succession with this rule)."}], "actions": [], "keywords": ["GELLERPOX INFECTED", "CHAOS", "MUTOID VERMIN", "EYESTINGER SWARM"]},
  {"name": "Sludge-grub", "weapons": [{"name": "Acid spit", "atk": 4, "hit": "4+", "dmg": "2/2", "wr": "Range 6\", 1\" Devastating 1, Piercing 1"}, {"name": "Fanged maw", "atk": 2, "hit": "4+", "dmg": "1/3"}], "abilities": [{"name": "Group Activation", "text": "Whenever this operative is expended, you must then activate one other ready friendly GELLERPOX INFECTED MUTOID VERMIN operative (if able) before your opponent activates. When that other operative is expended, your opponent then activates as normal (in other words, you cannot activate more than two operatives in succession with this rule)."}, {"name": "Caustic Demise", "text": "When this operative is incapacitated, before it’s removed from the killzone, roll one D6 separately for each enemy operative visible to and within 2\" of it: on a 4+, inflict 1 damage on that operative."}], "actions": [], "keywords": ["GELLERPOX INFECTED", "CHAOS", "MUTOID VERMIN", "SLUDGE-GRUB"]},
]
