// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Gore Tanks", text: "Each friendly GOREMONGER operative has a GORE TANK that has three levels: full, half and empty. They start the battle at half. Whenever a GORE TANK increases, it goes up one level;\nwhenever it decreases, it goes down one level. A GORE TANK cannot increase when it’s already full, or decrease when it’s already empty (see diagram on other side)." },
  { kind: 'faction', name: "Runes of Khorne", text: "Each friendly GOREMONGER operative cannot lose more than 8 wounds per Shoot action.\nWhenever a friendly GOREMONGER operative incapacitates an operative within its control range, or visible to and within 2\" of it, you can increase its GORE TANK.\nWhenever a friendly GOREMONGER operative uses a SANGUAVITAE rule, you must decrease its GORE TANK.\nFULL\nDECREASE\nINCREASE\nHALF\nDECREASE INCREASE" },
  { kind: 'faction', name: "Sanguavitae", text: "Each SANGUAVITAE rule specifies when it can be used, and you must decrease the operative’s GORE TANK to do so. You cannot use the same SANGUAVITAE rule more than once per activation or counteraction, and you cannot use more than two SANGUAVITAE rules per activation or counteraction. You cannot use Mania and Fury during the same activation.\nSANGUAVITAE RULES ARE PRESENTED ON THEIR OWN CARDS\nMania WHEN: During a friendly GOREMONGER operative’s activation, before or after it performs an action. EFFECT: Until the start of that operative’s next activation, add 1 to its APL stat.\nRejuvenate WHEN: During a friendly GOREMONGER operative’s activation or counteraction, before or after it performs an action. EFFECT: That operative regains up to D3+1 lost wounds.\nFury WHEN: During a friendly GOREMONGER operative’s activation, before or after it performs an action. EFFECT: That operative can perform two Fight actions during that activation, and the second one is free.\nRake WHEN: When a friendly GOREMONGER operative performs the Charge action during its activation. EFFECT: When that operative finishes moving during that action, you can inflict D3 damage on one enemy operative within its control range.\nRage WHEN: When a friendly GOREMONGER operative performs the Fight action. EFFECT: Until the end of that action, add 1 to the Atk stat of that operative’s melee weapons.\nSurge WHEN: When a friendly GOREMONGER operative performs the Charge or Reposition action. EFFECT: Until the end of that action, add 1\" to that operative’s Move stat." },
  { kind: 'strategy', name: "Enhanced Violence", text: "Whenever a friendly GOREMONGER operative’s GORE TANK is:\n• Half, its melee weapons have the Balanced weapon rule.\n• Full, its melee weapons have the Relentless weapon rule." },
  { kind: 'strategy', name: "Gory Tenacity", text: "Whenever a friendly GOREMONGER operative is fighting or retaliating, the first time your opponent strikes it during that sequence, halve the damage inflicted (rounding up and to a minimum of 2)." },
  { kind: 'strategy', name: "Augmented Endurance", text: "Whenever an operative is shooting a friendly GOREMONGER operative, if that friendly operative’s GORE TANK is:\n• Half, you can re-roll one of your defence dice.\n• Full, you can re-roll any of your defence dice." },
  { kind: 'strategy', name: "Hunt for Blood", text: "Select one friendly GOREMONGER operative. If it has a Conceal order, change it to Engage. Then it can immediately perform a free Charge action, but cannot move more than 3\" during that action." },
  { kind: 'firefight', name: "Unbridled Aggression", text: "When they close with the enemy, Goremongers fight with all the savage fury and martial prowess of the Bloodletters they so idolise. Use this firefight ploy when a friendly GOREMONGER operative is fighting during an activation in which it performed the Charge action, at the end of the Roll Attack Dice step. Until the end of that sequence, that operative’s melee weapons have the Severe weapon rule." },
  { kind: 'firefight', name: "Destructive Demise", text: "Use this firefight ploy when a friendly GOREMONGER operative is incapacitated, before it’s removed from the killzone. Inflict damage determined by that friendly operative’s GORE TANK on one enemy operative within that friendly operative’s control range. Inflict:\n• D3 if empty.\n• D3+1 if half.\n• D3+2 if full." },
  { kind: 'firefight', name: "Gorethirst", text: "Use this firefight ploy when you would counteract. You can do so with one friendly GOREMONGER operative that has a Conceal order, but before it counteracts, you must change its order to Engage and it cannot perform any actions other than Charge, Shoot or Fight during that counteraction." },
  { kind: 'firefight', name: "Lacerate Flesh", text: "Use this firefight ploy when a friendly GOREMONGER operative with an empty GORE TANK is activated or counteracts. Increase that operative’s GORE TANK. At the end of that activation/counteraction, decrease its GORE TANK (you cannot use this decrease to use a SANGUAVITAE rule); if you cannot decrease its\nGORE TANK, inflict D3 damage on it." },
  { kind: 'equipment', name: "Gory Totem", text: "Before the battle, you can set up one of your Gory Totem markers wholly within your territory and more than 2\" from other markers (excluding your Bloody Cadaver marker). Whenever an enemy operative within 3\" of your Gory Totem marker is shooting, fighting or retaliating, your opponent cannot re-roll their attack dice." },
  { kind: 'equipment', name: "Chaos Sigil", text: "Once per turning point, when an operative is shooting a friendly GOREMONGER operative, at the start of the Roll Defence Dice step, you can use this rule. If you do, worsen the x of the Piercing weapon rule by 1 (if any) until the end of that sequence. Note that Piercing 1 would therefore be ignored." },
  { kind: 'equipment', name: "Bloody Cadaver", text: "Before the battle, you can set up one of your Bloody Cadaver markers wholly within your territory and more than 2\" from other markers (excluding your Gory Totem marker). Friendly GOREMONGER operatives can perform the Pick Up Marker action on that marker. In the Ready step of each Strategy phase, you can increase the GORE TANK of one friendly GOREMONGER operative that controls that marker, unless that friendly operative is within control range of an enemy operative." },
  { kind: 'equipment', name: "Wrist Chains", text: "Once per turning point, when a friendly GOREMONGER operative performs the Shoot action and you’re selecting a ranged weapon, you can use this rule. If you do, until the end of that action, the following melee weapons are treated as ranged weapons with the Range 2\" weapon rule: chainblade, chainglaive, great chainaxe (ignore its Brutal weapon rule), pickrippers. If that melee weapon has the Balanced or Relentless weapon rules as a result of the Enhanced Violence strategy ploy, it has those weapon rules while it is a ranged weapon." },
]

export const operatives: Operative[] = [
  { id: "goremongers:goremonger-blood-herald", name: "Goremonger Blood Herald", apl: 2, move: "7\"", save: "5+", w: 11 },
  { id: "goremongers:goremonger-aspirant", name: "Goremonger Aspirant", apl: 2, move: "7\"", save: "5+", w: 10 },
  { id: "goremongers:goremonger-bloodtaker", name: "Goremonger Bloodtaker", apl: 2, move: "7\"", save: "5+", w: 10 },
  { id: "goremongers:goremonger-impaler", name: "Goremonger Impaler", apl: 2, move: "7\"", save: "5+", w: 10 },
  { id: "goremongers:goremonger-inciter", name: "Goremonger Inciter", apl: 2, move: "7\"", save: "5+", w: 10 },
  { id: "goremongers:goremonger-skullclaimer", name: "Goremonger Skullclaimer", apl: 2, move: "7\"", save: "5+", w: 10 },
  { id: "goremongers:goremonger-stalker", name: "Goremonger Stalker", apl: 2, move: "7\"", save: "5+", w: 10 },
]

export const datacards: Datacard[] = [
  {"name": "Goremonger Blood Herald", "weapons": [], "abilities": [{"name": "Khorne’s Favour", "text": "Once during each of this operative’s activations, before or after it performs an action, if its GORE TANK is empty, you can increase its GORE TANK."}, {"name": "Impending Apotheosis", "text": "Once per battle, when an attack dice inflicts Normal Dmg on this operative, you can ignore that inflicted damage."}], "actions": [], "keywords": ["GOREMONGER", "CHAOS", "LEADER", "BLOOD HERALD"]},
  {"name": "Goremonger Aspirant", "weapons": [], "abilities": [{"name": "Obsessive Bloodlust", "text": "Once per turning point, when an operative with this rule ends the Fight action, if it’s no longer within control range of enemy operatives, you can use this rule. If you do, it can immediately perform a free Charge action (even if it’s already performed the Charge action during that activation), but it cannot move more than 2\" during that action. Doing so doesn’t prevent it from performing the Charge, Dash or Reposition action afterwards during that activation."}], "actions": [], "keywords": ["GOREMONGER", "CHAOS", "ASPIRANT"]},
  {"name": "Goremonger Bloodtaker", "weapons": [], "abilities": [], "actions": [{"name": "Transfusion Ritual", "ap": 1, "text": "Decrease this operative’s GORE TANK. Instead of using a\nSANGUAVITAE rule, you can increase the GORE TANK\nof one other friendly GOREMONGER operative within 8\"\nof this operative.\nThis operative cannot perform this action while within control range of an enemy operative, or if its GORE TANK is empty."}], "keywords": ["GOREMONGER", "CHAOS", "BLOODTAKER"]},
  {"name": "Goremonger Impaler", "weapons": [], "abilities": [], "actions": [{"name": "Gore-fuel", "ap": 1, "text": "Decrease this operative’s GORE TANK. Until this operative uses any profile of its fleshskewer, all profiles of it have the Severe weapon rule.\nThis operative cannot perform this action while within control range of an enemy operative, or if its GORE TANK is empty."}], "keywords": ["GOREMONGER", "CHAOS", "IMPALER"]},
  {"name": "Goremonger Inciter", "weapons": [], "abilities": [{"name": "Incite the Hunt", "text": "Whenever this operative incapacitates an enemy operative from more than 2\" away, before that enemy operative is removed from the killzone, you can increase the GORE TANK of one friendly GOREMONGER operative within 8\" of that enemy operative.\nWhenever this operative inflicts damage on an enemy operative with either profile of its dual autopistols but doesn’t incapacitate it, that enemy operative gains one of your Bleeding tokens (if it doesn’t already have one). During a friendly GOREMONGER operative’s activation or counteraction, before or after it performs an action, if it’s within 8\" of an enemy operative that has one of your Bleeding tokens, you can remove that token and increase that friendly operative’s GORE TANK."}], "actions": [{"name": "Dash and Spray", "ap": 1, "text": "Perform a free Dash action and a free Shoot action with this operative in any order. You can only select dual autopistols (focused) for that Shoot action.\nThis operative cannot perform this action while it has a Conceal order, or while within control range of an enemy operative."}], "keywords": ["GOREMONGER", "CHAOS", "INCITER"]},
  {"name": "Goremonger Skullclaimer", "weapons": [], "abilities": [{"name": "Brutish", "text": "Whenever an attack dice would inflict Critical Dmg on this operative, you can choose for that attack dice to inflict Normal Dmg instead."}, {"name": "Claim Skull", "text": "Once per turning point, if this operative incapacitates an enemy operative with its great chainaxe, you gain 1CP."}], "actions": [], "keywords": ["GOREMONGER", "CHAOS", "SKULLCLAIMER"]},
  {"name": "Goremonger Stalker", "weapons": [], "abilities": [{"name": "Climbing Picks", "text": "Whenever this operative is climbing up, you can treat the vertical distance as 2\" (regardless of how far the operative actually moves vertically).\nNOTES:\nNOTES:\nNOTES:"}, {"name": "Rooftop Stalker", "text": "Whenever this operative is fighting during an activation in which it dropped from Vantage terrain at least 2\" higher than the killzone floor, or whenever this operative is fighting against an enemy operative that’s on Vantage terrain at least 2\" higher than the killzone floor, this operative’s melee weapons have the Relentless weapon rule."}], "actions": [], "keywords": ["GOREMONGER", "CHAOS", "STALKER"]},
]
