// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Power from Pain", text: "After a friendly HAND OF THE ARCHON operative performs an action, it gains one of your Pain tokens if:\n• An enemy operative was injured during that action, but was not incapacitated.\n• An enemy operative was incapacitated during that action. If that enemy operative had a Wounds stat of 12 or more, that friendly operative gains two of your Pain tokens instead.\nYou can spend friendly operatives’ Pain tokens on invigorations when the ‘when’ condition is met. You cannot use more than one invigoration per activation or counteraction, except Stimulated Senses, which can be used once per activation or counteraction in addition to another invigoration." },
  { kind: 'faction', name: "Rifles", text: "Whenever a friendly HAND OF THE ARCHON operative is shooting with a splinter rifle during an activation in which it hasn’t performed the Charge, Fall Back or Reposition action, that weapon has the Accurate 1 weapon rule. Note that operative isn’t restricted from performing those actions after shooting." },
  { kind: 'strategy', name: "Blade Artists", text: "Friendly HAND OF THE ARCHON operatives' melee weapons have the Rending weapon rule." },
  { kind: 'strategy', name: "Merciless Sadists", text: "Whenever a friendly HAND OF THE ARCHON operative is shooting against or fighting against a wounded enemy operative, that friendly operative’s weapons have the Balanced weapon rule." },
  { kind: 'strategy', name: "From Darkness, Death", text: "Whenever a friendly HAND OF THE ARCHON operative is activated, before you determine its order, you can select one enemy operative that friendly operative isn’t a valid target for. Until the end of that activation, the first time that friendly operative is shooting against or fighting against that enemy operative, you can retain one of your normal successes as a critical success instead." },
  { kind: 'firefight', name: "Cruel Deception", text: "Use this firefight ploy during a friendly HAND OF THE ARCHON operative’s activation, before or after it performs an action. During that activation, that operative can perform the Fall Back action for 1 less AP." },
  { kind: 'strategy', name: "Denizens of Night", text: "Whenever an enemy operative is shooting a friendly HAND OF THE ARCHON operative that’s more than 2\" from enemy operatives, if Heavy or Light terrain is intervening, or any part of that friendly operative’s base is underneath Vantage terrain, you can re-roll one of your defence dice." },
  { kind: 'firefight', name: "Devious Scheme", text: "Use this firefight ploy after an opponent uses a firefight ploy (excluding one that costs 0CP). The next time they would use that ploy, they must spend 1 additional CP to do so (at which point this effect ends). You cannot use this ploy again during the battle until its effect has ended." },
  { kind: 'firefight', name: "Heinous Arrogance", text: "Use this firefight ploy when it’s your turn to activate a friendly operative. You can skip that activation." },
  { kind: 'equipment', name: "Chain Snare", text: "Whenever an enemy operative would perform the Fall Back action while within control range of a friendly HAND OF THE ARCHON operative, if no other enemy operatives are within that friendly operative’s control range, you can use this rule. If you do, roll two D6, or one D6 if that enemy operative has a higher Wounds stat than that friendly operative. If any result is a 4+, that enemy operative cannot perform that action during that activation/counteraction (no AP are spent on it), and you cannot use this rule again during this turning point." },
  { kind: 'firefight', name: "Prey on the Wounded", text: "Use this firefight ploy after rolling your attack dice for a friendly HAND OF THE ARCHON operative, if it’s shooting against or fighting against a wounded enemy operative. You can re-roll any of your attack dice." },
  { kind: 'equipment', name: "Wicked Blades", text: "Add 1 to the Atk stat of friendly HAND OF THE ARCHON operatives’ array of blades." },
  { kind: 'equipment', name: "Toxin Coating", text: "Up to twice per turning point, whenever a friendly HAND OF THE ARCHON operative is fighting or retaliating and you’re selecting a melee weapon, you can use this rule. If you do, until the end of that sequence, that operative’s melee weapon has the Lethal 5+ weapon rule." },
  { kind: 'equipment', name: "Refined Poison", text: "Up to twice per turning point, whenever a friendly HAND OF THE ARCHON operative is performing the Shoot action and you select a shardcarbine, splinter cannon, splinter pistol, splinter rifle or stinger pistol, you can use this rule. If you do, until the end of that action, add 1 to the Normal Dmg stat of that weapon." },
]

export const operatives: Operative[] = [
  { id: "hand-of-the-archon:kabalite-archsybarite", name: "Kabalite Archsybarite", apl: 2, move: "7\"", save: "4+", w: 9 },
  { id: "hand-of-the-archon:kabalite-agent", name: "Kabalite Agent", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "hand-of-the-archon:kabalite-crimson-duellist", name: "Kabalite Crimson Duellist", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "hand-of-the-archon:kabalite-disciple-of-yaelindra", name: "Kabalite Disciple of Yaelindra", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "hand-of-the-archon:kabalite-elixicant", name: "Kabalite Elixicant", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "hand-of-the-archon:kabalite-flayer", name: "Kabalite Flayer", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "hand-of-the-archon:kabalite-gunner", name: "Kabalite Gunner", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "hand-of-the-archon:kabalite-heavy-gunner", name: "Kabalite Heavy Gunner", apl: 2, move: "7\"", save: "4+", w: 8 },
  { id: "hand-of-the-archon:kabalite-skysplinter-assassin", name: "Kabalite Skysplinter Assassin", apl: 2, move: "7\"", save: "4+", w: 8 },
]

export const datacards: Datacard[] = [
  {"name": "Kabalite Archsybarite", "weapons": [{"name": "Blast pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Piercing 2"}, {"name": "Splinter pistol", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Range 8\", Lethal 5+"}, {"name": "Splinter rifle", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Lethal 5+"}, {"name": "Agoniser", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Brutal, Lethal 5+, Shock"}, {"name": "Array of blades", "atk": 3, "hit": "3+", "dmg": "3/4"}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}, {"name": "Venom blade", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Lethal 4+"}], "abilities": [{"name": "Cunning", "text": "In the Gambit step of each Strategy phase, if this operative is in the killzone and you pass at the first opportunity, you gain 1CP. Ignore each STRATEGIC GAMBIT from the mission pack (if any) when determining this."}, {"name": "Torturous Vision", "text": "Once during each of this operative’s activations, if it doesn’t have any of your Pain tokens when it performs either the Fight or Shoot action, it can gain one of your Pain tokens when you select a valid target or an enemy operative to fight against."}], "actions": [], "keywords": ["HAND OF THE ARCHON", "AELDARI", "DRUKHARI", "LEADER", "ARCHSYBARITE"], "img": "/ops/hand-of-the-archon/kabalite-archsybarite.webp"},
  {"name": "Kabalite Agent", "weapons": [{"name": "Splinter rifle", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Lethal 5+"}, {"name": "Array of blades", "atk": 3, "hit": "3+", "dmg": "3/4"}], "abilities": [{"name": "Sadistic Competition", "text": "Once per turning point, when a friendly HAND OF THE ARCHON operative gains one of your Pain tokens, one friendly HAND OF THE ARCHON AGENT operative that doesn’t have one of your Pain tokens can also gain one."}], "actions": [], "keywords": ["HAND OF THE ARCHON", "AELDARI", "DRUKHARI", "AGENT"], "img": "/ops/hand-of-the-archon/kabalite-agent.webp"},
  {"name": "Kabalite Crimson Duellist", "weapons": [{"name": "Splinter pistol", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Range 8\", Lethal 5+"}, {"name": "Razorflail", "atk": 4, "hit": "2+", "dmg": "4/5", "wr": "Brutal, Tangle*"}], "abilities": [{"name": "Brutal Display", "text": "Once per turning point, when this operative incapacitates an enemy operative within its control range, you can select one other enemy operative visible to and within 6\" of either this operative or the incapacitated enemy operative. Until the start of the next turning point, that other enemy operative cannot control markers or perform the Pick Up Marker or mission actions."}, {"name": "Crimson Duellist", "text": "This operative can perform two Fight actions during its activation."}, {"name": "Tangle", "text": "Whenever this operative is fighting or retaliating with this weapon, each of your blocks can be allocated to block two unresolved successes (instead of one)."}], "actions": [], "keywords": ["HAND OF THE ARCHON", "AELDARI", "DRUKHARI", "CRIMSON DUELLIST"], "img": "/ops/hand-of-the-archon/kabalite-crimson-duellist.webp"},
  {"name": "Kabalite Disciple of Yaelindra", "weapons": [{"name": "Stinger pistol", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Lethal 5+, Stinger*"}, {"name": "Array of blades", "atk": 3, "hit": "3+", "dmg": "3/4"}], "abilities": [{"name": "Stinger", "text": "Whenever an enemy operative is incapacitated by this weapon, before it’s removed from the killzone, inflict D3 damage on each other operative visible to and within 2\" of it (roll separately for each). Each operative subsequently incapacitated as a result of this weapon rule will cause this to happen again."}], "actions": [{"name": "Torment Grenade", "ap": 1, "text": "Select one enemy operative visible to and within 6\" of this operative. That operative and each other operative within 1\" of it takes a poison test.\nFor an operative to take a poison test, roll one D6, adding 1 to the result if that operative has a Save stat of 4+ or worse: on a 3+, inflict D3 damage on that operative and it gains one of your Poison tokens (if it doesn’t already have one). Whenever an operative that has one of your Poison tokens is activated, inflict D3 damage on it.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["HAND OF THE ARCHON", "AELDARI", "DRUKHARI", "DISCIPLE OF YAELINDRA"], "img": "/ops/hand-of-the-archon/kabalite-disciple-of-yaelindra.webp"},
  {"name": "Kabalite Elixicant", "weapons": [{"name": "Splinter rifle", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Lethal 5+"}, {"name": "Stim-needler", "atk": 4, "hit": "3+", "dmg": "0/0", "wr": "Range 3\", Lethal 3+, Stun"}, {"name": "Array of blades", "atk": 3, "hit": "3+", "dmg": "3/4"}], "abilities": [{"name": "Combat Drugs", "text": "At the end of the Select Operatives step, if this operative is selected for deployment, select one of the following COMBAT DRUG rules for friendly HAND OF THE ARCHON operatives to have for the battle:\n• Painbringer: Whenever an attack dice inflicts damage of 3 or more on this operative, roll one D6: on a 6, subtract 1 from that inflicted damage. • Adrenalight: In the Ready step of each Strategy phase, you can select one friendly operative that has this COMBAT DRUG to gain one of your Pain tokens. • Hypex: You can ignore any changes to this operative’s Move stat from being injured."}], "actions": [{"name": "Administer Drug", "ap": 1, "text": "Select one friendly HAND OF THE ARCHON operative visible to and within 3\" of this operative, then select one of the following for that friendly operative:\n• It regains up to 2D3 lost wounds. • Select a different COMBAT DRUG rule for it to have for the battle (this replaces its previous one).\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["HAND OF THE ARCHON", "AELDARI", "DRUKHARI", "ELIXICANT"], "img": "/ops/hand-of-the-archon/kabalite-elixicant.webp"},
  {"name": "Kabalite Flayer", "weapons": [{"name": "Pain sculptors", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Ceaseless, Flay*"}], "abilities": [{"name": "Insensible to Pain", "text": "Normal and Critical Dmg of 3 or more inflicts 1 less damage on this operative."}, {"name": "Flay", "text": "Whenever this operative is using this weapon, the first time you strike with a critical success during that sequence, you can select one friendly HAND OF THE ARCHON operative within 6\" of it to gain one of your Pain tokens."}], "actions": [], "keywords": ["HAND OF THE ARCHON", "AELDARI", "DRUKHARI", "FLAYER"], "img": "/ops/hand-of-the-archon/kabalite-flayer.webp"},
  {"name": "Kabalite Gunner", "weapons": [{"name": "Blaster", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Piercing 2"}, {"name": "Shredder", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Rending, Torrent 2\""}, {"name": "Array of blades", "atk": 3, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["HAND OF THE ARCHON", "AELDARI", "DRUKHARI", "GUNNER"], "img": "/ops/hand-of-the-archon/kabalite-gunner.webp"},
  {"name": "Kabalite Heavy Gunner", "weapons": [{"name": "Dark lance", "atk": 4, "hit": "3+", "dmg": "6/7", "wr": "Heavy (Dash only), Piercing 2"}, {"name": "Splinter cannon (focused)", "atk": 5, "hit": "3+", "dmg": "3/5", "wr": "Heavy (Dash only), Lethal 5+"}, {"name": "Splinter cannon (sweeping)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Heavy (Dash only), Lethal 5+, Torrent 1\""}, {"name": "Array of blades", "atk": 3, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["HAND OF THE ARCHON", "AELDARI", "DRUKHARI", "HEAVY GUNNER"], "img": "/ops/hand-of-the-archon/kabalite-heavy-gunner.webp"},
  {"name": "Kabalite Skysplinter Assassin", "weapons": [{"name": "Razorwing", "atk": 4, "hit": "4+", "dmg": "1/2", "wr": "Saturate, Seek, Silent"}, {"name": "Shardcarbine", "atk": 4, "hit": "2+", "dmg": "2/2", "wr": "Devastating 2, Lethal 5+"}, {"name": "Array of blades", "atk": 3, "hit": "3+", "dmg": "3/4"}], "abilities": [{"name": "Merciless Hunter", "text": "If this operative doesn’t perform the Mark unique action (see other side of card) during its activation, it can perform two Shoot actions during its activation, but a razorwing must be selected for one (and only one) of those actions."}, {"name": "Omen", "text": "In the Select Operatives step, when you’re selecting equipment, you can select one enemy operative or one other\nfriendly HAND OF THE ARCHON operative (reveal your\nselection when you reveal equipment). Whenever attack or\ndefence dice are rolled for that operative:\n• If it’s an enemy operative, your opponent must re-roll their\ndice results of 6.\n• If it’s a friendly operative, you can re-roll any of your dice results of 1."}], "actions": [{"name": "Mark", "ap": 1, "text": "Select one enemy operative visible to this operative. Until the\nend of the turning point, whenever this operative is shooting\nthat enemy operative you can use this effect. If you do:\n• This operative’s ranged weapons have the Seek Light\nweapon rule.\n• That enemy operative cannot be obscured.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["HAND OF THE ARCHON", "AELDARI", "DRUKHARI", "SKYSPLINTER ASSASSIN"], "img": "/ops/hand-of-the-archon/kabalite-skysplinter-assassin.webp"},
]
