// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Grudge", text: "If a particular foe shames or insults the Kin gravely enough, they will become the subject of a Grudge. To destroy this most hated enemy, the Kin will go to any lengths, even if it is to their own detriment.\nWhenever an enemy operative incapacitates a friendly HEARTHKYN SALVAGER operative, that enemy operative gains one of your Grudge tokens for the battle.\nWhenever a friendly HEARTHKYN SALVAGER operative is shooting against, fighting against or retaliating against an enemy operative, for each of your Grudge tokens that enemy operative has, you can retain one of your normal successes as a critical success instead (including any normal successes already retained as a result of the Accurate weapon rule). Note that Grudge tokens aren’t removed when you do this." },
  { kind: 'strategy', name: "Need Keeps", text: "Select one objective marker or one of your mission markers.\n• Whenever determining control of that marker, treat the total APL stat of friendly HEARTHKYN SALVAGER operatives that contest it as 1 higher if at least one friendly HEARTHKYN SALVAGER operative contests that marker. Note this isn’t a change to the APL stat, so any changes are cumulative with this.\n• Whenever a friendly HEARTHKYN SALVAGER operative is within 3\" of that marker, add 1 to the Atk stat of its melee weapons (to a maximum of 4); if the weapon already has an Atk stat of 4, it has the Balanced weapon rule." },
  { kind: 'strategy', name: "Wrought Defence", text: "Whenever an operative is shooting a friendly HEARTHKYN SALVAGER operative, if you rolled one or less successes (including any re-rolls), you can retain one of your fails as a normal success instead of discarding it." },
  { kind: 'strategy', name: "Toil Earns", text: "Select one objective marker or one of your mission markers. Whenever an enemy operative is within 3\" of that marker, treat it as having one additional Grudge token." },
  { kind: 'strategy', name: "Proximate Firepower", text: "Whenever a friendly HEARTHKYN SALVAGER operative is shooting an enemy operative within 6\" of it, improve the Hit stat of that friendly operative’s ranged weapons by 1 (to a maximum of 3+). This can allow you to apply or remove the Hit stat change during an action (this takes precedence over the core rules)." },
  { kind: 'firefight', name: "The Ancestors Are Watching", text: "Use this firefight ploy during a friendly HEARTHKYN SALVAGER operative’s activation. Until the end of that activation, that operative can perform either a free Shoot or a free Fight action and you can ignore any changes to that operative’s weapon stats from being injured." },
  { kind: 'firefight', name: "Sturdy", text: "Use this firefight ploy when an operative is shooting a friendly HEARTHKYN SALVAGER operative, when you collect your defence dice. Change the attacker’s retained critical successes to normal successes (any weapon rules they’ve already resolved aren’t affected, e.g. Piercing Crits)." },
  { kind: 'firefight', name: "Worth It", text: "Use this firefight ploy when a friendly HEARTHKYN SALVAGER operative is incapacitated. It can perform a free mission action before it’s removed from the killzone." },
  { kind: 'firefight', name: "Engage to Acquire", text: "Use this firefight ploy after rolling your attack dice for a friendly HEARTHKYN SALVAGER operative, if it’s shooting against or fighting against an enemy operative that controls an objective marker or one of your mission markers. You can re-roll any of your attack dice." },
  { kind: 'equipment', name: "Plasma Knives", text: "Friendly HEARTHKYN SALVAGER operatives have the following melee weapon. Note that the FIELD MEDIC operative already has this weapon but with better stats; in that instance, use the better version.\nNAME ATK HIT DMG\nPlasma knife 3 4+ 3/5 WR Lethal 5+" },
  { kind: 'equipment', name: "Excavation Tools", text: "Friendly HEARTHKYN SALVAGER operatives can perform the Pick Up Marker action for 1 less AP, and don’t have to control the marker to do so (this takes precedence over that action’s conditions – they only need to contest the marker)." },
  { kind: 'equipment', name: "Climbing Rigs", text: "During each friendly HEARTHKYN SALVAGER operative’s activation, you can do one of the following:\n• When that operative is climbing up, you can treat the vertical distance as 2\" (regardless of how far the operative actually moves vertically).\n• When that operative is dropping, ignore the vertical distance." },
  { kind: 'equipment', name: "Writ of Claim", text: "When the Salvagers of a League have staked their claim, they will defend their due with steadfast determination.\nOnce per battle, if friendly HEARTHKYN SALVAGER operatives contest two or more objective markers, after rolling off to decide initiative, you can use this rule. If you do, you can re-roll your dice." },
]

export const operatives: Operative[] = [
  { id: "hearthkyn-salvagers:hearthkyn-theyn", name: "Hearthkyn Theyn", apl: 2, move: "5\"", save: "3+", w: 9 },
  { id: "hearthkyn-salvagers:hearthkyn-d-zr", name: "Hearthkyn Dôzr", apl: 2, move: "5\"", save: "3+", w: 8 },
  { id: "hearthkyn-salvagers:hearthkyn-field-medic", name: "Hearthkyn Field Medic", apl: 2, move: "5\"", save: "3+", w: 8 },
  { id: "hearthkyn-salvagers:hearthkyn-grenadier", name: "Hearthkyn Grenadier", apl: 2, move: "5\"", save: "3+", w: 8 },
  { id: "hearthkyn-salvagers:hearthkyn-gunner", name: "Hearthkyn Gunner", apl: 2, move: "5\"", save: "3+", w: 8 },
  { id: "hearthkyn-salvagers:hearthkyn-jump-pack-warrior", name: "Hearthkyn Jump Pack Warrior", apl: 2, move: "8\"", save: "3+", w: 8 },
  { id: "hearthkyn-salvagers:hearthkyn-kinlynk", name: "Hearthkyn Kinlynk", apl: 2, move: "5\"", save: "3+", w: 8 },
  { id: "hearthkyn-salvagers:hearthkyn-kognit-ar", name: "Hearthkyn Kognitâar", apl: 2, move: "5\"", save: "3+", w: 8 },
  { id: "hearthkyn-salvagers:hearthkyn-lok-tr", name: "Hearthkyn Lokâtr", apl: 2, move: "5\"", save: "3+", w: 8 },
  { id: "hearthkyn-salvagers:hearthkyn-lugger", name: "Hearthkyn Lugger", apl: 2, move: "5\"", save: "3+", w: 8 },
  { id: "hearthkyn-salvagers:hearthkyn-warrior", name: "Hearthkyn Warrior", apl: 2, move: "5\"", save: "3+", w: 8 },
]

export const datacards: Datacard[] = [
  {"name": "Hearthkyn Theyn", "weapons": [{"name": "Autoch-pattern bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Accurate 1"}, {"name": "Autoch-pattern bolter", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Accurate 1"}, {"name": "Bolt revolver", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\""}, {"name": "EtaCarn plasma pistol", "atk": 4, "hit": "4+", "dmg": "3/5", "wr": "Range 8\", Piercing 1"}, {"name": "Ion blaster", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Piercing Crits 1"}, {"name": "Ion pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Piercing Crits 1"}, {"name": "Concussion gauntlet", "atk": 4, "hit": "4+", "dmg": "5/7", "wr": "Brutal, Shock"}, {"name": "Plasma weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Eye of the Ancestors", "text": "STRATEGIC GAMBIT if this operative is in the killzone. Select one enemy operative, or up to two enemy operatives if three or more friendly HEARTHKYN SALVAGER operatives are incapacitated. Each of those enemy operatives gains one of your Grudge tokens."}, {"name": "Weavefield Crest", "text": "Once per battle, when an attack dice inflicts Normal Dmg on this operative, you can ignore that inflicted damage."}], "actions": [], "keywords": ["HEARTHKYN SALVAGER", "LEAGUES OF VOTANN", "LEADER", "THEYN"], "img": "/ops/hearthkyn-salvagers/hearthkyn-theyn.webp"},
  {"name": "Hearthkyn Dôzr", "weapons": [{"name": "Autoch-pattern bolt pistol", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Range 8\", Accurate 1"}, {"name": "Concussion knux", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Ceaseless, Lethal 5+, Shock"}], "abilities": [{"name": "Brawler", "text": "Whenever this operative is fighting or retaliating:\n• Enemy operatives cannot assist. • If it's incapacitated, you can strike the enemy operative in that sequence with one of your unresolved successes before it’s removed from the killzone. • Normal Dmg of 4 or more inflicts 1 less damage on it.\nHEARTHKYN SALVAGER , LEAGUES OF VOTANN, DÔZR"}], "actions": [{"name": "Knux Smash", "ap": 1, "text": "Select one enemy operative within this operative’s control range. You can move that enemy operative up to 3\" to a location it can be placed. Then inflict D3+1 damage on it (even if you don’t move it); if the D3 result is a 3, also subtract 1 from that enemy operative's APL stat until the end of its next activation. This operative can then immediately perform a free Charge action (even if it’s already performed the Charge action during that activation), but cannot move more than 3\" during that action.\nThis operative cannot perform this action unless an enemy operative is within its control range.\n28"}], "img": "/ops/hearthkyn-salvagers/hearthkyn-d-zr.webp"},
  {"name": "Hearthkyn Field Medic", "weapons": [{"name": "Bolt revolver", "atk": 4, "hit": "4+", "dmg": "3/5", "wr": "Range 8\""}, {"name": "Plasma knife", "atk": 4, "hit": "4+", "dmg": "3/5", "wr": "Lethal 5+"}], "abilities": [{"name": "Medic!", "text": "The first time during each turning point that another friendly HEARTHKYN SALVAGER operative would be incapacitated while visible to and within 3\" of this operative, you can use this rule, providing neither this nor that operative is within control range of an enemy operative. If you do, that friendly operative isn’t incapacitated, has 1 wound remaining and cannot be incapacitated for the remainder of the action. After that action, that friendly operative can immediately perform a free Dash action, but must end that move within this operative’s control range. Subtract 1 from this and that operative’s APL stats until the end of their next activations respectively, and if this rule was used during that friendly operative’s activation, that activation ends. You cannot use this rule if this operative is incapacitated, or if it’s a Shoot action and this operative would be a primary or secondary target."}], "actions": [{"name": "Medikit", "ap": 1, "text": "Select one friendly HEARTHKYN SALVAGER operative within this operative’s control range to regain up to 2D3 lost wounds. It cannot be an operative that the Medic! rule was used on during this turning point.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["HEARTHKYN SALVAGER", "LEAGUES OF VOTANN", "MEDIC", "FIELD MEDIC"], "img": "/ops/hearthkyn-salvagers/hearthkyn-field-medic.webp"},
  {"name": "Hearthkyn Grenadier", "weapons": [{"name": "Autoch-pattern bolt pistol", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Range 8\", Accurate 1"}, {"name": "C8 HX charge", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Range 4\", Blast 1\", Heavy (Reposition only), Limited 1, Piercing 1, Saturate"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Grenadier", "text": "This operative can use frag, krak, smoke and stun grenades (see universal equipment). Doing so doesn’t count towards any limited uses you have (i.e. if you also select those grenades from equipment for other operatives). Whenever this operative is using a frag or krak grenade, improve the Hit stat of that weapon by 1."}], "actions": [], "keywords": ["HEARTHKYN SALVAGER", "LEAGUES OF VOTANN", "GRENADIER"], "img": "/ops/hearthkyn-salvagers/hearthkyn-grenadier.webp"},
  {"name": "Hearthkyn Gunner", "weapons": [{"name": "EtaCarn plasma beamer", "atk": 4, "hit": "4+", "dmg": "5/6", "wr": "Piercing 1, Beam*"}, {"name": "HYLas auto rifle", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Ceaseless, Rending"}, {"name": "HYLas rotary cannon (focused)", "atk": 5, "hit": "4+", "dmg": "4/5", "wr": "Ceaseless, Heavy (Reposition only), Saturate"}, {"name": "HYLas rotary cannon (sweeping)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Ceaseless, Heavy (Reposition only), Saturate, Torrent 1\""}, {"name": "L7 missile launcher (blast)", "atk": 4, "hit": "4+", "dmg": "3/5", "wr": "Blast 2\""}, {"name": "L7 missile launcher (focused)", "atk": 4, "hit": "4+", "dmg": "5/6", "wr": "Piercing 1"}, {"name": "Magna rail rifle", "atk": 4, "hit": "4+", "dmg": "4/2", "wr": "Devastating 3, Heavy (Dash only), Piercing 2"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Beam", "text": "Whenever this operative is shooting with this weapon, each retained critical success immediately inflicts D3 damage on each other operative along one (and only one) beam line (roll\nseparately for each operative), but the target isn’t affected. An operative is along a beam line if a targeting line can be drawn from this operative to its base, and that line crosses the base of\nthe original target but doesn’t cross Heavy terrain. In this example, Operative A is the target. Operatives B and C are along the beam line, but Operative D isn’t."}], "actions": [], "keywords": ["HEARTHKYN SALVAGER", "LEAGUES OF VOTANN", "GUNNER"], "img": "/ops/hearthkyn-salvagers/hearthkyn-gunner.webp"},
  {"name": "Hearthkyn Jump Pack Warrior", "weapons": [{"name": "Autoch-pattern bolt pistol", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Range 8\", Accurate 1"}, {"name": "Plasma weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+, Force Impact*"}], "abilities": [{"name": "Jump Pack", "text": "Whenever this operative performs an action in which it moves, it can FLY. If it does, don’t move it. Instead, remove it from the killzone and set it back up wholly within a distance equal to its Move stat (or 3\" if it was a Dash) horizontally of its original location (in a killzone that uses the close quarters rules, e.g. Killzone: Tomb World, this distance cannot be measured over or through Wall terrain, and that operative cannot be set up on the other side of an access point – in other words it cannot FLY through an open hatchway). Note that it gains no additional distance when performing the Charge action. It must be set up in a location it can be placed, and unless it’s the Charge action, it cannot be set up within control range of an enemy operative."}, {"name": "Force Impact", "text": "Whenever this operative is fighting with this weapon, if it’s performed the Charge action during the activation, this weapon has the Brutal weapon rule."}], "actions": [], "keywords": ["HEARTHKYN SALVAGER", "LEAGUES OF VOTANN", "JUMP PACK WARRIOR"], "img": "/ops/hearthkyn-salvagers/hearthkyn-jump-pack-warrior.webp"},
  {"name": "Hearthkyn Kinlynk", "weapons": [{"name": "Autoch-pattern bolter", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Accurate 1"}, {"name": "Ion blaster", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Piercing Crits 1"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [{"name": "Signal", "ap": 1, "text": "SUPPORT. Select one other friendly HEARTHKYN                            This operative cannot perform this action while within control SALVAGER operative in the killzone. Until the end of that               range of an enemy operative. operative’s next activation, add 1 to its APL stat."}, {"name": "System Jam", "ap": 1, "text": "Select one enemy operative that's a valid target for this operative and that doesn’t have one of your System Jam tokens; it gains one. Until the end of the battle, whenever an enemy operative has one of your System Jam tokens, it cannot be activated until each enemy operative without one is expended. When an enemy operative that has one of your System Jam tokens is activated, remove that token.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["HEARTHKYN SALVAGER", "LEAGUES OF VOTANN", "KINLYNK"], "img": "/ops/hearthkyn-salvagers/hearthkyn-kinlynk.webp"},
  {"name": "Hearthkyn Kognitâar", "weapons": [{"name": "Autoch-pattern bolter", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Accurate 1"}, {"name": "Ion blaster", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Piercing Crits 1"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Tactician", "text": "STRATEGIC GAMBIT if this operative is in the killzone. Place either your Attack or Defence marker in the killzone. Whenever a friendly HEARTHKYN SALVAGER operative is shooting against, fighting against or retaliating against an enemy operative that’s within 3\" of your Attack marker, that friendly operative’s weapons have the Balanced weapon rule. Whenever an enemy operative is shooting a friendly HEARTHKYN SALVAGER operative that’s within 3\" of your Defence marker, you can re-roll one of your defence dice. In the Ready step of the next Strategy phase, remove that marker.\nHEARTHKYN SALVAGER , LEAGUES OF VOTANN, KOGNITÂAR                                                                                        28"}], "actions": [{"name": "Accelerated Appraisal", "ap": 1, "text": "If your Attack or Defence marker is in the killzone, remove it.\nPlace your Attack or Defence marker in the killzone.\nThis operative cannot perform this action while within control range of an enemy operative."}], "img": "/ops/hearthkyn-salvagers/hearthkyn-kognit-ar.webp"},
  {"name": "Hearthkyn Lokâtr", "weapons": [{"name": "Autoch-pattern bolter", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Accurate 1"}, {"name": "Ion blaster", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Piercing Crits 1"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [{"name": "Spot", "ap": 1, "text": "SUPPORT. Select one enemy operative visible to this operative. Until the end of the turning point, whenever a friendly HEARTHKYN SALVAGER operative within 3\" of this operative is shooting that enemy operative, you can use this effect. If you do:\n• That friendly operative’s ranged weapons have the Seek Light weapon rule. • That enemy operative cannot be obscured.\nThis operative cannot perform this action while within control range of an enemy operative."}, {"name": "Pan Spectral Scan", "ap": 1, "text": "Place your Pan Spectral Scan marker in the killzone. Whenever a friendly HEARTHKYN SALVAGER operative is shooting an enemy operative that’s within 3\" of that marker, that friendly operative’s ranged weapons have the Accurate 1 and Saturate weapon rules. When this operative is next activated, is incapacitated or performs this action again (whichever comes first), remove that marker.\nThis operative cannot perform this action while within control range of an enemy operative."}], "img": "/ops/hearthkyn-salvagers/hearthkyn-lok-tr.webp"},
  {"name": "Hearthkyn Lugger", "weapons": [{"name": "Autoch-pattern bolter", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Accurate 1"}, {"name": "Ion blaster", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Piercing Crits 1"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Well Supplied", "text": "You can select one additional equipment option, and in the Ready step of the first Strategy phase, you gain 1 additional CP."}, {"name": "I’ve Got It", "text": "Once during each of this operative’s activations, it can perform a mission action for 1 less AP."}], "actions": [], "keywords": ["HEARTHKYN SALVAGER", "LEAGUES OF VOTANN", "LUGGER"], "img": "/ops/hearthkyn-salvagers/hearthkyn-lugger.webp"},
  {"name": "Hearthkyn Warrior", "weapons": [{"name": "Autoch-pattern bolter", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Accurate 1"}, {"name": "Ion blaster", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Piercing Crits 1"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Secure Salvage", "text": "Whenever an enemy operative is shooting against, fighting against or retaliating against this operative, if this operative contests an objective marker or one of your mission markers, in the Resolve Attack Dice step, you can subtract 1 from the damage inflicted on it from one success."}], "actions": [], "keywords": ["HEARTHKYN SALVAGER", "LEAGUES OF VOTANN", "WARRIOR"], "img": "/ops/hearthkyn-salvagers/hearthkyn-warrior.webp"},
]
