// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Resourceful", text: "In the Ready step of each Strategy phase after the first, you gain Resourceful points determined by the number of friendly HERNKYN YAEGIR operatives in the killzone that aren’t within control range of enemy operatives. At the end of each turning point, discard your Resourceful points." },
  { kind: 'faction', name: "Dauntless Explorers", text: "The first of their kindred to set foot on new worlds, Yaegirs are frequently deployed for extended periods and are experts in swiftly evaluating and exploiting their area of operations.\nSTRATEGIC GAMBIT in the first turning point. Each friendly HERNKYN YAEGIR operative wholly within your drop zone can immediately perform a free Reposition action. Each that does so must end that move wholly within 4\" of your drop zone." },
  { kind: 'strategy', name: "Masterful Bladework", text: "Whenever a friendly HERNKYN YAEGIR operative is fighting, or has a Conceal order and is retaliating, add 1 to the Atk stat of its melee weapons (to a maximum of 4) and they have the Balanced weapon rule; if the weapon already has that weapon rule, it has the Ceaseless weapon rule instead of Balanced." },
  { kind: 'strategy', name: "Hidden Engagement", text: "Whenever a friendly HERNKYN YAEGIR operative is shooting, if it’s in cover from the target’s perspective, that friendly operative’s weapons have the Balanced weapon rule. Note that your opponent still determines the targeting lines for this (i.e. they decide which point of their operative’s base targeting lines are drawn from)." },
  { kind: 'strategy', name: "Tough Survivalists", text: "The first time an attack dice inflicts damage on each friendly HERNKYN YAEGIR operative during the turning point in the Resolve Attack Dice step, you can halve that inflicted damage (rounding up, to a minimum of 2)." },
  { kind: 'strategy', name: "In Position", text: "Whenever a friendly HERNKYN YAEGIR operative has a Conceal order and is in cover, it cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2\"." },
  { kind: 'firefight', name: "Bonds That Bind", text: "Use this firefight ploy when a friendly HERNKYN YAEGIR operative is activated. Select one other ready friendly HERNKYN YAEGIR operative visible to and within 3\" of that operative. When that first friendly operative is expended, you can activate that other friendly operative before your opponent activates. When that other operative is expended, your opponent then activates as normal.\nNeither operative can be a BOMBAST operative if its Wroughtlock Negotiation STRATEGIC GAMBIT has been used this turning point." },
  { kind: 'firefight', name: "Sturdy", text: "Use this firefight ploy when an operative is shooting a friendly HERNKYN YAEGIR operative, when you collect your defence dice. Change the attacker’s retained critical successes to normal successes (any weapon rules they’ve already resolved aren’t affected, e.g. Piercing Crits)." },
  { kind: 'firefight', name: "No Kin Left Behind", text: "Use this firefight ploy when a friendly HERNKYN YAEGIR operative is incapacitated. Before that operative is removed from the killzone, remove your Fallen Kin marker from the killzone (if any), then place it within that operative’s control range. That operative is then removed from the killzone as normal.\nWhenever a friendly HERNKYN YAEGIR operative within 3\" of your Fallen Kin marker is shooting, fighting or retaliating, in the Roll Attack Dice step, you can retain one of your fails as a normal success instead of discarding it, or retain one of your normal successes as a critical success instead." },
  { kind: 'firefight', name: "Stalwart Defence", text: "Use this firefight ploy when an enemy operative ends the Charge action within control range of a friendly HERNKYN YAEGIR operative. Select one other friendly HERNKYN YAEGIR operative visible to and within 6\" of that friendly operative, but that isn’t itself within control range of enemy operatives. The selected operative can perform a free Shoot action. During that action:\n• It can target that enemy operative even though it’s within control range of a friendly operative.\n• You cannot select any other enemy operative as a valid target.\n• You cannot select a frag or krak grenade, or a weapon with the Blast or x\" Devastating x weapon rule (i.e. Devastating with a distance)." },
  { kind: 'equipment', name: "Stabilised Bolt Shells", text: "Up to twice per turning point, whenever a friendly HERNKYN YAEGIR operative is performing the Shoot action and you select a bolt shotgun (long range), you can use this rule. If you do, until the end of that action, improve the Hit stat of that weapon by 1 and add 1 to both of its Dmg stats, and that weapon has the Accurate 1 weapon rule." },
  { kind: 'equipment', name: "Plasma Knives", text: "Friendly HERNKYN YAEGIR operatives have the following melee weapon — Plasma knife: ATK 3, HIT 4+, DMG 3/5. Note that some operatives already have this weapon but with better stats; in that instance, use the better version, and that weapon has the Balanced weapon rule for the battle.\nWR Lethal 5+" },
  { kind: 'equipment', name: "Firestorm Bolt Shells", text: "Once per turning point, when a friendly HERNKYN YAEGIR operative is performing the Shoot action and you select a bolt shotgun (short range), you can use this rule. If you do, until the end of that action, that weapon has the Blast 1\" weapon rule." },
  { kind: 'equipment', name: "Kv-ceramide Undersuit", text: "Whenever an operative is shooting a friendly HERNKYN YAEGIR operative, if the ranged weapon in that sequence has the Blast or Torrent weapon rule, you can re-roll one of your defence dice. In addition, friendly HERNKYN YAEGIR operatives aren’t affected by the x\" Devastating x weapon rule (i.e. Devastating with a distance) unless they are the target during that sequence." },
]

export const operatives: Operative[] = [
  { id: "hernkyn-yaegirs:yaegir-theyn", name: "Yaegir Theyn", apl: 2, move: "5\"", save: "4+", w: 9 },
  { id: "hernkyn-yaegirs:yaegir-bladekyn", name: "Yaegir Bladekyn", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "hernkyn-yaegirs:yaegir-bombast", name: "Yaegir Bombast", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "hernkyn-yaegirs:yaegir-gunner", name: "Yaegir Gunner", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "hernkyn-yaegirs:yaegir-ironbraek", name: "Yaegir Ironbraek", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "hernkyn-yaegirs:yaegir-riflekyn", name: "Yaegir Riflekyn", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "hernkyn-yaegirs:yaegir-tracker", name: "Yaegir Tracker", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "hernkyn-yaegirs:yaegir-warrior", name: "Yaegir Warrior", apl: 2, move: "5\"", save: "4+", w: 8 },
]

export const datacards: Datacard[] = [
  {"name": "Yaegir Theyn", "weapons": [{"name": "Bolt revolver", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\""}, {"name": "Bolt shotgun (short range)", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Range 6\""}, {"name": "Bolt shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "2/3"}, {"name": "Plasma knife", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Lethal 5+"}], "abilities": [{"name": "Veteran Adventurer", "text": "In the Ready step of each Strategy phase after the first, if this operative is in the killzone and isn’t within control range of enemy operatives, you gain 1 Resourceful point."}, {"name": "Outright Conviction", "text": "The first time this operative would be incapacitated during the battle, it’s not incapacitated, has 1 wound remaining and cannot be incapacitated for the remainder of the action. All remaining attack dice are discarded (including yours if this operative is fighting or retaliating)."}], "actions": [], "keywords": ["HERNKYN YAEGIR", "LEAGUES OF VOTANN", "LEADER", "THEYN"]},
  {"name": "Yaegir Bladekyn", "weapons": [{"name": "Throwing plasma knife", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 6\", Lethal 5+, Limited 1, Silent"}, {"name": "Dual plasma knives", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Ceaseless, Lethal 5+"}], "abilities": [{"name": "Stalker", "text": "This operative can perform the Charge action while it has a Conceal order."}, {"name": "Irrepressible Hardiness", "text": "If this operative is incapacitated during the Fight action, you can strike the enemy operative in that sequence with one of your unresolved successes before this operative is removed from the killzone."}], "actions": [], "keywords": ["HERNKYN YAEGIR", "LEAGUES OF VOTANN", "BLADEKYN"]},
  {"name": "Yaegir Bombast", "weapons": [{"name": "Wroughtlock revolvers", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 9\", Ceaseless, Lethal 5+"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Wroughtlock Negotiation", "text": "STRATEGIC GAMBIT. This operative can immediately perform a free Shoot action (you can change its order to Engage to do so)."}, {"name": "Brazen Killer", "text": "Whenever this operative incapacitates an enemy operative with its wroughtlock revolvers, roll one D6 separately for each other enemy operative visible to and within 2\" of that enemy operative: if the result is higher than that other enemy operative’s APL stat, subtract 1 from its APL stat until the end of its next activation."}], "actions": [], "keywords": ["HERNKYN YAEGIR", "LEAGUES OF VOTANN", "BOMBAST"]},
  {"name": "Yaegir Gunner", "weapons": [{"name": "APM launcher (armour piercing)", "atk": 5, "hit": "4+", "dmg": "4/5", "wr": "Heavy (Reposition only), Piercing 1, Bipod*"}, {"name": "APM launcher (breaching)", "atk": 5, "hit": "4+", "dmg": "3/5", "wr": "Blast 2\", Heavy (Reposition only), Bipod*"}, {"name": "APM launcher (high explosive)", "atk": 5, "hit": "4+", "dmg": "2/4", "wr": "Blast 3\", Heavy (Reposition only), Bipod*"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Bipod", "text": "Whenever this operative is shooting with this weapon, if it hasn’t moved during the activation, or if it’s a counteraction, this weapon has the Ceaseless weapon rule. Note this operative isn’t restricted from moving after shooting."}], "actions": [], "keywords": ["HERNKYN YAEGIR", "LEAGUES OF VOTANN", "GUNNER"]},
  {"name": "Yaegir Ironbraek", "weapons": [{"name": "Bolt revolver", "atk": 4, "hit": "4+", "dmg": "3/5", "wr": "Range 8\""}, {"name": "Entrencher", "atk": 3, "hit": "4+", "dmg": "3/4"}], "abilities": [{"name": "Minefield", "text": "You have five Minefield markers for the battle. On the reverse side, three of them are HY-Pex mines (see below) and two are blank. Set up all your Minefield markers as if they were one item of equipment. Each must be set up reverse-side down (their specifics aren’t revealed), more than 2\" from other markers, access points and Accessible terrain, and more than 6\" from your opponent’s drop zone and your other Minefield markers. Whenever this operative is readied, if it’s not within control range of enemy operatives, you can reset one of your flipped Minefield markers that’s within its control range (flip the marker back over again). HY-Pex Mines: Whenever one of your reverse-side down Minefield markers is both within an enemy operative’s control range and not within a friendly HERNKYN YAEGIR operative’s control range, flip the marker over. If it’s a blank, there’s no effect. If it’s a HY-Pex mine, inflict 3 damage on that enemy operative and roll one D6: if the result is less than that enemy operative’s Save stat, inflict additional damage on it equal to the dice result; regardless of the result, if it isn’t incapacitated, end its action (if any), even if that action’s effects aren’t fulfilled. If it cannot be placed, move it the minimum amount to do so. Regardless, that marker isn’t removed."}], "actions": [], "keywords": ["HERNKYN YAEGIR", "LEAGUES OF VOTANN", "IRONBRAEK"]},
  {"name": "Yaegir Riflekyn", "weapons": [{"name": "Magna-coil rifle (concealed)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy, Piercing 1, Silent, Concealed Position*"}, {"name": "Magna-coil rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Heavy (Reposition only), Piercing 1"}, {"name": "Magna-coil rifle (stationary)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy, Piercing 1"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Concealed Position", "text": "This operative can only use this weapon the first time it’s performing the Shoot action during the battle."}, {"name": "Weavewërke Cloak", "text": "Whenever an operative is shooting this operative:\n• Ignore the Saturate weapon rule. • If you can retain any cover saves, you can retain one additional cover save, or you can retain one cover save as a critical success instead. This isn’t cumulative with improved cover saves from Vantage terrain."}], "actions": [], "keywords": ["HERNKYN YAEGIR", "LEAGUES OF VOTANN", "RIFLEKYN"]},
  {"name": "Yaegir Tracker", "weapons": [{"name": "SiNR handbow", "atk": 4, "hit": "4+", "dmg": "3/5", "wr": "Silent"}, {"name": "Throwing hatchet", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 6\", Limited 1, Rending, Silent"}, {"name": "Hatchet", "atk": 4, "hit": "3+", "dmg": "4/5"}], "abilities": [{"name": "Pan Spectral Visor", "text": "Whenever this operative is shooting an operative within 6\" of it:\n• This operative’s weapons have the Seek Light weapon rule. • That operative cannot be obscured."}, {"name": "Tracker", "text": "Whenever this operative is shooting against or fighting against an expended operative within 6\" of it, this operative’s weapons have the Punishing weapon rule."}], "actions": [], "keywords": ["HERNKYN YAEGIR", "LEAGUES OF VOTANN", "TRACKER"]},
  {"name": "Yaegir Warrior", "weapons": [{"name": "Bolt revolver", "atk": 4, "hit": "4+", "dmg": "3/5", "wr": "Range 8\""}, {"name": "Bolt shotgun (short range)", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Range 6\""}, {"name": "Bolt shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "2/3"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}, {"name": "Plasma knife", "atk": 4, "hit": "4+", "dmg": "3/5", "wr": "Lethal 5+"}], "abilities": [{"name": "Intrepid", "text": "Whenever you spend a Resourceful point for this operative, the following take precedence:\n• If you add 1 to its APL stat, it lasts until the start of its next activation instead. • If it regains lost wounds, it regains up to 4 instead."}], "actions": [], "keywords": ["HERNKYN YAEGIR", "LEAGUES OF VOTANN", "WARRIOR"]},
]
