// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Resourceful", text: "In the Ready step of each Strategy phase after the first, you gain Resourceful points determined by the number of friendly HERNKYN YAEGIR operatives in the killzone that aren’t within control range of enemy operatives. At the end of each turning point, discard your Resourceful points." },
  { kind: 'faction', name: "Dauntless Explorers", text: "The first of their kindred to set foot on new worlds, Yaegirs are frequently deployed for extended periods and are experts in swiftly evaluating and exploiting their area of operations.\nSTRATEGIC GAMBIT in the first turning point. Each friendly HERNKYN YAEGIR operative wholly within your drop zone can immediately perform a free Reposition action. Each that does so must end that move wholly within 4\" of your drop zone." },
  { kind: 'strategy', name: "Masterful Bladework", text: "Whenever a friendly HERNKYN YAEGIR operative is fighting, or has a Conceal order and is retaliating, add 1 to the Atk stat of its melee weapons (to a maximum of 4) and they have the Balanced weapon rule; if the weapon already has that weapon rule, it has the Ceaseless weapon rule instead of Balanced." },
  { kind: 'strategy', name: "Hidden Engagement", text: "Whenever a friendly HERNKYN YAEGIR operative is shooting, if it’s in cover from the target’s perspective, that friendly operative’s weapons have the Balanced weapon rule. Note that your opponent still determines the targeting lines for this (i.e. they decide which point of their operative’s base targeting lines are drawn from)." },
  { kind: 'strategy', name: "Tough Survivalists", text: "The first time an attack dice inflicts damage on each friendly HERNKYN YAEGIR operative during the turning point in the Resolve Attack Dice step, you can halve that inflicted damage (rounding up, to a minimum of 2)." },
  { kind: 'strategy', name: "In Position", text: "Whenever a friendly HERNKYN YAEGIR operative has a Conceal order and is in cover, it cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2\"." },
  { kind: 'firefight', name: "Bonds That Bind", text: "Use this firefight ploy when a friendly HERNKYN YAEGIR operative is activated. Select one other ready friendly HERNKYN YAEGIR operative visible to and within 3\" of that operative. When that first friendly operative is expended, you can activate that other friendly operative before your opponent activates. When that other operative is expended, your opponent then activates as normal.\nNeither operative can be a BOMBAST operative if its Wroughtlock Negotiation STRATEGIC GAMBIT has been used this turning point." },
  { kind: 'firefight', name: "Sturdy", text: "Use this firefight ploy when an operative is shooting a friendly HERNKYN YAEGIR operative, when you collect your defence dice. Change the attacker’s retained critical successes to normal successes (any weapon rules they’ve already resolved aren’t affected, e.g. Piercing Crits)." },
  { kind: 'firefight', name: "No Kin Left Behind", text: "Use this firefight ploy when a friendly HERNKYN YAEGIR operative is incapacitated. Before that operative is removed from the killzone, remove your Fallen Kin marker from the killzone (if any), then place it within that operative’s control range. That operative is then removed from the killzone as normal.\nWhenever a friendly HERNKYN YAEGIR operative within 3\" of your Fallen Kin marker is shooting, fighting or retaliating, in the Roll Attack Dice step, you can retain one of your fails as a normal success instead of discarding it, or retain one of your normal successes as a critical success instead." },
  { kind: 'firefight', name: "Stalwart Defence", text: "Use this firefight ploy when an enemy operative ends the Charge action within control range of a friendly HERNKYN YAEGIR operative. Select one other friendly HERNKYN YAEGIR operative visible to and within 6\" of that friendly operative, but that isn’t itself within control range of enemy operatives. The selected operative can perform a free Shoot action. During that action:\n• It can target that enemy operative even though it’s within control range of a friendly operative.\n• You cannot select any other enemy operative as a valid target.\n• You cannot select a frag or krak grenade, or a weapon with the Blast or x\" Devastating x weapon rule (i.e. Devastating with a distance)." },
  { kind: 'equipment', name: "Stabilised Bolt Shells", text: "Up to twice per turning point, whenever a friendly HERNKYN YAEGIR operative is performing the Shoot action and you select a bolt shotgun (long range), you can use this rule. If you do, until the end of that action, improve the Hit stat of that weapon by 1 and add 1 to both of its Dmg stats, and that weapon has the Accurate 1 weapon rule." },
  { kind: 'equipment', name: "Plasma Knives", text: "Friendly HERNKYN YAEGIR operatives have the following melee weapon — Plasma knife: ATK 3, HIT 4+, DMG 3/5. Note that some operatives already have this weapon but with better stats; in that instance, use the better version, and that weapon has the Balanced weapon rule for the battle.\nWR Lethal 5+" },
  { kind: 'equipment', name: "Firestorm Bolt Shells", text: "Once per turning point, when a friendly HERNKYN YAEGIR operative is performing the Shoot action and you select a bolt shotgun (short range), you can use this rule. If you do, until the end of that action, that weapon has the Blast 1\" weapon rule." },
  { kind: 'equipment', name: "Kv-ceramide Undersuit", text: "Whenever an operative is shooting a friendly HERNKYN YAEGIR operative, if the ranged weapon in that sequence has the Blast or Torrent weapon rule, you can re-roll one of your defence dice. In addition, friendly HERNKYN YAEGIR operatives aren’t affected by the x\" Devastating x weapon rule (i.e. Devastating with a distance) unless they are the target during that sequence." },
]

export const operatives: Operative[] = [
  { id: "hernkyn-yaegirs:yaegir-theyn", name: "Yaegir Theyn", apl: 2, move: "5\"", save: "4+", w: 9 },
  { id: "hernkyn-yaegirs:yaegir-bladekyn", name: "Yaegir Bladekyn", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "hernkyn-yaegirs:yaegir-bombast", name: "Yaegir Bombast", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "hernkyn-yaegirs:yaegir-gunner", name: "Yaegir Gunner", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "hernkyn-yaegirs:yaegir-ironbraek", name: "Yaegir Ironbraek", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "hernkyn-yaegirs:yaegir-riflekyn", name: "Yaegir Riflekyn", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "hernkyn-yaegirs:yaegir-tracker", name: "Yaegir Tracker", apl: 2, move: "5\"", save: "4+", w: 8 },
  { id: "hernkyn-yaegirs:yaegir-warrior", name: "Yaegir Warrior", apl: 2, move: "5\"", save: "4+", w: 8 },
]
