// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Reanimation Protocols", text: "The first time each friendly HIEROTEK CIRCLE operative is incapacitated, before it's removed from the killzone, place one of your Reanimation markers within its control range. Then remove it as incapacitated, also removing any tokens and rules effects it had (e.g. CHRONOMANCER operative’s Chronometron action, Poison tokens, APL stat changes, being implanted, etc.).\nIn the Ready step of each Strategy phase, select one of your Reanimation markers and roll one D6: on a 1-2, leave that Reanimation marker in the killzone and repeat this process with a different one of your Reanimation markers (if any); on a 3+, an operative is REANIMATED." },
  { kind: 'faction', name: "Magnify", text: "Some HIEROTEK CIRCLE APPRENTEK and HIEROTEK CIRCLE CRYPTEK weapons in this team’s rules have the Magnify weapon rule below.\n*Magnify: Whenever this operative is performing the Shoot action with this weapon, if the target is visible to this operative, and another friendly HIEROTEK CIRCLE APPRENTEK or HIEROTEK CIRCLE CRYPTEK operative that has an Engage order and isn’t within control range of enemy operatives is visible to this operative, you can use this rule. If you do, treat that operative as the active operative for the purposes of determining a valid target, cover and obscured. If you do, this weapon has the Ceaseless weapon rule until the end of that action." },
  { kind: 'faction', name: "Living Metal", text: "In the Ready step of each Strategy phase, before resolving all other faction rules in this step (e.g. Reanimation Protocols), each friendly HIEROTEK CIRCLE operative regains up to D3+1 lost wounds (roll separately for each)." },
  { kind: 'strategy', name: "Relentless Onslaught", text: "Whenever a friendly HIEROTEK CIRCLE operative is shooting an operative within 8\" of it, that friendly operative’s ranged weapons have the Balanced weapon rule. Note that when you’re using the Magnify weapon rule, this operative must still be within 8\" of the target to use this rule (not the other friendly operative from which you’re determining a valid target)." },
  { kind: 'strategy', name: "Undying Androids", text: "Whenever an operative is shooting a friendly HIEROTEK CIRCLE operative, if you cannot retain any cover saves, you can retain one of your defence dice as a normal success without rolling it." },
  { kind: 'strategy', name: "Command Underlings", text: "Select one of the following:\n• SUPPORT. Each other friendly HIEROTEK\nCIRCLE operative visible to and within 6\" of a friendly CRYPTEK operative can immediately perform a free Dash action in an order of your choice.\n• SUPPORT. Each other friendly HIEROTEK CIRCLE operative (excluding CRYPTEK) visible to and within 3\" of a friendly APPRENTEK operative can immediately perform a free Dash action in an order of your choice." },
  { kind: 'strategy', name: "Methodical Elimination", text: "Friendly HIEROTEK CIRCLE operatives’ melee weapons have the Accurate 1 weapon rule. Whenever a friendly HIEROTEK CIRCLE operative is fighting during an activation in which it hasn’t moved more than its Move stat, or whenever it’s retaliating, its melee weapons have the Accurate 2 weapon rule instead." },
  { kind: 'firefight', name: "Cortical Control", text: "Use this firefight ploy when a friendly HIEROTEK CIRCLE APPRENTEK or HIEROTEK CIRCLE\nCRYPTEK operative performs a SUPPORT unique action. Until the end of that action, for the purposes of selecting another friendly operative, ignore the distance requirement (only visibility is a requirement)." },
  { kind: 'firefight', name: "Reanimated Function", text: "Use this firefight ploy when determining control of a marker. Select one of your Reanimation markers. Until the start of the next turning point, whenever determining control of a marker, treat that Reanimation marker as a friendly HIEROTEK CIRCLE operative that has an APL stat of 1. For the purposes of the Martyrs tac op (Approved Ops 2025), this ploy has no effect." },
  { kind: 'firefight', name: "Dimensional Ambush", text: "Use this firefight ploy during a friendly HIEROTEK CIRCLE DEATHMARK operative’s activation, if it has a Conceal order. During that activation, that operative can perform the Guard action regardless of the killzone and while it has a Conceal order (see close quarters rules, Kill Team Core Book), but when you perform the free Shoot or Fight action during the interruption, you must change its order to Engage." },
  { kind: 'firefight', name: "Living Lightning", text: "Use this firefight ploy when a friendly HIEROTEK CIRCLE IMMORTAL operative is performing the Shoot action and you select a tesla carbine. Until the end of that action, that weapon doesn’t have the 2\" from its Devastating weapon rule but has the Blast 2\" weapon rule." },
  { kind: 'equipment', name: "Magnification Conduits", text: "Once per turning point, when a friendly HIEROTEK CIRCLE APPRENTEK or HIEROTEK CIRCLE CRYPTEK operative is performing the Shoot action, you can use this rule. If you do, select one other friendly HIEROTEK CIRCLE operative (excluding PLASMACYTE) that has an Engage order, isn’t within control range of enemy operatives and is visible to that friendly operative. Until the end of that action, that other friendly operative can be treated as the active operative for the Magnify weapon rule." },
  { kind: 'equipment', name: "Phase Shifter", text: "Once per turning point, when an operative is shooting a friendly CRYPTEK operative, at the start of the Roll Defence Dice step, you can use this rule. If you do, worsen the x of the Piercing weapon rule by 1 (if any) until the end of that sequence. Note that Piercing 1 would therefore be ignored." },
  { kind: 'equipment', name: "Tesla Weave", text: "Once per turning point, when an enemy operative ends the Charge action with friendly HIEROTEK CIRCLE operatives within its control range, you can use this rule. If you do, inflict D3+1 damage on that enemy operative." },
  { kind: 'equipment', name: "Tesseract Cube", text: "In the Ready step of each Strategy phase, when you gain CP, if a friendly CRYPTEK operative isn’t incapacitated, isn’t within control range of enemy operatives and hasn’t been REANIMATED this turning point, you can use this rule. If you do, roll one D6: on a 1, you cannot use this rule for the rest of the battle; on a 4+, you gain 1CP. Once you’ve gained 2CP from this rule, you cannot use it for the rest of the battle.\nNOTES:" },
]

export const operatives: Operative[] = [
  { id: "hierotek-circle:chronomancer", name: "Chronomancer", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "hierotek-circle:psychomancer", name: "Psychomancer", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "hierotek-circle:technomancer", name: "Technomancer", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "hierotek-circle:plasmacyte-accelerator", name: "Plasmacyte Accelerator", apl: 2, move: "7\"", save: "5+", w: 5 },
  { id: "hierotek-circle:plasmacyte-reanimator", name: "Plasmacyte Reanimator", apl: 2, move: "7\"", save: "5+", w: 5 },
  { id: "hierotek-circle:apprentek", name: "Apprentek", apl: 3, move: "6\"", save: "3+", w: 11 },
  { id: "hierotek-circle:deathmark", name: "Deathmark", apl: 2, move: "5\"", save: "3+", w: 10 },
  { id: "hierotek-circle:immortal-despotek", name: "Immortal Despotek", apl: 2, move: "5\"", save: "3+", w: 11 },
  { id: "hierotek-circle:immortal-guardian", name: "Immortal Guardian", apl: 2, move: "5\"", save: "3+", w: 10 },
]
