// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Doctrina Imperatives", text: "At the end of the Select Operatives step, select one DOCTRINA IMPERATIVE to be a Primary Mode for your kill team until the end of the battle (note that selecting a Primary Mode doesn’t automatically give you the effects of that DOCTRINA IMPERATIVE for the battle; you must still select it as a STRATEGIC GAMBIT, as below). STRATEGIC GAMBIT. Select one DOCTRINA IMPERATIVE for friendly HUNTER CLADE operatives to have until the Ready step of the next Strategy phase. Each DOCTRINA IMPERATIVE has both an Optimisation and a Deprecation rule. Both are in effect while your kill team has that DOCTRINA IMPERATIVE. Once per battle, when you select the DOCTRINA IMPERATIVE that’s your kill team’s Primary Mode, you can ignore its Deprecation rule." },
  { kind: 'strategy', name: "Debilitating Irradiation", text: "Whenever an enemy operative is shooting against, fighting against or retaliating against a friendly HUNTER CLADE VANGUARD operative, if that enemy operative is under the effects of the Rad-Saturation rule (see VANGUARD operatives), subtract 1 from the Normal Dmg stat of its weapons (to a minimum of 3)." },
  { kind: 'strategy', name: "Neurostatic Interference", text: "Whenever an enemy operative within 6\" of a friendly HUNTER CLADE INFILTRATOR operative is shooting, fighting or retaliating, your opponent cannot re-roll their attack dice." },
  { kind: 'strategy', name: "Scouting Protocol", text: "Each friendly HUNTER CLADE RANGER operative that has a Conceal order and is more than 6\" from enemy operatives can immediately perform a free Dash action in an order of your choice. You cannot use this ploy during the first turning point." },
  { kind: 'firefight', name: "Control Edict", text: "Use this firefight ploy when it’s your turn to activate a friendly operative. Select one friendly HUNTER CLADE LEADER operative and one other ready friendly HUNTER CLADE operative visible to and within 3\" of that LEADER operative; activate one of them as normal. When that first friendly operative you activate is expended, you can activate the other friendly operative before your opponent activates. When that other operative is expended, your opponent then activates as normal. Whenever you use this ploy, you cannot select more than one HUNTER CLADE SICARIAN operative." },
  { kind: 'strategy', name: "Accelerant Agents", text: "During each friendly HUNTER CLADE RUSTSTALKER operative’s activation, it can perform two Fight actions, and one of them can be free." },
  { kind: 'firefight', name: "Scrapcode Overload", text: "Use this firefight ploy when a friendly HUNTER CLADE INFILTRATOR operative is activated. Alternatively, use this firefight ploy when a friendly HUNTER CLADE INFILTRATOR operative, or an enemy operative within 3\" of that friendly operative, would perform the Pick Up Marker or a mission action (excluding Operate Hatch). Until the start of that friendly operative’s next activation, whenever determining control of a marker, treat the total APL stat of enemy operatives that contest it as 1 lower if at least one of those enemy operatives is within 3\" of that friendly operative. Note this isn’t a change to the APL stat, so any changes are cumulative with this, and this can change control of a marker before performing the action." },
  { kind: 'firefight', name: "Command Override", text: "Use this firefight ploy when you activate a friendly HUNTER CLADE operative. Select a DOCTRINA IMPERATIVE for that operative to have instead of its current one (if any) until the Ready step of the next Strategy phase.\n• Bulwark: Improve this operative’s Save stat by 1. In addition, whenever an operative is shooting this operative, you can collect and roll one additional defence dice. If you use this ploy during a Shoot action, this operative’s Save stat is changed immediately (this takes precedence over the core rules).\n• Aggressor: You can ignore the first vertical distance of 2\" this operative moves during one climb up.\n• Neutral: None.\nNote that you can use this ploy after rolling attack or defence dice for this operative, or before or after retaining or re-rolling those dice." },
  { kind: 'firefight', name: "Omnissiah’s Imperative", text: "Use this firefight ploy during a friendly HUNTER CLADE operative’s activation. Alternatively, use it when an enemy operative is shooting a friendly HUNTER CLADE operative, at the end of the Roll Attack Dice step. Until the Ready step of the next Strategy phase, that friendly operative has an additional rule determined by its current DOCTRINA IMPERATIVE as follows:\n• Protector: This operative’s ranged weapons have the Severe weapon rule.\n• Conqueror: Whenever this operative is fighting, after resolving your first attack dice during that sequence, you can immediately resolve another (before your opponent)." },
  { kind: 'equipment', name: "Rad Bombardment", text: "Once per battle STRATEGIC GAMBIT in any turning point after the first. Select one objective marker or your opponent’s drop zone. Roll one D6 separately for each enemy operative within control range of that selected objective marker or within that drop zone, and subtract 1 if any part of that enemy operative's base is underneath Vantage terrain: on a 4+, subtract 1 from that operative's APL stat until the end of its next activation; on a 6, also inflict D3 damage on it (roll separately for each)." },
  { kind: 'equipment', name: "Redundancy Systems", text: "Once per turning point, when a friendly HUNTER CLADE operative is activated, if it’s not within control range of enemy operatives, you can use this rule. If you do, that friendly operative regains up to D3+2 lost wounds." },
  { kind: 'equipment', name: "Extremis Mind-link", text: "Once per battle, you can use the Control Edict firefight ploy for 0CP, but instead of activating the selected friendly operatives in succession, activate them at the same time. Complete their activations action by action in any order." },
  { kind: 'equipment', name: "Refractor Field", text: "Once per turning point, when an operative is shooting a friendly HUNTER CLADE operative, at the start of the Roll Defence Dice step, you can use this rule. If you do, worsen the x of the Piercing weapon rule by 1 (if any) until the end of that sequence. Note that Piercing 1 would therefore be ignored.\nNOTES:" },
]

export const operatives: Operative[] = [
  { id: "hunter-clade:sicarian-ruststalker-princeps", name: "Sicarian Ruststalker Princeps", apl: 2, move: "6\"", save: "4+", w: 11 },
  { id: "hunter-clade:sicarian-infiltrator-princeps", name: "Sicarian Infiltrator Princeps", apl: 2, move: "6\"", save: "4+", w: 11 },
  { id: "hunter-clade:skitarii-ranger-alpha", name: "Skitarii Ranger Alpha", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "hunter-clade:skitarii-vanguard-alpha", name: "Skitarii Vanguard Alpha", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "hunter-clade:sicarian-infiltrator-warrior", name: "Sicarian Infiltrator Warrior", apl: 2, move: "6\"", save: "4+", w: 10 },
  { id: "hunter-clade:sicarian-ruststalker-warrior", name: "Sicarian Ruststalker Warrior", apl: 2, move: "6\"", save: "4+", w: 10 },
  { id: "hunter-clade:skitarii-ranger-diktat", name: "Skitarii Ranger Diktat", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "hunter-clade:skitarii-ranger-gunner", name: "Skitarii Ranger Gunner", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "hunter-clade:skitarii-ranger-surveyor", name: "Skitarii Ranger Surveyor", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "hunter-clade:skitarii-ranger-warrior", name: "Skitarii Ranger Warrior", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "hunter-clade:skitarii-vanguard-diktat", name: "Skitarii Vanguard Diktat", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "hunter-clade:skitarii-vanguard-gunner", name: "Skitarii Vanguard Gunner", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "hunter-clade:skitarii-vanguard-surveyor", name: "Skitarii Vanguard Surveyor", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "hunter-clade:skitarii-vanguard-warrior", name: "Skitarii Vanguard Warrior", apl: 2, move: "6\"", save: "4+", w: 7 },
]

export const datacards: Datacard[] = [
  {"name": "Sicarian Ruststalker Princeps", "weapons": [{"name": "Chordclaw & transonic blades", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Balanced, Rending"}], "abilities": [{"name": "Canticle of Destruction", "text": "Whenever a friendly HUNTER CLADE RUSTSTALKER operative within 3\" of this operative is fighting, the first time you strike with a critical success during that sequence, inflict 1 additional damage."}, {"name": "Wasteland Stalker", "text": "Whenever an operative is shooting this operative, if you can retain any cover saves, you can retain one additional cover save, or you can retain one cover save as a critical success instead. This isn’t cumulative with improved cover saves from Vantage terrain."}, {"name": "Control Protocol", "text": "You can use the Command Override firefight ploy for 0CP if the specified friendly HUNTER CLADE operative is visible to this operative."}], "actions": [], "keywords": ["HUNTER CLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "LEADER", "SICARIAN", "RUSTSTALKER", "PRINCEPS"]},
  {"name": "Sicarian Infiltrator Princeps", "weapons": [{"name": "Flechette blaster", "atk": 5, "hit": "3+", "dmg": "2/2", "wr": "Range 8\", Saturate, Silent"}, {"name": "Stubcarbine", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Ceaseless"}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}, {"name": "Taser goad", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Lethal 5+, Shock"}], "abilities": [{"name": "Canticle of Shroudpsalm", "text": "Whenever a friendly HUNTER CLADE INFILTRATOR operative is within 3\" of this operative, has a Conceal order and is in cover, that friendly operative cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2\"."}, {"name": "Control Protocol", "text": "You can use the Command Override firefight ploy for 0CP if the specified friendly HUNTER CLADE operative is visible to this operative."}], "actions": [], "keywords": ["HUNTER CLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "LEADER", "SICARIAN", "INFILTRATOR", "PRINCEPS"]},
  {"name": "Skitarii Ranger Alpha", "weapons": [{"name": "Arc pistol", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Piercing 1, Stun"}, {"name": "Galvanic rifle", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Heavy (Reposition only), Piercing Crits 1"}, {"name": "Master-crafted radium pistol", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Range 8\", Balanced, Rending"}, {"name": "Phosphor blast pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Blast 1\", Severe"}, {"name": "Arc maul", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Shock"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}, {"name": "Power weapon", "atk": 4, "hit": "4+", "dmg": "4/6", "wr": "Lethal 5+"}, {"name": "Taser goad", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Lethal 5+, Shock"}], "abilities": [{"name": "Canticle of Elimination", "text": "Whenever a friendly HUNTER CLADE RANGER operative is within 3\" of this operative, that friendly operative's ranged weapons have the Punishing weapon rule."}, {"name": "Targeting Protocol", "text": "Whenever this operative is shooting, if it hasn’t moved during the activation, or if it’s a counteraction, ranged weapons on its datacard have the Lethal 5+ weapon rule. Note this operative isn’t restricted from moving after shooting."}, {"name": "Control Protocol", "text": "You can use the Command Override firefight ploy for 0CP if the specified friendly HUNTER CLADE operative is visible to this operative."}], "actions": [], "keywords": ["HUNTER CLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "LEADER", "SKITARII", "RANGER", "ALPHA"]},
  {"name": "Skitarii Vanguard Alpha", "weapons": [{"name": "Arc pistol", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Piercing 1, Stun"}, {"name": "Master-crafted radium pistol", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Range 8\", Balanced, Rending"}, {"name": "Phosphor blast pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Blast 1\", Severe"}, {"name": "Radium carbine", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Rending"}, {"name": "Arc maul", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Shock"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}, {"name": "Power weapon", "atk": 4, "hit": "4+", "dmg": "4/6", "wr": "Lethal 5+"}, {"name": "Taser goad", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Lethal 5+, Shock"}], "abilities": [{"name": "Canticle of the Glow", "text": "Whenever an enemy operative is within 3\" of this operative, if it's under the effects of the Rad- Saturation rule, also subtract 1 from the Atk stat of that enemy operative’s weapons."}, {"name": "Rad-Saturation", "text": "Whenever an enemy operative is within 2\" of friendly HUNTER CLADE VANGUARD operatives, worsen the Hit stat of that enemy operative’s weapons by 1. This isn’t cumulative with being injured."}, {"name": "Control Protocol", "text": "You can use the Command Override firefight ploy for 0CP if the specified friendly HUNTER CLADE operative is visible to this operative."}], "actions": [], "keywords": ["HUNTER CLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "LEADER", "SKITARII", "VANGUARD", "ALPHA"]},
  {"name": "Sicarian Infiltrator Warrior", "weapons": [{"name": "Flechette blaster", "atk": 5, "hit": "3+", "dmg": "2/2", "wr": "Range 8\", Saturate, Silent"}, {"name": "Stubcarbine", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Ceaseless"}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}, {"name": "Taser goad", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Lethal 5+, Shock"}], "abilities": [], "actions": [], "keywords": ["HUNTER CLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "SICARIAN", "INFILTRATOR", "WARRIOR"]},
  {"name": "Sicarian Ruststalker Warrior", "weapons": [{"name": "Chordclaw & transonic razor", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Balanced"}, {"name": "Transonic blades", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Rending"}], "abilities": [{"name": "Wasteland Stalker", "text": "Whenever an operative is shooting this operative, if you can retain any cover saves, you can retain one additional cover save, or you can retain one cover save as a critical success instead. This isn’t cumulative with improved cover saves from Vantage terrain."}], "actions": [], "keywords": ["HUNTER CLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "SICARIAN", "RUSTSTALKER", "WARRIOR"]},
  {"name": "Skitarii Ranger Diktat", "weapons": [{"name": "Galvanic rifle", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Heavy (Reposition only), Piercing Crits 1"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Targeting Protocol", "text": "Whenever this operative is shooting, if it hasn’t moved during the activation, or if it’s a counteraction,\nranged weapons on its datacard have the Lethal 5+ weapon rule.\nNote this operative isn’t restricted from moving after shooting."}], "actions": [{"name": "Signal", "ap": 1, "text": "SUPPORT. Select one other friendly HUNTER CLADE\noperative visible to and within 6\" of this operative. Until the\nend of that operative’s next activation, add 1 to its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["HUNTER CLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "SKITARII", "RANGER", "DIKTAT"]},
  {"name": "Skitarii Ranger Gunner", "weapons": [{"name": "Arc rifle1", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Piercing 1, Stun"}], "abilities": [{"name": "Targeting Protocol", "text": "Whenever this operative is shooting, if it hasn’t moved during the activation, or if it’s a counteraction, ranged weapons on its datacard have the Lethal 5+ weapon rule. Note this operative isn’t restricted from moving after shooting.\n25    2 60x35"}], "actions": [], "keywords": ["HUNTER CLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "SKITARII", "RANGER", "GUNNER"]},
  {"name": "Skitarii Ranger Surveyor", "weapons": [{"name": "Galvanic rifle", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Heavy (Reposition only), Piercing Crits 1"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Targeting Protocol", "text": "Whenever this operative is shooting, if it hasn’t moved during the activation, or if it’s a counteraction, ranged weapons on its datacard have the Lethal 5+ weapon rule. Note this operative isn’t restricted from moving after shooting."}], "actions": [{"name": "Spot", "ap": 1, "text": "SUPPORT. Select one enemy operative visible to this operative. Until the end of the turning point, whenever a friendly HUNTER CLADE operative within 3\" of this operative is shooting that enemy operative, you can use this effect. If you do: • That friendly operative’s ranged weapons have the Seek Light weapon rule. • That enemy operative cannot be obscured. This operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["HUNTER CLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "SKITARII", "RANGER", "SURVEYOR"]},
  {"name": "Skitarii Ranger Warrior", "weapons": [{"name": "Galvanic rifle", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Heavy (Reposition only), Piercing Crits 1"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Targeting Protocol", "text": "Whenever this operative is shooting, if it hasn’t moved during the activation, or if it’s a counteraction, ranged weapons on its datacard have the Lethal 5+ weapon rule. Note this operative isn’t restricted from moving after shooting."}], "actions": [], "keywords": ["HUNTER CLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "SKITARII", "RANGER", "WARRIOR"]},
  {"name": "Skitarii Vanguard Diktat", "weapons": [{"name": "Radium carbine", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Rending"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Rad-Saturation", "text": "Whenever an enemy operative is within 2\" of friendly HUNTER CLADE VANGUARD operatives, worsen\nthe Hit stat of that enemy operative’s weapons by 1. This isn’t\ncumulative with being injured."}], "actions": [{"name": "Signal", "ap": 1, "text": "SUPPORT. Select one other friendly HUNTER CLADE\noperative visible to and within 6\" of this operative. Until the\nend of that operative’s next activation, add 1 to its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["HUNTER CLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "SKITARII", "VANGUARD", "DIKTAT"]},
  {"name": "Skitarii Vanguard Gunner", "weapons": [{"name": "Arc rifle1", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Piercing 1, Stun"}], "abilities": [{"name": "Rad-Saturation", "text": "Whenever an enemy operative is within 2\" of friendly HUNTER CLADE VANGUARD operatives, worsen the Hit stat of that enemy operative’s weapons by 1. This isn’t cumulative with being injured.\n25    2 60x35"}], "actions": [], "keywords": ["HUNTER CLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "SKITARII", "VANGUARD", "GUNNER"]},
  {"name": "Skitarii Vanguard Surveyor", "weapons": [{"name": "Radium carbine", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Rending"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Rad-Saturation", "text": "Whenever an enemy operative is within 2\" of friendly HUNTER CLADE VANGUARD operatives, worsen the Hit stat of that enemy operative’s weapons by 1. This isn’t cumulative with being injured."}], "actions": [{"name": "Spot", "ap": 1, "text": "SUPPORT. Select one enemy operative visible to this operative. Until the end of the turning point, whenever a friendly HUNTER CLADE operative within 3\" of this operative is shooting that enemy operative, you can use this effect. If you do: • That friendly operative’s ranged weapons have the Seek Light weapon rule. • That enemy operative cannot be obscured. This operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["HUNTER CLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "SKITARII", "VANGUARD", "SURVEYOR"]},
  {"name": "Skitarii Vanguard Warrior", "weapons": [{"name": "Radium carbine", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Rending"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Rad-Saturation", "text": "Whenever an enemy operative is within 2\" of friendly HUNTER CLADE VANGUARD operatives, worsen the Hit stat of that enemy operative’s weapons by 1. This isn’t cumulative with being injured."}], "actions": [], "keywords": ["HUNTER CLADE", "IMPERIUM", "ADEPTUS MECHANICUS", "SKITARII", "VANGUARD", "WARRIOR"]},
]
