// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Void Armour", text: "Whenever an operative is shooting a friendly IMPERIAL NAVY BREACHER operative, if the ranged weapon in that sequence has the Blast or Torrent weapon rule (excluding weapons that have a sweeping profile), you can re-roll one of your defence dice, or up to two of your defence dice if that friendly operative is a GRENADIER.\nFriendly IMPERIAL NAVY BREACHER operatives aren’t affected by the x\" Devastating x weapon rule (i.e. Devastating with a distance) unless they are the target during that sequence." },
  { kind: 'faction', name: "Breach and Clear", text: "Once per turning point, when a ready friendly IMPERIAL NAVY BREACHER operative is activated, you can use this rule. If you do, select one other ready friendly IMPERIAL NAVY BREACHER operative visible to and within 3\" of that operative. When that first friendly operative is expended, you can activate that other friendly operative before your opponent activates. When that other operative is expended, your opponent then activates as normal." },
  { kind: 'strategy', name: "Defence Order", text: "Place your Defence Order marker in the killzone. Whenever an operative is shooting a friendly IMPERIAL NAVY BREACHER operative that’s within 3\" of that marker, you can re-roll any of your defence dice results of one result (e.g.\nresults of 2). In the Ready step of the next\nStrategy phase, remove that marker. You cannot use this ploy and the Attack Order strategy ploy during the same Strategy phase." },
  { kind: 'strategy', name: "Attack Order", text: "Place your Attack Order marker in the killzone. Whenever a friendly IMPERIAL NAVY BREACHER operative within 3\" of that marker is shooting, fighting or retaliating, its weapons have the Ceaseless weapon rule. In the Ready step of the next Strategy phase, remove that marker. You cannot use this ploy and the Defence Order strategy ploy during the same Strategy phase." },
  { kind: 'strategy', name: "Close Assault", text: "Whenever a friendly IMPERIAL NAVY BREACHER operative is fighting or shooting an operative within 3\" of it:\n• Add 1 to both Dmg stats of all profiles of its Navis shotguns or Navis heavy shotguns\n(if any).\n• If you roll two or more fails, you can discard one of them to retain another as a normal success instead." },
  { kind: 'strategy', name: "Brace for Counterattack", text: "Whenever an operative is shooting against, fighting against or retaliating against a friendly IMPERIAL NAVY BREACHER operative that’s within your territory or that hasn’t performed the Charge, Fall Back or Reposition action during this turning point, Normal and Critical Dmg of 3 or more inflicts 1 less damage on that friendly operative." },
  { kind: 'firefight', name: "Blitz", text: "Use this firefight ploy when a friendly IMPERIAL NAVY BREACHER operative performs the Shoot or Fight action, and you select an enemy operative within 6\" of it as a valid target or to fight against. If it’s the first friendly operative to perform either of those actions during this turning point, its weapons have the Accurate 1 weapon rule for that action. If it’s the first friendly operative to be activated during this turning point, its weapons also have the Severe weapon rule for that action." },
  { kind: 'firefight', name: "Overwhelm Target", text: "Use this firefight ploy when you activate either friendly IMPERIAL NAVY BREACHER operative while using the Breach and Clear faction rule. Until the end of that operative’s activation, add 1 to its APL stat." },
  { kind: 'firefight', name: "Lock It Down", text: "Use this firefight ploy when a friendly IMPERIAL\nNAVY BREACHER operative is activated. Select one objective marker. Until the end of the battle or until you use this ploy again (whichever comes first), when determining control of that objective marker, treat that friendly operative’s APL stat as 1 higher. Note this isn’t a change to the APL stat, so any changes are cumulative with this." },
  { kind: 'firefight', name: "Deck Hand", text: "Use this firefight ploy during a friendly IMPERIAL NAVY BREACHER operative’s activation, before or after it performs an action. That operative can move through one Accessible terrain feature without it counting as an additional 1\" and/or perform a free Operate Hatch action during its activation, and can do so during the Charge or Fall Back action. You cannot use this ploy if the access point has been welded shut (see HATCHCUTTER) unless it’s a friendly HATCHCUTTER operative’s activation." },
  { kind: 'equipment', name: "Slugs", text: "Up to three times per turning point, whenever a friendly IMPERIAL NAVY BREACHER operative is performing the Shoot action and you select a Navis shotgun (long range), you can use this rule. If you do, until the end of that action, improve the Hit stat of that weapon by 1 and add 1 to both of its Dmg stats, and that weapon has the Accurate 1 weapon rule." },
  { kind: 'equipment', name: "Rebreathers", text: "You can ignore any changes to the APL stat of friendly IMPERIAL NAVY BREACHER operatives, and they aren’t affected by enemy operatives’ Shock weapon rule." },
  { kind: 'equipment', name: "Combat Stimms", text: "You can ignore any changes to the Move stat of friendly IMPERIAL NAVY BREACHER operatives from being injured." },
  { kind: 'equipment', name: "System Override Device", text: "Once per turning point, one friendly IMPERIAL NAVY BREACHER operative can perform the Operate Hatch action for 1 less AP." },
]

export const operatives: Operative[] = [
  { id: "imperial-navy-breachers:navis-sergeant-at-arms", name: "Navis Sergeant-at-arms", apl: 2, move: "6\"", save: "4+", w: 9 },
  { id: "imperial-navy-breachers:navis-armsman", name: "Navis Armsman", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "imperial-navy-breachers:navis-axejack", name: "Navis Axejack", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "imperial-navy-breachers:navis-c-a-t-unit", name: "Navis C.a.t. Unit", apl: 2, move: "8\"", save: "5+", w: 5 },
  { id: "imperial-navy-breachers:navis-endurant", name: "Navis Endurant", apl: 2, move: "4\"", save: "2+", w: 11 },
  { id: "imperial-navy-breachers:navis-gheistskull", name: "Navis Gheistskull", apl: 2, move: "8\"", save: "5+", w: 5 },
  { id: "imperial-navy-breachers:navis-grenadier", name: "Navis Grenadier", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "imperial-navy-breachers:navis-gunner", name: "Navis Gunner", apl: 2, move: "6\"", save: "4+", w: 9 },
  { id: "imperial-navy-breachers:navis-hatchcutter", name: "Navis Hatchcutter", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "imperial-navy-breachers:navis-surveyor", name: "Navis Surveyor", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "imperial-navy-breachers:navis-void-jammer", name: "Navis Void-jammer", apl: 2, move: "6\"", save: "4+", w: 8 },
]

export const datacards: Datacard[] = [
  {"name": "Navis Sergeant-at-arms", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Heirloom autopistol", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Range 8\", Lethal 5+"}, {"name": "Navis shotgun (close range)", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Range 6\""}, {"name": "Navis shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "1/2"}, {"name": "Chainsword", "atk": 4, "hit": "3+", "dmg": "4/5"}, {"name": "Navis hatchet", "atk": 3, "hit": "4+", "dmg": "3/4"}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Command Breach", "text": "Whenever you would use the Attack Order or Defence Order strategy ploy, if this operative is in the killzone, it costs you 0CP. Once during each of this operative’s activations, before or after it performs an action, if your Attack Order or Defence Order marker is in the killzone (see relevant strategy ploy), you can either:\n• Remove that marker and place it again. • Change the selected ploy to the other (e.g. your Attack Order becomes a Defence Order).\nYou cannot do both, and you don’t need to spend any CP to change the ploy."}], "actions": [], "keywords": ["IMPERIAL NAVY BREACHER", "IMPERIUM", "LEADER", "SERGEANT-AT-ARMS"], "img": "/ops/imperial-navy-breachers/navis-sergeant-at-arms.webp"},
  {"name": "Navis Armsman", "weapons": [{"name": "Navis shotgun (close range)", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Range 6\""}, {"name": "Navis shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "1/2"}, {"name": "Navis hatchet", "atk": 3, "hit": "4+", "dmg": "3/4"}], "abilities": [{"name": "Group Activation", "text": "Whenever this operative is expended, you must then activate one other ready friendly IMPERIAL NAVY BREACHER ARMSMAN operative (if able) before your opponent activates. When that other operative is expended, your opponent then activates as normal (in other words, you cannot activate more than two operatives in succession with this rule). Ignore this rule when you are using the Breach and Clear faction rule."}], "actions": [], "keywords": ["IMPERIAL NAVY BREACHER", "IMPERIUM", "ARMSMAN"], "img": "/ops/imperial-navy-breachers/navis-armsman.webp"},
  {"name": "Navis Axejack", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Emboldened", "text": "Whenever an attack dice inflicts damage of 3 or more on this operative during a turning point in which it performed the Charge action, roll one D6: on a 5+, subtract 1 from that inflicted damage."}], "actions": [], "keywords": ["IMPERIAL NAVY BREACHER", "IMPERIUM", "AXEJACK"], "img": "/ops/imperial-navy-breachers/navis-axejack.webp"},
  {"name": "Navis C.a.t. Unit", "weapons": [], "abilities": [{"name": "Expendable", "text": "This operative is ignored for your opponent’s kill/elimination op (when\nit’s incapacitated, and when determining\nyour starting number of operatives). It’s\nalso ignored for victory conditions and\nscoring VPs if either require operatives to\n‘escape’, ‘survive’ or be incapacitated by enemy operatives (if it escapes/survives/ is incapacitated, determining how many operatives must escape/survive/be incapacitated, etc.)."}], "actions": [{"name": "Spot", "ap": 1, "text": "Select one enemy operative visible to this operative. Until the end of the turning\npoint, until that enemy operative is no longer visible to this operative or until this\noperative performs this action again (whichever comes first), whenever a friendly\nIMPERIAL NAVY BREACHER operative is shooting that enemy operative, you\ncan use this effect. If you do:\n• That friendly operative’s ranged weapons have the Seek Light weapon rule. • That enemy operative cannot be obscured.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["IMPERIAL NAVY BREACHER", "IMPERIUM", "C.A.T. UNIT"], "img": "/ops/imperial-navy-breachers/navis-c-a-t-unit.webp"},
  {"name": "Navis Endurant", "weapons": [{"name": "Navis heavy shotgun (close range)", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Range 6\", Relentless"}, {"name": "Navis heavy shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "1/2", "wr": "Relentless"}, {"name": "Shield bash", "atk": 3, "hit": "4+", "dmg": "1/2", "wr": "Brutal, Shield*"}], "abilities": [{"name": "Breachwall", "text": "Whenever your opponent is selecting a valid target, they cannot select another friendly IMPERIAL NAVY BREACHER operative whose base is touching this operative’s if this operative has an Engage order and is intervening. This rule has no effect if more than one other friendly operative’s base is touching this operative’s."}, {"name": "Shield", "text": "Whenever this operative is fighting or retaliating with this weapon, each of your blocks can be allocated to block two unresolved successes (instead of one)."}, {"name": "Disengage", "text": "This operative can perform the Fall Back action for 1 less AP."}], "actions": [], "keywords": ["IMPERIAL NAVY BREACHER", "IMPERIUM", "ENDURANT"], "img": "/ops/imperial-navy-breachers/navis-endurant.webp"},
  {"name": "Navis Gheistskull", "weapons": [], "abilities": [{"name": "Expendable", "text": "This operative is ignored for your opponent’s kill/elimination op (when it’s incapacitated, and when determining your starting number of operatives). It’s also ignored for victory conditions and scoring VPs if either require operatives to ‘escape’, ‘survive’ or be incapacitated by enemy operatives (if it escapes/survives/is incapacitated, determining how many operatives must escape/survive/be incapacitated, etc.)."}], "actions": [{"name": "Boost", "ap": 1, "text": "The next time this operative performs a Charge action during this activation, add 4\" to the distance it can move (instead of 2\").\nThis operative cannot perform this action more than once per battle, and cannot perform it during the first turning point."}], "keywords": ["IMPERIAL NAVY BREACHER", "IMPERIUM", "GHEISTSKULL"], "img": "/ops/imperial-navy-breachers/navis-gheistskull.webp"},
  {"name": "Navis Grenadier", "weapons": [{"name": "Demolition charge", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Range 3\", Blast 2\", Heavy (Reposition only), Limited 1, Piercing 1, Saturate"}, {"name": "Navis shotgun (close range)", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Range 6\""}, {"name": "Navis shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "1/2"}, {"name": "Navis hatchet", "atk": 3, "hit": "4+", "dmg": "3/4"}], "abilities": [{"name": "Grenadier", "text": "This operative can use frag, krak and stun grenades (see universal equipment). Doing so doesn’t count towards any limited uses you have (i.e. if you also select those grenades from equipment for other operatives). Whenever this operative is using a frag or krak grenade, improve the Hit stat of that weapon by 1."}], "actions": [], "keywords": ["IMPERIAL NAVY BREACHER", "IMPERIUM", "GRENADIER"], "img": "/ops/imperial-navy-breachers/navis-grenadier.webp"},
  {"name": "Navis Gunner", "weapons": [{"name": "Meltagun", "atk": 4, "hit": "4+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Navis las-volley (focused)", "atk": 5, "hit": "4+", "dmg": "4/5", "wr": "Heavy (Dash only), Rending"}, {"name": "Navis las-volley (sweeping)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Heavy (Dash only), Rending, Torrent 1\""}, {"name": "Plasma gun (standard)", "atk": 4, "hit": "4+", "dmg": "4/6", "wr": "Piercing 1"}, {"name": "Plasma gun (supercharge)", "atk": 4, "hit": "4+", "dmg": "5/6", "wr": "Hot, Lethal 5+, Piercing 1"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [], "keywords": ["IMPERIAL NAVY BREACHER", "IMPERIUM", "GUNNER"], "img": "/ops/imperial-navy-breachers/navis-gunner.webp"},
  {"name": "Navis Hatchcutter", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Chainfist", "atk": 4, "hit": "4+", "dmg": "5/6", "wr": "Brutal, Rending"}], "abilities": [], "actions": [{"name": "Weld Shut", "ap": 1, "text": "Select a closed hatchway (e.g. Killzone: Tomb World) within           This operative cannot perform this action while within control this operative’s control range. 1 additional AP must be spent         range of an enemy operative, or if it isn’t within 1\" of a for other operatives to perform the Operate Hatch action              closed hatchway. to open that hatchway. This effect ends when that hatchway is opened. Note this operative isn’t affected by this effect."}, {"name": "Breach Point", "ap": 1, "text": "Place one of your Breach markers within this operative’s control range as close as possible to a terrain feature within control range of it. Whenever an operative is within 1\" of that marker, it treats parts of that terrain feature that are no more than 1\" thick as Accessible terrain.\nThis operative cannot perform this action while within control range of an enemy operative, or if a terrain feature isn’t within its control range."}], "keywords": ["IMPERIAL NAVY BREACHER", "IMPERIUM", "HATCHCUTTER"], "img": "/ops/imperial-navy-breachers/navis-hatchcutter.webp"},
  {"name": "Navis Surveyor", "weapons": [{"name": "Navis shotgun (close range)", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Range 6\""}, {"name": "Navis shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "1/2"}, {"name": "Navis hatchet", "atk": 3, "hit": "4+", "dmg": "3/4"}], "abilities": [], "actions": [{"name": "Wayfind", "ap": 1, "text": "SUPPORT. Select one other friendly IMPERIAL NAVY BREACHER operative                        This operative cannot perform this (excluding C.A.T. UNIT or GHEISTSKULL) visible to and within 6\" of this                    action while within control range of an operative, or visible to and within 6\" of a friendly IMPERIAL NAVY BREACHER                enemy operative. C.A.T. UNIT operative. Until the end of that operative’s next activation, add 1 to its APL stat. For the purposes of the Comms Device universal equipment, the operative the distance is being determined from must control that marker."}, {"name": "Remote Control", "ap": 1, "text": "Select one friendly IMPERIAL NAVY BREACHER C.A.T. UNIT operative. That operative can immediately perform one free action, but it cannot move more than 3\" during that action.\nThis operative cannot perform this action while within control range of an enemy operative, or if a friendly IMPERIAL NAVY BREACHER C.A.T. UNIT operative isn’t in the killzone."}], "keywords": ["IMPERIAL NAVY BREACHER", "IMPERIUM", "SURVEYOR"], "img": "/ops/imperial-navy-breachers/navis-surveyor.webp"},
  {"name": "Navis Void-jammer", "weapons": [{"name": "Gheistskull detonator", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Blast 1\", Lethal 4+, Limited 1, Silent, Stun, Detonate*"}, {"name": "Navis shotgun (close range)", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Range 6\""}, {"name": "Navis shotgun (long range)", "atk": 4, "hit": "5+", "dmg": "1/2"}, {"name": "Navis hatchet", "atk": 3, "hit": "4+", "dmg": "3/4"}], "abilities": [{"name": "Detonate", "text": "Don’t select a valid target. Instead, a friendly IMPERIAL NAVY BREACHER GHEISTSKULL operative is always the primary target and cannot be in cover or obscured. If that operative isn’t in the killzone, you cannot select this weapon."}], "actions": [{"name": "Interference Pulse", "ap": 1, "text": "Select one enemy operative visible to and within 8\" of a friendly GHEISTSKULL operative. Roll one D6, adding 1 to the result if that enemy operative is a valid target for that friendly GHEISTSKULL operative: on a 3+, subtract 1 from that enemy operative’s APL stat until the end of its next activation.\nThis operative cannot perform this action while within control range of an enemy operative, or if a friendly GHEISTSKULL operative isn’t in the killzone."}], "keywords": ["IMPERIAL NAVY BREACHER", "IMPERIUM", "VOID-JAMMER"], "img": "/ops/imperial-navy-breachers/navis-void-jammer.webp"},
]
