// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Inquisitorial Requisition", text: "REQUISITIONED operatives can be taken from one of the following groups to supplement an INQUISITORIAL AGENT kill team, as specified in this kill team’s selection rules:\n• DEATH KORPS\n• EXACTION SQUAD\n• IMPERIAL NAVY BREACHER\n• KASRKIN\n• SISTER OF SILENCE\n• TEMPESTUS SCION\nThese operatives have their faction keyword replaced in all instances on their datacards with INQUISITORIAL AGENT (unless they already have it). You cannot use ploys and equipment associated with a REQUISITIONED operative’s former faction keyword, and you cannot use a REQUISITIONED operative’s former faction rules unless specified on their Inquisitorial Requisition card (it only applies to those REQUISITIONED operatives). Note that with their new faction keyword, REQUISITIONED operatives can interact with the INQUISITORIAL AGENT rules. For example, a REQUISITIONED VOX-OPERATOR operative from the DEATH KORPS group would have its DEATH KORPS keyword replaced in all instances on its datacard with INQUISITORIAL AGENT . This allows you to select any other friendly INQUISITORIAL AGENT operative for its Signal unique action. However, the Guardsman Orders faction rule isn’t permitted, so its Relay Orders additional rule would be ignored. It" },
  { kind: 'strategy', name: "Denounce", text: "Select one enemy operative and roll one D3. In the Firefight phase of this turning point, that enemy operative cannot be activated or perform actions until it's the last enemy operative to be activated, or your opponent has activated a number of enemy operatives equal to the result of the D3 (whichever comes first). This ploy costs you 1 additional CP for each previous time you’ve used it during the battle (e.g. 1CP the first time you would use it, 2CP the second time, etc.)." },
  { kind: 'strategy', name: "Intense Scrutiny", text: "Whenever you’re selecting a valid target for a friendly INQUISITORIAL AGENT operative, enemy operatives within 4\" of it cannot be in cover (instead of 2\"). While this can allow such operatives to be targeted (assuming they’re visible), it doesn’t remove their cover save (if any), unless the friendly INQUISITORIAL AGENT operative is within 2\" as normal." },
  { kind: 'strategy', name: "Quarry", text: "Select one enemy operative to be your quarry for the turning point. Whenever a friendly INQUISITORIAL AGENT operative is shooting against, fighting against or retaliating against your quarry, that friendly operative’s weapons have the Ceaseless weapon rule. Whenever your quarry is incapacitated, you can select a new enemy operative to be your quarry (and can continue to do so during this turning point)." },
  { kind: 'firefight', name: "Absolute Authority", text: "Use this firefight ploy during the battle, when an opponent uses a strategy or firefight ploy (excluding Command Re-roll or one that costs 0CP). Their ploy isn’t used, the CP spent on it is refunded and they cannot use that ploy again during this turning point. This ploy cannot be used to stop the same ploy more than once per battle." },
  { kind: 'strategy', name: "Irrefutable Jurisdiction", text: "Whenever an operative is shooting a friendly INQUISITORIAL AGENT operative that’s within 3\" of an objective marker, you can re-roll one of your defence dice. If that friendly operative contests that marker, you can re-roll any of your defence dice results of one result instead (e.g. results of 2)." },
  { kind: 'firefight', name: "Relentless in Pursuit", text: "Use this firefight ploy when an enemy operative within 2\" of a ready friendly INQUISITORIAL AGENT operative performs an action in which it moves. After it moves, that friendly INQUISITORIAL AGENT operative can either perform a free Reposition action, but must end that move within 2\" of that enemy operative, or a free Charge action, but must end that move within control range of that enemy operative. If neither is possible, that friendly operative cannot perform those actions, this ploy isn’t used and the CP spent on it is refunded." },
  { kind: 'firefight', name: "The Emperor's Will", text: "Use this firefight ploy when a friendly INQUISITORIAL AGENT operative is activated. Until the end of that operative’s activation, you can ignore any changes to its stats (including its weapons’ stats)." },
  { kind: 'equipment', name: "Inquisitorial Rosette", text: "Once per battle, when a friendly INQUISITORIAL AGENT operative is activated, if you’ve used the Quarry strategy ploy during this turning point, you can use this rule. If you do, you can select a new enemy operative to be your quarry until the end of the turning point." },
  { kind: 'firefight', name: "Intimidating Presence", text: "Use this firefight ploy when an enemy operative visible to and within 3\" of a friendly INQUISITORIAL AGENT operative, or visible to and within 6\" of a friendly MYSTIC operative, performs the Pick Up Marker or a mission action (excluding Operate Hatch). Your opponent must spend 1 additional AP for that enemy operative to perform that action (if they cannot or choose not to, the AP spent on it is refunded)." },
  { kind: 'equipment', name: "Combat Daggers", text: "In the press of melee combat, a simple dagger can be the difference between life and death. Friendly INQUISITORIAL AGENT operatives have the following melee weapon — Combat dagger: ATK 3, HIT 4+, DMG 3/4. Whenever a friendly SISTER OF SILENCE operative is using it, add 1 to its Atk stat." },
  { kind: 'equipment', name: "Armoured Bodysuits", text: "Whenever an operative is shooting a friendly INQUISITORIAL AGENT operative (excluding TOME-SKULL) that has a 5+ Save stat, you can retain one of your defence dice results of 4 as a normal success." },
  { kind: 'equipment', name: "Servo-skull", text: "Once per battle, one friendly INQUISITORIAL AGENT operative can perform a mission action for 1 less AP." },
]

export const operatives: Operative[] = [
  { id: "inquisitorial-agents:interrogator-agent", name: "Interrogator Agent", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "inquisitorial-agents:tome-skull", name: "Tome-skull", apl: 2, move: "6\"", save: "5+", w: 5 },
  { id: "inquisitorial-agents:autosavant-agent", name: "Autosavant Agent", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "inquisitorial-agents:death-world-veteran-agent", name: "Death World Veteran Agent", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "inquisitorial-agents:enlightener-agent", name: "Enlightener Agent", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "inquisitorial-agents:hexorcist-agent", name: "Hexorcist Agent", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "inquisitorial-agents:mystic-agent", name: "Mystic Agent", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "inquisitorial-agents:penal-legionnaire-agent", name: "Penal Legionnaire Agent", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "inquisitorial-agents:pistolier-agent", name: "Pistolier Agent", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "inquisitorial-agents:questkeeper-agent", name: "Questkeeper Agent", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "inquisitorial-agents:requisitioned-gun-servitor", name: "Requisitioned Gun Servitor", apl: 1, move: "5\"", save: "4+", w: 11 },
  { id: "inquisitorial-agents:sister-of-silence-prosecutor", name: "Sister of Silence Prosecutor", apl: 2, move: "6\"", save: "3+", w: 8 },
  { id: "inquisitorial-agents:sister-of-silence-vigilator", name: "Sister of Silence Vigilator", apl: 2, move: "6\"", save: "3+", w: 8 },
  { id: "inquisitorial-agents:sister-of-silence-witchseeker", name: "Sister of Silence Witchseeker", apl: 2, move: "6\"", save: "3+", w: 8 },
  { id: "inquisitorial-agents:tempestus-scion-gunner", name: "Tempestus Scion Gunner", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "inquisitorial-agents:tempestus-scion-medic", name: "Tempestus Scion Medic", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "inquisitorial-agents:tempestus-scion-trooper", name: "Tempestus Scion Trooper", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "inquisitorial-agents:tempestus-scion-vox-operator", name: "Tempestus Scion Vox-operator", apl: 2, move: "6\"", save: "4+", w: 8 },
]

export const datacards: Datacard[] = [
  {"name": "Interrogator Agent", "weapons": [{"name": "Extended stock relic autopistol", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Range 12\", Lethal 5+"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Inquisitorial Tomes", "text": "STRATEGIC                  • Denunciation: Whenever a friendly GAMBIT if this operative is in the                INQUISITORIAL AGENT operative killzone. Select one of the following             is shooting against, fighting against or INQUISITORIAL TOME rules for                      retaliating against an enemy operative this operative to have, and one for a             within 2\" of friendly operatives with friendly INQUISITORIAL AGENT                      this rule, add 1 to the Atk stat of that TOME-SKULL operative to have (they                friendly operative’s weapons. cannot be the same, and ignore the rule you didn’t select for each operative):"}], "actions": [], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "INQUISITION", "LEADER", "INTERROGATOR"], "img": "/ops/inquisitorial-agents/interrogator-agent.webp"},
  {"name": "Tome-skull", "weapons": [], "abilities": [{"name": "Consecrated Tome", "text": "This operative can have an INQUISITORIAL TOME rule (see INTERROGATOR). Note it keeps that rule even if that friendly INTERROGATOR operative is removed from the killzone."}, {"name": "Machine", "text": "• This operative cannot perform any actions other than Charge, Dash, Fall Back and Reposition. • It cannot retaliate or assist in a fight. • Whenever determining control of a marker, treat this operative’s APL stat as 1 lower. Note this isn’t a change to its APL stat, so any changes are cumulative with this. • Whenever this operative has a Conceal order and is in cover, it cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2\"."}, {"name": "Expendable", "text": "This operative is ignored for your opponent’s kill/ elimination op (when it’s incapacitated, and when determining your starting number of operatives). It’s also ignored for victory conditions and scoring VPs if either require operatives to ‘escape’, ‘survive’ or be incapacitated by enemy operatives (if it escapes/survives/is incapacitated, determining how many operatives must escape/survive/be incapacitated, etc.)."}, {"name": "Group Activation", "text": "Whenever this operative is expended, you must then activate a ready friendly INQUISITORIAL AGENT INTERROGATOR operative (if able) before your opponent activates. The same is true in reverse (INTERROGATOR followed by TOME-SKULL). When that other operative is expended, your opponent then activates as normal."}], "actions": [], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "INQUISITION", "TOME-SKULL"], "img": "/ops/inquisitorial-agents/tome-skull.webp"},
  {"name": "Autosavant Agent", "weapons": [{"name": "Mechanical appendages", "atk": 3, "hit": "5+", "dmg": "1/2"}], "abilities": [{"name": "Scrivener", "text": "Each subsequent time your opponent uses each ploy during the battle (excluding Command Re-roll), if this operative is in the killzone, you gain 1CP (to a maximum of 2CP per turning point)."}, {"name": "Irrefutable Report", "text": "Whenever this operative contests an objective marker or one of your mission markers, it always controls that marker. This takes precedence over all other rules."}, {"name": "Lightly Armed", "text": "This operative cannot use any weapons that aren’t on its datacard, or perform unique actions."}], "actions": [], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "INQUISITION", "AUTOSAVANT"], "img": "/ops/inquisitorial-agents/autosavant-agent.webp"},
  {"name": "Death World Veteran Agent", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Knife", "atk": 1, "hit": "2+", "dmg": "5/7", "wr": "Lethal 5+"}, {"name": "Polearm", "atk": 4, "hit": "3+", "dmg": "4/5"}], "abilities": [{"name": "Hunter", "text": "This operative can perform the Charge action while it has a Conceal order."}, {"name": "Weathered", "text": "Once per turning point, when this operative is fighting or retaliating, in the Resolve Attack Dice step, you can ignore the damage inflicted on it from one normal success."}], "actions": [], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "INQUISITION", "DEATH WORLD VETERAN"], "img": "/ops/inquisitorial-agents/death-world-veteran-agent.webp"},
  {"name": "Enlightener Agent", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Paired blades", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Balanced, Rending"}], "abilities": [{"name": "No Escape", "text": "Whenever an enemy operative would perform the Fall Back action while within control range of this operative, you can use this rule. If you do, roll one D6, subtracting 1 from the result if that enemy operative has a higher Wounds stat than this operative, and adding 1 if that enemy operative is wounded: on a 4+, that enemy operative cannot perform that action during that activation/counteraction (the AP spent on it isn’t refunded)."}, {"name": "Extract Information", "text": "Whenever an enemy operative is incapacitated within this operative’s control range, you gain 1CP."}], "actions": [], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "INQUISITION", "ENLIGHTENER"], "img": "/ops/inquisitorial-agents/enlightener-agent.webp"},
  {"name": "Hexorcist Agent", "weapons": [{"name": "Shotgun", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Range 6\""}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Hexorcise", "text": "Whenever an enemy operative is visible to and within 6\" of this operative,\nyour opponent cannot re-roll their attack\nor defence dice for that operative."}], "actions": [{"name": "Chasten", "ap": 1, "text": "Select one enemy operative that's a valid target for this operative and within 6\" of it,\nthen select one additional rule (including a unique action) that enemy operative has\non its datacard (excluding a weapon rule or a rule that states it is ignored for the kill/ elimination op). Until the end of that enemy operative’s next activation, it’s treated as not having that additional rule.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "INQUISITION", "HEXORCIST"], "img": "/ops/inquisitorial-agents/hexorcist-agent.webp"},
  {"name": "Mystic Agent", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "2+", "dmg": "2/3", "wr": "Range 8\", Seek"}, {"name": "Fists", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [{"name": "Icon Bearer", "text": "Whenever determining control of a marker, treat this operative’s APL stat as 1 higher. Note this isn’t a change to its APL stat, so any changes are cumulative with this."}, {"name": "Lightly Armed", "text": "This operative cannot use any weapons that aren’t on its datacard."}], "actions": [{"name": "Scry", "ap": 1, "text": "PSYCHIC. Select one friendly INQUISITORIAL AGENT operative within 6\" of this operative, then select one of the following effects to last until the start of this operative’s next activation, until it’s incapacitated or until it performs this action again (whichever comes first):\n• Guidance: PSYCHIC. Whenever the selected operative is shooting, fighting or retaliating, in the Roll Attack Dice step, you can retain one of your fails as a normal success instead of discarding it, or retain one of your normal successes as a critical success instead. • Protection: PSYCHIC. Whenever an operative is shooting the selected operative, in the Roll Defence Dice step, you can retain one of your fails as a normal success instead of discarding it, or retain one of your normal successes as a critical success instead.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "INQUISITION", "PSYKER", "MYSTIC"], "img": "/ops/inquisitorial-agents/mystic-agent.webp"},
  {"name": "Penal Legionnaire Agent", "weapons": [{"name": "Hand flamer", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 6\", Saturate, Torrent 1\""}, {"name": "Chainsword", "atk": 4, "hit": "4+", "dmg": "4/5"}], "abilities": [{"name": "Chem-mask", "text": "You can ignore any changes to this operative’s APL stat, and any changes to its stats from being injured. This operative isn’t affected by enemy operatives’ Shock and Stun weapon rules."}, {"name": "Cruel", "text": "Whenever this operative is shooting against, fighting against or retaliating against a wounded enemy operative, this operative’s weapons have the Relentless weapon rule."}], "actions": [], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "INQUISITION", "PENAL LEGIONNAIRE"], "img": "/ops/inquisitorial-agents/penal-legionnaire-agent.webp"},
  {"name": "Pistolier Agent", "weapons": [{"name": "Scoped plasma pistol (standard)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 12\", Piercing 1"}, {"name": "Scoped plasma pistol (supercharge)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 12\", Hot, Lethal 5+, Piercing 1"}, {"name": "Suppressed autopistol", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Range 8\", Silent"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Pistolier", "text": "You can ignore any changes to the Hit stat of this operative’s\nranged weapons."}], "actions": [{"name": "Pistol Barrage", "ap": 1, "text": "Perform two free Shoot actions with this operative (this takes precedence over\naction restrictions). You must select a profile of its scoped plasma pistol for one action and its suppressed autopistol for the other (in any order).\nThis operative cannot perform this action while it has a Conceal order, or during an activation in which it performed the Shoot action (or vice versa)."}], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "INQUISITION", "PISTOLIER"], "img": "/ops/inquisitorial-agents/pistolier-agent.webp"},
  {"name": "Questkeeper Agent", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Eviscerator", "atk": 4, "hit": "4+", "dmg": "5/6", "wr": "Brutal"}], "abilities": [{"name": "Irrepressible Purpose", "text": "If this operative is incapacitated during the Fight action, you can strike the enemy operative in that sequence with one of your unresolved successes before this operative is removed from the killzone."}, {"name": "Zealot", "text": "Whenever an attack dice inflicts damage of 3 or more on this operative, roll one D6: on a 5+, subtract 1 from that inflicted damage."}], "actions": [], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "INQUISITION", "QUESTKEEPER"], "img": "/ops/inquisitorial-agents/questkeeper-agent.webp"},
  {"name": "Requisitioned Gun Servitor", "weapons": [{"name": "Heavy bolter (focused)", "atk": 5, "hit": "4+", "dmg": "4/5", "wr": "Heavy (Dash only), Piercing Crits 1"}, {"name": "Heavy bolter (sweeping)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Heavy (Dash only), Piercing Crits 1, Torrent 1\""}, {"name": "Multi-melta", "atk": 4, "hit": "4+", "dmg": "6/3", "wr": "Devastating 4, Heavy (Dash only), Piercing 2"}, {"name": "Plasma cannon (standard)", "atk": 4, "hit": "4+", "dmg": "4/6", "wr": "Blast 2\", Heavy (Dash only), Piercing 1"}, {"name": "Plasma cannon (supercharge)", "atk": 4, "hit": "4+", "dmg": "5/6", "wr": "Blast 2\", Heavy (Dash only), Hot, Lethal 5+, Piercing 1"}, {"name": "Servo claw", "atk": 3, "hit": "4+", "dmg": "4/5"}], "abilities": [{"name": "Lobotomised", "text": "Whenever this operative is activated, if it’s visible to and within 3\" of another friendly INQUISITORIAL AGENT operative (excluding GUN SERVITOR) or vice versa, add 1 to this operative’s APL stat until the end of that activation."}], "actions": [], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "INQUISITION", "GUN SERVITOR"], "img": "/ops/inquisitorial-agents/requisitioned-gun-servitor.webp"},
  {"name": "Sister of Silence Prosecutor", "weapons": [{"name": "Boltgun", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Gun butt", "atk": 4, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Psychic Null", "text": "PSYCHIC ranged weapons cannot inflict damage on this operative. For the effects of PSYCHIC actions, this operative cannot be selected and is never treated as being within those actions’ required distances. Whenever an operative is within 6\" of this operative:\n• That operative cannot perform PSYCHIC actions or use PSYCHIC additional rules. • That operative cannot use PSYCHIC ranged weapons. • PSYCHIC melee weapons have no weapon rules and cannot have Dmg stats higher than 3/4."}], "actions": [], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "ANATHEMA PSYKANA", "SISTER OF SILENCE", "PROSECUTOR"], "img": "/ops/inquisitorial-agents/sister-of-silence-prosecutor.webp"},
  {"name": "Sister of Silence Vigilator", "weapons": [{"name": "Executioner greatblade", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Psychic Null", "text": "PSYCHIC ranged weapons cannot inflict damage on this operative. For the effects of PSYCHIC actions, this operative cannot be selected and is never treated as being within those actions’ required distances. Whenever an operative is within 6\" of this operative:\n• That operative cannot perform PSYCHIC actions or use PSYCHIC additional rules. • That operative cannot use PSYCHIC ranged weapons. • PSYCHIC melee weapons have no weapon rules and cannot have Dmg stats higher than 3/4."}], "actions": [], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "ANATHEMA PSYKANA", "SISTER OF SILENCE", "VIGILATOR"], "img": "/ops/inquisitorial-agents/sister-of-silence-vigilator.webp"},
  {"name": "Sister of Silence Witchseeker", "weapons": [{"name": "Flamer", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 8\", Saturate, Torrent 2\""}, {"name": "Gun butt", "atk": 4, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Psychic Null", "text": "PSYCHIC ranged weapons cannot inflict damage on this operative. For the effects of PSYCHIC actions, this operative cannot be selected and is never treated as being within those actions’ required distances. Whenever an operative is within 6\" of this operative:\n• That operative cannot perform PSYCHIC actions or use PSYCHIC additional rules. • That operative cannot use PSYCHIC ranged weapons. • PSYCHIC melee weapons have no weapon rules and cannot have Dmg stats higher than 3/4."}], "actions": [], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "ANATHEMA PSYKANA", "SISTER OF SILENCE", "WITCHSEEKER"], "img": "/ops/inquisitorial-agents/sister-of-silence-witchseeker.webp"},
  {"name": "Tempestus Scion Gunner", "weapons": [{"name": "Flamer", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 8\", Saturate, Torrent 2\""}, {"name": "Grenade launcher (frag)", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Blast 2\""}, {"name": "Grenade launcher (krak)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Piercing 1"}, {"name": "Hot-shot volley gun (focused)", "atk": 5, "hit": "3+", "dmg": "3/4", "wr": "Piercing Crits 1"}, {"name": "Hot-shot volley gun (sweeping)", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Piercing Crits 1, Torrent 1\""}, {"name": "Meltagun", "atk": 4, "hit": "3+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Plasma gun (standard)", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Piercing 1"}, {"name": "Plasma gun (supercharge)", "atk": 4, "hit": "3+", "dmg": "5/6", "wr": "Hot, Lethal 5+, Piercing 1"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "ASTRA MILITARUM", "TEMPESTUS SCION", "GUNNER"], "img": "/ops/inquisitorial-agents/tempestus-scion-gunner.webp"},
  {"name": "Tempestus Scion Medic", "weapons": [{"name": "Hot-shot lasgun", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Medic!", "text": "The first time during each turning point that another friendly INQUISITORIAL AGENT operative would be incapacitated while visible to and within 3\" of this operative, you can use this rule, providing neither this nor that operative is within control range of an enemy operative. If you do, that friendly operative isn’t incapacitated, has 1 wound remaining and cannot be incapacitated for the remainder of the action. After that action, that friendly operative can immediately perform a free Dash action, but must end that move within this operative’s control range. Subtract 1 from this and that operative’s APL stats until the end of their next activations respectively, and if this rule was used during that friendly operative’s activation, that activation ends. You cannot use this rule if this operative is incapacitated, or if it’s a Shoot action and this operative would be a primary or secondary target."}], "actions": [{"name": "Medikit", "ap": 1, "text": "Select one friendly INQUISITORIAL AGENT operative within this operative’s control range to regain up to 2D3 lost wounds. It cannot be an operative that the Medic! rule was used on during this turning point.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "ASTRA MILITARUM", "TEMPESTUS SCION", "MEDIC"], "img": "/ops/inquisitorial-agents/tempestus-scion-medic.webp"},
  {"name": "Tempestus Scion Trooper", "weapons": [{"name": "Hot-shot lasgun", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Adaptive Equipment", "text": "You can do each of the following once per turning point:\n• One friendly INQUISITORIAL AGENT TEMPESTUS SCION TROOPER operative can perform the Smoke Grenade action. • One friendly INQUISITORIAL AGENT TEMPESTUS SCION TROOPER operative can perform the Stun Grenade action.\nThe rules for these actions are found in universal equipment. Performing these actions using this rule doesn’t count towards their action limits (i.e. if you also select those grenades from equipment)."}], "actions": [], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "ASTRA MILITARUM", "TEMPESTUS SCION", "TROOPER"], "img": "/ops/inquisitorial-agents/tempestus-scion-trooper.webp"},
  {"name": "Tempestus Scion Vox-operator", "weapons": [{"name": "Hot-shot lasgun", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [{"name": "Signal", "ap": 1, "text": "SUPPORT. Select one other friendly INQUISITORIAL AGENT operative in the killzone. Until the end of that operative’s next activation, add 1 to its APL stat.\nThis operative can perform this action twice during its activation, but cannot perform this action while within control range of an enemy operative."}], "keywords": ["INQUISITORIAL AGENT", "IMPERIUM", "ASTRA MILITARUM", "TEMPESTUS SCION", "VOX-OPERATOR"], "img": "/ops/inquisitorial-agents/tempestus-scion-vox-operator.webp"},
]
