// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Skill at Arms", text: "STRATEGIC GAMBIT. Select a SKILL AT ARMS for friendly KASRKIN operatives to have until the Ready step of the next Strategy phase.\nFriendly KASRKIN operatives’ ranged weapons have the Severe weapon rule.\nWhenever a friendly KASRKIN operative is performing the Reposition action, add 1\" to its Move stat.\nAdd 1 to the Atk stat of friendly KASRKIN operatives’ melee weapons (to a maximum of 4). Whenever a friendly KASRKIN operative is fighting, the first time you strike during that sequence, inflict 1 additional damage.\nWhenever a friendly KASRKIN operative is fighting or retaliating, or an operative is shooting it, the first time an attack dice inflicts Normal Dmg of 3 or more on this operative during that sequence, that dice inflicts 1 less damage on it." },
  { kind: 'faction', name: "Rapid Fire", text: "Each friendly KASRKIN operative that doesn’t perform an action in which it moves during its activation can perform two Shoot actions (excluding Guard) during that activation, but a bolt pistol, hot-shot lasgun or hot-shot laspistol must be selected for both of those actions." },
  { kind: 'strategy', name: "Engage from Cover", text: "Whenever an operative is shooting a friendly KASRKIN operative that’s in cover, you can re-roll one of your defence dice." },
  { kind: 'strategy', name: "Elimination Pattern", text: "Whenever a friendly KASRKIN operative is shooting with a hot-shot weapon against an operative that cannot retain any cover saves or is being scanned (see RECON-TROOPER), that weapon has the Piercing Crits 1 weapon rule, or Piercing 1 instead if it’s a hot-shot volley gun." },
  { kind: 'strategy', name: "Clearance Sweep", text: "Place your Clearance Sweep marker in the killzone. Whenever a friendly KASRKIN operative within 5\" horizontally of that marker is shooting an operative also within 5\" horizontally of that marker, that friendly operative’s weapons have the Ceaseless weapon rule. In the Ready step of the next Strategy phase, remove that marker." },
  { kind: 'strategy', name: "Relocate", text: "Select one friendly KASRKIN operative that’s more than 3\" from enemy operatives. That operative, and each other friendly KASRKIN operative that’s both within 3\" of that operative and more than 3\" from enemy operatives, can immediately perform a free Dash action in an order of your choice. You cannot use this ploy during the first turning point." },
  { kind: 'firefight', name: "Cover Retreat", text: "Use this firefight ploy when a friendly KASRKIN operative performs the Fall Back action while visible to and within 6\" of another friendly KASRKIN operative that’s not within control range of enemy operatives. After that friendly operative has finished moving, but before that Fall Back action ends, that other friendly operative can immediately perform a free Shoot action (you can change its order to Engage to do so)." },
  { kind: 'firefight', name: "Seize the Initiative", text: "Use this firefight ploy at the start of the Firefight phase. One friendly KASRKIN operative can immediately perform a 1AP action for free, but it cannot move during that action. You cannot use this ploy if you’re the player with initiative." },
  { kind: 'firefight', name: "Neutralise Target", text: "Use this firefight ploy after rolling your attack dice for a friendly KASRKIN operative, if it’s shooting an operative that either cannot retain any cover saves or is being scanned (see RECON-TROOPER). You can re-roll any of your attack dice." },
  { kind: 'firefight', name: "Give No Ground", text: "Use this firefight ploy during a friendly KASRKIN operative’s activation, or at the end of the Firefight phase. Select one of your mission markers or an objective marker. Until the end of that activation or until the start of the next turning point respectively, if the total APL of friendly KASRKIN operatives that contest that marker is 2, and the total APL of enemy operatives that contest it is the same, friendly KASRKIN operatives control that marker." },
  { kind: 'equipment', name: "Long-range Scope", text: "Whenever a friendly KASRKIN operative is shooting an operative more than 6\" from it, that friendly operative’s hot-shot weapons have the Saturate weapon rule." },
  { kind: 'equipment', name: "Foregrip", text: "Whenever a friendly KASRKIN operative is shooting an operative within 3\" of it, ranged weapons on its datacard (excluding weapons that include ‘pistol’ in their name, e.g. hot-shot laspistol, all profiles of a plasma pistol, etc.) have the Accurate 1 weapon rule." },
  { kind: 'equipment', name: "Relics of Cadia", text: "Once per turning point, when a friendly KASRKIN operative is shooting, fighting or retaliating, if you roll two or more fails, you can discard one of them to retain another as a normal success instead." },
  { kind: 'equipment', name: "Combat Daggers", text: "Friendly KASRKIN operatives have the following melee weapon — Combat dagger: ATK 3, HIT 4+, DMG 3/4." },
]

export const operatives: Operative[] = [
  { id: "kasrkin:kasrkin-sergeant", name: "Kasrkin Sergeant", apl: 3, move: "6\"", save: "4+", w: 9 },
  { id: "kasrkin:kasrkin-combat-medic", name: "Kasrkin Combat Medic", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "kasrkin:kasrkin-demo-trooper", name: "Kasrkin Demo-trooper", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "kasrkin:kasrkin-gunner", name: "Kasrkin Gunner", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "kasrkin:kasrkin-recon-trooper", name: "Kasrkin Recon-trooper", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "kasrkin:kasrkin-sharpshooter", name: "Kasrkin Sharpshooter", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "kasrkin:kasrkin-trooper", name: "Kasrkin Trooper", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "kasrkin:kasrkin-vox-trooper", name: "Kasrkin Vox-trooper", apl: 2, move: "6\"", save: "4+", w: 8 },
]

export const datacards: Datacard[] = [
  {"name": "Kasrkin Sergeant", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Hot-shot lasgun", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Hot-shot laspistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Plasma pistol (standard)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Piercing 1"}, {"name": "Plasma pistol (supercharge)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Hot, Lethal 5+, Piercing 1"}, {"name": "Chainsword", "atk": 4, "hit": "3+", "dmg": "4/5"}, {"name": "Gun butt", "atk": 3, "hit": "3+", "dmg": "2/3"}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Veteran Leadership", "text": "Whenever this operative is in the killzone and you use the SKILL AT ARMS STRATEGIC GAMBIT,\nyou can select one additional SKILL AT ARMS but they\ncannot be the same."}], "actions": [{"name": "Tactical Command", "ap": 0, "text": "Select one friendly KASRKIN operative, then select one\nSKILL AT ARMS for that operative to have until the Ready\nstep of the next Strategy phase. This can be in addition to any SKILL AT ARMS it already has, but they cannot be the same.\nAlternatively, instead of resolving the above effect, if your Clearance Sweep marker is in the killzone, you can remove it and place it again.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["KASRKIN", "IMPERIUM", "ASTRA MILITARUM", "LEADER", "SERGEANT"]},
  {"name": "Kasrkin Combat Medic", "weapons": [{"name": "Hot-shot lasgun", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Medic!", "text": "The first time during each turning point that another friendly KASRKIN operative would be incapacitated while visible to and within 3\" of this operative, you can use this rule, providing neither this nor that operative is within control range of an enemy operative. If you do, that friendly operative isn’t incapacitated, has 1 wound remaining and cannot be incapacitated for the remainder of the action. After that action, that friendly operative can immediately perform a free Dash action, but must end that move within this operative’s control range. Subtract 1 from this and that operative’s APL stats until the end of their next activations respectively, and if this rule was used during that friendly operative’s activation, that activation ends. You cannot use this rule if this operative is incapacitated, or if it’s a Shoot action and this operative would be a primary or secondary target."}], "actions": [{"name": "Medikit", "ap": 0, "text": "Select one friendly KASRKIN operative within this operative’s control range to regain up to 2D3 lost wounds. It cannot be an operative that the Medic! rule was used on during this turning point.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["KASRKIN", "IMPERIUM", "ASTRA MILITARUM", "MEDIC", "COMBAT MEDIC"]},
  {"name": "Kasrkin Demo-trooper", "weapons": [{"name": "Hot-shot laspistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Melta Mine", "text": "This operative is carrying your Melta Mine marker. It can perform the Pick Up Marker action on that marker, and whenever it performs the Place Marker action on that marker, it can immediately perform a free Dash action. That marker cannot be placed within an enemy operative’s control range (if this operative is incapacitated while carrying that marker and that marker cannot be placed, it’s removed with this operative)."}, {"name": "Proximity Mine", "text": "The first time your Melta Mine marker is within another operative’s control range, remove that marker and inflict 2D6+3 damage on that operative; if it isn’t incapacitated, end its action (if any), even if that action’s effects aren’t fulfilled. If it cannot be placed, move it the minimum amount to do so. Note that this operative is ignored for these effects (i.e. it cannot set it off or take damage from that marker)."}, {"name": "Blast Padding", "text": "Whenever an operative is shooting this operative with a weapon that has the Blast or Torrent weapon rule (excluding weapons that have a sweeping profile), you can re-roll one of your defence dice. In addition, this operative isn’t affected by the x\" Devastating x weapon rule (i.e. Devastating with a distance) unless they are the target during that sequence."}], "actions": [], "keywords": ["KASRKIN", "IMPERIUM", "ASTRA MILITARUM", "DEMO-TROOPER"]},
  {"name": "Kasrkin Gunner", "weapons": [{"name": "Flamer", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 8\", Saturate, Torrent 2\""}, {"name": "Grenade launcher (frag)", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Blast 2\""}, {"name": "Grenade launcher (krak)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Piercing 1"}, {"name": "Hot-shot volley gun (focused)", "atk": 5, "hit": "3+", "dmg": "3/4", "wr": "Piercing Crits 1"}, {"name": "Hot-shot volley gun (sweeping)", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Piercing Crits 1, Torrent 1\""}, {"name": "Meltagun", "atk": 4, "hit": "3+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Plasma gun (standard)", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Piercing 1"}, {"name": "Plasma gun (supercharge)", "atk": 4, "hit": "3+", "dmg": "5/6", "wr": "Hot, Lethal 5+, Piercing 1"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [], "keywords": ["KASRKIN", "IMPERIUM", "ASTRA MILITARUM", "GUNNER"]},
  {"name": "Kasrkin Recon-trooper", "weapons": [{"name": "Hot-shot lasgun", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Reconnoitre Killzone", "text": "The Relocate strategy ploy costs you 0CP if this operative is the selected friendly KASRKIN operative."}], "actions": [{"name": "Auspex Scan", "ap": 1, "text": "Until the start of this operative’s next activation or until it’s incapacitated (whichever comes first), whenever an enemy operative is within 8\" of this operative, that enemy operative is being scanned. Whenever a friendly KASRKIN operative is shooting an enemy operative that’s being scanned, that enemy operative cannot be obscured\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["KASRKIN", "IMPERIUM", "ASTRA MILITARUM", "RECON-TROOPER"]},
  {"name": "Kasrkin Sharpshooter", "weapons": [{"name": "Hot-shot marksman rifle (concealed)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy, Silent, Concealed Position*"}, {"name": "Hot-shot marksman rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Hot-shot marksman rifle (stationary)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Camo Cloak", "text": "Whenever an operative is shooting this operative:\n• Ignore the Saturate weapon rule. • If you can retain any cover saves, you can retain one additional cover save, or you can retain one cover save as a critical success instead. This isn’t cumulative with improved cover saves from Vantage terrain."}, {"name": "Concealed Position", "text": "This operative can only use this weapon the first time it’s performing the Shoot action during the battle."}], "actions": [], "keywords": ["KASRKIN", "IMPERIUM", "ASTRA MILITARUM", "SHARPSHOOTER"]},
  {"name": "Kasrkin Trooper", "weapons": [{"name": "Hot-shot lasgun", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Adaptive Equipment", "text": "You can do each of the following once per turning point:\n• One friendly KASRKIN TROOPER operative can perform the Smoke Grenade action. • One friendly KASRKIN TROOPER operative can perform the Stun Grenade action.\nThe rules for these actions are found in universal equipment. Performing these actions using this rule doesn’t count towards their action limits (i.e. if you also select those grenades from equipment)."}], "actions": [], "keywords": ["KASRKIN", "IMPERIUM", "ASTRA MILITARUM", "TROOPER"]},
  {"name": "Kasrkin Vox-trooper", "weapons": [{"name": "Hot-shot lasgun", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [{"name": "Battle Comms", "ap": 1, "text": "Select one other friendly KASRKIN operative. Until the end of that operative’s next activation, add 1 to its APL stat (to a maximum of 3 after all APL stat changes have been totalled).\nThis operative can perform this action twice during its activation, but cannot perform this action while within control range of an enemy operative."}], "keywords": ["KASRKIN", "IMPERIUM", "ASTRA MILITARUM", "VOX-TROOPER"]},
]
