// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Throat Slittas", text: "Each friendly KOMMANDO operative (excluding BOMB SQUIG) can perform the Charge action while it has a Conceal order." },
  { kind: 'strategy', name: "Dakka! Dakka! Dakka!", text: "Friendly KOMMANDO operatives’ ranged weapons have the Punishing weapon rule." },
  { kind: 'strategy', name: "Waaagh!", text: "Friendly KOMMANDO operatives’ melee weapons have the Balanced weapon rule." },
  { kind: 'strategy', name: "Sssshhhh!", text: "Each friendly KOMMANDO operative that’s not a valid target for enemy operatives, or has a Conceal order and is more than 6\" from enemy operatives, can immediately perform a free Dash action. You cannot use this ploy during the first turning point." },
  { kind: 'strategy', name: "Skulk About", text: "Whenever an enemy operative is shooting a friendly KOMMANDO operative that has a Conceal order, you can retain one of your defence dice as a normal success without rolling it (in addition to a cover save, if any)." },
  { kind: 'firefight', name: "Just a Scratch", text: "Use this firefight ploy when an attack dice inflicts Normal Dmg on a friendly KOMMANDO operative (excluding BOMB SQUIG and GROT). Ignore that inflicted damage." },
  { kind: 'firefight', name: "Krump ’em!", text: "Use this firefight ploy at the end of the Firefight phase. Select one friendly KOMMANDO operative. It can immediately perform a free Fight action." },
  { kind: 'firefight', name: "Shake It Off", text: "Use this firefight ploy when a friendly KOMMANDO operative is activated, or when its APL stat is changed. Until the start of the next turning point, you can ignore any changes to its APL stat." },
  { kind: 'firefight', name: "Kunnin’ But Brutal", text: "Use this firefight ploy when a friendly KOMMANDO operative that has a Conceal order is fighting during an activation in which it performed the Charge action, you’re resolving the first attack dice, and it’s a strike with a normal success. Treat that normal success as a critical success instead." },
  { kind: 'equipment', name: "Choppas", text: "Friendly KOMMANDO operatives (excluding BOMB SQUIG and GROT) have the following melee weapon — Choppa: ATK 3, HIT 3+, DMG 4/5. Note that some operatives already have this weapon but with better stats; in that instance, use the better version." },
  { kind: 'equipment', name: "Dynamite", text: "Once per battle, a friendly KOMMANDO operative (excluding BOMB SQUIG and GROT) can use the following ranged weapon — Dynamite: ATK 5, HIT 4+, DMG 4/5. WR Range 4\", Blast 1\", Heavy (Reposition only), Saturate." },
  { kind: 'equipment', name: "Collapsible Stocks", text: "Remove the Range weapon rule from the following ranged weapons friendly KOMMANDO operatives have:\n• Shokka pistol\n• Slugga" },
  { kind: 'equipment', name: "Harpoon", text: "Once per turning point, a friendly KOMMANDO operative (excluding BOMB SQUIG and GROT) can use the following ranged weapon — Harpoon: ATK 4, HIT 4+, DMG 4/5. WR Range 8\", Lethal 5+, Stun.\nNOTES:" },
]

export const operatives: Operative[] = [
  { id: "kom:kommando-boss-nob", name: "Kommando Boss Nob", apl: 3, move: "6\"", save: "5+", w: 14 },
  { id: "kom:kommando-bomb-squig", name: "Kommando Bomb Squig", apl: 2, move: "6\"", save: "5+", w: 5 },
  { id: "kom:kommando-boy", name: "Kommando Boy", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "kom:kommando-breacha-boy", name: "Kommando Breacha Boy", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "kom:kommando-burna-boy", name: "Kommando Burna Boy", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "kom:kommando-comms-boy", name: "Kommando Comms Boy", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "kom:kommando-dakka-boy", name: "Kommando Dakka Boy", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "kom:kommando-grot", name: "Kommando Grot", apl: 2, move: "6\"", save: "5+", w: 5 },
  { id: "kom:kommando-rokkit-boy", name: "Kommando Rokkit Boy", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "kom:kommando-slasha-boy", name: "Kommando Slasha Boy", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "kom:kommando-snipa-boy", name: "Kommando Snipa Boy", apl: 2, move: "6\"", save: "5+", w: 10 },
]

export const datacards: Datacard[] = [
  {"name": "Kommando Boss Nob", "weapons": [{"name": "Slugga", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Big choppa", "atk": 5, "hit": "3+", "dmg": "5/6"}, {"name": "Power klaw", "atk": 4, "hit": "3+", "dmg": "5/7", "wr": "Brutal, Shock"}], "abilities": [{"name": "Krumpin’ Time", "text": "This operative can perform two Fight actions during its activation."}], "actions": [{"name": "Get It Dun!", "ap": 1, "text": "SUPPORT. Select one other friendly KOMMANDO operative (excluding BOMB SQUIG) visible to and within 6\" of this operative. Until the end of that operative’s next activation, add 1 to its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative, or while counteracting."}], "keywords": ["KOMMANDO", "ORK", "LEADER", "BOSS NOB"]},
  {"name": "Kommando Bomb Squig", "weapons": [{"name": "Explosives", "atk": 6, "hit": "4+", "dmg": "4/5", "wr": "Blast 1\", Limited 1, Explosive*"}, {"name": "Bite", "atk": 3, "hit": "4+", "dmg": "4/5"}], "abilities": [{"name": "Stoopid", "text": "In the Firefight phase, whenever you determine this operative’s order, you cannot select Conceal. This operative cannot perform any actions other than Charge, Dash, Fight, Reposition and Shoot. It cannot use any weapons that aren’t on its datacard."}, {"name": "Expendable", "text": "This operative is ignored for your opponent’s kill/ elimination op (when it’s incapacitated, and when determining your starting number of operatives). It’s also ignored for victory conditions and scoring VPs if either require operatives to ‘escape’, ‘survive’ or be incapacitated by enemy operatives (if it escapes/survives/is incapacitated, determining how many operatives must escape/survive/be incapacitated, etc.)."}], "actions": [], "keywords": ["KOMMANDO", "ORK", "BOMB SQUIG"]},
  {"name": "Kommando Boy", "weapons": [{"name": "Slugga", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Choppa", "atk": 4, "hit": "3+", "dmg": "4/5"}], "abilities": [{"name": "Taktical Wot-notz", "text": "You can do each of the following once per turning point:\n• One friendly KOMMANDO BOY operative can perform the Smoke Grenade action. • One friendly KOMMANDO BOY operative can perform the Stun Grenade action.\nThe rules for these actions are found in universal equipment. Performing these actions using this rule doesn’t count towards their action limits (i.e. if you also select those grenades from equipment)."}], "actions": [], "keywords": ["KOMMANDO", "ORK", "BOY"]},
  {"name": "Kommando Breacha Boy", "weapons": [{"name": "Slugga", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Breacha ram", "atk": 4, "hit": "4+", "dmg": "5/5", "wr": "Brutal, Severe, Shock"}], "abilities": [], "actions": [{"name": "Breach", "ap": 1, "text": "Place one of your Breach markers within this operative’s control range as close as possible to a terrain feature within control range of it. Whenever an operative is within 1\" of that marker, it treats parts of that terrain feature that are no more than 1\" thick as Accessible terrain.\nThis operative can perform this action during the Charge or Reposition action, and it can do so for 1 less AP during those actions. Any remaining move distance can be used after it does so.\nThis operative cannot perform this action while within control range of an enemy operative, or if a terrain feature isn’t within its control range."}], "keywords": ["KOMMANDO", "ORK", "BREACHA BOY"]},
  {"name": "Kommando Burna Boy", "weapons": [{"name": "Burna (standard)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 8\", Saturate, Torrent 2\""}, {"name": "Burna (deluge)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 4\", Saturate, Seek, Torrent 0\"*"}, {"name": "Fists", "atk": 3, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["KOMMANDO", "ORK", "BURNA BOY"]},
  {"name": "Kommando Comms Boy", "weapons": [{"name": "Shokka pistol", "atk": 6, "hit": "4+", "dmg": "1/0", "wr": "Range 8\", Devastating 2, Severe, Stun"}, {"name": "Fists", "atk": 3, "hit": "3+", "dmg": "3/4"}], "abilities": [{"name": "I Got a Plan, Ladz", "text": "Once during each of this operative’s activations, it can perform\nthe Pick Up Marker, Place Marker\nor a mission action for 1 less AP."}], "actions": [{"name": "Listen in", "ap": 1, "text": "SUPPORT. Select one other friendly KOMMANDO operative (excluding\nBOMB SQUIG) visible to and within 6\" of this operative. Until the end of that\noperative’s next activation, add 1 to its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["KOMMANDO", "ORK", "COMMS BOY"]},
  {"name": "Kommando Dakka Boy", "weapons": [{"name": "Dakka shoota (short range)", "atk": 5, "hit": "4+", "dmg": "3/4", "wr": "Range 9\", Ceaseless"}, {"name": "Dakka shoota (long range)", "atk": 5, "hit": "4+", "dmg": "3/4"}, {"name": "Fists", "atk": 3, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [{"name": "Dakka Dash", "ap": 1, "text": "Perform a free Dash action and a free Shoot action with this operative in any order. You can only select a dakka shoota for that Shoot action.\nThis operative cannot perform this action while it has a Conceal order, or while within control range of an enemy operative."}], "keywords": ["KOMMANDO", "ORK", "DAKKA BOY"]},
  {"name": "Kommando Grot", "weapons": [{"name": "Grot choppa", "atk": 3, "hit": "5+", "dmg": "1/4"}], "abilities": [{"name": "Sneaky Zogger", "text": "This operative cannot have an Engage order. Whenever this\noperative is in cover, it cannot be selected\nas a valid target, taking precedence over\nall other rules (e.g. Seek, Vantage terrain)\nexcept being within 2\"."}], "actions": [{"name": "Grappling Hook", "ap": 1, "text": "Select a visible point on a terrain feature for this operative. Remove this operative\nfrom the killzone and set it back up within 1\" horizontally of that point in a location\nit can be placed, not within control range of enemy operatives, and with that point\nvisible to it. This operative cannot perform the Operate Hatch action during\nthis action.\nThis action is treated as a Reposition action. This operative cannot perform this action while within control range of an enemy operative, or during an activation in which it performed the Charge or Fall Back action (or vice versa)."}], "keywords": ["KOMMANDO", "ORK", "GROT"]},
  {"name": "Kommando Rokkit Boy", "weapons": [{"name": "Rokkit launcha (aimed)", "atk": 6, "hit": "4+", "dmg": "4/5", "wr": "Blast 1\", Ceaseless, Heavy (Dash only)"}, {"name": "Rokkit launcha (mobile)", "atk": 6, "hit": "4+", "dmg": "4/5", "wr": "Blast 1\""}, {"name": "Fists", "atk": 3, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["KOMMANDO", "ORK", "ROKKIT BOY"]},
  {"name": "Kommando Slasha Boy", "weapons": [{"name": "Throwing knives", "atk": 4, "hit": "3+", "dmg": "2/5", "wr": "Range 6\", Silent"}, {"name": "Twin choppas", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Ceaseless, Lethal 5+"}], "abilities": [{"name": "Dat All You Got?", "text": "After this operative fights or retaliates, if it wasn’t incapacitated, you can inflict D3 damage on the enemy operative in that sequence."}], "actions": [], "keywords": ["KOMMANDO", "ORK", "SLASHA BOY"]},
  {"name": "Kommando Snipa Boy", "weapons": [{"name": "Scoped big shoota (concealed)", "atk": 5, "hit": "3+", "dmg": "3/3", "wr": "Devastating 2, Heavy, Silent, Concealed Position*"}, {"name": "Scoped big shoota (stationary)", "atk": 5, "hit": "3+", "dmg": "3/3", "wr": "Devastating 2, Heavy"}, {"name": "Scoped big shoota (sweeping)", "atk": 5, "hit": "3+", "dmg": "3/4", "wr": "Heavy (Dash only), Torrent 1\""}, {"name": "Fists", "atk": 3, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["KOMMANDO", "ORK", "SNIPA BOY"]},
]
