// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Marks of Chaos", text: "Whenever you select a LEGIONARY operative for the battle, you must select one of the following keywords for it to have for that battle: KHORNE, NURGLE, SLAANESH, TZEENTCH, UNDIVIDED. Each operative’s keyword can be different, but a BALEFIRE ACOLYTE operative cannot have the KHORNE keyword. Friendly LEGIONARY operatives have an additional rule determined by this keyword. In addition, LEGIONARY ploys have additional benefits for operatives with the relevant keyword.\nKHORNE Wrathful Onslaught This operative’s melee weapons have the Severe weapon rule." },
  { kind: 'faction', name: "Marks of Chaos Nurgle", text: "Disgusting Vigour Whenever Normal Dmg of 3 or more is inflicted on this operative, roll one D6: on a 5+, subtract 1 from that inflicted damage." },
  { kind: 'faction', name: "Marks of Chaos Tzeentch", text: "Empyreal Guidance This operative’s ranged weapons have the Severe weapon rule." },
  { kind: 'faction', name: "Marks of Chaos Slaanesh", text: "Unnatural Agility Add 1\" to this operative’s Move stat." },
  { kind: 'faction', name: "Marks of Chaos Undivided", text: "Vicious Reavers Whenever this operative is shooting against, fighting against or retaliating against an enemy operative within 6\" of it, this operative’s weapons have the Ceaseless weapon rule." },
  { kind: 'faction', name: "Astartes", text: "During each friendly LEGIONARY operative’s activation, it can perform either two Shoot actions or two Fight actions. If it’s two Shoot actions, a bolt pistol, boltgun or tainted bolt pistol must be selected for at least one of them. Each friendly LEGIONARY operative can counteract regardless of its order." },
  { kind: 'strategy', name: "Blood for the Blood God", text: "Whenever a friendly LEGIONARY operative (excluding KHORNE) is fighting, the first time you strike during that sequence, inflict 1 additional damage (to a maximum of 7).\nAdd 1 to both Dmg stats of friendly LEGIONARY KHORNE operatives’ melee weapons (to a maximum of 7)." },
  { kind: 'strategy', name: "Implacable", text: "Whenever an operative is shooting a friendly LEGIONARY operative, weapons with the Piercing 1 weapon rule have the Piercing Crits 1 weapon rule instead.\nYou can ignore any changes to the stats of friendly LEGIONARY NURGLE operatives from being injured (including their weapons’ stats)." },
  { kind: 'strategy', name: "Quicksilver Speed", text: "Whenever a friendly LEGIONARY operative that performed an action in which it moved during this turning point is fighting, worsen the Hit stat of the enemy operative’s melee weapons by 1. Whenever an operative is shooting a friendly LEGIONARY SLAANESH operative more than 6\" from it that performed an action in which it moved during this turning point, worsen the Hit stat of the enemy operative’s weapons by 1. In all cases for this ploy, this isn’t cumulative with being injured." },
  { kind: 'firefight', name: "Unending Bloodshed", text: "Use this firefight ploy when a friendly LEGIONARY KHORNE operative is incapacitated while fighting or retaliating. You can strike the enemy operative in that sequence with one of your unresolved successes before it’s removed from the killzone." },
  { kind: 'strategy', name: "Fickle Fates", text: "Whenever a friendly LEGIONARY operative is shooting a ready enemy operative, that friendly operative’s ranged weapons have the Balanced weapon rule. Whenever an operative is shooting a ready friendly LEGIONARY TZEENTCH operative, in the Roll Defence Dice step, if you retain any critical successes, you can retain one of your fails as a normal success instead of discarding it." },
  { kind: 'firefight', name: "Mutability and Change", text: "Use this firefight ploy when a friendly LEGIONARY TZEENTCH operative is activated. Until the end of that operative’s activation, add 1 to its APL stat, but it cannot perform the same action more than once during that activation. If it’s a WARRIOR operative, that operative’s Marks of Chaos keyword cannot be changed during this turning point (see Infernal Pact additional rule)." },
  { kind: 'firefight', name: "Malignant Aura", text: "Use this firefight ploy when a friendly LEGIONARY NURGLE operative is performing the Shoot action, when you select a valid target. Until the end of that action, whenever that friendly operative is shooting an enemy operative within 3\" of it (i.e. including secondary targets, if any), that friendly operative’s ranged weapons have the Piercing 1 weapon rule." },
  { kind: 'equipment', name: "Warded Armour", text: "STRATEGIC GAMBIT. Select one friendly LEGIONARY operative. Until the Ready step of the next Strategy phase, change that operative’s Save stat to 2+." },
  { kind: 'firefight', name: "Sickening Captivation", text: "Use this firefight ploy during a friendly LEGIONARY SLAANESH operative’s activation, before or after it performs an action. Select one enemy operative visible to and within 4\" of that friendly operative. Until the end of that enemy operative’s next activation, subtract 1 from its APL stat." },
  { kind: 'equipment', name: "Tainted Rounds", text: "Once per turning point, when a friendly LEGIONARY operative is performing the Shoot action and you select a bolt pistol or boltgun, you can use this rule. If you do, until the end of that action, that weapon has the Rending weapon rule." },
  { kind: 'equipment', name: "Chaos Talismans", text: "STRATEGIC GAMBIT. Select one Marks of Chaos keyword. Once during each of their activations, when a friendly LEGIONARY operative that has that keyword is shooting, fighting or retaliating, if you roll two or more fails, you can inflict D3 damage on that friendly operative to discard one of them and retain the other as a normal success instead. Note that if it’s the Shoot action and that damage incapacitates that friendly operative, the action doesn’t end (continue the sequence with your successful attack dice)." },
  { kind: 'equipment', name: "Malefic Blades", text: "Friendly LEGIONARY operatives have the following melee weapon:\nNAME ATK HIT DMG\nMalefic blade 5 3+ 3/4" },
]

export const operatives: Operative[] = [
  { id: "legionaries:legionary-aspiring-champion", name: "Legionary Aspiring Champion", apl: 3, move: "6\"", save: "3+", w: 15 },
  { id: "legionaries:legionary-chosen", name: "Legionary Chosen", apl: 3, move: "6\"", save: "3+", w: 15 },
  { id: "legionaries:legionary-anointed", name: "Legionary Anointed", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "legionaries:legionary-balefire-acolyte", name: "Legionary Balefire Acolyte", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "legionaries:legionary-butcher", name: "Legionary Butcher", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "legionaries:legionary-gunner", name: "Legionary Gunner", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "legionaries:legionary-heavy-gunner", name: "Legionary Heavy Gunner", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "legionaries:legionary-icon-bearer", name: "Legionary Icon Bearer", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "legionaries:legionary-shrivetalon", name: "Legionary Shrivetalon", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "legionaries:legionary-warrior", name: "Legionary Warrior", apl: 3, move: "6\"", save: "3+", w: 14 },
]

export const datacards: Datacard[] = [
  {"name": "Legionary Aspiring Champion", "weapons": [{"name": "Plasma pistol (standard)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Piercing 1"}, {"name": "Plasma pistol (supercharge)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Hot, Lethal 5+, Piercing 1"}, {"name": "Tainted bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Rending"}, {"name": "Power fist", "atk": 5, "hit": "4+", "dmg": "5/7", "wr": "Brutal"}, {"name": "Power maul", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Shock"}, {"name": "Power weapon", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}, {"name": "Tainted chainsword", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Rending"}], "abilities": [{"name": "In the Eyes of the Gods", "text": "Once during each of this operative’s activations, if it incapacitates an enemy operative, add 1 to its APL stat until the end of that activation."}], "actions": [], "keywords": ["LEGIONARY", "CHAOS", "HERETIC ASTARTES", "LEADER", "ASPIRING CHAMPION"]},
  {"name": "Legionary Chosen", "weapons": [{"name": "Plasma pistol (standard)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Piercing 1"}, {"name": "Plasma pistol (supercharge)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Hot, Lethal 5+, Piercing 1"}, {"name": "Tainted bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Rending"}, {"name": "Daemon blade", "atk": 5, "hit": "3+", "dmg": "4/7", "wr": "Lethal 5+"}], "abilities": [{"name": "Daemonic Aura", "text": "Whenever an enemy operative performs the Fall Back action while within control range of this operative, you can use this rule. If you do, roll one D6: on a 3+, that enemy operative cannot perform that action during that activation/ counteraction (the AP spent on it is refunded)."}, {"name": "Soul Gorge", "text": "After this operative fights or retaliates, if it isn’t incapacitated, but it incapacitated an enemy operative during that sequence, it regains up to D3+1 lost wounds."}], "actions": [], "keywords": ["LEGIONARY", "CHAOS", "HERETIC ASTARTES", "LEADER", "CHOSEN"]},
  {"name": "Legionary Anointed", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Daemonic claw", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Rending"}], "abilities": [{"name": "Unleash Daemon", "text": "Once per battle, when this operative is activated, you can use this rule. If you do, until the end of the battle:\n• This operative cannot perform the Pick Up Marker or mission actions (excluding Operate Hatch). If it’s carrying a marker, it must immediately perform the Place Marker action for 0AP (this takes precedence over all other rules). • Normal and Critical Dmg of 4 or more inflicts 1 less damage on this operative. If this operative has the NURGLE keyword, you cannot reduce the damage of an attack dice by more than 1. In other words, you cannot use both rules to reduce Normal Dmg of 4 or more by 2. • Its daemonic claw has the Ceaseless and Lethal 5+ weapon rules."}], "actions": [], "keywords": ["LEGIONARY", "CHAOS", "HERETIC ASTARTES", "ANOINTED"]},
  {"name": "Legionary Balefire Acolyte", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Fireblast", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "PSYCHIC, Blast 2\", 1\" Devastating 1, Saturate"}, {"name": "Life siphon", "atk": 5, "hit": "3+", "dmg": "3/3", "wr": "PSYCHIC, Saturate, Siphon Life*"}, {"name": "Fell dagger", "atk": 5, "hit": "3+", "dmg": "3/4", "wr": "PSYCHIC, Rending, Siphon Life*"}], "abilities": [{"name": "Siphon Life", "text": "When you select this weapon, you can use this rule. If you do, at the start of the Resolve Attack Dice step, select one friendly LEGIONARY operative visible to and within 6\" of this operative. For each attack dice you resolve during that step that inflicts damage, that friendly operative regains 1 lost wound, or D3 lost wounds if it was a critical success. You cannot use this weapon rule more than once per turning point."}], "actions": [], "keywords": ["LEGIONARY", "CHAOS", "HERETIC ASTARTES", "PSYKER", "BALEFIRE ACOLYTE"]},
  {"name": "Legionary Butcher", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Double-handed chainaxe", "atk": 5, "hit": "4+", "dmg": "5/7", "wr": "Brutal"}], "abilities": [], "actions": [], "keywords": ["LEGIONARY", "CHAOS", "HERETIC ASTARTES", "BUTCHER"]},
  {"name": "Legionary Gunner", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Flamer", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 8\", Saturate, Torrent 2\""}, {"name": "Meltagun", "atk": 4, "hit": "3+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Plasma gun (standard)", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Piercing 1"}, {"name": "Plasma gun (supercharge)", "atk": 4, "hit": "3+", "dmg": "5/6", "wr": "Hot, Lethal 5+, Piercing 1"}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["LEGIONARY", "CHAOS", "HERETIC ASTARTES", "GUNNER"]},
  {"name": "Legionary Heavy Gunner", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Heavy bolter (focused)", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Heavy (Reposition only), Piercing Crits 1"}, {"name": "Heavy bolter (sweeping)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Heavy (Reposition only), Piercing Crits 1, Torrent 1\""}, {"name": "Missile launcher (frag)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Blast 2\", Heavy (Reposition only)"}, {"name": "Missile launcher (krak)", "atk": 4, "hit": "3+", "dmg": "5/7", "wr": "Heavy (Reposition only), Piercing 1"}, {"name": "Reaper chaincannon (focused)", "atk": 5, "hit": "3+", "dmg": "3/4", "wr": "Ceaseless, Heavy (Reposition only), Punishing"}, {"name": "Reaper chaincannon (sweeping)", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Ceaseless, Heavy (Reposition only), Punishing, Torrent 2\""}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["LEGIONARY", "CHAOS", "HERETIC ASTARTES", "HEAVY GUNNER"]},
  {"name": "Legionary Icon Bearer", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Boltgun", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Chainsword", "atk": 5, "hit": "3+", "dmg": "4/5"}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [{"name": "Icon Bearer", "text": "Whenever determining control of a marker, treat this operative’s APL stat as 1 higher. Note this isn’t a change to its APL stat, so any changes are cumulative with this."}, {"name": "Favoured of the Dark Gods", "text": "In the Ready step of each Strategy phase, if this operative controls an objective marker that isn’t tainted, that objective marker is tainted for the battle and you gain 1CP. Note that if any operative (including enemy operatives) has tainted an objective marker, you cannot taint that objective marker."}], "actions": [], "keywords": ["LEGIONARY", "CHAOS", "HERETIC ASTARTES", "ICON BEARER"]},
  {"name": "Legionary Shrivetalon", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Flensing blades", "atk": 5, "hit": "3+", "dmg": "3/5", "wr": "Lethal 5+"}], "abilities": [{"name": "Vicious Reflexes", "text": "Whenever this operative is retaliating, you resolve the first attack dice (i.e. defender instead of attacker)."}, {"name": "Horrifying Dismemberment", "text": "Whenever this operative incapacitates an enemy operative while fighting or retaliating, select one other enemy operative visible to and within 3\" of either this operative or the incapacitated enemy operative. Subtract 1 from that enemy operative’s APL stat until the end of its next activation."}], "actions": [{"name": "Grisly Mark", "ap": 2, "text": "Place your Grisly marker within this operative’s control range.\n• Whenever an enemy operative is within 3\" of your Grisly marker, your opponent must spend 1 additional AP for that enemy operative to perform the Pick Up Marker and mission actions. • Whenever determining control of a marker, treat the total APL stat of enemy operatives that contest it as 1 lower if at least one of those enemy operatives is within 3\" of your Grisly marker. Note this isn’t a change to the APL stat, so any changes are cumulative with this.\nThis operative cannot perform this action more than once per battle, and cannot perform it while within control range of an enemy operative."}], "keywords": ["LEGIONARY", "CHAOS", "HERETIC ASTARTES", "SHRIVETALON"]},
  {"name": "Legionary Warrior", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Boltgun", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Chainsword", "atk": 5, "hit": "3+", "dmg": "4/5"}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [{"name": "Infernal Pact", "text": "Once per battle, when a friendly LEGIONARY WARRIOR operative is activated, you can use this rule. If you do, change that operative’s Marks of Chaos keyword."}], "actions": [], "keywords": ["LEGIONARY", "CHAOS", "HERETIC ASTARTES", "WARRIOR"]},
]
