// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Shadow Passage", text: "Once per turning point, one friendly MANDRAKE operative WITHIN SHADOW can use a SHADOW PASSAGE when it performs the Reposition action. If it does, don’t move it. Instead, remove it from the killzone and set it back up WITHIN SHADOW in a location it can be placed. When you set it back up, it cannot:\n• Be within control range of an enemy operative.\n• Be a valid target for an enemy operative.\n• Perform the Shoot or Fight action until the start of the next turning point." },
  { kind: 'faction', name: "Soulstrike", text: "Each result that’s equal to or less than the target’s APL stat is a success and is retained. Each result that’s higher than the target’s APL stat is a fail and is discarded. Each result of 1 is always a critical success. Each other success is a normal success. Each result of 6 is always a fail. Designer’s Note: Many of this kill team’s rules refer to an enemy operative’s APL stat. This would be the APL stat at the time the rule takes effect (i.e. including changes)." },
  { kind: 'faction', name: "Umbral Entities", text: "Whenever an operative is shooting a friendly MANDRAKE operative, ignore the Piercing weapon rule. Whenever a friendly MANDRAKE operative is WITHIN SHADOW, improve its Save stat by 1." },
  { kind: 'faction', name: "Within Shadow", text: "An operative is WITHIN SHADOW if any of the following are true:\n• It’s within 1\" of Heavy terrain that’s not lower than it.\n• Any part of its base is underneath Vantage terrain.\n• A Shadow Portal marker is within its control range (see SHADEWEAVER)." },
  { kind: 'strategy', name: "Creeping Horror", text: "After each enemy operative’s activation, before the next operative is activated, one friendly MANDRAKE operative that has a Conceal order can perform a free Dash action if it starts and ends that action WITHIN SHADOW. You cannot use this ploy during the first turning point, and you cannot select each friendly operative for this ploy more than once per turning point." },
  { kind: 'strategy', name: "Gloaming Shroud", text: "Whenever an operative is shooting a friendly MANDRAKE operative that’s WITHIN SHADOW, you can retain one of your defence dice as a normal success without rolling it (in addition to a cover save, if any)." },
  { kind: 'strategy', name: "Blade in the Dark", text: "Each friendly MANDRAKE operative can perform the Charge action while it has a Conceal order if it starts or ends that action WITHIN SHADOW." },
  { kind: 'firefight', name: "Slither Out of Sight", text: "Use this firefight ploy at the end of any operative’s activation. Select one friendly MANDRAKE operative that has an Engage order and is WITHIN SHADOW. Change that operative’s order to Conceal." },
  { kind: 'strategy', name: "Inescapable Nightmare", text: "Whenever a friendly MANDRAKE operative is shooting, fighting or retaliating, if it’s WITHIN SHADOW, you can re-roll one of your attack dice." },
  { kind: 'firefight', name: "Soul Feast", text: "Use this firefight ploy when a friendly MANDRAKE operative is shooting against, fighting against or retaliating against an enemy operative within 6\" of it, at the end of the Resolve Attack Dice step. That friendly operative regains a number of lost wounds equal to that enemy operative’s APL stat, multiplied by the number of your attack dice that inflicted damage during that sequence. Excess attack dice are ignored (i.e. if the enemy operative is incapacitated before remaining attack dice are resolved). You cannot use this ploy if that friendly MANDRAKE operative is incapacitated." },
  { kind: 'firefight', name: "Nowhere to Hide", text: "Use this firefight ploy during a friendly MANDRAKE operative’s activation, when it performs an action in which it moves. Until the end of that activation, that operative can move through parts of terrain features as if they weren’t there, but it cannot move more than its Move stat if it’s the Charge action and must end those moves in a location it can be placed." },
  { kind: 'equipment', name: "Chain Snare", text: "Whenever an enemy operative would perform the Fall Back action while within control range of a friendly MANDRAKE operative, if no other enemy operatives are within that friendly operative’s control range, you can use this rule. If you do, roll two D6, or one D6 if that enemy operative has a higher Wounds stat than that friendly operative. If any result is a 4+, that enemy operative cannot perform that action during that activation/counteraction (no AP are spent on it), and you cannot use this rule again during this turning point." },
  { kind: 'firefight', name: "Shadow’s Bite", text: "Use this firefight ploy when an enemy operative performs the Fight action during an activation in which it performed the Charge action, and selects a friendly MANDRAKE operative WITHIN SHADOW to fight against. In the Resolve Attack Dice step of that sequence, you resolve the first attack dice (i.e. defender instead of attacker)." },
  { kind: 'equipment', name: "Shadow Glyph", text: "Once per turning point, when a friendly MANDRAKE operative is activated WITHIN SHADOW, you can use this rule. If you do, until the start of its next activation, while that operative has a Conceal order and is in cover, it cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2\"." },
  { kind: 'equipment', name: "Soul Gem", text: "Once per turning point, when a friendly MANDRAKE operative is performing the Shoot action and you select a baleblast, you can use this rule. If you do, until the end of that action, that weapon has the Blast 1\" weapon rule." },
  { kind: 'equipment', name: "Bone Darts", text: "Once per turning point, a friendly MANDRAKE operative can use the following ranged weapon — Bone dart: ATK 4, HIT 3+, DMG 2/4. WR Range 6\", Rending, Silent." },
]

export const operatives: Operative[] = [
  { id: "mandrakes:mandrake-nightfiend", name: "Mandrake Nightfiend", apl: 2, move: "7\"", save: "5+", w: 9 },
  { id: "mandrakes:mandrake-abyssal", name: "Mandrake Abyssal", apl: 2, move: "7\"", save: "5+", w: 8 },
  { id: "mandrakes:mandrake-chooser-of-the-flesh", name: "Mandrake Chooser of the Flesh", apl: 2, move: "7\"", save: "5+", w: 8 },
  { id: "mandrakes:mandrake-dirgemaw", name: "Mandrake Dirgemaw", apl: 2, move: "7\"", save: "5+", w: 8 },
  { id: "mandrakes:mandrake-shadeweaver", name: "Mandrake Shadeweaver", apl: 2, move: "7\"", save: "5+", w: 8 },
  { id: "mandrakes:mandrake-warrior", name: "Mandrake Warrior", apl: 2, move: "7\"", save: "5+", w: 8 },
]
