// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Shadow Passage", text: "Once per turning point, one friendly MANDRAKE operative WITHIN SHADOW can use a SHADOW PASSAGE when it performs the Reposition action. If it does, don’t move it. Instead, remove it from the killzone and set it back up WITHIN SHADOW in a location it can be placed. When you set it back up, it cannot:\n• Be within control range of an enemy operative.\n• Be a valid target for an enemy operative.\n• Perform the Shoot or Fight action until the start of the next turning point." },
  { kind: 'faction', name: "Soulstrike", text: "Each result that’s equal to or less than the target’s APL stat is a success and is retained. Each result that’s higher than the target’s APL stat is a fail and is discarded. Each result of 1 is always a critical success. Each other success is a normal success. Each result of 6 is always a fail. Designer’s Note: Many of this kill team’s rules refer to an enemy operative’s APL stat. This would be the APL stat at the time the rule takes effect (i.e. including changes)." },
  { kind: 'faction', name: "Umbral Entities", text: "Whenever an operative is shooting a friendly MANDRAKE operative, ignore the Piercing weapon rule. Whenever a friendly MANDRAKE operative is WITHIN SHADOW, improve its Save stat by 1." },
  { kind: 'faction', name: "Within Shadow", text: "An operative is WITHIN SHADOW if any of the following are true:\n• It’s within 1\" of Heavy terrain that’s not lower than it.\n• Any part of its base is underneath Vantage terrain.\n• A Shadow Portal marker is within its control range (see SHADEWEAVER)." },
  { kind: 'strategy', name: "Creeping Horror", text: "After each enemy operative’s activation, before the next operative is activated, one friendly MANDRAKE operative that has a Conceal order can perform a free Dash action if it starts and ends that action WITHIN SHADOW. You cannot use this ploy during the first turning point, and you cannot select each friendly operative for this ploy more than once per turning point." },
  { kind: 'strategy', name: "Gloaming Shroud", text: "Whenever an operative is shooting a friendly MANDRAKE operative that’s WITHIN SHADOW, you can retain one of your defence dice as a normal success without rolling it (in addition to a cover save, if any)." },
  { kind: 'strategy', name: "Blade in the Dark", text: "Each friendly MANDRAKE operative can perform the Charge action while it has a Conceal order if it starts or ends that action WITHIN SHADOW." },
  { kind: 'firefight', name: "Slither Out of Sight", text: "Use this firefight ploy at the end of any operative’s activation. Select one friendly MANDRAKE operative that has an Engage order and is WITHIN SHADOW. Change that operative’s order to Conceal." },
  { kind: 'strategy', name: "Inescapable Nightmare", text: "Whenever a friendly MANDRAKE operative is shooting, fighting or retaliating, if it’s WITHIN SHADOW, you can re-roll one of your attack dice." },
  { kind: 'firefight', name: "Soul Feast", text: "Use this firefight ploy when a friendly MANDRAKE operative is shooting against, fighting against or retaliating against an enemy operative within 6\" of it, at the end of the Resolve Attack Dice step. That friendly operative regains a number of lost wounds equal to that enemy operative’s APL stat, multiplied by the number of your attack dice that inflicted damage during that sequence. Excess attack dice are ignored (i.e. if the enemy operative is incapacitated before remaining attack dice are resolved). You cannot use this ploy if that friendly MANDRAKE operative is incapacitated." },
  { kind: 'firefight', name: "Nowhere to Hide", text: "Use this firefight ploy during a friendly MANDRAKE operative’s activation, when it performs an action in which it moves. Until the end of that activation, that operative can move through parts of terrain features as if they weren’t there, but it cannot move more than its Move stat if it’s the Charge action and must end those moves in a location it can be placed." },
  { kind: 'equipment', name: "Chain Snare", text: "Whenever an enemy operative would perform the Fall Back action while within control range of a friendly MANDRAKE operative, if no other enemy operatives are within that friendly operative’s control range, you can use this rule. If you do, roll two D6, or one D6 if that enemy operative has a higher Wounds stat than that friendly operative. If any result is a 4+, that enemy operative cannot perform that action during that activation/counteraction (no AP are spent on it), and you cannot use this rule again during this turning point." },
  { kind: 'firefight', name: "Shadow’s Bite", text: "Use this firefight ploy when an enemy operative performs the Fight action during an activation in which it performed the Charge action, and selects a friendly MANDRAKE operative WITHIN SHADOW to fight against. In the Resolve Attack Dice step of that sequence, you resolve the first attack dice (i.e. defender instead of attacker)." },
  { kind: 'equipment', name: "Shadow Glyph", text: "Once per turning point, when a friendly MANDRAKE operative is activated WITHIN SHADOW, you can use this rule. If you do, until the start of its next activation, while that operative has a Conceal order and is in cover, it cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2\"." },
  { kind: 'equipment', name: "Soul Gem", text: "Once per turning point, when a friendly MANDRAKE operative is performing the Shoot action and you select a baleblast, you can use this rule. If you do, until the end of that action, that weapon has the Blast 1\" weapon rule." },
  { kind: 'equipment', name: "Bone Darts", text: "Once per turning point, a friendly MANDRAKE operative can use the following ranged weapon — Bone dart: ATK 4, HIT 3+, DMG 2/4. WR Range 6\", Rending, Silent." },
]

export const operatives: Operative[] = [
  { id: "mandrakes:mandrake-nightfiend", name: "Mandrake Nightfiend", apl: 2, move: "7\"", save: "5+", w: 9 },
  { id: "mandrakes:mandrake-abyssal", name: "Mandrake Abyssal", apl: 2, move: "7\"", save: "5+", w: 8 },
  { id: "mandrakes:mandrake-chooser-of-the-flesh", name: "Mandrake Chooser of the Flesh", apl: 2, move: "7\"", save: "5+", w: 8 },
  { id: "mandrakes:mandrake-dirgemaw", name: "Mandrake Dirgemaw", apl: 2, move: "7\"", save: "5+", w: 8 },
  { id: "mandrakes:mandrake-shadeweaver", name: "Mandrake Shadeweaver", apl: 2, move: "7\"", save: "5+", w: 8 },
  { id: "mandrakes:mandrake-warrior", name: "Mandrake Warrior", apl: 2, move: "7\"", save: "5+", w: 8 },
]

export const datacards: Datacard[] = [
  {"name": "Mandrake Nightfiend", "weapons": [{"name": "Baleblast", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Soulstrike*"}, {"name": "Huskblade", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+, Shock"}], "abilities": [{"name": "Harrowing Whispers", "text": "Whenever your opponent would activate an enemy operative within 6\" of this operative, you can roll one D6 (you cannot do so if you already interrupted that operative’s activation with this rule or the DIRGEMAW operative’s Haunting Focus additional rule during this turning point): if the result is higher than that enemy operative’s APL stat, your opponent cannot activate it during this activation. If there are no other enemy operatives eligible to be activated, this rule has no effect."}, {"name": "Oubliex", "text": "Whenever this operative is readied, or if this operative incapacitates an enemy operative with its huskblade, its oubliex becomes active. Whenever its oubliex is active and an attack dice would inflict damage on this operative, you can roll one D6: on a 5+, ignore the damage inflicted from that attack dice and its oubliex is no longer active."}], "actions": [], "keywords": ["MANDRAKE", "AELDARI", "DRUKHARI", "LEADER", "NIGHTFIEND"], "img": "/ops/mandrakes/mandrake-nightfiend.webp"},
  {"name": "Mandrake Abyssal", "weapons": [{"name": "Balesurge (blast)", "atk": 5, "hit": "3+", "dmg": "3/4", "wr": "Blast 2\", Soulstrike*"}, {"name": "Balesurge (burn)", "atk": 5, "hit": "3+", "dmg": "3/4", "wr": "Lethal 5+, Soulstrike*"}, {"name": "Glimmersteel blade", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Lethal 5+"}], "abilities": [{"name": "Balefire", "text": "Whenever a friendly MANDRAKE operative is shooting an enemy operative that has one of your Balefire tokens, add 1 to both Dmg stats of that friendly operative’s ranged weapons, and those weapons have the Saturate weapon rule. Whenever an operative is shooting a friendly MANDRAKE operative that has one of your Balefire tokens, subtract 1 from both Dmg stats of that operative’s ranged weapons (to a minimum of 1)."}], "actions": [{"name": "Wreathe in Balefire", "ap": 1, "text": "Select one operative visible to this operative that doesn’t have one of your Balefire tokens. Until the start of this operative’s next activation, until it’s incapacitated or until it performs this action again (whichever comes first), that selected operative gains one of your Balefire tokens.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["MANDRAKE", "AELDARI", "DRUKHARI", "ABYSSAL"], "img": "/ops/mandrakes/mandrake-abyssal.webp"},
  {"name": "Mandrake Chooser of the Flesh", "weapons": [{"name": "Baleblast", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Soulstrike*"}, {"name": "Baleblade", "atk": 4, "hit": "3+", "dmg": "5/6", "wr": "Brutal, Lethal 5+"}], "abilities": [{"name": "Soul Harvest", "text": "Whenever an enemy operative is incapacitated as a result of this operative’s Part Collector rule or baleblade, you gain 1 Soul Harvest point, or two if that enemy operative had an APL stat of 3 or more. Whenever a friendly MANDRAKE operative is activated, you can spend 1 of your Soul Harvest points to either add 1 to its APL stat until the end of the battle, or have it regain up to 2D3 lost wounds. Note you can spend your Soul Harvest points even if this operative is incapacitated."}, {"name": "Part Collector", "text": "Whenever an enemy operative performs the Fall Back action while within control range of this operative, you can use this rule. If you do, inflict 2D3 damage on that enemy operative before it moves."}], "actions": [], "keywords": ["MANDRAKE", "AELDARI", "DRUKHARI", "CHOOSER OF THE FLESH"], "img": "/ops/mandrakes/mandrake-chooser-of-the-flesh.webp"},
  {"name": "Mandrake Dirgemaw", "weapons": [{"name": "Baleblast", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Soulstrike*"}, {"name": "Horrifying scream", "atk": 5, "hit": "2+", "dmg": "2/2", "wr": "Range 6\", Devastating 2, Seek Light, Stun, Soulstrike*"}, {"name": "Glimmersteel blade", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Lethal 5+"}], "abilities": [{"name": "Haunting Focus", "text": "STRATEGIC GAMBIT. Select one enemy operative. Until the Ready step of the next Strategy phase, it gains your Haunting Focus token. The next time your opponent would activate an enemy operative that has your Haunting Focus token, if this operative is ready, you can activate this operative first (you cannot do so if you also rolled to prevent that operative’s activation with the NIGHTFIEND operative’s Harrowing Whispers additional rule during this turning point). If you do, during that activation, this operative must shoot against or fight against that enemy operative, and cannot do so against any other enemy operatives until it does (if this isn’t possible, this operative’s activation is cancelled). After completing this operative’s activation, your opponent activates that enemy operative (if possible), or activates a different enemy operative if they can’t."}], "actions": [{"name": "Pareidolic Projection", "ap": 1, "text": "Select one enemy operative that’s a valid target for this operative or is WITHIN SHADOW. Until the start of this operative’s next activation, until it’s incapacitated or until it performs this action again (whichever comes first), worsen the Hit stat of that enemy operative’s weapons by 1 and subtract 2\" from its Move stat (these aren’t cumulative with being injured).\nThis operative cannot perform this action while within control range of an enemy operative, unless the only enemy operative it’s within control range of is selected for this action."}], "keywords": ["MANDRAKE", "AELDARI", "DRUKHARI", "DIRGEMAW"], "img": "/ops/mandrakes/mandrake-dirgemaw.webp"},
  {"name": "Mandrake Shadeweaver", "weapons": [{"name": "Baleblast", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Soulstrike*"}, {"name": "Glimmersteel blade", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Lethal 5+"}], "abilities": [{"name": "Shadow Portal", "text": "Whenever this operative performs the Reposition action using a SHADOW PASSAGE, you can use this rule. If you do, remove your Shadow Portal markers from the killzone (if any), then place one of your Shadow Portal markers within this operative’s control range before it’s removed and one within its control range after it’s set up.\nEach friendly MANDRAKE operative can use a SHADOW PASSAGE each turning point (this takes precedence over one operative once per turning point) if one of your Shadow Portal markers is within that operative’s control range when it’s removed, and the other is when it’s set up. Note that friendly operatives can do so even if this operative has been incapacitated, and doing so doesn’t prevent one operative from using a SHADOW PASSAGE in the normal manner."}], "actions": [{"name": "Weave Darkness", "ap": 1, "text": "Remove your Weave Darkness marker from the killzone (if any). Then place your Weave Darkness marker visible to this operative, or on Vantage terrain of a terrain feature visible to this operative. That marker creates an area of smoke with the same size and effects as a smoke grenade (see universal equipment), except you don’t remove it during the following turning point. If this operative is incapacitated, remove your Weave Darkness marker from the killzone.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["MANDRAKE", "AELDARI", "DRUKHARI", "SHADEWEAVER"], "img": "/ops/mandrakes/mandrake-shadeweaver.webp"},
  {"name": "Mandrake Warrior", "weapons": [{"name": "Baleblast", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Soulstrike*"}, {"name": "Glimmersteel blade", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Lethal 5+"}], "abilities": [{"name": "Shadow Warrior", "text": "Whenever this operative is WITHIN SHADOW, add 1 to the Critical Dmg stat of its glimmersteel blade."}], "actions": [], "keywords": ["MANDRAKE", "AELDARI", "DRUKHARI", "WARRIOR"], "img": "/ops/mandrakes/mandrake-warrior.webp"},
]
