// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Jump Pack", text: "Whenever a friendly MURDERWING operative is performing the Charge, Fall Back or Reposition action during its activation, at the start of any straight-line increment, as long as no part of its base is underneath Vantage terrain, it can do a BOOST for that increment. If it does, don’t move it for that increment. Instead, remove it from the killzone and set it back up wholly within x\" horizontally of its original location. X is a distance of your choice (rounded up to the nearest inch, as per the Reposition action), but it’s added to the total move distance used for that action (in other words, move plus BOOST cannot exceed the action’s move allowance). If it would BOOST during the Charge action, its move allowance cannot be higher than 6\"." },
  { kind: 'faction', name: "Jump Pack Example", text: "In this example, the MURDERWING operative (A) does a BOOST for the second increment of movement. It moves as normal during the first and third increments, as it cannot BOOST from or to a location underneath Vantage terrain.\n1\" MOVE\n4\" B OO ST\n1\" MOVE" },
  { kind: 'faction', name: "Boost Actions Example", text: "In this example, the top operative (C) is within the MURDERWING operative’s (A) BOOST ZONE. The bottom operative (B) is not, as its base is underneath Vantage terrain." },
  { kind: 'faction', name: "Boost Actions", text: "Some actions are known as BOOST actions. These are actions performed during other actions when a BOOST is used. Each operative cannot perform more than one BOOST action per activation. Most BOOST actions affect enemy operatives within a friendly MURDERWING operative’s\nBOOST ZONE. This is the horizontal area between a friendly MURDERWING operative’s current location and the location from which it used BOOST. A marker the same size as the operative’s base can be temporarily placed to help determine this. Enemy operatives with any part of their base underneath Vantage terrain are not within friendly MURDERWING operatives’ BOOST ZONEs." },
  { kind: 'faction', name: "Astartes", text: "During each friendly MURDERWING operative’s activation, it can perform either two Shoot actions or two Fight actions. If it’s two Shoot actions, a bolt pistol must be selected for at least one of them. Each friendly MURDERWING operative can counteract regardless of its order." },
  { kind: 'strategy', name: "Cull the Weak", text: "Whenever a friendly MURDERWING operative is shooting or fighting, its weapons have the Punishing weapon rule if any of the following are true for the operative that friendly operative is shooting or fighting against:\n• It’s at least 2\" lower than that friendly operative.\n• Its APL stat is less than normal.\n• It was wounded at the start of the activation/counteraction." },
  { kind: 'strategy', name: "Predators Above", text: "Whenever a friendly MURDERWING operative is at least 2\" higher than the killzone floor, its weapons have the Balanced weapon rule. Whenever a friendly MURDERWING operative does a BOOST, its weapons have the Balanced weapon rule until the end of that activation." },
  { kind: 'strategy', name: "Nightmare on High", text: "Whenever an operative is shooting a friendly MURDERWING operative that’s at least 2\" higher than the killzone floor, or that did a BOOST during this turning point, you can re-roll one of your defence dice." },
  { kind: 'strategy', name: "Instil Fear", text: "Whenever a friendly MURDERWING operative is fighting, Normal Dmg of 3 or more inflicts 1 less damage on it." },
  { kind: 'firefight', name: "Murderous Descent", text: "Use this firefight ploy when an enemy operative ends the Charge, Dash, Fall Back or Reposition action within 3\" horizontally and more than 2\" lower than a friendly MURDERWING operative (or in close quarters, within 2\" and that enemy operative must be in a different room to where it started that action). Interrupt that enemy operative’s activation/counteraction and immediately perform a free Charge action with that friendly operative. It must end that action within control range of that enemy operative. If this isn’t possible, the interruption is cancelled and this rule hasn’t been used." },
  { kind: 'firefight', name: "Malicious Narcissism", text: "Use this firefight ploy when it’s your turn to activate with a friendly operative, if only one friendly MURDERWING operative is ready. Until the end of the turning point, whenever you have less ready friendly operatives than your opponent, you can skip your activations (in other words, you can delay that friendly MURDERWING operative’s activation until your opponent has only one ready operative). Note that you cannot counteract until that friendly MURDERWING operative is expended." },
  { kind: 'firefight', name: "Long Forgotten Honour", text: "Use this firefight ploy when a friendly MURDERWING operative is fighting or retaliating, when you resolve a critical success. Instead of striking or blocking, end that sequence (any remaining attack dice are discarded) and immediately perform a free Fall Back action up to 3\" with that operative (then the Fight action ends). That operative can do so even if it’s performed an action that prevents it from performing the Fall Back action." },
  { kind: 'firefight', name: "Wings of Darkness", text: "Use this firefight ploy when a friendly MURDERWING operative is performing the Fall Back or Reposition action, when it does a BOOST. That operative can be set up an additional 3\" away during that BOOST (adding this to the permitted move distance), but it cannot perform the Shoot, Fight or Carving Blow (see DEPREDATOR operative) action until the next turning point. You cannot use this ploy during the first turning point." },
  { kind: 'equipment', name: "Clawed Armour", text: "Friendly MURDERWING operatives can perform the following unique action:\nCLAWED CHARGE (0AP): BOOST action. Inflict 1 damage on one enemy operative within this operative’s control range, then the Charge action ends.\nAn operative cannot perform this action normally. Instead, it performs this action during the Charge action after setting up from a BOOST." },
  { kind: 'equipment', name: "Bladefins", text: "Friendly MURDERWING operatives can perform the following unique action:\nSLICE FROM ABOVE (1AP): BOOST action. Inflict D3+1 damage on one enemy operative within this operative’s BOOST ZONE.\nAn operative cannot perform this action normally. Instead it performs this action during the Fall Back or Reposition action after setting up from a BOOST." },
  { kind: 'equipment', name: "Warp Fuel", text: "Once per turning point, when an enemy operative ends the Fall Back action during its activation, if at least one friendly MURDERWING operative was within its control range at the start of that action, you can use this rule. One of those friendly operatives can immediately perform a free Reposition or Charge action, but cannot use more than 3\" of move distance. Note that if the enemy operative doesn’t perform the Fall Back action during its own activation, this has no effect." },
  { kind: 'equipment', name: "Vox-casters", text: "Once per turning point, one friendly MURDERWING operative can perform the following unique action:\nVOX-CRY (1AP): Each enemy operative within 2\" of this operative takes a stun test. For an operative to take a stun test, roll one D6: on a 3+, subtract 1 from its APL stat until the end of its next activation. An operative cannot perform this action while it has a Conceal order." },
]

export const operatives: Operative[] = [
  { id: "murderwing:murderwing-chaos-lord", name: "Murderwing Chaos Lord", apl: 3, move: "6\"", save: "3+", w: 15 },
  { id: "murderwing:murderwing-champion", name: "Murderwing Champion", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "murderwing:murderwing-curseclaw", name: "Murderwing Curseclaw", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "murderwing:murderwing-depredator", name: "Murderwing Depredator", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "murderwing:murderwing-huntmaster", name: "Murderwing Huntmaster", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "murderwing:murderwing-raptor", name: "Murderwing Raptor", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "murderwing:murderwing-shrieker", name: "Murderwing Shrieker", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "murderwing:murderwing-skysear", name: "Murderwing Skysear", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "murderwing:murderwing-warp-talon", name: "Murderwing Warp Talon", apl: 3, move: "6\"", save: "3+", w: 14 },
]
