// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Astartes", text: "During each friendly NEMESIS CLAW operative’s activation, it can perform either two Shoot actions or two Fight actions. If it’s two Shoot actions, a bolt pistol, boltgun or scoped bolt pistol must be selected for at least one of them.\nEach friendly NEMESIS CLAW operative can counteract regardless of its order." },
  { kind: 'faction', name: "In Midnight Clad", text: "Whenever an enemy operative is shooting a friendly NEMESIS CLAW operative, that friendly operative is obscured if both of the following are true:\n• It’s more than 8\" from enemy operatives it’s visible to.\n• It’s within 1\" of Heavy terrain that’s not lower than it, or any part of its base is underneath Vantage terrain." },
  { kind: 'strategy', name: "The Black Hunt", text: "Whenever a friendly NEMESIS CLAW operative is shooting against, fighting against or retaliating against a wounded enemy operative, you can re-roll one of your attack dice." },
  { kind: 'strategy', name: "We Have Come for You", text: "Whenever a friendly NEMESIS CLAW operative is activated, if the first action it performs during that activation is the Charge action, when it ends its move during that action, you can inflict D3 damage on one enemy operative within its control range." },
  { kind: 'strategy', name: "Preysight", text: "Whenever a friendly NEMESIS CLAW operative performs the Shoot action, you can use this rule. If you do, until the end of that action, that friendly operative’s ranged weapons have the Range 6\" and Seek Light weapon rules." },
  { kind: 'strategy', name: "Return to Darkness", text: "One friendly NEMESIS CLAW operative can immediately perform a free Fall Back or Reposition action, but it must end that move with Heavy terrain within its control range, or any part of its base underneath Vantage terrain. In addition, it cannot move more than 4\" during that action and it cannot end that move closer to enemy operatives (in a killzone that uses the close quarters rules, e.g. Killzone: Tomb World, ignore Wall terrain when determining this)." },
  { kind: 'firefight', name: "Death to the False Emperor", text: "Use this firefight ploy after rolling your attack dice for a friendly NEMESIS CLAW operative, if it’s shooting against, fighting against or retaliating against an enemy operative that has the IMPERIUM keyword. That friendly operative’s weapons have the Ceaseless weapon rule until the end of that sequence; if that enemy operative also has the ADEPTUS ASTARTES keyword, that friendly operative’s weapons have the Relentless weapon rule until the end of that sequence instead." },
  { kind: 'firefight', name: "Vox Scream", text: "Use this firefight ploy when your opponent would activate an enemy operative that’s visible to a friendly NEMESIS CLAW operative. Roll one D6; if the result is higher than that enemy operative’s APL stat, your opponent cannot activate it during this activation; if the result is less than or equal to that enemy operative’s APL stat, this ploy isn’t used, the CP spent on it is refunded and you cannot use this ploy again during this turning point. If there are no other enemy operatives eligible to be activated, this ploy has no effect." },
  { kind: 'firefight', name: "Proclivity for Murder", text: "Use this firefight ploy after a friendly NEMESIS CLAW operative incapacitates an enemy operative within its control range. That friendly operative can immediately perform a free Charge or Dash action (for the former, it cannot move more than 3\"), even if it’s performed an action that prevents it from performing those actions." },
  { kind: 'firefight', name: "Dirty Fighter", text: "Use this firefight ploy when a friendly NEMESIS CLAW operative is retaliating, at the start of the Resolve Attack Dice step. You can resolve one of your successes before the normal order. If you do, you cannot resolve any other successes during that sequence." },
  { kind: 'equipment', name: "Chain Snare", text: "Whenever an enemy operative would perform the Fall Back action while within control range of a friendly NEMESIS CLAW operative, if no other enemy operatives are within that friendly operative’s control range, you can use this rule. If you do, roll two D6, or one D6 if that enemy operative has a higher Wounds stat than that friendly operative. If any result is a 4+, that enemy operative cannot perform that action during that activation/counteraction (no AP are spent on it), and you cannot use this rule again during this turning point." },
  { kind: 'equipment', name: "Flayed Skin", text: "Whenever an enemy operative is shooting against, fighting against or retaliating against a friendly NEMESIS CLAW operative within 2\" of it, your opponent cannot re-roll their attack dice results of 1." },
  { kind: 'equipment', name: "Grisly Trophy", text: "Once per battle, when a friendly NEMESIS CLAW operative incapacitates an enemy operative within 2\" of it, you can use this rule. If you do, that friendly operative gains one of your Grisly Trophy tokens (if it doesn’t already have one). Whenever a friendly NEMESIS CLAW operative that has one of your Grisly Trophy tokens is visible to and within 2\" of an enemy operative, subtract 1 from the Atk stat of that enemy operative’s weapons." },
  { kind: 'equipment', name: "Comms Jammers", text: "Whenever an enemy operative is within 3\" of a friendly NEMESIS CLAW operative, that enemy operative’s APL stat cannot be added to. Note that this doesn’t affect APL stats that have already been changed." },
]

export const operatives: Operative[] = [
  { id: "nemesis-claw:night-lord-visionary", name: "Night Lord Visionary", apl: 3, move: "6\"", save: "3+", w: 15 },
  { id: "nemesis-claw:night-lord-fearmonger", name: "Night Lord Fearmonger", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "nemesis-claw:night-lord-gunner", name: "Night Lord Gunner", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "nemesis-claw:night-lord-heavy-gunner", name: "Night Lord Heavy Gunner", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "nemesis-claw:night-lord-screecher", name: "Night Lord Screecher", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "nemesis-claw:night-lord-skinthief", name: "Night Lord Skinthief", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "nemesis-claw:night-lord-ventrilokar", name: "Night Lord Ventrilokar", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "nemesis-claw:night-lord-warrior", name: "Night Lord Warrior", apl: 3, move: "6\"", save: "3+", w: 14 },
]

export const datacards: Datacard[] = [
  {"name": "Night Lord Visionary", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Plasma pistol (standard)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Piercing 1"}, {"name": "Plasma pistol (supercharge)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Hot, Lethal 5+, Piercing 1"}, {"name": "Nostraman chainblade", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Rending"}, {"name": "Power fist", "atk": 5, "hit": "4+", "dmg": "5/7", "wr": "Brutal"}, {"name": "Power maul", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Shock"}, {"name": "Power weapon", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Prescience", "text": "PSYCHIC. In the Ready step of each Strategy phase, you gain D3 Prescience points. At the end of each turning point, discard your Prescience points. You can spend your Prescience points in the Firefight phase as follows (you cannot use each of the following rules more than once per turning point):\n• Foreboding: PSYCHIC. Whenever it’s your turn to activate a friendly operative, you can spend 1 of your Prescience points to skip that activation. • Portent: PSYCHIC. Whenever an attack dice inflicts Normal Dmg on this operative, you can spend 1 of your Prescience points to ignore that inflicted damage.\nYou cannot gain or spend your Prescience points if this operative is incapacitated."}], "actions": [{"name": "Premonition", "ap": 1, "text": "PSYCHIC. Spend 1 of your Prescience points to gain 1CP.\nThis operative cannot perform this action while within control range of an enemy operative, or more than once per turning point."}], "keywords": ["NEMESIS CLAW", "CHAOS", "HERETIC ASTARTES", "PSYKER", "LEADER", "VISIONARY"]},
  {"name": "Night Lord Fearmonger", "weapons": [], "abilities": [{"name": "Terrorchem Poison", "text": "Whenever an operative that has one of your Terrorchem tokens is activated, inflict D3 damage on it."}], "actions": [{"name": "Poison Objective", "ap": 1, "text": "Select one objective marker this operative controls to gain one of your Terrorchem tokens. It cannot be an objective marker within control range of an enemy operative, or one that already has one of your Terrorchem tokens. The first time an enemy operative that doesn’t have one of your Terrorchem tokens contests that objective marker, that operative gains that Terrorchem token, then inflict 2D3 damage on it (if it’s during an action, at the end of that action).\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["NEMESIS CLAW", "CHAOS", "HERETIC ASTARTES", "FEARMONGER"]},
  {"name": "Night Lord Gunner", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Flamer", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 8\", Saturate, Torrent 2\""}, {"name": "Meltagun", "atk": 4, "hit": "3+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Plasma gun (standard)", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Piercing 1"}, {"name": "Plasma gun (supercharge)", "atk": 4, "hit": "3+", "dmg": "5/6", "wr": "Hot, Lethal 5+, Piercing 1"}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["NEMESIS CLAW", "CHAOS", "HERETIC ASTARTES", "GUNNER"]},
  {"name": "Night Lord Heavy Gunner", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Heavy bolter (focused)", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Heavy (Reposition only), Piercing Crits 1"}, {"name": "Heavy bolter (sweeping)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Heavy (Reposition only), Piercing Crits 1,"}], "abilities": [], "actions": [], "keywords": ["NEMESIS CLAW", "CHAOS", "HERETIC ASTARTES", "HEAVY GUNNER"]},
  {"name": "Night Lord Screecher", "weapons": [{"name": "Lightning claws", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Ceaseless, Lethal 5+"}], "abilities": [{"name": "Screecher", "text": "Whenever an enemy operative within 3\" of this                  Appetite for Cruelty: Whenever this operative is fighting against operative is shooting, fighting or retaliating, your opponent             a wounded enemy operative, this operative’s lightning claws have cannot re-roll their attack dice.                                         the Lethal 4+ weapon rule."}], "actions": [], "keywords": ["NEMESIS CLAW", "CHAOS", "HERETIC ASTARTES", "SCREECHER"]},
  {"name": "Night Lord Skinthief", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Nostraman chainglaive", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Rending"}], "abilities": [{"name": "Flay Them Alive", "text": "Once per turning point, when this operative incapacitates an enemy operative within its control range, you can select one other enemy operative visible to and within 6\" of either this operative or the incapacitated enemy operative. Until the start of the next turning point, that other enemy operative cannot control markers or perform the Pick Up Marker or mission actions."}, {"name": "Tyrant of the Skinning Pits", "text": "Whenever this operative is fighting or retaliating, Normal and Critical Dmg of 3 or more inflicts 1 less damage on it."}], "actions": [], "keywords": ["NEMESIS CLAW", "CHAOS", "HERETIC ASTARTES", "SKINTHIEF"]},
  {"name": "Night Lord Ventrilokar", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Chainsword", "atk": 5, "hit": "3+", "dmg": "4/5"}], "abilities": [{"name": "Icon Bearer", "text": "Whenever               DISCONCERTING MIMICRY                                                                        1AP determining control of a PSYCHIC. Select one enemy operative within 6\" of this operative, then select one of the marker, treat this operative’s following for that enemy operative (you can only select each option once per battle): APL stat as 1 higher. Note this isn’t a change to its APL stat,    • Until the end of its next activation, subtract 1 from its APL stat. so any changes are cumulative      • Change its order. with this.                         • Perform a free Dash action with it (specify the location for your opponent to move it to).\nThis operative cannot perform this action while within control range of an enemy operative."}], "actions": [], "keywords": ["NEMESIS CLAW", "CHAOS", "HERETIC ASTARTES", "PSYKER", "VENTRILOKAR"]},
  {"name": "Night Lord Warrior", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Boltgun", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Chainsword", "atk": 5, "hit": "3+", "dmg": "4/5"}, {"name": "Fists", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [{"name": "Cruel Tormenter", "text": "Whenever this operative is shooting against, fighting against or retaliating against an injured enemy operative, or an enemy operative that has a Wounds stat of 7 or less, this operative’s weapons have the Lethal 5+ weapon rule.\nNOTES:\nNOTES:"}], "actions": [], "keywords": ["NEMESIS CLAW", "CHAOS", "HERETIC ASTARTES", "WARRIOR"]},
]
