// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Astartes", text: "During each friendly NEMESIS CLAW operative’s activation, it can perform either two Shoot actions or two Fight actions. If it’s two Shoot actions, a bolt pistol, boltgun or scoped bolt pistol must be selected for at least one of them.\nEach friendly NEMESIS CLAW operative can counteract regardless of its order." },
  { kind: 'faction', name: "In Midnight Clad", text: "Whenever an enemy operative is shooting a friendly NEMESIS CLAW operative, that friendly operative is obscured if both of the following are true:\n• It’s more than 8\" from enemy operatives it’s visible to.\n• It’s within 1\" of Heavy terrain that’s not lower than it, or any part of its base is underneath Vantage terrain." },
  { kind: 'strategy', name: "The Black Hunt", text: "Whenever a friendly NEMESIS CLAW operative is shooting against, fighting against or retaliating against a wounded enemy operative, you can re-roll one of your attack dice." },
  { kind: 'strategy', name: "We Have Come for You", text: "Whenever a friendly NEMESIS CLAW operative is activated, if the first action it performs during that activation is the Charge action, when it ends its move during that action, you can inflict D3 damage on one enemy operative within its control range." },
  { kind: 'strategy', name: "Preysight", text: "Whenever a friendly NEMESIS CLAW operative performs the Shoot action, you can use this rule. If you do, until the end of that action, that friendly operative’s ranged weapons have the Range 6\" and Seek Light weapon rules." },
  { kind: 'strategy', name: "Return to Darkness", text: "One friendly NEMESIS CLAW operative can immediately perform a free Fall Back or Reposition action, but it must end that move with Heavy terrain within its control range, or any part of its base underneath Vantage terrain. In addition, it cannot move more than 4\" during that action and it cannot end that move closer to enemy operatives (in a killzone that uses the close quarters rules, e.g. Killzone: Tomb World, ignore Wall terrain when determining this)." },
  { kind: 'firefight', name: "Death to the False Emperor", text: "Use this firefight ploy after rolling your attack dice for a friendly NEMESIS CLAW operative, if it’s shooting against, fighting against or retaliating against an enemy operative that has the IMPERIUM keyword. That friendly operative’s weapons have the Ceaseless weapon rule until the end of that sequence; if that enemy operative also has the ADEPTUS ASTARTES keyword, that friendly operative’s weapons have the Relentless weapon rule until the end of that sequence instead." },
  { kind: 'firefight', name: "Vox Scream", text: "Use this firefight ploy when your opponent would activate an enemy operative that’s visible to a friendly NEMESIS CLAW operative. Roll one D6; if the result is higher than that enemy operative’s APL stat, your opponent cannot activate it during this activation; if the result is less than or equal to that enemy operative’s APL stat, this ploy isn’t used, the CP spent on it is refunded and you cannot use this ploy again during this turning point. If there are no other enemy operatives eligible to be activated, this ploy has no effect." },
  { kind: 'firefight', name: "Proclivity for Murder", text: "Use this firefight ploy after a friendly NEMESIS CLAW operative incapacitates an enemy operative within its control range. That friendly operative can immediately perform a free Charge or Dash action (for the former, it cannot move more than 3\"), even if it’s performed an action that prevents it from performing those actions." },
  { kind: 'firefight', name: "Dirty Fighter", text: "Use this firefight ploy when a friendly NEMESIS CLAW operative is retaliating, at the start of the Resolve Attack Dice step. You can resolve one of your successes before the normal order. If you do, you cannot resolve any other successes during that sequence." },
  { kind: 'equipment', name: "Chain Snare", text: "Whenever an enemy operative would perform the Fall Back action while within control range of a friendly NEMESIS CLAW operative, if no other enemy operatives are within that friendly operative’s control range, you can use this rule. If you do, roll two D6, or one D6 if that enemy operative has a higher Wounds stat than that friendly operative. If any result is a 4+, that enemy operative cannot perform that action during that activation/counteraction (no AP are spent on it), and you cannot use this rule again during this turning point." },
  { kind: 'equipment', name: "Flayed Skin", text: "Whenever an enemy operative is shooting against, fighting against or retaliating against a friendly NEMESIS CLAW operative within 2\" of it, your opponent cannot re-roll their attack dice results of 1." },
  { kind: 'equipment', name: "Grisly Trophy", text: "Once per battle, when a friendly NEMESIS CLAW operative incapacitates an enemy operative within 2\" of it, you can use this rule. If you do, that friendly operative gains one of your Grisly Trophy tokens (if it doesn’t already have one). Whenever a friendly NEMESIS CLAW operative that has one of your Grisly Trophy tokens is visible to and within 2\" of an enemy operative, subtract 1 from the Atk stat of that enemy operative’s weapons." },
  { kind: 'equipment', name: "Comms Jammers", text: "Whenever an enemy operative is within 3\" of a friendly NEMESIS CLAW operative, that enemy operative’s APL stat cannot be added to. Note that this doesn’t affect APL stats that have already been changed." },
]

export const operatives: Operative[] = [
  { id: "nemesis-claw:night-lord-visionary", name: "Night Lord Visionary", apl: 3, move: "6\"", save: "3+", w: 15 },
  { id: "nemesis-claw:night-lord-fearmonger", name: "Night Lord Fearmonger", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "nemesis-claw:night-lord-gunner", name: "Night Lord Gunner", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "nemesis-claw:night-lord-heavy-gunner", name: "Night Lord Heavy Gunner", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "nemesis-claw:night-lord-screecher", name: "Night Lord Screecher", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "nemesis-claw:night-lord-skinthief", name: "Night Lord Skinthief", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "nemesis-claw:night-lord-ventrilokar", name: "Night Lord Ventrilokar", apl: 3, move: "6\"", save: "3+", w: 14 },
  { id: "nemesis-claw:night-lord-warrior", name: "Night Lord Warrior", apl: 3, move: "6\"", save: "3+", w: 14 },
]
