// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Acts of Faith", text: "In the Ready step of each Strategy phase, you gain a number of Faith points equal to half the number of friendly NOVITIATE operatives that haven’t been incapacitated (rounding up). Whenever a friendly NOVITIATE operative is shooting, fighting or retaliating, or an operative is shooting it, in the Roll Attack Dice (or Roll Defence Dice step if an operative is shooting it), you can spend your Faith points to use one ACT OF FAITH. You cannot use more than one ACT OF FAITH per sequence, and their costs and effects are as follows (see other side of card):" },
  { kind: 'strategy', name: "Ardent Vengeance", text: "Whenever a friendly NOVITIATE operative is shooting against, fighting against or retaliating against an expended enemy operative, that friendly operative’s weapons have the Punishing weapon rule." },
  { kind: 'strategy', name: "Blessed Rejuvenation", text: "Whenever you spend Faith points, at the end of that action, the friendly operative you spent them on can regain up to D3 lost wounds. Note this ploy has no effect if that friendly operative was incapacitated during that action, or if the ACT OF FAITH doesn’t cost any Faith points, e.g. Auto-chastisers equipment." },
  { kind: 'strategy', name: "Defenders of the Faith", text: "Whenever an operative is shooting against, fighting against or retaliating against a friendly NOVITIATE operative that contests an objective marker, in the Resolve Attack Dice step of that sequence, you can halve the damage inflicted (rounding up and to a minimum of 2) on that friendly operative from one success." },
  { kind: 'strategy', name: "Righteous Advance", text: "Up to one third of the friendly NOVITIATE operatives in the killzone (rounding down, to a minimum of 1) can immediately perform a free Dash action in an order of your choice, but each that does so must end that move closer to its closest enemy operative, its closest objective marker or your opponent’s drop zone (you can choose separately for each). You cannot use this ploy during the first turning point." },
  { kind: 'firefight', name: "Glorious Martyrdom", text: "Use this firefight ploy when a friendly NOVITIATE operative is incapacitated, before it’s removed from the killzone. For each enemy operative visible to and within 2\" of it, you gain 1 Faith point and inflict D3 damage on that enemy operative (roll separately for each)." },
  { kind: 'firefight', name: "Blinding Aura", text: "Use this firefight ploy when an enemy operative is performing the Shoot action and selects a friendly NOVITIATE operative as the valid target. Until the end of that activation/counteraction, while that friendly operative is more than 2\" from that enemy operative, your opponent cannot select it as a valid target. If there are no other valid targets that your opponent can select, that action ends (it’s not cancelled, so that operative has still performed it). Note this ploy has no effect if it’s not the selected operative, e.g. if it’s a secondary target from the Blast weapon rule." },
  { kind: 'firefight', name: "Blazing Inferno", text: "Use this firefight ploy when a friendly NOVITIATE operative is shooting with a Ministorum flamer and you inflict damage with any critical successes. The target gains one of your Blaze tokens (if it doesn’t already have one). Whenever an operative that has one of your Blaze tokens is activated:\n• Inflict D3 damage on it.\n• Its controlling player can subtract 1 from that operative’s APL stat until the end of that activation to remove that token. Note that this must be done before that operative performs any actions during that activation." },
  { kind: 'firefight', name: "Guided by Faith", text: "Use this firefight ploy when a friendly NOVITIATE operative is performing the Shoot action and you’re selecting a ranged weapon. Until the end of that action, whenever that operative is shooting an operative within 6\" of it, that weapon has the Seek Light weapon rule." },
  { kind: 'equipment', name: "Icon of Faith", text: "Once per turning point, you can use up to two ACTS OF FAITH during a sequence, but each one must be different. This takes precedence over the normal ACTS OF FAITH rules." },
  { kind: 'equipment', name: "Auto-chastisers", text: "Once per turning point, when a friendly NOVITIATE operative is shooting, fighting or retaliating, in the Roll Attack Dice step, you can inflict 1-3 damage on that friendly operative (but not enough to incapacitate it). If you do, you can use one ACT OF FAITH for free during that sequence with a Faith points cost no more than the damage you inflicted from this rule." },
  { kind: 'equipment', name: "Sanctified Rounds", text: "Whenever a friendly NOVITIATE operative is shooting with an autogun, autopistol, relic bolt pistol or relic boltgun, if you spend a Faith point, that weapon has the Piercing Crits 1 weapon rule until the end of that sequence." },
  { kind: 'equipment', name: "Holy Embrocations", text: "You can ignore any changes to the Move stat of friendly NOVITIATE operatives from being injured." },
]

export const operatives: Operative[] = [
  { id: "novitiates:novitiate-superior", name: "Novitiate Superior", apl: 3, move: "6\"", save: "3+", w: 9 },
  { id: "novitiates:novitiate-condemnor", name: "Novitiate Condemnor", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "novitiates:novitiate-dialogus", name: "Novitiate Dialogus", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "novitiates:novitiate-duellist", name: "Novitiate Duellist", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "novitiates:novitiate-exactor", name: "Novitiate Exactor", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "novitiates:novitiate-hospitaller", name: "Novitiate Hospitaller", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "novitiates:novitiate-militant", name: "Novitiate Militant", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "novitiates:novitiate-penitent", name: "Novitiate Penitent", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "novitiates:novitiate-preceptor", name: "Novitiate Preceptor", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "novitiates:novitiate-pronatus", name: "Novitiate Pronatus", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "novitiates:novitiate-purgatus", name: "Novitiate Purgatus", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "novitiates:novitiate-reliquarius", name: "Novitiate Reliquarius", apl: 2, move: "6\"", save: "4+", w: 7 },
]

export const datacards: Datacard[] = [
  {"name": "Novitiate Superior", "weapons": [{"name": "Plasma pistol (standard)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Piercing 1"}, {"name": "Plasma pistol (supercharge)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Hot, Lethal 5+, Piercing 1"}, {"name": "Relic bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Lethal 5+"}, {"name": "Relic boltgun", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Lethal 5+"}, {"name": "Gun butt", "atk": 3, "hit": "3+", "dmg": "2/3"}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Inspirational Example", "text": "Whenever this operative incapacitates an enemy operative, you gain 1 Faith point, or 2 Faith points if that enemy operative had a Wounds stat of 12 or more. This rule has no effect when using the Glorious Martyrdom firefight ploy."}], "actions": [], "keywords": ["NOVITIATE", "IMPERIUM", "ADEPTA SORORITAS", "LEADER", "SUPERIOR"]},
  {"name": "Novitiate Condemnor", "weapons": [{"name": "Condemnor stakethrower", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Anti-PSYKER*, Devastating 2, Piercing Crits 1,"}], "abilities": [{"name": "Null Rod", "text": "PSYCHIC ranged weapons cannot inflict damage on this operative. For the             *Anti-PSYKER: Whenever this weapon is effects of PSYCHIC actions, this operative cannot be selected and is never treated as         being used against an operative that has being within those actions’ required distances. Whenever an operative is within 6\" of         the PSYKER keyword, add 1 to both this operative:                                                                               Dmg stats of this weapon and it has the Lethal 5+ weapon rule. • That operative cannot perform PSYCHIC actions or use PSYCHIC additional rules. • That operative cannot use PSYCHIC ranged weapons. • PSYCHIC melee weapons have no weapon rules and cannot have Dmg stats higher than 3/4."}], "actions": [], "keywords": ["NOVITIATE", "IMPERIUM", "ADEPTA SORORITAS", "CONDEMNOR"]},
  {"name": "Novitiate Dialogus", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Dialogus stave", "atk": 4, "hit": "4+", "dmg": "3/3", "wr": "Shock"}], "abilities": [], "actions": [{"name": "Stirring Rhetoric", "ap": 1, "text": "SUPPORT. Select one other friendly NOVITIATE operative visible to and within 6\" of this operative, or within 6\" of your Auto-broadcaster marker. Until the end of that operative’s next activation, add 1 to its APL stat (to a maximum of 3 after all APL stat changes have been totalled).\nThis operative cannot perform this action while within control range of an enemy operative."}, {"name": "Auto-broadcaster", "ap": 0, "text": "If your Auto-broadcaster marker isn’t in the killzone, place it within 8\" horizontally of this operative; otherwise, move your Auto- broadcaster marker up to 8\" horizontally. If this operative is removed from the killzone, remove your Auto-broadcaster marker from the killzone.\nWhenever an enemy operative within 3\" of your Auto-broadcaster marker is shooting, fighting or retaliating, your opponent cannot re-roll their attack dice.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["NOVITIATE", "IMPERIUM", "ADEPTA SORORITAS", "DIALOGUS"]},
  {"name": "Novitiate Duellist", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Duelling blades", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Ceaseless, Riposte*"}], "abilities": [], "actions": [], "keywords": ["NOVITIATE", "IMPERIUM", "ADEPTA SORORITAS", "DUELLIST"]},
  {"name": "Novitiate Exactor", "weapons": [{"name": "Neural whips (ranged)", "atk": 5, "hit": "3+", "dmg": "2/3", "wr": "Range 3\", Lethal 5+, Stun"}, {"name": "Neural whips (melee)", "atk": 5, "hit": "3+", "dmg": "2/3", "wr": "Lethal 5+, Shock"}], "abilities": [], "actions": [{"name": "Whip Into Frenzy", "ap": 1, "text": "Select one other friendly NOVITIATE operative (excluding SUPERIOR) visible to and within 3\" of this operative that isn’t currently benefitting from the effects of this action. Until the end of that operative’s next activation, add 1 to its APL stat, add 1\" to its Move stat, and it can perform two Fight actions during its next activation.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["NOVITIATE", "IMPERIUM", "ADEPTA SORORITAS", "EXACTOR"]},
  {"name": "Novitiate Hospitaller", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Surgical saw", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Lethal 5+, Rending"}], "abilities": [{"name": "Medic!", "text": "The first time during each turning point that another friendly NOVITIATE operative would be incapacitated while visible to and within 3\" of this operative, you can use this rule, providing neither this nor that operative is within control range of an enemy operative. If you do, that friendly operative isn’t incapacitated, has 1 wound remaining and cannot be incapacitated for the remainder of the action. After that action, that friendly operative can immediately perform a free Dash action, but must end that move within this operative’s control range. Subtract 1 from this and that operative’s APL stats until the end of their next activations respectively, and if this rule was used during that friendly operative’s activation, that activation ends. You cannot use this rule if this operative is incapacitated, or if it’s a Shoot action and this operative would be a primary or secondary target."}], "actions": [{"name": "Chirurgeon’s Tools", "ap": 1, "text": "Select one friendly NOVITIATE operative within this operative’s control range to regain up to 2D3 lost wounds. It cannot be an operative that the Medic! rule was used on during this turning point.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["NOVITIATE", "IMPERIUM", "ADEPTA SORORITAS", "MEDIC", "HOSPITALLER"]},
  {"name": "Novitiate Militant", "weapons": [{"name": "Autogun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}, {"name": "Novitiate blade", "atk": 4, "hit": "4+", "dmg": "4/5"}], "abilities": [{"name": "Militant Faith", "text": "Whenever this operative is shooting, fighting or retaliating, if you use an ACT OF FAITH during that sequence and an enemy operative is incapacitated, the Faith points spent on that ACT OF FAITH are refunded. If you use the Icon of Faith equipment, Faith points are only refunded for one of those ACTS OF FAITH (your choice)."}], "actions": [], "keywords": ["NOVITIATE", "IMPERIUM", "ADEPTA SORORITAS", "MILITANT"]},
  {"name": "Novitiate Penitent", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Penitent eviscerator", "atk": 4, "hit": "4+", "dmg": "5/6", "wr": "Brutal, Zealous Rage*"}], "abilities": [], "actions": [], "keywords": ["NOVITIATE", "IMPERIUM", "ADEPTA SORORITAS", "PENITENT"]},
  {"name": "Novitiate Preceptor", "weapons": [{"name": "Mace of the Righteous", "atk": 4, "hit": "4+", "dmg": "5/5", "wr": "Brutal, Severe"}], "abilities": [{"name": "Unflinching Example", "text": "Whenever this operative incapacitates a         Glorious Hymnal: SUPPORT. Whenever a friendly ready enemy operative within its control range, you gain 1 Faith     NOVITIATE operative is within 3\" of this operative, that point, or 2 Faith points if that enemy operative had a Wounds stat   friendly operative’s weapons have the Severe weapon rule. of 12 or more."}], "actions": [], "keywords": ["NOVITIATE", "IMPERIUM", "ADEPTA SORORITAS", "PRECEPTOR"]},
  {"name": "Novitiate Pronatus", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Relic Seeker", "text": "Once during each of this operative’s activations,      Divine Acquisition: Once per turning point, when this operative it can perform the Pick Up Marker, Place Marker or a                 performs a mission action that requires it to control an objective mission action for 1 less AP.                                        or mission marker, you gain a number of Faith points equal to the turning point number."}], "actions": [], "keywords": ["NOVITIATE", "IMPERIUM", "ADEPTA SORORITAS", "PRONATUS"]},
  {"name": "Novitiate Purgatus", "weapons": [{"name": "Ministorum flamer", "atk": 4, "hit": "2+", "dmg": "4/4", "wr": "Range 8\", Saturate, Torrent 2\""}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Purge with Flame", "text": "Once per turning point, you can use the Inferno firefight ploy for 0CP if this is the specified friendly NOVITIATE operative."}], "actions": [], "keywords": ["NOVITIATE", "IMPERIUM", "ADEPTA SORORITAS", "PURGATUS"]},
  {"name": "Novitiate Reliquarius", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Icon Bearer", "text": "Whenever determining control of a marker, treat this operative’s\nAPL stat as 1 higher. Note this isn’t a\nchange to its APL stat, so any changes are cumulative with this.\nNOTES:\nNOTES:"}], "actions": [{"name": "Raise Icon", "ap": 1, "text": "You gain 1 Faith point. If this operative controls an objective marker, you also gain a\nnumber of Faith points equal to the turning point number.\nThis operative cannot perform this action more than once per turning point, and cannot perform it while within control range of an enemy operative."}], "keywords": ["NOVITIATE", "IMPERIUM", "ADEPTA SORORITAS", "RELIQUARIUS"]},
]
