// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Markerlights", text: "Some PATHFINDER operatives (indicated on their datacard) can perform the Markerlight unique action:\nMARKERLIGHT (1AP): Select one enemy operative visible to this operative. That enemy operative gains one of your Markerlight tokens (to a maximum of four). An operative cannot perform this action while within control range of an enemy operative. If an operative (excluding MB3 RECON) would perform the Shoot action (excluding Guard) and this action during the same activation, only the target of that Shoot action can be selected for this action (and vice versa).\nOnce during each of their activations, whenever an enemy operative that has any of your Markerlight tokens performs the Dash, Charge, Fall Back or Reposition action, remove one of those tokens.\nWhile only some PATHFINDER operatives can perform the Markerlight action, all PATHFINDER operatives can benefit from its effects. Whenever a friendly PATHFINDER operative is shooting with a weapon from its datacard (excluding\nASSAULT GRENADIER’s fusion grenade), it has additional rules determined by the number of your Markerlight tokens the target has. These are cumulative, so if an enemy operative has two of your Markerlight tokens, the friendly operative shooting it has the rules for 1 and 2 tokens during that sequence." },
  { kind: 'strategy', name: "Recon Sweep", text: "Select one killzone edge (excluding your own). Each friendly PATHFINDER operative that’s wholly within 6\" of that edge can immediately perform a free Dash action in an order of your choice, but each that does so must end that move wholly within 6\" of a killzone edge (excluding your own). You cannot use this ploy during the first turning point." },
  { kind: 'strategy', name: "Suppressing Fire", text: "Whenever an enemy operative is performing the Shoot action, if the target (the primary target if the weapon has the Blast or Torrent weapon rules) isn’t the closest valid target, your opponent cannot re-roll their attack dice. Ignore friendly PATHFINDER operatives that have a Conceal order or are obscured when determining this." },
  { kind: 'strategy', name: "Bonded", text: "Whenever a friendly PATHFINDER operative (excluding DRONE) is shooting or retaliating with a ranged weapon (see Point-Blank Fusillade firefight ploy), if it’s within 3\" of another friendly PATHFINDER operative (excluding DRONE), that first friendly operative’s ranged weapons have the Accurate 1 weapon rule." },
  { kind: 'firefight', name: "A Worthy Cause", text: "Use this firefight ploy at the start of the Firefight phase. One friendly PATHFINDER operative (excluding DRONE) can immediately perform a free mission action." },
  { kind: 'strategy', name: "Take Cover", text: "Whenever an operative is shooting a friendly PATHFINDER operative, if you can retain any cover saves, improve that friendly operative’s Save stat by 1." },
  { kind: 'firefight', name: "Supporting Fire", text: "Use this firefight ploy when a friendly PATHFINDER operative is performing the Shoot action and you’re selecting a valid target within 6\" of it. Having other friendly PATHFINDER operatives within an enemy operative’s control range doesn’t prevent that enemy operative from being selected." },
  { kind: 'firefight', name: "Saviour Protocols", text: "Use this firefight ploy when a friendly PATHFINDER operative (excluding DRONE) is selected as the valid target of a Shoot action. Select one friendly PATHFINDER DRONE operative visible to and within 3\" of that first friendly operative to become the valid target instead (even if it wouldn’t normally be valid for this). That friendly DRONE operative is only in cover or obscured if the original target was. This ploy has no effect if the ranged weapon has the Blast or Torrent weapon rule." },
  { kind: 'equipment', name: "Target Analysis Optic", text: "Once per turning point, when a friendly PATHFINDER operative (excluding DRONE) is performing the Shoot action and you’re selecting a valid target, you can use this rule. If you do, until the end of that action, if the target has at least one of your Markerlight tokens, it's treated as having one more. If the ranged weapon has the Blast or Torrent weapon rule, only the primary target is affected." },
  { kind: 'firefight', name: "Point-blank Fusillade", text: "Use this firefight ploy when a friendly PATHFINDER operative (excluding DRONE) is retaliating, if it wasn’t within control range of enemy operatives at the start of that activation/ counteraction. You can use one of its ranged weapons as a melee weapon (excluding a weapon that has the word ‘grenade’ in its name) during that sequence. If you do, you cannot block during that sequence, and the following weapon rules have no effect on its weapons until the end of that sequence: Devastating, Piercing, Torrent. If that friendly operative is ready, has an Engage order and is retaliating with a pulse weapon, you resolve the first attack dice (i.e. defender instead of attacker)." },
  { kind: 'equipment', name: "High-intensity Markerlight", text: "Up to twice per turning point, when a friendly PATHFINDER operative (excluding MV7 MARKER DRONE) performs the Markerlight action, you can use this rule. If you do, the enemy operative you select gains two of your Markerlight tokens (instead of one)." },
  { kind: 'equipment', name: "Photon Grenade", text: "Once per turning point, a friendly PATHFINDER operative that has the Markerlight action on their datacard (excluding DRONE) can perform the following unique action:\nPHOTON GRENADE (1AP): Select one enemy operative visible to this operative and roll one D6: on a 3+, until the end of that operative’s next activation, subtract 2\" from its Move stat. An operative cannot perform this action while within control range of an enemy operative." },
  { kind: 'equipment', name: "Orbital Survey Uplink", text: "Once per turning point, when a friendly PATHFINDER operative performs the Markerlight action, you can use this rule. If you do, you can select one enemy operative in the killzone to gain one of your Markerlight tokens instead (it doesn’t need to be visible). This isn’t cumulative with the High-intensity Markerlight or Analyse rules." },
]

export const operatives: Operative[] = [
  { id: "pathfinders:shas-ui-pathfinder", name: "Shas’ui Pathfinder", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "pathfinders:assault-grenadier-pathfinder", name: "Assault Grenadier Pathfinder", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "pathfinders:blooded-pathfinder", name: "Blooded Pathfinder", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "pathfinders:comms-specialist-pathfinder", name: "Comms Specialist Pathfinder", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "pathfinders:drone-controller-pathfinder", name: "Drone Controller Pathfinder", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "pathfinders:marksman-pathfinder", name: "Marksman Pathfinder", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "pathfinders:medical-technician-pathfinder", name: "Medical Technician Pathfinder", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "pathfinders:shas-la-pathfinder", name: "Shas’la Pathfinder", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "pathfinders:transpectral-interference-pathfinder", name: "Transpectral Interference Pathfinder", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "pathfinders:weapons-expert-pathfinder", name: "Weapons Expert Pathfinder", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "pathfinders:mb3-recon-drone", name: "MB3 Recon Drone", apl: 3, move: "6\"", save: "4+", w: 12 },
  { id: "pathfinders:mv1-gun-drone", name: "MV1 Gun Drone", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "pathfinders:mv4-shield-drone", name: "MV4 Shield Drone", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "pathfinders:mv7-marker-drone", name: "MV7 Marker Drone", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "pathfinders:mv31-pulse-accelerator-drone", name: "MV31 Pulse Accelerator Drone", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "pathfinders:mv33-grav-inhibitor-drone", name: "MV33 Grav-inhibitor Drone", apl: 2, move: "6\"", save: "4+", w: 7 },
]

export const datacards: Datacard[] = [
  {"name": "Shas’ui Pathfinder", "weapons": [{"name": "Pulse carbine", "atk": 4, "hit": "3+", "dmg": "4/5"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Art of War", "text": "STRATEGIC GAMBIT if this operative is in the killzone. Select one of the following and apply its rules until the\nend of the turning point. You cannot select each option more than once per battle:\n• Mont’ka: Add 1\" to the Move stat of friendly PATHFINDER operatives. • Kauyon: Friendly PATHFINDER operatives can perform a free Markerlight action during their activation if they have a Conceal order."}], "actions": [{"name": "Markerlight", "ap": 1, "text": "See the Markerlights faction rule."}], "keywords": ["PATHFINDER", "T'AU EMPIRE", "LEADER", "SHAS’UI"], "img": "/ops/pathfinders/shas-ui-pathfinder.webp"},
  {"name": "Assault Grenadier Pathfinder", "weapons": [{"name": "Fusion grenade", "atk": 4, "hit": "3+", "dmg": "4/3", "wr": "Range 6\", Devastating 2, Limited 1, Piercing 2, Saturate"}, {"name": "Pulse carbine", "atk": 4, "hit": "4+", "dmg": "4/5"}, {"name": "Gun butt", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [{"name": "Grenadier Specialist", "text": "This operative can use frag and krak grenades (see universal equipment). Doing so doesn’t count\ntowards any limited uses you have (i.e. if you also select those grenades from equipment for other operatives). Whenever it’s doing so, improve the Hit stat of that weapon by 1."}], "actions": [{"name": "Markerlight", "ap": 1, "text": "See the Markerlights faction rule."}], "keywords": ["PATHFINDER", "T'AU EMPIRE", "ASSAULT GRENADIER"], "img": "/ops/pathfinders/assault-grenadier-pathfinder.webp"},
  {"name": "Blooded Pathfinder", "weapons": [{"name": "Suppressed pulse carbine", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Silent"}, {"name": "Bionic arm", "atk": 3, "hit": "4+", "dmg": "3/4"}], "abilities": [{"name": "Veteran", "text": "During a turning point in which you have used a friendly SHAS’UI operative’s Art of War STRATEGIC GAMBIT and\nyou selected Mont’ka, this operative can use Kauyon instead during its activation (and vice versa)."}], "actions": [{"name": "Markerlight", "ap": 1, "text": "See the Markerlights faction rule."}], "keywords": ["PATHFINDER", "T'AU EMPIRE", "BLOODED"], "img": "/ops/pathfinders/blooded-pathfinder.webp"},
  {"name": "Comms Specialist Pathfinder", "weapons": [{"name": "Pulse carbine", "atk": 4, "hit": "4+", "dmg": "4/5"}, {"name": "Fists", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [], "actions": [{"name": "Markerlight", "ap": 1, "text": "See the Markerlights faction rule."}, {"name": "Signal", "ap": 1, "text": "SUPPORT. Select one other friendly PATHFINDER operative visible to and within 6\" of this operative. Until the end of that operative’s next activation, add 1 to its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["PATHFINDER", "T'AU EMPIRE", "COMMS SPECIALIST"], "img": "/ops/pathfinders/comms-specialist-pathfinder.webp"},
  {"name": "Drone Controller Pathfinder", "weapons": [{"name": "Pulse carbine", "atk": 4, "hit": "4+", "dmg": "4/5"}, {"name": "Gun butt", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [{"name": "Drone Controller", "text": "Whenever this operative is in the killzone: • Add 2\" to the Move stat of friendly PATHFINDER DRONE operatives. • The Saviour Protocols firefight ploy costs you 0CP."}], "actions": [{"name": "Markerlight", "ap": 1, "text": "See the Markerlights faction rule."}, {"name": "Remote Pilot", "ap": 1, "text": "One friendly PATHFINDER DRONE operative can immediately perform one free action, but it cannot move more than 2\" during that action. That action can be one that’s normally restricted by its Drone rule (this takes precedence over that rule).\nThis operative cannot perform this action while within control range of an enemy operative. This operative can perform this action more than once during its activation, but if it does, the same DRONE operative cannot perform the same free action more than once per activation."}], "keywords": ["PATHFINDER", "T'AU EMPIRE", "DRONE CONTROLLER"], "img": "/ops/pathfinders/drone-controller-pathfinder.webp"},
  {"name": "Marksman Pathfinder", "weapons": [{"name": "Marksman rail rifle (standard)", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Devastating 2, Lethal 5+, Piercing 1"}, {"name": "Marksman rail rifle (dart round)", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Piercing 1, Silent"}, {"name": "Gun butt", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [{"name": "Inertial Dampener", "text": "You can ignore any changes to the Hit stat of this operative’s marksman rail rifle."}], "actions": [], "keywords": ["PATHFINDER", "T'AU EMPIRE", "MARKSMAN"], "img": "/ops/pathfinders/marksman-pathfinder.webp"},
  {"name": "Medical Technician Pathfinder", "weapons": [{"name": "Pulse carbine", "atk": 4, "hit": "4+", "dmg": "4/5"}, {"name": "Gun butt", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [{"name": "Medic!", "text": "The first time during each turning point that another friendly PATHFINDER operative (excluding DRONE) would be incapacitated while visible to and within 3\" of this operative, you can use this rule, providing neither this nor that operative is within control range of an enemy operative. If you do, that friendly operative isn’t incapacitated, has 1 wound remaining and cannot be incapacitated for the remainder of the action. After that action, that friendly operative can immediately perform a free Dash action, but must end that move within this operative’s control range. Subtract 1 from this and that operative’s APL stats until the end of their next activations respectively, and if this rule was used during that friendly operative’s activation, that activation ends. You cannot use this rule if this operative is incapacitated, or if it’s a Shoot action and this operative would be a primary or secondary target."}], "actions": [{"name": "Markerlight", "ap": 1, "text": "See the Markerlights faction rule."}, {"name": "Medikit", "ap": 1, "text": "Select one friendly PATHFINDER operative (excluding DRONE) within this operative’s control range to regain up to 2D3 lost wounds. It cannot be an operative that the Medic! rule was used on during this turning point.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["PATHFINDER", "T'AU EMPIRE", "MEDIC", "MEDICAL TECHNICIAN"], "img": "/ops/pathfinders/medical-technician-pathfinder.webp"},
  {"name": "Shas’la Pathfinder", "weapons": [{"name": "Pulse carbine", "atk": 4, "hit": "4+", "dmg": "4/5"}, {"name": "Gun butt", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [{"name": "Group Activation", "text": "Whenever this operative is expended, you must then activate one other ready friendly PATHFINDER SHAS’LA operative (if able) before your opponent activates. When that other operative is expended, your opponent then activates as normal (in other words, you cannot activate more than two operatives in succession with this rule)."}, {"name": "Fearless on the Frontline", "text": "This operative can perform the Markerlight action while within control range of an enemy operative (this takes precedence over the Markerlight action’s normal conditions). In addition, this operative can perform the Fall Back action for 1 less AP."}], "actions": [{"name": "Markerlight", "ap": 1, "text": "See the Markerlights faction rule."}], "keywords": ["PATHFINDER", "T'AU EMPIRE", "SHAS’LA"], "img": "/ops/pathfinders/shas-la-pathfinder.webp"},
  {"name": "Transpectral Interference Pathfinder", "weapons": [{"name": "Pulse carbine", "atk": 4, "hit": "4+", "dmg": "4/5"}, {"name": "Gun butt", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [{"name": "Multi-Dimensional Vision", "text": "Whenever this operative is shooting, enemy operatives cannot be obscured."}], "actions": [{"name": "Markerlight 1ap System Jam", "ap": 1, "text": "See the Markerlights            Select one enemy operative visible to this faction rule.                   operative. Until the end of that operative’s next activation, subtract 1 from its APL stat.\nThis operative cannot perform this action while it has a Conceal order, or while within control range of an enemy operative."}], "keywords": ["PATHFINDER", "T'AU EMPIRE", "TRANSPECTRAL INTERFERENCE"], "img": "/ops/pathfinders/transpectral-interference-pathfinder.webp"},
  {"name": "Weapons Expert Pathfinder", "weapons": [{"name": "Ion rifle (standard)", "atk": 5, "hit": "4+", "dmg": "4/5", "wr": "Piercing Crits 1"}, {"name": "Ion rifle (overcharge)", "atk": 5, "hit": "4+", "dmg": "4/5", "wr": "Hot, Lethal 5+, Piercing 1"}, {"name": "Rail rifle", "atk": 4, "hit": "4+", "dmg": "4/4", "wr": "Devastating 2, Lethal 5+, Piercing 1"}, {"name": "Gun butt", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [], "actions": [], "keywords": ["PATHFINDER", "T'AU EMPIRE", "WEAPONS EXPERT"], "img": "/ops/pathfinders/weapons-expert-pathfinder.webp"},
  {"name": "MB3 Recon Drone", "weapons": [{"name": "Burst cannon (focused)", "atk": 5, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless, Heavy (Reposition only), Punishing"}, {"name": "Burst cannon (sweeping)", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless, Heavy (Reposition only), Punishing, Torrent 1\""}, {"name": "Ram", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [{"name": "Analyse", "text": "Whenever this operative performs the Markerlight         Drone: action, each other enemy operative that’s both visible to this    • This operative cannot perform any actions other than Charge, operative and within 3\" of the enemy operative you selected for     Dash, Fall Back, Fight, Markerlight, Reposition and that action also gains one of your Markerlight tokens.              Shoot. It cannot use any weapons that aren’t on its datacard. • Whenever determining control of an objective marker, treat MARKERLIGHT                                                  1AP   this operative’s APL stat as 1 lower. Note this isn’t a change to See the Markerlights faction rule.                                  its APL stat, so any changes are cumulative with this. • Whenever determining what’s visible to this operative, the round disc at the top of the miniature is its head."}], "actions": [], "keywords": ["PATHFINDER", "T'AU EMPIRE", "MB3 RECON", "DRONE"], "img": "/ops/pathfinders/mb3-recon-drone.webp"},
  {"name": "MV1 Gun Drone", "weapons": [{"name": "Twin pulse carbine", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Ceaseless"}, {"name": "Ram", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [{"name": "Drone", "text": "• This operative cannot perform any actions other than Charge, Dash, Fall Back, Fight, Reposition and Shoot. It cannot use any weapons that aren’t on its datacard. • Whenever determining control of an objective marker, treat this operative’s APL stat as 1 lower. Note this isn’t a change to its APL stat, so any changes are cumulative with this. • Whenever determining what’s visible to this operative, the round disc at the top of the miniature is its head."}], "actions": [], "keywords": ["PATHFINDER", "T'AU EMPIRE", "MV1 GUN", "DRONE"], "img": "/ops/pathfinders/mv1-gun-drone.webp"},
  {"name": "MV4 Shield Drone", "weapons": [{"name": "Ram", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [{"name": "Drone", "text": "• This operative cannot perform any actions other than Charge, Dash, Fall Back, Fight and Reposition. It cannot use any weapons that aren’t on its datacard. • Whenever determining control of an objective marker, treat this operative’s APL stat as 1 lower. Note this isn’t a change to its APL stat, so any changes are cumulative with this. • Whenever determining what’s visible to this operative, the round disc at the top of the miniature is its head."}, {"name": "Shield Generator", "text": "• This operative ignores the Piercing weapon rule. • Once per turning point, when an attack dice inflicts Normal Dmg on this operative, you can ignore that inflicted damage. • You can use the Saviour Protocols firefight ploy for 0CP if this is the specified DRONE operative."}], "actions": [], "keywords": ["PATHFINDER", "T'AU EMPIRE", "MV4 SHIELD", "DRONE"], "img": "/ops/pathfinders/mv4-shield-drone.webp"},
  {"name": "MV7 Marker Drone", "weapons": [{"name": "Ram", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [{"name": "High-intensity Markerlight", "text": "Whenever this operative performs the Markerlight action, the selected enemy operative gains two of your Markerlight tokens (instead of one)."}, {"name": "Drone", "text": "• This operative cannot perform any actions other than Charge, Dash, Fall Back, Fight, Markerlight and Reposition. It cannot use any weapons that aren’t on\nits datacard. • When determining control of an objective marker, treat this operative’s APL stat as 1 lower. Note this isn’t a change to its APL stat, so any changes are cumulative with this. • When determining what’s visible to this operative, the round disc at the top of the miniature is its head."}], "actions": [{"name": "Markerlight", "ap": 1, "text": "See the Markerlights faction rule."}], "keywords": ["PATHFINDER", "T'AU EMPIRE", "MV7 MARKER", "DRONE"], "img": "/ops/pathfinders/mv7-marker-drone.webp"},
  {"name": "MV31 Pulse Accelerator Drone", "weapons": [{"name": "Ram", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [{"name": "Drone", "text": "• This operative cannot perform any actions other than Charge, Dash, Fall Back, Fight, Pulse Accelerator and Reposition. It cannot use any weapons that aren’t on its datacard. • When determining control of an objective marker, treat this operative’s APL stat as 1 lower. Note this isn’t a change to its APL stat, so any changes are cumulative with this. • When determining what’s visible to this operative, the round disc at the top of the miniature is its head."}], "actions": [{"name": "Pulse Accelerator", "ap": 1, "text": "Until the start of this operative’s next activation or until it's incapacitated (whichever comes first), whenever another friendly PATHFINDER operative is shooting with a pulse weapon within 3\" of this operative, that weapon has the Lethal 5+ and Severe weapon rules."}], "keywords": ["PATHFINDER", "T'AU EMPIRE", "MV31 PULSE ACCELERATOR", "DRONE"], "img": "/ops/pathfinders/mv31-pulse-accelerator-drone.webp"},
  {"name": "MV33 Grav-inhibitor Drone", "weapons": [{"name": "Ram", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [{"name": "Drone", "text": "• This operative cannot perform any actions other than Charge, Dash, Fall Back, Fight and Reposition. It cannot use any weapons that aren’t on its datacard. • When determining control of an objective marker, treat this operative’s APL stat as 1 lower. Note this isn’t a change to its APL stat, so any changes are cumulative with this. • When determining what’s visible to this operative, the round disc at the top of the miniature is its head."}, {"name": "Grav-inhibitor", "text": "• Whenever an enemy operative performs an action in which it moves (excluding Dash), if it would move visible to and within 6\" of this operative, treat the distance as an additional 2\" and ignore the additional distances from the Obstructing and Accessible terrain rules. • Whenever an enemy operative is fighting or retaliating while visible to and within 6\" of this operative, worsen the Hit stat of that enemy operative’s melee weapons by 1. This is cumulative with being injured."}], "actions": [], "keywords": ["PATHFINDER", "T'AU EMPIRE", "MV33 GRAV-INHIBITOR", "DRONE"], "img": "/ops/pathfinders/mv33-grav-inhibitor-drone.webp"},
]
