// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Scarper", text: "After each enemy operative’s activation, before the next operative is activated, one friendly RATLING operative (excluding BULLGRYN, OGRYN and SNEAK) can perform a free Dash action, but it cannot end that move within 3\" of an enemy operative unless it’s not visible to every enemy operative when it ends that move. Each friendly operative can only do this once per turning point, and cannot do so after the final activation of the turning point." },
  { kind: 'strategy', name: "Sniper Positions", text: "Whenever a friendly RATLING operative is more than 6\" from enemy operatives and within 1\" of Heavy terrain, the stationary profile of its rifle (if any) has the Silent weapon rule." },
  { kind: 'strategy', name: "Shifty", text: "Whenever a friendly RATLING operative (excluding OGRYN or BULLGRYN) has a Conceal order and is in cover, it cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2\"." },
  { kind: 'strategy', name: "Crack Shots", text: "Whenever a friendly RATLING operative is shooting an enemy operative more than 6\" from it, if that friendly operative hasn’t performed the Charge, Fall Back or Reposition action during the activation, or if it’s a counteraction, its rifle (if any) has the Balanced weapon rule. Note that operative isn’t restricted from performing those actions after shooting." },
  { kind: 'strategy', name: "Frontline Assault", text: "Whenever a friendly RATLING BULLGRYN or friendly RATLING OGRYN operative within your opponent’s territory or within 3\" of an objective marker is shooting, fighting or retaliating, its weapons have the Balanced weapon rule." },
  { kind: 'firefight', name: "Survival Instincts", text: "Use this firefight ploy when an enemy operative is shooting against or fighting against a friendly RATLING operative (excluding OGRYN or BULLGRYN) and you’re allocating a dice to block. If it’s a normal success, it can block one unresolved critical success; if it’s a critical success, it can block two unresolved successes (normal or critical)." },
  { kind: 'firefight', name: "Larcenous", text: "Use this firefight ploy during a friendly RATLING operative’s activation (excluding OGRYN or BULLGRYN). Until the end of that activation, that operative doesn’t have to control a marker to perform the Pick Up Marker or mission actions that usually require this (this takes precedence over that action’s conditions – it only needs to contest the marker), and having an enemy operative within its control range doesn’t prevent it from doing so." },
  { kind: 'firefight', name: "Sharpshot", text: "Use this firefight ploy when a friendly RATLING operative is performing the Shoot action with a rifle and you’re selecting a valid target. Having other friendly RATLING operatives within an enemy operative’s control range doesn’t prevent that enemy operative from being selected." },
  { kind: 'firefight', name: "Shoot and Hide", text: "Use this firefight ploy after a friendly RATLING operative that has an Engage order performs the Shoot action with a rifle. If it’s more than 3\" from enemy operatives, or not visible to every enemy operative, you can change its order to Conceal." },
  { kind: 'equipment', name: "Purloined Rations", text: "Once per turning point, when a friendly RATLING operative is shooting with a rifle and you’ve rolled your attack dice, you can use this rule. If you do, improve the Hit stat of its rifle by 1 until the end of that sequence. This can allow you to apply the Hit stat change during an action (this takes precedence over the core rules)." },
  { kind: 'equipment', name: "Stolen Goods", text: "At the end of the Select Operatives step, roll one D3. If the result is:\n• 1, you lose 1CP.\n• 2, you gain 1CP.\n• 3, your opponent loses 1CP." },
  { kind: 'equipment', name: "Lucky Round", text: "Once per turning point, when a friendly RATLING operative is shooting with a rifle and you’ve rolled your attack dice, you can use this rule. If you do, that weapon has the Severe weapon rule until the end of that sequence." },
  { kind: 'equipment', name: "Improvised Armour", text: "Whenever an operative is shooting a friendly RATLING BULLGRYN or friendly RATLING\nOGRYN operative, defence dice results of 5+ are critical successes." },
]

export const operatives: Operative[] = [
  { id: "ratlings:ratling-fixer", name: "Ratling Fixer", apl: 2, move: "5\"", save: "5+", w: 7 },
  { id: "ratlings:ratling-battlemutt", name: "Ratling Battlemutt", apl: 2, move: "6\"", save: "5+", w: 4 },
  { id: "ratlings:bullgryn", name: "Bullgryn", apl: 2, move: "6\"", save: "4+", w: 16 },
  { id: "ratlings:ogryn", name: "Ogryn", apl: 2, move: "6\"", save: "5+", w: 16 },
  { id: "ratlings:ratling-big-shot", name: "Ratling Big Shot", apl: 2, move: "5\"", save: "5+", w: 6 },
  { id: "ratlings:ratling-bomber", name: "Ratling Bomber", apl: 2, move: "5\"", save: "4+", w: 6 },
  { id: "ratlings:ratling-hardbit", name: "Ratling Hardbit", apl: 2, move: "5\"", save: "5+", w: 6 },
  { id: "ratlings:ratling-raider", name: "Ratling Raider", apl: 2, move: "5\"", save: "5+", w: 6 },
  { id: "ratlings:ratling-sneak", name: "Ratling Sneak", apl: 2, move: "5\"", save: "5+", w: 6 },
  { id: "ratlings:ratling-sniper", name: "Ratling Sniper", apl: 2, move: "5\"", save: "5+", w: 6 },
  { id: "ratlings:ratling-spotter", name: "Ratling Spotter", apl: 2, move: "5\"", save: "5+", w: 6 },
  { id: "ratlings:ratling-stashmaster", name: "Ratling Stashmaster", apl: 2, move: "5\"", save: "5+", w: 6 },
  { id: "ratlings:ratling-vox-thief", name: "Ratling Vox-thief", apl: 2, move: "5\"", save: "5+", w: 6 },
]

export const datacards: Datacard[] = [
  {"name": "Ratling Fixer", "weapons": [{"name": "Battle rifle", "atk": 4, "hit": "2+", "dmg": "3/4"}, {"name": "Sniper rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Sniper rifle (stationary)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy"}, {"name": "Fists", "atk": 3, "hit": "5+", "dmg": "1/2"}], "abilities": [{"name": "Munitorum Contacts", "text": "You can select one           Target Designation: STRATEGIC GAMBIT. Select one enemy operative. Until the additional equipment option.                     end of the turning point, whenever a friendly RATLING operative is shooting that enemy operative with a rifle, that weapon has the Lethal 5+ weapon rule."}], "actions": [], "keywords": ["RATLING", "IMPERIUM", "ASTRA MILITARUM", "LEADER", "FIXER"]},
  {"name": "Ratling Battlemutt", "weapons": [{"name": "Bite", "atk": 4, "hit": "3+", "dmg": "2/4"}], "abilities": [{"name": "Early Warning", "text": "Once per turning point, after an enemy operative performs an action in which it moves or is set up, you can interrupt to use this rule. If you do, each friendly RATLING operative (excluding OGRYN and BULLGRYN) within 6\" of this operative and within 2\" of that enemy operative can immediately perform a free Dash or Fall Back action in an order of your choice (choose separately for each), but it cannot move more than 3\" during that action. In either case, each one cannot end that move within 2\" of an enemy operative unless it’s not visible to every enemy operative when it ends that move (if this isn’t possible for an operative, it cannot move)."}, {"name": "Beast", "text": "This operative cannot perform any actions other than Charge, Dash, Fall Back, Fight and Reposition. It cannot use any weapons that aren’t on its datacard."}], "actions": [], "keywords": ["RATLING", "IMPERIUM", "ASTRA MILITARUM", "BATTLEMUTT"]},
  {"name": "Bullgryn", "weapons": [{"name": "Grenadier gauntlet", "atk": 4, "hit": "4+", "dmg": "3/5", "wr": "Blast 2\""}, {"name": "Power maul", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Shock"}, {"name": "Brute shield", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Slabshield", "atk": 4, "hit": "4+", "dmg": "3/4"}], "abilities": [{"name": "Shield", "text": "If this operative has a slabshield, it has a 3+ Save stat; if it has a brute shield, whenever it’s fighting or retaliating, each of your blocks can be allocated to block two unresolved successes (instead of one)."}, {"name": "Brute", "text": "Whenever your opponent is selecting a valid target, if this operative has a Conceal order, it cannot use Light terrain for cover. While this can allow this operative to be targeted (assuming it’s visible), it doesn’t remove its cover save (if any)."}, {"name": "Slow-witted", "text": "You must spend 1 additional AP for this operative to perform the Pick Up Marker and mission actions (excluding Operate Hatch)."}], "actions": [], "keywords": ["RATLING", "IMPERIUM", "ASTRA MILITARUM", "BULLGRYN"]},
  {"name": "Ogryn", "weapons": [{"name": "Ripper gun", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Punishing"}, {"name": "Bayonet", "atk": 4, "hit": "3+", "dmg": "4/5"}], "abilities": [{"name": "Bayonet Charge", "text": "Whenever this operative finishes moving during the Charge action, you can inflict D3+1 damage on one enemy operative within its control range."}, {"name": "Brute", "text": "Whenever your opponent is selecting a valid target, if this operative has a Conceal order, it cannot use Light terrain for cover. While this can allow this operative to be targeted (assuming it’s visible), it doesn’t remove its cover save (if any)."}, {"name": "Slow-witted", "text": "You must spend 1 additional AP for this operative to perform the Pick Up Marker and mission actions (excluding Operate Hatch)."}], "actions": [], "keywords": ["RATLING", "IMPERIUM", "ASTRA MILITARUM", "OGRYN"]},
  {"name": "Ratling Big Shot", "weapons": [{"name": "Tankstopper rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Devastating 1, Heavy (Dash only), Piercing 1"}, {"name": "Tankstopper rifle (stationary)", "atk": 4, "hit": "2+", "dmg": "4/2", "wr": "Devastating 4, Heavy, Piercing 1, Severe"}, {"name": "Fists", "atk": 3, "hit": "5+", "dmg": "1/2"}], "abilities": [], "actions": [], "keywords": ["RATLING", "IMPERIUM", "ASTRA MILITARUM", "BIG SHOT"]},
  {"name": "Ratling Bomber", "weapons": [{"name": "Explosive arsenal", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Range 3\", Blast 1\", Heavy (Reposition only),"}], "abilities": [{"name": "Tripwire", "text": "When setting up equipment before the battle, you can set up to two of your Tripwire markers up wholly within your territory and more than 2\" from other markers, access points and Accessible terrain. The first time that marker is within an enemy operative’s control range, remove that marker, subtract 1 from that operative’s APL stat until the end of its next activation and end its action (if any), even if that action’s effects aren’t fulfilled. If it cannot be placed, move it the minimum amount to do so."}, {"name": "Mine", "text": "Mines you select from universal equipment inflict 2D3+3 damage instead, and friendly RATLING operatives (excluding OGRYN and BULLGRYN) are ignored for your mines’ effects (i.e. they cannot trigger or take damage from them). This takes precedence over the normal mines rules."}], "actions": [], "keywords": ["RATLING", "IMPERIUM", "ASTRA MILITARUM", "BOMBER"]},
  {"name": "Ratling Hardbit", "weapons": [{"name": "Battle rifle", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Combat knife", "atk": 3, "hit": "3+", "dmg": "3/5", "wr": "Balanced"}], "abilities": [{"name": "Hunter", "text": "This operative can perform the Charge action while it               Lie in Wait: Whenever this operative is retaliating while Light has a Conceal order. If it does so during its activation, until the         or Heavy terrain is within its control range, you resolve the first end of that activation, add 1 to the Atk stat of its combat knife           attack dice (i.e. defender instead of attacker). and that melee weapon has the Brutal weapon rule."}], "actions": [], "keywords": ["RATLING", "IMPERIUM", "ASTRA MILITARUM", "HARDBIT"]},
  {"name": "Ratling Raider", "weapons": [{"name": "Suppressed sniper rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Silent"}, {"name": "Suppressed sniper rifle (stationary)", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Devastating 2, Heavy, Silent"}, {"name": "Dagger", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Grappling Hook", "text": "Whenever this operative is climbing up, you can treat the vertical distance as 2\" (regardless of how far the operative actually moves vertically)."}], "actions": [{"name": "Slingshot", "ap": 1, "text": "Select a point on a terrain feature; that point must be visible to and within 6\" of this operative. Remove this operative from the killzone and set it back up in a location it can be placed\nwholly within 6\" horizontally of that point, not within control\nrange of enemy operatives, and with that point visible to it.\nThis action is treated as a Reposition action. This operative cannot perform this action while within control range of an enemy operative, or during an activation in which it performed the Charge, Fall Back or Shoot action (or vice versa)."}], "keywords": ["RATLING", "IMPERIUM", "ASTRA MILITARUM", "RAIDER"]},
  {"name": "Ratling Sneak", "weapons": [{"name": "Suppressed sniper rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Silent"}, {"name": "Suppressed sniper rifle (stationary)", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Devastating 2, Heavy, Silent"}, {"name": "Fists", "atk": 3, "hit": "5+", "dmg": "1/2"}], "abilities": [{"name": "Evade", "text": "Once per turning point, after an enemy operative performs an action, you can interrupt and perform a free Dash\naction with this operative. Note this operative cannot use the\nScarper faction rule (it has this rule instead)."}], "actions": [{"name": "Optics", "ap": 1, "text": "Until the start of this operative’s next activation, whenever\nit’s shooting, enemy operatives cannot be obscured and the\nstationary profile of this operative’s suppressed sniper rifle has the Lethal 5+ weapon rule.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["RATLING", "IMPERIUM", "ASTRA MILITARUM", "SNEAK"]},
  {"name": "Ratling Sniper", "weapons": [{"name": "Sniper rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Sniper rifle (stationary)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy"}, {"name": "Fists", "atk": 3, "hit": "5+", "dmg": "1/2"}], "abilities": [], "actions": [], "keywords": ["RATLING", "IMPERIUM", "ASTRA MILITARUM", "SNIPER"]},
  {"name": "Ratling Spotter", "weapons": [{"name": "Sniper rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Sniper rifle (stationary)", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Devastating 3, Heavy"}, {"name": "Fists", "atk": 3, "hit": "5+", "dmg": "1/2"}], "abilities": [], "actions": [{"name": "Spot", "ap": 1, "text": "SUPPORT. Select one enemy operative visible to this operative. Until the end of the turning point, whenever a friendly RATLING operative within 3\" of this operative is shooting that enemy operative, you can use this effect. If you do:\n• That friendly operative’s ranged weapons have the Seek Light weapon rule. • That enemy operative cannot be obscured.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["RATLING", "IMPERIUM", "ASTRA MILITARUM", "SPOTTER"]},
  {"name": "Ratling Stashmaster", "weapons": [{"name": "Sniper rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Sniper rifle (stationary)", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Devastating 3, Heavy"}, {"name": "Fists", "atk": 3, "hit": "5+", "dmg": "1/2"}], "abilities": [{"name": "Light-fingered", "text": "Once during each of this operative’s activations,           Well Stocked: If you select an Ammo Cache from universal it can perform the Pick Up Marker, Place Marker or a                        equipment, you can set up an additional Ammo Cache marker. mission action for 1 less AP."}], "actions": [], "keywords": ["RATLING", "IMPERIUM", "ASTRA MILITARUM", "STASHMASTER"]},
  {"name": "Ratling Vox-thief", "weapons": [{"name": "Sniper rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Sniper rifle (stationary)", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Devastating 3, Heavy"}, {"name": "Fists", "atk": 3, "hit": "5+", "dmg": "1/2"}], "abilities": [], "actions": [{"name": "Intercept Communications", "ap": 1, "text": "SUPPORT. Select one other friendly RATLING operative visible to and within 6\" of this operative. Until the end of its next activation, add 1 to that operative’s APL stat.\nThis operative cannot perform this action while within control range of an enemy operative.\nNOTES:"}], "keywords": ["RATLING", "IMPERIUM", "ASTRA MILITARUM", "VOX-THIEF"]},
]
