// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Burrow", text: "When setting up a RAVENER kill team before the battle, your first two operatives must be set up as normal. Each other friendly RAVENER operative thereafter can be set up underground: place it to one side instead of in the killzone.\nIn the Firefight phase, friendly RAVENER operatives set up underground are activated and can counteract as normal. Whenever a friendly\nRAVENER operative is underground, it cannot perform any actions other than Burrow. At the end of the battle, each friendly RAVENER operative that’s underground is incapacitated." },
  { kind: 'faction', name: "Tunnel", text: "At the end of the Set Up Operatives step, place your Tunnel marker numbered ‘0’ on the killzone floor, wholly within your drop zone and touching your killzone edge. As a STRATEGIC GAMBIT in the first four turning points, you can place your next numbered Tunnel marker on the killzone floor wholly within 5\" of your preceding Tunnel marker. This means that, as the battle progresses, you can have a series of sequentially numbered Tunnel markers (0, 1, 2, 3 and 4). Once you have placed five Tunnel markers, don’t place any more (i.e. if your battle lasts more than four turning points). Your Tunnel markers and the area between your sequentially numbered markers (i.e. between 0 and 1, 1 and 2, etc.), create your TUNNEL." },
  { kind: 'faction', name: "Predatory Instincts", text: "During each friendly RAVENER operative’s activation, it can perform two Fight actions. Each friendly RAVENER operative can counteract regardless of its order. Whenever it does:\n• You can change its order first, or change its order instead of performing an action (for the latter, still treat it as having counteracted this turning point).\n• During that counteraction, if it doesn’t perform a mission action it can perform a free\nBurrow action." },
  { kind: 'strategy', name: "Death from Below", text: "Whenever a friendly RAVENER operative is fighting:\n• If it’s performed the Burrow action during that activation/counteraction, its melee weapons have the Balanced weapon rule.\n• If it’s on your TUNNEL, its melee weapons have the Ceaseless weapon rule." },
  { kind: 'strategy', name: "Whipcord Emergence", text: "Whenever an operative is shooting a friendly RAVENER operative:\n• If that friendly operative has performed the\nBurrow action during that turning point, you can re-roll one of your defence dice.\n• If that friendly operative is on your TUNNEL, you can re-roll any of your defence dice results of one result." },
  { kind: 'strategy', name: "Tunnel Lurkers", text: "Whenever a friendly RAVENER operative is on your TUNNEL it’s in cover, unless it’s within 2\" of the active operative. Treat this as cover provided by Light terrain (therefore it’s affected by rules that prevent this, e.g. Seek Light and\nVantage terrain)." },
  { kind: 'strategy', name: "Writhe Out of Sight", text: "Select one friendly RAVENER operative in the killzone. That friendly operative can immediately perform a free Burrow action. If it’s within 2\" of your TUNNEL, it can immediately perform a free\nFall Back or Reposition action before it does so." },
  { kind: 'firefight', name: "Slithering Evasion", text: "Use this firefight ploy during a friendly RAVENER operative’s activation or counteraction, before or after it performs an action. During that activation/ counteraction, that operative can:\n• Perform the Fall Back action for 1 less AP.\n• Perform the Charge action while within control range of an enemy operative, and can leave that operative’s control range to do so (but then normal requirements for that move apply)." },
  { kind: 'firefight', name: "Subterranean Horror", text: "Use this firefight ploy when an enemy operative is performing the Fight action and selects a friendly RAVENER operative on your TUNNEL to fight against. In the Resolve Attack Dice step of that sequence, you resolve the first attack dice (i.e. defender instead of attacker)." },
  { kind: 'firefight', name: "Death Frenzy", text: "Use this firefight ploy when a friendly RAVENER operative is incapacitated. Before that operative is removed from the killzone, inflict D3 damage on each enemy operative within its control range (roll separately for each). If that friendly operative is a VENOMSPITTER that’s currently benefitting from the effects of its Distend Dorsal Sac action, inflict 2D3 damage instead." },
  { kind: 'firefight', name: "Burrowing Strike", text: "Use this firefight ploy when a friendly RAVENER operative performs the Burrow action. Before that operative is removed from the killzone, or after setting it up on your TUNNEL, inflict D3+1 damage on each enemy operative within its control range (roll separately for each). You cannot use this ploy in the Strategy phase, or during a FELLTALON operative’s activation or counteraction if it performs the Toxic Lunge action (and vice versa)." },
  { kind: 'equipment', name: "Chromatospore Camouflage", text: "Whenever an operative is shooting a friendly RAVENER operative, if you can retain any cover saves, you can retain one additional cover save. This isn’t cumulative with improved cover saves from Vantage terrain." },
  { kind: 'equipment', name: "Acid Blood", text: "Whenever a friendly RAVENER operative is fighting or retaliating, whenever an attack dice inflicts damage on it, roll one D6: on a 5+, inflict 1 damage on the enemy operative in that sequence." },
  { kind: 'equipment', name: "Heightened Senses", text: "Once per battle, after rolling off to decide initiative, if a friendly RAVENER operative is underground and an enemy operative is within 5\" of your TUNNEL, you can re-roll your dice." },
  { kind: 'equipment', name: "Metamorphic Flesh", text: "Whenever a friendly RAVENER operative is activated, it regains up to D3 lost wounds.\nNOTES:" },
]

export const operatives: Operative[] = [
  { id: "rav:ravener-prime", name: "Ravener Prime", apl: 3, move: "7\"", save: "5+", w: 19 },
  { id: "rav:ravener-felltalon", name: "Ravener Felltalon", apl: 3, move: "7\"", save: "5+", w: 18 },
  { id: "rav:ravener-tremorscythe", name: "Ravener Tremorscythe", apl: 3, move: "7\"", save: "5+", w: 18 },
  { id: "rav:ravener-venomspitter", name: "Ravener Venomspitter", apl: 3, move: "7\"", save: "5+", w: 18 },
  { id: "rav:ravener-warrior", name: "Ravener Warrior", apl: 3, move: "7\"", save: "5+", w: 18 },
  { id: "rav:ravener-wrecker", name: "Ravener Wrecker", apl: 3, move: "7\"", save: "4+", w: 18 },
]
