// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Blaze", text: "Whenever an operative that has one of your Blaze tokens is activated, inflict D3 damage on it. Then that operative’s controlling player selects one of the following:\n• Roll one D6: on a 3+, remove that token.\n• Subtract 1 from the operative’s APL stat until the end of that activation to remove that token." },
  { kind: 'faction', name: "Ministorum Sermon", text: "STRATEGIC GAMBIT. Select one friendly SANCTIFIER operative. If a friendly CONFESSOR operative hasn’t been incapacitated, you must select it. Until you use this STRATEGIC GAMBIT again during the battle, that operative has the\nORATOR keyword.\nWhenever a friendly SANCTIFIER operative is within 3\" of a friendly ORATOR operative (or 6\" if the ORATOR is a CONFESSOR), that friendly\nSANCTIFIER operative is benefitting from the SERMON." },
  { kind: 'strategy', name: "The Emperor Protects", text: "Whenever an operative is shooting a friendly SANCTIFIER operative that’s benefitting from the SERMON, you can re-roll any of your defence dice results of one result (e.g. results of 2)." },
  { kind: 'strategy', name: "Fervent Brawl", text: "Whenever a friendly SANCTIFIER operative that’s benefitting from the SERMON is fighting or retaliating, its melee weapons have the Ceaseless weapon rule." },
  { kind: 'strategy', name: "Zealous Persecution", text: "Whenever a friendly SANCTIFIER operative is fighting during an activation in which it performed the Charge action, its melee weapons have the Lethal 5+ weapon rule." },
  { kind: 'firefight', name: "Rosarius", text: "Use this firefight ploy when an attack dice inflicts Normal Dmg on a friendly SANCTIFIER operative. Ignore that inflicted damage." },
  { kind: 'strategy', name: "Rally the Flock", text: "Each friendly SANCTIFIER operative (excluding ORATOR) that’s benefitting from the SERMON can immediately perform a free Dash or Fall Back action in an order of your choice (choose separately for each and, for the latter, it cannot move more than 3\"). Each that does so must end that move closer and visible to (or vice versa) a friendly ORATOR operative. You cannot use this ploy during the first turning point." },
  { kind: 'firefight', name: "Ardent Eradication", text: "Use this firefight ploy after rolling your attack dice for a friendly SANCTIFIER operative, if it’s shooting against or fighting against an enemy operative that’s within 3\" of a friendly ORATOR operative (or 6\" if the ORATOR is a CONFESSOR). You can re-roll any of your attack dice." },
  { kind: 'firefight', name: "Redeemed Through Fire", text: "Use this firefight ploy when a friendly SANCTIFIER operative that has a weapon with the Blaze weapon rule is incapacitated, before it’s removed from the killzone. Each enemy operative visible to and within 2\" of it gains one of your Blaze tokens (if it doesn’t already have one)." },
  { kind: 'equipment', name: "Sanctification Orbs", text: "Once per turning point, one friendly SANCTIFIER operative (excluding CHERUB, DEATH CULT ASSASSIN and MIRACULIST) can perform the following unique action:" },
  { kind: 'firefight', name: "Unwavering Devotion", text: "Use this firefight ploy when a friendly SANCTIFIER ORATOR or SANCTIFIER MIRACULIST operative is selected as the valid target of a Shoot action or to fight against during the Fight action. Select one other friendly SANCTIFIER operative (excluding CONFESSOR, MIRACULIST and ORATOR) visible to and within 3\" of that first friendly operative to become the valid target or to be fought against (as appropriate) instead (even if it wouldn’t normally be valid for this). If it’s the Fight action, treat that other operative as being within the fighting operative’s control range for the duration of that action. If it’s the Shoot action, that other operative is only in cover or obscured if the original target was. This ploy has no effect if it’s the Shoot action and the ranged weapon has the Blast or Torrent weapon rule.\nSANCTIFICATION ORB (1AP): Select one enemy operative visible to and within 6\" of this operative. That operative and each other enemy operative within 1\" of it takes a doused test. For an operative to take a doused test, roll one D6: on a 3+, it gains one of your Doused tokens.\nWhenever a friendly SANCTIFIER operative is shooting an operative that has one of your Doused tokens with a weapon that has the Blaze weapon rule, that weapon also has the Seek weapon rule. After a friendly SANCTIFIER operative uses a weapon that has the Blaze weapon rule against an enemy operative that has one of your Doused tokens, remove that token (even if the Seek weapon rule wasn’t used). This operative cannot perform this action while within control range of an enemy operative." },
  { kind: 'equipment', name: "Purity Seals", text: "Once per turning point, when a friendly SANCTIFIER operative is shooting or fighting, if you roll two or more fails, you can discard one of them to retain another as a normal success instead." },
  { kind: 'equipment', name: "Imperial Cult Symbols", text: "Once per turning point, when an operative is shooting a friendly SANCTIFIER operative that’s benefitting from the SERMON, when you collect your defence dice, you can use this rule. If you do, change one of the attacker’s retained critical successes to a normal success (any weapon rules they’ve already resolved aren’t affected, e.g. Piercing Crits)." },
  { kind: 'equipment', name: "Ecclesiarchy Texts", text: "In the Ready step of each Strategy phase, roll 3D6: if the result is less than the remaining wounds of a friendly ORATOR operative, you gain 1CP. Note that this is done before the Gambit step, so if there isn’t a valid ORATOR operative, you cannot use this rule during that turning point (e.g. during the first turning point).\nNOTES:" },
]

export const operatives: Operative[] = [
  { id: "sanctifiers:sanctifier-confessor", name: "Sanctifier Confessor", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "sanctifiers:sanctifier-cherub", name: "Sanctifier Cherub", apl: 2, move: "7\"", save: "5+", w: 5 },
  { id: "sanctifiers:sanctifier-conflagrator", name: "Sanctifier Conflagrator", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "sanctifiers:sanctifier-death-cult-assassin", name: "Sanctifier Death Cult Assassin", apl: 3, move: "6\"", save: "5+", w: 8 },
  { id: "sanctifiers:sanctifier-drill-abbot", name: "Sanctifier Drill Abbot", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "sanctifiers:sanctifier-persecutor", name: "Sanctifier Persecutor", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "sanctifiers:sanctifier-miraculist", name: "Sanctifier Miraculist", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "sanctifiers:sanctifier-missionary", name: "Sanctifier Missionary", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "sanctifiers:sanctifier-preacher", name: "Sanctifier Preacher", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "sanctifiers:sanctifier-reliquant", name: "Sanctifier Reliquant", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "sanctifiers:sanctifier-salvationist", name: "Sanctifier Salvationist", apl: 2, move: "6\"", save: "5+", w: 7 },
]
