// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Blaze", text: "Whenever an operative that has one of your Blaze tokens is activated, inflict D3 damage on it. Then that operative’s controlling player selects one of the following:\n• Roll one D6: on a 3+, remove that token.\n• Subtract 1 from the operative’s APL stat until the end of that activation to remove that token." },
  { kind: 'faction', name: "Ministorum Sermon", text: "STRATEGIC GAMBIT. Select one friendly SANCTIFIER operative. If a friendly CONFESSOR operative hasn’t been incapacitated, you must select it. Until you use this STRATEGIC GAMBIT again during the battle, that operative has the\nORATOR keyword.\nWhenever a friendly SANCTIFIER operative is within 3\" of a friendly ORATOR operative (or 6\" if the ORATOR is a CONFESSOR), that friendly\nSANCTIFIER operative is benefitting from the SERMON." },
  { kind: 'strategy', name: "The Emperor Protects", text: "Whenever an operative is shooting a friendly SANCTIFIER operative that’s benefitting from the SERMON, you can re-roll any of your defence dice results of one result (e.g. results of 2)." },
  { kind: 'strategy', name: "Fervent Brawl", text: "Whenever a friendly SANCTIFIER operative that’s benefitting from the SERMON is fighting or retaliating, its melee weapons have the Ceaseless weapon rule." },
  { kind: 'strategy', name: "Zealous Persecution", text: "Whenever a friendly SANCTIFIER operative is fighting during an activation in which it performed the Charge action, its melee weapons have the Lethal 5+ weapon rule." },
  { kind: 'firefight', name: "Rosarius", text: "Use this firefight ploy when an attack dice inflicts Normal Dmg on a friendly SANCTIFIER operative. Ignore that inflicted damage." },
  { kind: 'strategy', name: "Rally the Flock", text: "Each friendly SANCTIFIER operative (excluding ORATOR) that’s benefitting from the SERMON can immediately perform a free Dash or Fall Back action in an order of your choice (choose separately for each and, for the latter, it cannot move more than 3\"). Each that does so must end that move closer and visible to (or vice versa) a friendly ORATOR operative. You cannot use this ploy during the first turning point." },
  { kind: 'firefight', name: "Ardent Eradication", text: "Use this firefight ploy after rolling your attack dice for a friendly SANCTIFIER operative, if it’s shooting against or fighting against an enemy operative that’s within 3\" of a friendly ORATOR operative (or 6\" if the ORATOR is a CONFESSOR). You can re-roll any of your attack dice." },
  { kind: 'firefight', name: "Redeemed Through Fire", text: "Use this firefight ploy when a friendly SANCTIFIER operative that has a weapon with the Blaze weapon rule is incapacitated, before it’s removed from the killzone. Each enemy operative visible to and within 2\" of it gains one of your Blaze tokens (if it doesn’t already have one)." },
  { kind: 'equipment', name: "Sanctification Orbs", text: "Once per turning point, one friendly SANCTIFIER operative (excluding CHERUB, DEATH CULT ASSASSIN and MIRACULIST) can perform the following unique action:" },
  { kind: 'firefight', name: "Unwavering Devotion", text: "Use this firefight ploy when a friendly SANCTIFIER ORATOR or SANCTIFIER MIRACULIST operative is selected as the valid target of a Shoot action or to fight against during the Fight action. Select one other friendly SANCTIFIER operative (excluding CONFESSOR, MIRACULIST and ORATOR) visible to and within 3\" of that first friendly operative to become the valid target or to be fought against (as appropriate) instead (even if it wouldn’t normally be valid for this). If it’s the Fight action, treat that other operative as being within the fighting operative’s control range for the duration of that action. If it’s the Shoot action, that other operative is only in cover or obscured if the original target was. This ploy has no effect if it’s the Shoot action and the ranged weapon has the Blast or Torrent weapon rule.\nSANCTIFICATION ORB (1AP): Select one enemy operative visible to and within 6\" of this operative. That operative and each other enemy operative within 1\" of it takes a doused test. For an operative to take a doused test, roll one D6: on a 3+, it gains one of your Doused tokens.\nWhenever a friendly SANCTIFIER operative is shooting an operative that has one of your Doused tokens with a weapon that has the Blaze weapon rule, that weapon also has the Seek weapon rule. After a friendly SANCTIFIER operative uses a weapon that has the Blaze weapon rule against an enemy operative that has one of your Doused tokens, remove that token (even if the Seek weapon rule wasn’t used). This operative cannot perform this action while within control range of an enemy operative." },
  { kind: 'equipment', name: "Purity Seals", text: "Once per turning point, when a friendly SANCTIFIER operative is shooting or fighting, if you roll two or more fails, you can discard one of them to retain another as a normal success instead." },
  { kind: 'equipment', name: "Imperial Cult Symbols", text: "Once per turning point, when an operative is shooting a friendly SANCTIFIER operative that’s benefitting from the SERMON, when you collect your defence dice, you can use this rule. If you do, change one of the attacker’s retained critical successes to a normal success (any weapon rules they’ve already resolved aren’t affected, e.g. Piercing Crits)." },
  { kind: 'equipment', name: "Ecclesiarchy Texts", text: "In the Ready step of each Strategy phase, roll 3D6: if the result is less than the remaining wounds of a friendly ORATOR operative, you gain 1CP. Note that this is done before the Gambit step, so if there isn’t a valid ORATOR operative, you cannot use this rule during that turning point (e.g. during the first turning point).\nNOTES:" },
]

export const operatives: Operative[] = [
  { id: "sanctifiers:sanctifier-confessor", name: "Sanctifier Confessor", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "sanctifiers:sanctifier-cherub", name: "Sanctifier Cherub", apl: 2, move: "7\"", save: "5+", w: 5 },
  { id: "sanctifiers:sanctifier-conflagrator", name: "Sanctifier Conflagrator", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "sanctifiers:sanctifier-death-cult-assassin", name: "Sanctifier Death Cult Assassin", apl: 3, move: "6\"", save: "5+", w: 8 },
  { id: "sanctifiers:sanctifier-drill-abbot", name: "Sanctifier Drill Abbot", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "sanctifiers:sanctifier-persecutor", name: "Sanctifier Persecutor", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "sanctifiers:sanctifier-miraculist", name: "Sanctifier Miraculist", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "sanctifiers:sanctifier-missionary", name: "Sanctifier Missionary", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "sanctifiers:sanctifier-preacher", name: "Sanctifier Preacher", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "sanctifiers:sanctifier-reliquant", name: "Sanctifier Reliquant", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "sanctifiers:sanctifier-salvationist", name: "Sanctifier Salvationist", apl: 2, move: "6\"", save: "5+", w: 7 },
]

export const datacards: Datacard[] = [
  {"name": "Sanctifier Confessor", "weapons": [{"name": "Mace of Censure", "atk": 4, "hit": "3+", "dmg": "5/5", "wr": "Brutal, Shock"}], "abilities": [{"name": "Lead the Procession", "text": "In each turning point after the first, whenever this operative is an ORATOR and performs the Charge, Fall Back or Reposition action during its activation, you can use this rule before it moves. If you do, determine each other friendly SANCTIFIER operative that’s benefitting from the SERMON and is visible to this operative (or vice versa). After this operative ends that action, each of those friendly SANCTIFIER operatives can immediately perform a free Charge, Fall Back or Reposition action in an order of your choice (choose separately for each), but each cannot move more than or be removed and set up more than 3\" and must end that move in a location where they are still benefitting from the SERMON. If this operative is incapacitated before this rule is fully resolved, e.g. from the Guard action’s interruption (see close quarters rules, Kill Team Core Book), don’t remove it from the killzone until this rule has been resolved."}, {"name": "Commanding Declamation", "text": "Whenever an enemy operative would perform an action during an activation or counteraction while visible to and within 6\" of this operative, you can use this rule. If you do, roll one D6: if the result is higher than that enemy operative’s APL stat:\n• It cannot perform that action during that activation/ counteraction (the AP spent on it isn’t refunded). If it’s a counteraction, that counteraction ends. • You cannot use this rule again during the battle."}], "actions": [], "keywords": ["SANCTIFIER", "IMPERIUM", "ADEPTUS MINISTORUM", "LEADER", "CONFESSOR"]},
  {"name": "Sanctifier Cherub", "weapons": [{"name": "Incentiviser", "atk": 3, "hit": "5+", "dmg": "1/3", "wr": "Shock"}], "abilities": [{"name": "Fly", "text": "Whenever this operative is performing the Charge, Fall Back or Reposition action, it can FLY. If it does, don’t move it. Instead, remove it from the killzone and set it back up wholly within a distance equal to its Move stat horizontally of its original location (in a killzone that uses the close quarters rules, e.g. Killzone: Tomb World, this distance cannot be measured over or through Wall terrain). Note that it gains no additional distance when performing the Charge action. It must be set up in a location it can be placed, and unless it’s the Charge action, it cannot be set up within control range of an enemy operative."}], "actions": [{"name": "Incentivise", "ap": 1, "text": "SUPPORT. Select one other friendly SANCTIFIER operative (excluding CONFESSOR, DEATH CULT ASSASSIN, MIRACULIST and ORATOR) visible to and within 2\" of this operative. Until the end of that operative’s next activation, add 1 to its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["SANCTIFIER", "IMPERIUM", "ADEPTUS MINISTORUM", "CHERUB"]},
  {"name": "Sanctifier Conflagrator", "weapons": [{"name": "Twin hand flamers (focused)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 6\", Saturate, Torrent 2\", Blaze*"}, {"name": "Twin hand flamers (twin torrent)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 6\", Saturate, Torrent 0\", Twin Torrent¹, Blaze*"}, {"name": "Gun butts", "atk": 4, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Twin Torrent", "text": "Select up to two different valid targets that aren’t within control range of friendly operatives. Shoot with this weapon against both of them in an order of your choice (roll each sequence separately). Torrent 0\" means you cannot select secondary targets, but this weapon still has the Torrent weapon rule for all other rules purposes, e.g. the Condensed Stronghold rule (see Killzone: Volkus, Kill Team Core Book)."}, {"name": "Sanctification Rack", "text": "This operative can perform the Sanctification Orb action (see faction equipment). Doing so in this manner doesn’t count towards the once per turning point limit (i.e. if you also select that equipment for other operatives)."}], "actions": [], "keywords": ["SANCTIFIER", "IMPERIUM", "ADEPTUS MINISTORUM", "CONFLAGRATOR"]},
  {"name": "Sanctifier Death Cult Assassin", "weapons": [{"name": "Throwing knives", "atk": 4, "hit": "3+", "dmg": "2/5", "wr": "Range 6\", Silent"}, {"name": "Ritual blades", "atk": 4, "hit": "2+", "dmg": "4/6"}], "abilities": [{"name": "Bladed Stance", "text": "Whenever this operative is fighting or retaliating, you can resolve one of your successes before the normal order. If\nyou do, that success must be used to block."}], "actions": [{"name": "Trained Assassin", "ap": 1, "text": "Change this operative’s order.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["SANCTIFIER", "IMPERIUM", "ADEPTUS MINISTORUM", "DEATH CULT ASSASSIN"]},
  {"name": "Sanctifier Drill Abbot", "weapons": [{"name": "Great hammer", "atk": 4, "hit": "4+", "dmg": "4/4", "wr": "Brutal, Shock"}], "abilities": [{"name": "Schola Progenium Disciplinarian", "text": "Whenever a friendly SANCTIFIER operative is within 6\" of this operative, you can ignore any changes to that operative’s stats from being injured (including its weapons’ stats)."}, {"name": "Null Skull", "text": "Whenever an enemy operative is within 4\" of this operative, that enemy operative’s APL stat cannot be added to (remove all positive APL stat changes it has). If an enemy operative that’s more than 4\" from this operative has a positive APL stat change and your opponent spends its final AP to move that operative within 4\" of this operative, this can cause your opponent to have spent more AP than its APL stat – this is permitted in this situation."}], "actions": [], "keywords": ["SANCTIFIER", "IMPERIUM", "ADEPTUS MINISTORUM", "DRILL ABBOT"]},
  {"name": "Sanctifier Persecutor", "weapons": [{"name": "Hand flamer", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Range 6\", Saturate, Torrent 1\", Blaze*"}, {"name": "Eviscerator", "atk": 4, "hit": "4+", "dmg": "5/6", "wr": "Brutal"}], "abilities": [{"name": "Merciless Castigation", "text": "The first time this operative performs the Fight action during each of its activations, if neither it nor the enemy operative in that sequence is incapacitated, this operative can immediately perform a free Fight action afterwards, but you cannot select any other enemy operative to fight against during that action (and only if it’s still valid to fight against). This takes precedence over action restrictions."}, {"name": "Fanatical Retribution", "text": "If this operative is incapacitated during the Fight action, you can strike the enemy operative in that sequence with one of your unresolved successes before this operative is removed from the killzone."}], "actions": [], "keywords": ["SANCTIFIER", "IMPERIUM", "ADEPTUS MINISTORUM", "PERSECUTOR"]},
  {"name": "Sanctifier Miraculist", "weapons": [{"name": "Holy light", "atk": 4, "hit": "2+", "dmg": "4/3", "wr": "Range 8\", Devastating 3, Limited 1, Piercing 1, Saturate, Blaze*"}, {"name": "Wreathe in fire", "atk": 4, "hit": "2+", "dmg": "4/4", "wr": "Blast 1\", Limited 1, Wreathed¹, Blaze*"}, {"name": "Burning hands", "atk": 1, "hit": "2+", "dmg": "7/8", "wr": "Brutal, Limited 1, Blaze*"}, {"name": "Fists", "atk": 2, "hit": "5+", "dmg": "1/2"}], "abilities": [{"name": "Wreathed", "text": "This operative can perform the Shoot action with this weapon while within control range of an enemy operative. Don’t select a valid target. Instead, this operative is always the primary target, but only shoot against secondary targets and they cannot be in cover or obscured (in other words, determine Blast from this operative, but this operative isn’t affected)."}, {"name": "Miracle", "text": "The first time this operative would be incapacitated during the battle, it’s not incapacitated, has 1 wound remaining and cannot be incapacitated for the remainder of the action. All remaining attack dice are discarded (including yours if this operative is fighting or retaliating), then this operative can immediately perform a free Dash or Fall Back action (for the latter, it cannot move more than 3\"), even if it’s performed an action that prevents it from performing those actions."}], "actions": [], "keywords": ["SANCTIFIER", "IMPERIUM", "ADEPTUS MINISTORUM", "MIRACULIST"]},
  {"name": "Sanctifier Missionary", "weapons": [{"name": "Brazier of holy fire", "atk": 4, "hit": "2+", "dmg": "4/4", "wr": "Range 4\", Saturate, Torrent 1\", Blaze*"}, {"name": "Meltagun", "atk": 4, "hit": "4+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Ministorum flamer", "atk": 4, "hit": "2+", "dmg": "4/4", "wr": "Range 8\", Saturate, Torrent 2\", Blaze*"}, {"name": "Plasma gun (standard)", "atk": 4, "hit": "4+", "dmg": "4/6", "wr": "Piercing 1"}, {"name": "Plasma gun (supercharge)", "atk": 4, "hit": "4+", "dmg": "5/6", "wr": "Hot, Lethal 5+, Piercing 1"}, {"name": "Brazier of holy fire", "atk": 4, "hit": "4+", "dmg": "4/4", "wr": "Shock, Blaze*"}, {"name": "Chainsword", "atk": 4, "hit": "4+", "dmg": "4/5"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Holy Relic", "text": "If this operative has a holy relic, it’s always benefitting from the SERMON."}, {"name": "Spread the Word of the God-Emperor", "text": "Whenever this operative is more than 6\" from other friendly operatives, its weapons have the Severe weapon rule."}], "actions": [], "keywords": ["SANCTIFIER", "IMPERIUM", "ADEPTUS MINISTORUM", "MISSIONARY"]},
  {"name": "Sanctifier Preacher", "weapons": [{"name": "Hand flamer", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 6\", Saturate, Torrent 1\", Blaze*"}, {"name": "Chainsword", "atk": 4, "hit": "4+", "dmg": "4/5"}], "abilities": [{"name": "Defend the Faith", "text": "Whenever this operative controls an objective marker, it’s benefitting from the SERMON."}], "actions": [], "keywords": ["SANCTIFIER", "IMPERIUM", "ADEPTUS MINISTORUM", "PREACHER"]},
  {"name": "Sanctifier Reliquant", "weapons": [{"name": "Hand flamer", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 6\", Saturate, Torrent 1\", Blaze*"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Cult Icon", "text": "Whenever determining control of a marker within 4\" of this operative, treat the total APL stat of friendly SANCTIFIER operatives that contest it as 1 higher if at least one friendly SANCTIFIER operative contests that marker. Note this isn’t a change to the APL stat, so any changes are cumulative with this."}, {"name": "Imperial Cult Devotion", "text": "Once per turning point, when a ready friendly SANCTIFIER operative is incapacitated while visible to and within 6\" of this operative, you can use this rule. If you do, before that operative is removed from the killzone, it can perform one free action (excluding Fight), and you can change its order to do so. It’s then removed from the killzone as normal."}], "actions": [], "keywords": ["SANCTIFIER", "IMPERIUM", "ADEPTUS MINISTORUM", "RELIQUANT"]},
  {"name": "Sanctifier Salvationist", "weapons": [{"name": "Soulstave", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [{"name": "Conversion Field", "text": "Whenever an operative more than 6\" from this operative is shooting a friendly SANCTIFIER operative\nwithin 6\" of this operative, improve that friendly operative’s Save\nstat by 1."}], "actions": [{"name": "Medikit", "ap": 1, "text": "Select one friendly SANCTIFIER operative within this\noperative’s control range to regain up to 2D3 lost wounds.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["SANCTIFIER", "IMPERIUM", "ADEPTUS MINISTORUM", "MEDIC", "SALVATIONIST"]},
]
