// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Forward Scouting", text: "Perform a free Reposition action with one friendly operative that’s wholly within your drop zone.\nIt must end that move wholly within 3\" of your drop zone.\nTrip Alarm (2) Place one of your Trip Alarm markers more than 6\" from your opponent’s drop zone. During the first and second turning point, whenever a friendly SCOUT SQUAD operative is shooting an enemy operative that’s within 2\" of that marker, that friendly operative’s ranged weapons have the Seek weapon rule. In the Ready step of the third Strategy phase, remove that marker.\nAt the end of the Set Up Operatives step, you can select and resolve up to six Forward Scouting options. Each option has a number in brackets, which is the maximum number of times you can select and resolve it for the battle. For example, your six selections could be Reposition (2), Trip Alarm (1), Booby Trap (1) and Diversion (1). If both players have this rule, alternate resolving selection by selection, starting with the player with initiative.\nFORWARD SCOUTING OPTIONS ARE PRESENTED ON THEIR OWN CARDS\nBooby Trap (1) Place one of your Booby Trap markers more than 6\" from your opponent’s drop zone and more than 2\" from other markers, access points and Accessible terrain. The first time your Booby Trap marker is within an enemy operative’s control range, remove that marker and inflict 2D3 damage on that operative; if it isn’t incapacitated, end its action (if any), even if that action’s effects aren’t fulfilled. If it cannot be placed, move it the minimum amount to do so.\nTactical Manoeuvre (1)\nTwice per battle STRATEGIC GAMBIT. Select one friendly operative. Until the end of that operative’s next activation, add 1 to its APL stat.\nDiversion (1) Once per battle STRATEGIC GAMBIT. Select one enemy operative within 6\" of a killzone edge. Until the end of that operative’s next activation, subtract 1 from its APL stat.\nDevise Plan (1) You gain 1CP.\nDesignate Target (1) Select one enemy operative to gain one of your Target tokens. Whenever a friendly SCOUT SQUAD operative is shooting against, fighting against or retaliating against an enemy operative that has one of your Target tokens, you can re-roll one of your attack dice.\nSpy (1) Approved Ops only. Your opponent must reveal their selected tac op." },
  { kind: 'strategy', name: "Guerrilla Engagement", text: "Whenever an enemy operative is shooting a friendly SCOUT SQUAD operative, if that friendly operative is in cover and more than 6\" from enemy operatives it’s visible to, you can re-roll one of your defence dice." },
  { kind: 'strategy', name: "Ambush", text: "Whenever a friendly SCOUT SQUAD operative is shooting or fighting during its activation, if its order was changed from Conceal to Engage at the start of that activation, or it wasn’t visible to enemy operatives at the start of that activation:\n• That friendly operative’s weapons have the Balanced weapon rule.\n• If the target is expended, that friendly operative’s weapons have the Ceaseless weapon rule instead." },
  { kind: 'strategy', name: "Adaptable Training", text: "You can change the order of up to D3 friendly SCOUT SQUAD operatives that are more than 4\" from enemy operatives." },
  { kind: 'firefight', name: "Astartes Training", text: "Use this firefight ploy during a friendly SCOUT SQUAD operative’s activation. Until the end of that activation, that operative can do one of the following:\n• Perform two Fight actions.\n• Perform two Shoot actions if an Astartes shotgun, bolt pistol or boltgun is selected for at least one of them.\n• Perform two Shoot actions with a heavy bolter, missile launcher or sniper rifle, but 1 additional AP must be spent for the second action." },
  { kind: 'strategy', name: "Stealth Relocation", text: "Up to D3 friendly SCOUT SQUAD operatives that have a Conceal order and are more than 4\" from enemy operatives can immediately perform a free Dash action. You cannot use this ploy during the first turning point." },
  { kind: 'firefight', name: "Raw Physiology", text: "Use this firefight ploy during a friendly SCOUT SQUAD operative’s activation, before or after it performs an action. Until the start of its next activation, add 1\" to its Move stat and you can ignore any changes to that operative’s stats from being injured (including its weapons’ stats)." },
  { kind: 'firefight', name: "Emboldened Aspirant", text: "Use this firefight ploy when a friendly SCOUT SQUAD operative performs the Shoot or Fight action, after any re-rolls. If it’s the first friendly operative to perform either of those actions during this turning point, or if the enemy operative in that action (primary target, if relevant) has a higher Wounds stat than that friendly SCOUT SQUAD operative, you can retain one of your normal successes as a critical success instead." },
  { kind: 'equipment', name: "Camo Cloak", text: "Whenever an operative is shooting a friendly SCOUT SQUAD operative (excluding SNIPER), if you can retain any cover saves, you can retain one additional cover save. This isn’t cumulative with improved cover saves from Vantage terrain." },
  { kind: 'firefight', name: "Covert Position", text: "Use this firefight ploy during a friendly SCOUT SQUAD operative’s activation. Until the start of its next activation, while that operative has a Conceal order and is in cover, it cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2\"." },
  { kind: 'equipment', name: "Targeting Oculars", text: "Up to twice per turning point, when a friendly SCOUT SQUAD operative is performing the Shoot action and you’re selecting a valid target, you can use this rule. If you do, until the end of that action, that friendly operative’s ranged weapons have the Lethal 5+ and Saturate weapon rules." },
  { kind: 'equipment', name: "Combat Blades", text: "Friendly SCOUT SQUAD operatives have the following melee weapon — Combat blade: ATK 3, HIT 3+, DMG 4/5. Note that some operatives already have this weapon but with better stats; in that instance, use the better version." },
  { kind: 'equipment', name: "Tactical Vox-link", text: "Once per turning point, you can use the Astartes Training or Emboldened Aspirant firefight ploy for 0CP if a friendly SERGEANT operative is in the killzone." },
]

export const operatives: Operative[] = [
  { id: "sct:scout-sergeant", name: "Scout Sergeant", apl: 3, move: "6\"", save: "4+", w: 11 },
  { id: "sct:scout-heavy-gunner", name: "Scout Heavy Gunner", apl: 2, move: "6\"", save: "4+", w: 10 },
  { id: "sct:scout-hunter", name: "Scout Hunter", apl: 2, move: "6\"", save: "4+", w: 10 },
  { id: "sct:scout-sniper", name: "Scout Sniper", apl: 2, move: "6\"", save: "4+", w: 10 },
  { id: "sct:scout-tracker", name: "Scout Tracker", apl: 2, move: "6\"", save: "4+", w: 10 },
  { id: "sct:scout-warrior", name: "Scout Warrior", apl: 2, move: "6\"", save: "4+", w: 10 },
]
