// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Elite Fieldcraft (card 1/3)", text: "In the Ready step of each Strategy phase, you gain 1 Fieldcraft point, or 2 if a friendly SPECTRE SQUAD VOX-OPERATOR operative is in the killzone and isn’t within control range of enemy operatives. At the end of each turning point, discard your Fieldcraft points. After an enemy operative that has an Engage order performs an action during its activation, you can spend 1 of your Fieldcraft points to interrupt that activation. If you do, a ready friendly SPECTRE SQUAD operative that isn’t within control range of any other enemy operatives can perform a free Shoot (excluding Guard), Dash or Reposition action." },
  { kind: 'faction', name: "Elite Fieldcraft (card 2/3)", text: "You cannot select any other enemy operative as a valid target during that action. Being within that enemy operative’s control range (but no others) doesn’t prevent that friendly operative from performing that action, in which case follow the rules for a point-blank shot from the Guard action (see Kill Team Core Book)." },
  { kind: 'faction', name: "Camo Cloaks", text: "Whenever an operative is shooting a friendly SPECTRE SQUAD operative (excluding VOX-RELAY BEACON), if you can retain any cover saves, you can retain one additional cover save, or you can retain one cover save as a critical success instead. This isn’t cumulative with improved cover saves from Vantage terrain." },
  { kind: 'faction', name: "Elite Fieldcraft (card 3/3)", text: "If it’s the Reposition action, that friendly operative cannot perform that action again during the turning point. If it’s the Dash or Reposition action, that friendly operative cannot end this move closer to that enemy operative or your opponent’s drop zone (unless it ends that move wholly within your drop zone). In a killzone that uses the close quarters rules (e.g. Killzone: Tomb World), ignore Wall terrain when determining closer and you cannot teleport." },
  { kind: 'strategy', name: "Disappear", text: "One friendly SPECTRE SQUAD operative can immediately perform a free Reposition action. It cannot end that move closer to enemy operatives or your opponent’s drop zone (unless it ends that move wholly within your drop zone) and it cannot perform that action again during the turning point. In a killzone that uses the close quarters rules (e.g. Killzone: Tomb World), ignore Wall terrain when determining closer." },
  { kind: 'strategy', name: "Ambushing Volley", text: "Whenever a friendly SPECTRE SQUAD operative is activated, if it’s more than 3\" from enemy operatives and isn’t a valid target for enemy operatives before determining its order, its ranged weapons (excluding the suppressive profile of an autostubber) have the Devastating 1 weapon rule until the end of that activation. If that weapon already had the Devastating x weapon rule, add 1 to the x of its Devastating x weapon rule instead." },
  { kind: 'strategy', name: "Hidden Engagement", text: "Whenever a friendly SPECTRE SQUAD operative is shooting, if it’s in cover from the target’s perspective, that friendly operative’s weapons have the Balanced weapon rule. Note that your opponent still determines the targeting lines for this (i.e. they decide which point of their operative’s base targeting lines are drawn from)." },
  { kind: 'strategy', name: "Patience", text: "In the Firefight phase of this turning point, you can do one of the following:\n• Once, when it’s your turn to activate a friendly operative, you can skip that activation. You cannot do this until after your opponent’s first activation.\n• When a friendly SPECTRE SQUAD operative performs the Shoot or Fight action during its activation, if it’s the last friendly operative to be activated during this turning point, its weapons have the Relentless weapon rule for that action." },
  { kind: 'firefight', name: "Dodge", text: "Use this firefight ploy during a friendly SPECTRE SQUAD operative’s activation, before or after it performs an action. During that activation, that operative can perform the Fall Back action for 1 less AP." },
  { kind: 'firefight', name: "Sharp Reactions", text: "Use this firefight ploy after an enemy operative that has a Conceal order performs an action during its activation, if it’s within 8\" of a friendly SPECTRE SQUAD operative. You can use the Elite Fieldcraft faction rule to interrupt that activation with that friendly SPECTRE SQUAD operative regardless of that enemy operative’s order (taking precedence over the normal rules)." },
  { kind: 'firefight', name: "Silent Killers", text: "Use this firefight ploy during a friendly SPECTRE SQUAD operative’s activation before or after it performs an action, if it has a Conceal order and isn’t a valid target for enemy operatives. Until the end of that activation, it can perform the Charge action while it has a Conceal order, and the first time it strikes you can inflict 3 additional damage, but cannot resolve any other successes during that sequence." },
  { kind: 'firefight', name: "Prepared Defence", text: "Use this firefight ploy when a friendly SPECTRE SQUAD operative that has a Conceal order or is ready is retaliating. You can do one of the following:\n• At the start of the Resolve Attack Dice step, you can resolve one of your successes before the normal order. If you do, that success must be used to block.\n• When you block, that block can be allocated to block two unresolved successes (instead of one). You cannot use this ploy during an activation in which you’ve interrupted with the Elite Fieldcraft faction rule." },
  { kind: 'equipment', name: "Sniper Overwatch", text: "Once per turning point, a friendly SPECTRE SQUAD operative can use the following ranged weapon — Sniper overwatch: ATK 4, HIT 3+, DMG 3/3.\nWR Devastating 2, Heavy (Dash only), Saturate, Silent" },
  { kind: 'equipment', name: "Starshell Flare", text: "STRATEGIC GAMBIT. One friendly SPECTRE SQUAD operative can immediately perform a free Stun Grenade action (see universal equipment). Performing this action using this rule doesn’t count towards its action limits (i.e. if you also select that grenade from equipment). When an enemy operative’s APL stat is changed as a result of this STRATEGIC GAMBIT, you cannot use this equipment for the rest of the battle." },
  { kind: 'equipment', name: "Tvid-feed Triangulation", text: "Once per turning point, when a friendly SPECTRE SQUAD operative is performing the Shoot action and you’re selecting a valid target, you can use this rule. If you do, that target cannot be obscured if either of the following are true:\n• It’s also a valid target for another friendly SPECTRE SQUAD operative.\n• It’s within 6\" of a friendly VOX-RELAY BEACON operative." },
  { kind: 'equipment', name: "Advanced Camouflage", text: "Friendly SPECTRE SQUAD operatives (excluding VOX-RELAY BEACON) can perform the following unique action:\nADVANCED CAMOUFLAGE (1AP): Until the start of this operative’s next activation, while it has a Conceal order and is in cover, it cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2\". This operative cannot perform this action while visible to and within 3\" of an enemy operative." },
]

export const operatives: Operative[] = [
  { id: "spectre-squad:spectre-veteran-sergeant", name: "Spectre Veteran Sergeant", apl: 2, move: "6\"", save: "5+", w: 9 },
  { id: "spectre-squad:spectre-field-medicae", name: "Spectre Field Medicae", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-grenadier", name: "Spectre Grenadier", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-guide", name: "Spectre Guide", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-gunner", name: "Spectre Gunner", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-heavy-gunner", name: "Spectre Heavy Gunner", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-loader", name: "Spectre Loader", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-sharpshooter", name: "Spectre Sharpshooter", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-stub-gunner", name: "Spectre Stub-gunner", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-trooper", name: "Spectre Trooper", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-vox-operator", name: "Spectre Vox-operator", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-vox-relay-beacon", name: "Spectre Vox-relay Beacon", apl: 1, move: "0\"", save: "5+", w: 3 },
]
