// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Elite Fieldcraft (card 1/3)", text: "In the Ready step of each Strategy phase, you gain 1 Fieldcraft point, or 2 if a friendly SPECTRE SQUAD VOX-OPERATOR operative is in the killzone and isn’t within control range of enemy operatives. At the end of each turning point, discard your Fieldcraft points. After an enemy operative that has an Engage order performs an action during its activation, you can spend 1 of your Fieldcraft points to interrupt that activation. If you do, a ready friendly SPECTRE SQUAD operative that isn’t within control range of any other enemy operatives can perform a free Shoot (excluding Guard), Dash or Reposition action." },
  { kind: 'faction', name: "Elite Fieldcraft (card 2/3)", text: "You cannot select any other enemy operative as a valid target during that action. Being within that enemy operative’s control range (but no others) doesn’t prevent that friendly operative from performing that action, in which case follow the rules for a point-blank shot from the Guard action (see Kill Team Core Book)." },
  { kind: 'faction', name: "Camo Cloaks", text: "Whenever an operative is shooting a friendly SPECTRE SQUAD operative (excluding VOX-RELAY BEACON), if you can retain any cover saves, you can retain one additional cover save, or you can retain one cover save as a critical success instead. This isn’t cumulative with improved cover saves from Vantage terrain." },
  { kind: 'faction', name: "Elite Fieldcraft (card 3/3)", text: "If it’s the Reposition action, that friendly operative cannot perform that action again during the turning point. If it’s the Dash or Reposition action, that friendly operative cannot end this move closer to that enemy operative or your opponent’s drop zone (unless it ends that move wholly within your drop zone). In a killzone that uses the close quarters rules (e.g. Killzone: Tomb World), ignore Wall terrain when determining closer and you cannot teleport." },
  { kind: 'strategy', name: "Disappear", text: "One friendly SPECTRE SQUAD operative can immediately perform a free Reposition action. It cannot end that move closer to enemy operatives or your opponent’s drop zone (unless it ends that move wholly within your drop zone) and it cannot perform that action again during the turning point. In a killzone that uses the close quarters rules (e.g. Killzone: Tomb World), ignore Wall terrain when determining closer." },
  { kind: 'strategy', name: "Ambushing Volley", text: "Whenever a friendly SPECTRE SQUAD operative is activated, if it’s more than 3\" from enemy operatives and isn’t a valid target for enemy operatives before determining its order, its ranged weapons (excluding the suppressive profile of an autostubber) have the Devastating 1 weapon rule until the end of that activation. If that weapon already had the Devastating x weapon rule, add 1 to the x of its Devastating x weapon rule instead." },
  { kind: 'strategy', name: "Hidden Engagement", text: "Whenever a friendly SPECTRE SQUAD operative is shooting, if it’s in cover from the target’s perspective, that friendly operative’s weapons have the Balanced weapon rule. Note that your opponent still determines the targeting lines for this (i.e. they decide which point of their operative’s base targeting lines are drawn from)." },
  { kind: 'strategy', name: "Patience", text: "In the Firefight phase of this turning point, you can do one of the following:\n• Once, when it’s your turn to activate a friendly operative, you can skip that activation. You cannot do this until after your opponent’s first activation.\n• When a friendly SPECTRE SQUAD operative performs the Shoot or Fight action during its activation, if it’s the last friendly operative to be activated during this turning point, its weapons have the Relentless weapon rule for that action." },
  { kind: 'firefight', name: "Dodge", text: "Use this firefight ploy during a friendly SPECTRE SQUAD operative’s activation, before or after it performs an action. During that activation, that operative can perform the Fall Back action for 1 less AP." },
  { kind: 'firefight', name: "Sharp Reactions", text: "Use this firefight ploy after an enemy operative that has a Conceal order performs an action during its activation, if it’s within 8\" of a friendly SPECTRE SQUAD operative. You can use the Elite Fieldcraft faction rule to interrupt that activation with that friendly SPECTRE SQUAD operative regardless of that enemy operative’s order (taking precedence over the normal rules)." },
  { kind: 'firefight', name: "Silent Killers", text: "Use this firefight ploy during a friendly SPECTRE SQUAD operative’s activation before or after it performs an action, if it has a Conceal order and isn’t a valid target for enemy operatives. Until the end of that activation, it can perform the Charge action while it has a Conceal order, and the first time it strikes you can inflict 3 additional damage, but cannot resolve any other successes during that sequence." },
  { kind: 'firefight', name: "Prepared Defence", text: "Use this firefight ploy when a friendly SPECTRE SQUAD operative that has a Conceal order or is ready is retaliating. You can do one of the following:\n• At the start of the Resolve Attack Dice step, you can resolve one of your successes before the normal order. If you do, that success must be used to block.\n• When you block, that block can be allocated to block two unresolved successes (instead of one). You cannot use this ploy during an activation in which you’ve interrupted with the Elite Fieldcraft faction rule." },
  { kind: 'equipment', name: "Sniper Overwatch", text: "Once per turning point, a friendly SPECTRE SQUAD operative can use the following ranged weapon — Sniper overwatch: ATK 4, HIT 3+, DMG 3/3.\nWR Devastating 2, Heavy (Dash only), Saturate, Silent" },
  { kind: 'equipment', name: "Starshell Flare", text: "STRATEGIC GAMBIT. One friendly SPECTRE SQUAD operative can immediately perform a free Stun Grenade action (see universal equipment). Performing this action using this rule doesn’t count towards its action limits (i.e. if you also select that grenade from equipment). When an enemy operative’s APL stat is changed as a result of this STRATEGIC GAMBIT, you cannot use this equipment for the rest of the battle." },
  { kind: 'equipment', name: "Tvid-feed Triangulation", text: "Once per turning point, when a friendly SPECTRE SQUAD operative is performing the Shoot action and you’re selecting a valid target, you can use this rule. If you do, that target cannot be obscured if either of the following are true:\n• It’s also a valid target for another friendly SPECTRE SQUAD operative.\n• It’s within 6\" of a friendly VOX-RELAY BEACON operative." },
  { kind: 'equipment', name: "Advanced Camouflage", text: "Friendly SPECTRE SQUAD operatives (excluding VOX-RELAY BEACON) can perform the following unique action:\nADVANCED CAMOUFLAGE (1AP): Until the start of this operative’s next activation, while it has a Conceal order and is in cover, it cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2\". This operative cannot perform this action while visible to and within 3\" of an enemy operative." },
]

export const operatives: Operative[] = [
  { id: "spectre-squad:spectre-veteran-sergeant", name: "Spectre Veteran Sergeant", apl: 2, move: "6\"", save: "5+", w: 9 },
  { id: "spectre-squad:spectre-field-medicae", name: "Spectre Field Medicae", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-grenadier", name: "Spectre Grenadier", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-guide", name: "Spectre Guide", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-gunner", name: "Spectre Gunner", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-heavy-gunner", name: "Spectre Heavy Gunner", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-loader", name: "Spectre Loader", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-sharpshooter", name: "Spectre Sharpshooter", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-stub-gunner", name: "Spectre Stub-gunner", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-trooper", name: "Spectre Trooper", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-vox-operator", name: "Spectre Vox-operator", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "spectre-squad:spectre-vox-relay-beacon", name: "Spectre Vox-relay Beacon", apl: 1, move: "0\"", save: "5+", w: 3 },
]

export const datacards: Datacard[] = [
  {"name": "Spectre Veteran Sergeant", "weapons": [{"name": "Scoped lascarbine", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Lethal 5+, Rending"}, {"name": "Bionic arm", "atk": 3, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [{"name": "Issue Mission", "ap": 0, "text": "Select one expended friendly SPECTRE SQUAD operative (excluding VOX-RELAY BEACON) visible to this operative that hasn’t interrupted an enemy operative’s activation with the Elite Fieldcraft faction rule this turning point. Until the end of the turning point, that friendly operative can do so even though it’s expended (taking precedence over the normal rules). However, if it does, it cannot counteract during the turning point, or perform the Reposition action if it’s already done so this turning point.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["SPECTRE SQUAD", "IMPERIUM", "ASTRA MILITARUM", "LEADER", "VETERAN SERGEANT"], "img": "/ops/spectre-squad/spectre-veteran-sergeant.webp"},
  {"name": "Spectre Field Medicae", "weapons": [{"name": "Lascarbine", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Rending"}, {"name": "Lasrifle", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Heavy (Reposition only), Lethal 5+"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Medic!", "text": "The first time during each turning point that another friendly SPECTRE SQUAD operative (excluding VOX-RELAY BEACON) would be incapacitated while visible to and within 3\" of this operative, you can use this rule, providing neither this nor that operative is within control range of an enemy operative. If you do, that friendly operative isn’t incapacitated, has 1 wound remaining and cannot be incapacitated for the remainder of the action. After that action, that friendly operative can immediately perform a free Dash action, but must end that move within this operative’s control range. Subtract 1 from this and that operative’s APL stats until the end of their next activations respectively, and if this rule was used during that friendly operative’s activation, that activation ends. You cannot use this rule if this operative is incapacitated, or if it’s a Shoot action and this operative would be a primary or secondary target."}], "actions": [{"name": "Medikit", "ap": 0, "text": "Select one friendly SPECTRE SQUAD operative (excluding VOX-RELAY BEACON) within this operative’s control range to regain up to 2D3 lost wounds. It cannot be an operative that the Medic! rule was used on during this turning point.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["SPECTRE SQUAD", "IMPERIUM", "ASTRA MILITARUM", "FIELD MEDICAE"], "img": "/ops/spectre-squad/spectre-field-medicae.webp"},
  {"name": "Spectre Grenadier", "weapons": [{"name": "Lascarbine", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Rending"}, {"name": "Lasrifle", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Heavy (Reposition only), Lethal 5+"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Grenadier", "text": "This operative can use frag, krak, and smoke grenades (see universal equipment). Doing so doesn’t count towards any limited uses you have (i.e. if you also select those grenades from equipment for other operatives). Whenever this operative is using a frag or krak grenade, improve the Hit stat of that weapon by 1."}, {"name": "Melta Mine", "text": "This operative is carrying your Melta Mine marker. It can perform the Pick Up Marker action on that marker, and whenever it performs the Place Marker action on that marker, it can immediately perform a free Dash action. That marker cannot be placed within an enemy operative’s control range (if this operative is incapacitated while carrying that marker and that marker cannot be placed, it’s removed with this operative)."}, {"name": "Proximity Mine", "text": "The first time your Melta Mine marker is within another operative’s control range, remove that marker and inflict 2D6+3 damage on that operative; if it isn’t incapacitated, end its action (if any), even if that action’s effects aren’t fulfilled. If it cannot be placed, move it the minimum amount to do so. Note that this operative is ignored for these effects (i.e. it cannot set it off or take damage from that marker)."}], "actions": [], "keywords": ["SPECTRE SQUAD", "IMPERIUM", "ASTRA MILITARUM", "GRENADIER"], "img": "/ops/spectre-squad/spectre-grenadier.webp"},
  {"name": "Spectre Guide", "weapons": [{"name": "Lascarbine", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Rending"}, {"name": "Lasrifle", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Heavy (Reposition only), Lethal 5+"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Prepared Killzone", "text": "You can select one additional equipment option, but it must be an Ammo Cache or an equipment terrain feature (see universal equipment)."}, {"name": "Scout Terrain", "text": "Terrain features within your territory or within 3\" of this operative are scouted for friendly SPECTRE SQUAD operatives. Once in each of their activations, friendly SPECTRE SQUAD operatives can do one of the following:\n• Ignore the first vertical distance of 2\" it moves during one climb up if the terrain feature is scouted for friendly SPECTRE SQUAD operatives. • Perform the Operate Hatch action for 1 less AP if the access point is scouted for friendly SPECTRE SQUAD operatives."}], "actions": [], "keywords": ["SPECTRE SQUAD", "IMPERIUM", "ASTRA MILITARUM", "GUIDE"], "img": "/ops/spectre-squad/spectre-guide.webp"},
  {"name": "Spectre Gunner", "weapons": [{"name": "Meltagun", "atk": 4, "hit": "3+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Plasma gun (standard)", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Piercing 1"}, {"name": "Plasma gun (supercharge)", "atk": 4, "hit": "3+", "dmg": "5/6", "wr": "Hot, Lethal 5+, Piercing 1"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [], "keywords": ["SPECTRE SQUAD", "IMPERIUM", "ASTRA MILITARUM", "GUNNER"], "img": "/ops/spectre-squad/spectre-gunner.webp"},
  {"name": "Spectre Heavy Gunner", "weapons": [{"name": "Laspistol", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Missile launcher (frag)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Blast 2\", Heavy"}, {"name": "Missile launcher (krak)", "atk": 4, "hit": "3+", "dmg": "5/7", "wr": "Heavy, Piercing 1"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Weapons Team", "text": "Whenever this operative is activated, if a friendly LOADER operative is within its control range, all profiles of its missile launcher have the Heavy (Dash only) weapon rule instead of the Heavy weapon rule until the end of that activation."}], "actions": [], "keywords": ["SPECTRE SQUAD", "IMPERIUM", "ASTRA MILITARUM", "HEAVY GUNNER"], "img": "/ops/spectre-squad/spectre-heavy-gunner.webp"},
  {"name": "Spectre Loader", "weapons": [{"name": "Laspistol", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Weapon Assist", "text": "Whenever another friendly SPECTRE SQUAD operative within control range of this operative is shooting, you can re-roll one of your attack dice."}], "actions": [{"name": "Load Weapon", "ap": 1, "text": "Select one friendly SPECTRE SQUAD operative within this operative’s control range and not within 3\" of enemy operatives. That friendly operative can immediately perform a free Shoot action (excluding Guard), and you can change its order to do so.\nThis operative cannot perform this action while within control range of an enemy operative, while counteracting, or during an activation in which it performed the Charge, Dash or Shoot action (or vice versa)."}], "keywords": ["SPECTRE SQUAD", "IMPERIUM", "ASTRA MILITARUM", "LOADER"], "img": "/ops/spectre-squad/spectre-loader.webp"},
  {"name": "Spectre Sharpshooter", "weapons": [{"name": "Long-las (concealed)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy, Silent, Concealed Position*"}, {"name": "Long-las (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}, {"name": "Long-las (stationary)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Concealed Position", "text": "This operative can only use this weapon the first time it’s performing the Shoot action during the battle."}], "actions": [], "keywords": ["SPECTRE SQUAD", "IMPERIUM", "ASTRA MILITARUM", "SHARPSHOOTER"], "img": "/ops/spectre-squad/spectre-sharpshooter.webp"},
  {"name": "Spectre Stub-gunner", "weapons": [{"name": "Autostubber (focused)", "atk": 5, "hit": "3+", "dmg": "3/4", "wr": "Heavy (Dash only)"}, {"name": "Autostubber (suppressive)", "atk": 5, "hit": "5+", "dmg": "0/0", "wr": "Heavy, Lethal 5+, Seek Light, Stun, Torrent 1\""}, {"name": "Autostubber (sweeping)", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Heavy (Dash only), Torrent 1\""}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Suppressive Fire", "text": "Whenever an enemy operative is visible to and within 3\" of this operative, if this operative has an Engage order and isn’t within control range of any other enemy operatives, subtract 1 from the Atk stat of that enemy operative’s weapons (to a minimum of 1). This rule has no effect if this operative performed the Charge action during this turning point."}], "actions": [], "keywords": ["SPECTRE SQUAD", "IMPERIUM", "ASTRA MILITARUM", "STUB-GUNNER"], "img": "/ops/spectre-squad/spectre-stub-gunner.webp"},
  {"name": "Spectre Trooper", "weapons": [{"name": "Lascarbine", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Rending"}, {"name": "Lasrifle", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Heavy (Reposition only), Lethal 5+"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Cool-Headed", "text": "Once per turning point, one friendly SPECTRE SQUAD operative with this rule can interrupt an enemy operative’s activation with the Elite Fieldcraft faction rule for 0 Fieldcraft points (taking precedence over the normal rules)."}], "actions": [], "keywords": ["SPECTRE SQUAD", "IMPERIUM", "ASTRA MILITARUM", "TROOPER"], "img": "/ops/spectre-squad/spectre-trooper.webp"},
  {"name": "Spectre Vox-operator", "weapons": [{"name": "Lascarbine", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Rending"}, {"name": "Lasrifle", "atk": 4, "hit": "3+", "dmg": "2/3", "wr": "Heavy (Reposition only), Lethal 5+"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [{"name": "Signal", "ap": 1, "text": "SUPPORT. Select one other friendly SPECTRE SQUAD operative (excluding VOX-RELAY BEACON) visible to this operative. Until the end of that operative’s next activation, add 1 to its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["SPECTRE SQUAD", "IMPERIUM", "ASTRA MILITARUM", "VOX-OPERATOR"], "img": "/ops/spectre-squad/spectre-vox-operator.webp"},
  {"name": "Spectre Vox-relay Beacon", "weapons": [], "abilities": [{"name": "Pre-Deploy", "text": "In the Set Up Operatives step, this operative can be set up outside of your drop zone. It must be set up in a location it can be placed, wholly within your territory and more than 2\" from markers and equipment terrain features."}, {"name": "Expendable", "text": "This operative cannot perform any actions other than Signal. It cannot counteract, retaliate or assist in a fight.\nThis operative cannot contest markers or areas of the killzone, and is ignored for your opponent’s kill/elimination op (when it’s incapacitated, and when determining your starting number of operatives). It’s also ignored for victory conditions and scoring VPs if either require operatives to ‘escape’, ‘survive’ or be incapacitated by enemy operatives (if it escapes/survives/is incapacitated, determining how many operatives must escape/survive/be incapacitated, etc.).\nOperatives can move through this operative. Your opponent can ignore this operative’s control range at any time. Whenever a friendly SPECTRE SQUAD operative is performing the Shoot action and you’re selecting a valid target, you can ignore this operative’s control range. Note that control range wouldn’t be mutual when ignored."}], "actions": [{"name": "Signal", "ap": 1, "text": "Select one other friendly SPECTRE SQUAD operative within 6\" of this operative. Until the end of that operative’s next activation, add 1 to its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["SPECTRE SQUAD", "IMPERIUM", "ASTRA MILITARUM", "VOX-RELAY BEACON"], "img": "/ops/spectre-squad/spectre-vox-relay-beacon.webp"},
]
