// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Drop Insertion", text: "When setting up a TEMPESTUS AQUILON kill team before the battle, the first third of your kill team must be set up as normal. Each third thereafter can be set up above: place them to one side instead of in the killzone. For each third that’s set up above, you must set up the whole third in this way (not some of them), then place one of your Drop markers wholly within your drop zone.\nAs a STRATEGIC GAMBIT in the first and second turning point, you can move your Drop markers up to 4\" horizontally. In a killzone that uses the close quarters rules (e.g. Killzone: Tomb World), this can be measured and moved through Wall terrain.\nIn the Firefight phase, friendly TEMPESTUS AQUILON operatives set up above are activated as normal. When you do, you can either expend or land that operative. If it lands, set it up in the killzone in a location it can be placed as follows (it’s no longer set up above):" },
  { kind: 'faction', name: "Grav‑chute", text: "Whenever a friendly TEMPESTUS AQUILON operative is dropping, ignore the vertical distance." },
  { kind: 'strategy', name: "Sudden Offensive", text: "Count the number of friendly TEMPESTUS AQUILON operatives that aren’t incapacitated, then halve the result (rounding up) to give you x. Until the end of their activation, friendly TEMPESTUS AQUILON operatives’ weapons have the Balanced weapon rule if they are the first friendly operatives activated this turning point equal to x. For example, if you have five operatives, the first three friendly operatives activated will benefit." },
  { kind: 'strategy', name: "Maintain Momentum", text: "Whenever a friendly TEMPESTUS AQUILON operative is shooting against or fighting against a ready enemy operative, that friendly operative’s weapons have the Severe weapon rule." },
  { kind: 'strategy', name: "Eye Above", text: "Select one enemy operative. That operative and each other enemy operative within 3\" of it gains one of your Detected tokens until the end of the turning point. Whenever an enemy operative that has one of your Detected tokens:\n• Is shooting a friendly TEMPESTUS AQUILON operative, you can re‑roll one of your defence dice.\n• Is fighting or retaliating against a friendly TEMPESTUS AQUILON operative, one of your blocks can be allocated to block two unresolved successes (instead of one)." },
  { kind: 'firefight', name: "Hot Drop", text: "Use this firefight ploy after rolling your attack dice for a friendly TEMPESTUS AQUILON operative that’s wholly within your opponent’s territory, or either landed or dropped from Vantage terrain at least 2\" higher than the killzone floor during this activation. If the target is within 6\" of it, you can re‑roll any of your attack dice." },
  { kind: 'strategy', name: "Drop and Secure", text: "Select one marker.\n• Until the Ready step of the next Strategy phase, when determining control of that marker, treat the total APL stat of friendly\nTEMPESTUS AQUILON operatives that contest it as 1 higher if at least one friendly TEMPESTUS AQUILON operative contests that marker. Note this isn’t a change to the APL stat, so any changes are cumulative with this.\n• Whenever a friendly TEMPESTUS AQUILON operative is within 3\" of that marker, add 1 to the Atk stat of its melee weapons (to a maximum of 4)." },
  { kind: 'firefight', name: "Adjust Coordinates", text: "Use this firefight ploy when a friendly TEMPESTUS AQUILON operative lands. You can set it up within 5\" horizontally of one of your Drop markers, taking precedence over the normal distance requirement. It cannot perform the Dash, Shoot or Fight actions during this turning point." },
  { kind: 'firefight', name: "Tempestus Exemplars", text: "Use this firefight ploy during a friendly\nTEMPESTUS AQUILON operative’s activation (excluding SERVO‑SENTRY and any operative that has an APL stat higher than 2). During that activation, that operative can perform the Pick Up Marker, Place Marker or a mission action for 1 less AP." },
  { kind: 'equipment', name: "Tempestus Daggers", text: "Friendly TEMPESTUS AQUILON operatives (excluding SERVO‑SENTRY) have the following melee weapon — Tempestus dagger: ATK 3, HIT 4+, DMG 3/4." },
  { kind: 'firefight', name: "Progena", text: "Use this firefight ploy when a friendly TEMPESTUS AQUILON operative (excluding SERVO‑SENTRY) is activated. It regains up to 2D3 lost wounds, and during that activation you can ignore any changes to its APL stat." },
  { kind: 'equipment', name: "Combat Stimms", text: "You can ignore any changes to the Move stat of friendly TEMPESTUS AQUILON operatives from being injured." },
  { kind: 'equipment', name: "Drop Augury", text: "Once per battle, when a friendly TEMPESTUS AQUILON operative that’s set up above is activated, before expending or landing that operative, you can move one of your Drop markers again. However, it cannot be moved closer to your opponent’s drop zone." },
  { kind: 'equipment', name: "Remote Overseer", text: "Once per battle, after rolling off to decide initiative, you can re‑roll your dice." },
]

export const operatives: Operative[] = [
  { id: "tempestus-aquilons:aquilon-tempestor", name: "Aquilon Tempestor", apl: 3, move: "6\"", save: "4+", w: 9 },
  { id: "tempestus-aquilons:aquilon-grenadier", name: "Aquilon Grenadier", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "tempestus-aquilons:aquilon-gunfighter", name: "Aquilon Gunfighter", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "tempestus-aquilons:aquilon-gunner", name: "Aquilon Gunner", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "tempestus-aquilons:aquilon-marksman", name: "Aquilon Marksman", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "tempestus-aquilons:aquilon-precursor", name: "Aquilon Precursor", apl: 2, move: "6\"", save: "4+", w: 8 },
  { id: "tempestus-aquilons:aquilon-servo-sentry", name: "Aquilon Servo‑sentry", apl: 2, move: "4\"", save: "3+", w: 10 },
  { id: "tempestus-aquilons:aquilon-trooper", name: "Aquilon Trooper", apl: 2, move: "6\"", save: "4+", w: 8 },
]

export const datacards: Datacard[] = [
  {"name": "Aquilon Tempestor", "weapons": [{"name": "Hot‑shot lascarbine", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "‑"}, {"name": "Hot‑shot laspistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Relic bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Lethal 5+"}, {"name": "Chainsword", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "‑"}, {"name": "Fists", "atk": 3, "hit": "3+", "dmg": "2/3", "wr": "‑"}, {"name": "Power weapon", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Tempestus Veteran", "text": "Once per battle, you can either use a firefight ploy for 0CP if this is the specified TEMPESTUS AQUILON operative, or the Command Re‑roll firefight ploy for 0CP if this is the operative the attack or defence dice was rolled for."}], "actions": [{"name": "Command", "ap": 1, "text": "SUPPORT. Select one other friendly TEMPESTUS AQUILON operative (excluding SERVO‑SENTRY) visible to and within 6\" of this operative. Until the end of that operative’s next activation, add 1 to its APL stat.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["TEMPESTUS AQUILON", "IMPERIUM", "LEADER", "TEMPESTOR"], "img": "/ops/tempestus-aquilons/aquilon-tempestor.webp"},
  {"name": "Aquilon Grenadier", "weapons": [{"name": "Hot‑shot laspistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Melta bomb", "atk": 4, "hit": "3+", "dmg": "5/3", "wr": "Range 3\", Devastating 3, Heavy (Reposition only), Limited 1, Piercing 2"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3", "wr": "‑"}], "abilities": [{"name": "Grenadier", "text": "This operative can use frag, krak, smoke and stun grenades (see universal equipment). Doing so doesn’t count towards any limited uses you have (i.e. if you also select those grenades from equipment for other operatives). Whenever this operative is using a frag or krak grenade, improve the Hit stat of that weapon by 1."}], "actions": [], "keywords": ["TEMPESTUS AQUILON", "IMPERIUM", "GRENADIER"], "img": "/ops/tempestus-aquilons/aquilon-grenadier.webp"},
  {"name": "Aquilon Gunfighter", "weapons": [{"name": "Hot‑shot laspistols (focused)", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Ceaseless, Rending"}, {"name": "Hot‑shot laspistols (salvo)", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Range 8\", Salvo*"}, {"name": "Hot‑shot laspistols (point‑blank)", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Ceaseless"}], "abilities": [{"name": "Salvo", "text": "Select up to two different valid targets that aren’t within control range of friendly operatives. Shoot with this weapon against both of them in an order of your choice (roll each sequence separately)."}, {"name": "Gunfight", "text": "Whenever an enemy operative within 8\" of this operative shoots this operative, keep track of each attack dice that’s discarded as a fail. After the action, before incapacitated operatives are removed (including this one, if relevant), this operative can perform a free Shoot action (you can change its order to Engage to do so), but it can only target that enemy operative with its hot‑shot laspistols (focused), and you only roll a number of attack dice equal to the opponent’s discarded attack dice plus one (to a maximum of four)."}], "actions": [], "keywords": ["TEMPESTUS AQUILON", "IMPERIUM", "GUNFIGHTER"], "img": "/ops/tempestus-aquilons/aquilon-gunfighter.webp"},
  {"name": "Aquilon Gunner", "weapons": [{"name": "Melta carbine", "atk": 4, "hit": "3+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Plasma carbine (standard)", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Piercing 1"}, {"name": "Plasma carbine (supercharge)", "atk": 4, "hit": "3+", "dmg": "5/6", "wr": "Hot, Lethal 5+, Piercing 1"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3", "wr": "‑"}], "abilities": [], "actions": [], "keywords": ["TEMPESTUS AQUILON", "IMPERIUM", "GUNNER"], "img": "/ops/tempestus-aquilons/aquilon-gunner.webp"},
  {"name": "Aquilon Marksman", "weapons": [{"name": "Hot‑shot long‑las (concealed)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy, Silent, Concealed Position*"}, {"name": "Hot‑shot long‑las (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "‑"}, {"name": "Hot‑shot long‑las (stationary)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Devastating 3, Heavy"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3", "wr": "‑"}], "abilities": [{"name": "Sniper’s Vantage", "text": "Whenever this operative is on Vantage terrain and is shooting an operative that has an Engage order and is at least 2\" lower than it, all profiles of its hot‑shot long‑las have the Severe weapon rule."}, {"name": "Concealed Position", "text": "This operative can only use this weapon the first time it’s performing the Shoot action during the battle."}], "actions": [], "keywords": ["TEMPESTUS AQUILON", "IMPERIUM", "MARKSMAN"], "img": "/ops/tempestus-aquilons/aquilon-marksman.webp"},
  {"name": "Aquilon Precursor", "weapons": [{"name": "Hot‑shot laspistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Tempestus dagger", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Ceaseless, Lethal 5+"}], "abilities": [{"name": "Vicious Knife Fighter", "text": "Whenever this operative is fighting, after resolving your first attack dice during that sequence, you can immediately resolve another (before your opponent)."}, {"name": "Dynamic", "text": "Whenever this operative performs the Shoot or Fight action, it can immediately perform a free Dash action afterwards. It can do so even if it’s performed the Charge action during this activation."}], "actions": [], "keywords": ["TEMPESTUS AQUILON", "IMPERIUM", "PRECURSOR"], "img": "/ops/tempestus-aquilons/aquilon-precursor.webp"},
  {"name": "Aquilon Servo‑sentry", "weapons": [{"name": "Flamer", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 8\", Saturate, Torrent 2\""}, {"name": "Grenade launcher (frag)", "atk": 4, "hit": "4+", "dmg": "2/4", "wr": "Blast 2\""}, {"name": "Grenade launcher (krak)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Piercing 1"}, {"name": "Hot‑shot volley gun (focused)", "atk": 5, "hit": "4+", "dmg": "3/4", "wr": "Piercing Crits 1"}, {"name": "Hot‑shot volley gun (sweeping)", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Piercing Crits 1, Torrent 1\""}], "abilities": [{"name": "Machine", "text": "This operative cannot perform any actions other than Dash, Fall Back, Reposition and Shoot. It cannot retaliate, assist in a fight or use any weapons that aren’t on its datacard.\nTEMPESTUS AQUILON , IMPERIUM, SERVO‑SENTRY"}, {"name": "Turret", "text": "This operative can perform two Shoot actions during its activation.\n40"}], "actions": [], "img": "/ops/tempestus-aquilons/aquilon-servo-sentry.webp"},
  {"name": "Aquilon Trooper", "weapons": [{"name": "Hot‑shot lascarbine", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "‑"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "2/3", "wr": "‑"}], "abilities": [{"name": "Rapid Insertion", "text": "STRATEGIC GAMBIT in the first turning point. Each friendly TEMPESTUS AQUILON TROOPER operative wholly within your drop zone can immediately perform a free Reposition action, but must end that move wholly within 3\" of your drop zone."}, {"name": "Swift Landing", "text": "When this operative lands, you can set it up within 4\" horizontally of one of your Drop markers, taking precedence over the normal distance requirement."}], "actions": [], "keywords": ["TEMPESTUS AQUILON", "IMPERIUM", "TROOPER"], "img": "/ops/tempestus-aquilons/aquilon-trooper.webp"},
]
