// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Communion", text: "Communion points are used to maintain the tactical focus of friendly VESPID STINGWING operatives. In the Ready step of each Strategy phase, you gain D3 Communion points, plus 1 if a friendly OVERSIGHT DRONE operative is in the killzone. Communion points are used as follows (OVERSIGHT DRONE operatives aren’t affected by the following):\nRULE CONTINUES ON OTHER SIDE" },
  { kind: 'faction', name: "Neutron Charge", text: "Neutron weapons are powered by radioactive crystals from the Vespids’ home world. The harmonic thrumming of Vespids’ wings resonates within the crystals to charge them. When unleashed, even heavy combat armour can barely protect against this atom‑stripping energy charge.\nNeutron weapons are any weapons that have the word ‘neutron’ in their name, e.g. neutron blaster, neutron grenade launcher, etc. Whenever a friendly VESPID STINGWING operative moves or uses FLY, its neutron weapons have the Piercing 1 weapon rule until the end of the turning point." },
  { kind: 'faction', name: "Fly", text: "Whenever a friendly VESPID STINGWING operative performs an action in which it moves, it can FLY. If it does, don’t move it. Instead, remove it from the killzone and set it back up wholly within a distance equal to its Move stat (or 3\" if it was a Dash) horizontally of its original location (in a killzone that uses the close quarters rules, e.g. Killzone: Tomb World, this distance cannot be measured over or through Wall terrain, and that operative cannot be set up on the other side of an access point – in other words it cannot FLY through an open hatchway). Note that it gains no additional distance when performing the Charge action. It must be set up in a location it can be placed, and unless it’s the Charge action, it cannot be set up within control range of an enemy operative." },
  { kind: 'strategy', name: "Hardened Exoskeleton", text: "Whenever a friendly VESPID STINGWING operative (excluding OVERSIGHT DRONE) is fighting or retaliating, Normal Dmg of 4 or more inflicts 1 less damage on it." },
  { kind: 'strategy', name: "Aerial Agility", text: "Whenever an operative is shooting a friendly VESPID STINGWING operative while counteracting or interrupting, or during an activation in which that shooting operative moved or was set up, roll one D6 whenever an attack dice would inflict Normal Dmg: on a 5+, ignore that inflicted damage. You cannot ignore more than one attack dice per Shoot action sequence this way." },
  { kind: 'strategy', name: "Airborne Predators", text: "Whenever a friendly VESPID STINGWING operative moves or uses FLY during its activation, its weapons have the Balanced weapon rule until the end of that activation." },
  { kind: 'firefight', name: "Ocelli", text: "Use this firefight ploy when a friendly VESPID STINGWING operative performs the Shoot action during an activation in which it’s used FLY. Until the end of that action, it gains all benefits from the first and second main features of Vantage terrain. When determining the height difference between operatives for Vantage terrain rules, treat that friendly operative as being 3\" higher than it currently is (but not when determining the distance for Communion)." },
  { kind: 'strategy', name: "Sting", text: "Improve the Hit stat of friendly VESPID STINGWING operatives’ claws by 1, and those weapons have the Lethal 5+ and Shock weapon rules." },
  { kind: 'firefight', name: "Darting Flight", text: "Use this firefight ploy when a friendly VESPID\nSTINGWING operative performs the Reposition action. Until the end of that action, it can move an additional D3\", or be set up an additional D3\" away if it uses FLY. In either case, it cannot perform Shoot or Fight actions for the rest of the turning point." },
  { kind: 'firefight', name: "Neutron Overload", text: "Use this firefight ploy when you resolve a critical success for a friendly VESPID STINGWING operative that’s shooting with a neutron weapon during an activation in which it’s moved or used FLY. If the target is within 4\" of it, inflict D3 additional damage." },
  { kind: 'equipment', name: "Neurostimulant", text: "In the Ready step of each Strategy phase, when determining how many Communion points to gain, you can roll two D3 and select one D3 to use." },
  { kind: 'firefight', name: "Vicious Venom", text: "Use this firefight ploy when a friendly VESPID STINGWING operative (excluding OVERSIGHT DRONE) is fighting and you strike with a critical success. Inflict D3 additional damage." },
  { kind: 'equipment', name: "Convergence Stimulant", text: "Once per turning point, a friendly VESPID STINGWING operative can perform the Pick Up Marker or a mission action without you spending a Communion point." },
  { kind: 'equipment', name: "Accelerant Stimulant", text: "Whenever a friendly VESPID STINGWING operative (excluding OVERSIGHT DRONE) performs the Charge or Dash action, it can move an additional 1\". If it uses FLY for this action, you can set it back up 1\" further away." },
  { kind: 'equipment', name: "Aggression Stimulant", text: "Whenever a friendly VESPID STINGWING operative (excluding OVERSIGHT DRONE) is fighting, its melee weapons have the Ceaseless weapon rule." },
]

export const operatives: Operative[] = [
  { id: "vespid-stingwings:vespid-strain-leader", name: "Vespid Strain Leader", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "vespid-stingwings:oversight-drone", name: "Oversight Drone", apl: 2, move: "8\"", save: "2+", w: 5 },
  { id: "vespid-stingwings:vespid-longsting", name: "Vespid Longsting", apl: 2, move: "6\"", save: "5+", w: 9 },
  { id: "vespid-stingwings:vespid-shadestrain", name: "Vespid Shadestrain", apl: 2, move: "6\"", save: "3+", w: 9 },
  { id: "vespid-stingwings:vespid-skyblast", name: "Vespid Skyblast", apl: 2, move: "6\"", save: "5+", w: 9 },
  { id: "vespid-stingwings:vespid-swarmguard", name: "Vespid Swarmguard", apl: 2, move: "6\"", save: "5+", w: 9 },
  { id: "vespid-stingwings:vespid-warrior", name: "Vespid Warrior", apl: 2, move: "6\"", save: "5+", w: 9 },
]

export const datacards: Datacard[] = [
  {"name": "Vespid Strain Leader", "weapons": [{"name": "Neutron blaster", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Devastating 2"}, {"name": "Claws", "atk": 3, "hit": "4+", "dmg": "3/4"}], "abilities": [{"name": "Communion Helm", "text": "Once during each of this operative’s activations, you can do one of the following:\n• Spend 1 Communion point for free. • Spend 1 Communion point and select one friendly VESPID STINGWING operative within 3\" of this operative. That other friendly operative can immediately perform a free 1AP mission action (you must still spend a Communion point for it to perform that action as normal, and this cannot be ignored using the Convergence Stimulant equipment)."}, {"name": "Commune", "text": "When selecting your operatives for the battle, also select one VESPID STINGWING strategy ploy. Whenever this operative is in the killzone and isn’t within control range of enemy operatives, that ploy costs you 0CP."}], "actions": [], "keywords": ["VESPID STINGWING", "T’AU EMPIRE", "STRAIN", "LEADER"]},
  {"name": "Oversight Drone", "weapons": [{"name": "Ram", "atk": 3, "hit": "5+", "dmg": "1/2"}], "abilities": [{"name": "Evasive Drone", "text": "• This operative cannot perform any actions other than Aerial Guidance, Charge, Dash, Fall Back, Fight and Reposition. • Whenever determining control of an objective marker, treat this operative’s APL stat as 1 lower. Note this isn’t a change to its APL stat, so any changes are cumulative with this. • Whenever determining what’s visible to this operative, the round disc at the top of the miniature is its head. • Whenever this operative has a Conceal order and is in cover, it cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2\". • Whenever an operative is shooting this operative, ignore the Piercing weapon rule."}], "actions": [{"name": "Aerial Guidance", "ap": 1, "text": "SUPPORT. Until the start of this operative’s next activation, whenever another friendly VESPID STINGWING operative within 6\" of this operative is shooting an enemy operative visible to this operative, that friendly operative’s ranged weapons have the Lethal 5+ and Saturate weapon rules. This has no effect while this operative is within control range of an enemy operative. This operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["VESPID STINGWING", "T’AU EMPIRE", "OVERSIGHT", "DRONE"]},
  {"name": "Vespid Longsting", "weapons": [{"name": "Neutron rail rifle (standard)", "atk": 4, "hit": "4+", "dmg": "4/4", "wr": "Devastating 2, Neutron Fragment*"}, {"name": "Neutron rail rifle (aimed)", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Devastating 2, Heavy (Dash only), Lethal 5+,"}], "abilities": [], "actions": [], "keywords": ["VESPID STINGWING", "T’AU EMPIRE", "LONGSTING"]},
  {"name": "Vespid Shadestrain", "weapons": [{"name": "Neutron sting", "atk": 4, "hit": "4+", "dmg": "3/3", "wr": "Range 8\", Devastating 2"}, {"name": "Neutron grenade", "atk": 4, "hit": "4+", "dmg": "3/3", "wr": "Range 6\", Blast 2\", Devastating 2, Limited 1,"}], "abilities": [{"name": "Ghost Rig", "text": "While this operative has a Conceal order, your              Camouflaged: Whenever an operative is shooting this operative, opponent cannot select it as a valid target unless it’s within 6\" of   ignore the Piercing weapon rule and all cover saves are retained the operative trying to target it. Note that this rule has no effect   as critical successes. This rule has no effect if this operative isn’t if this operative isn’t selected as the valid target, e.g. if it’s a   selected as the valid target, e.g. if it’s a secondary target from secondary target from the Blast weapon rule.                           the Blast weapon rule."}], "actions": [], "keywords": ["VESPID STINGWING", "T’AU EMPIRE", "SHADESTRAIN"]},
  {"name": "Vespid Skyblast", "weapons": [{"name": "Neutron grenade launcher", "atk": 4, "hit": "4+", "dmg": "3/3", "wr": "Blast 2\", Devastating 2, Neutron Bombardment*"}, {"name": "Claws", "atk": 3, "hit": "4+", "dmg": "3/4"}], "abilities": [], "actions": [], "keywords": ["VESPID STINGWING", "T’AU EMPIRE", "SKYBLAST"]},
  {"name": "Vespid Swarmguard", "weapons": [{"name": "Flamer (standard)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 8\", Saturate, Torrent 2\""}, {"name": "Flamer (skytorch)", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Saturate, Torrent 0\", Skytorch*"}, {"name": "Claws", "atk": 3, "hit": "4+", "dmg": "3/4", "wr": "-                                                          -"}], "abilities": [], "actions": [{"name": "Skytorch Assault", "ap": 2, "text": "Perform a free Reposition action with this operative. During that action, it must FLY and can move an additional 2\". Then perform a free Shoot action. You can only select a flamer (skytorch) for that Shoot action.\nThis operative cannot perform this action while it has a Conceal order, or while within control range of an enemy operative."}], "keywords": ["VESPID STINGWING", "T’AU EMPIRE", "SWARMGUARD"]},
  {"name": "Vespid Warrior", "weapons": [{"name": "Neutron blaster", "atk": 4, "hit": "4+", "dmg": "3/3", "wr": "Devastating 2"}, {"name": "Claws", "atk": 3, "hit": "4+", "dmg": "3/4"}], "abilities": [{"name": "Warrior Instincts", "text": "Whenever this operative is shooting, if you don’t spend Communion points during that sequence, its neutron blaster has the Accurate 1 weapon rule until the end of that sequence.\nNOTES:\nNOTES:\nNOTES:"}], "actions": [], "keywords": ["VESPID STINGWING", "T’AU EMPIRE", "WARRIOR"]},
]
