// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Saedath", text: "As a STRATEGIC GAMBIT in the first turning point, you must select an ALLEGORY (Epic or Melodrama below) for your kill team for the battle, and one friendly VOID-DANCER TROUPE operative to have the PIVOTAL ROLE for the battle. Whenever a friendly operative has the PIVOTAL ROLE, it has the ACCOLADE rule of your ALLEGORY for the battle. As a STRATEGIC GAMBIT in each subsequent turning point, you can select one friendly VOID-DANCER TROUPE operative to gain the ACCOLADE rule of your ALLEGORY for the battle. Once per turning point, when a friendly operative that has the PIVOTAL ROLE completes the performance of your ALLEGORY, you can select one friendly VOID-DANCER TROUPE operative to gain the ACCOLADE rule of your ALLEGORY for the battle.\nEpic Performance: The operative incapacitates an enemy operative while fighting.\nAccolade: Whenever this operative is fighting, its melee weapons have the Balanced weapon rule.\nMelodrama Performance: The operative incapacitates an enemy operative while shooting.\nAccolade: The operative’s ranged weapons have the Balanced weapon rule." },
  { kind: 'faction', name: "Harlequin’s Panoply", text: "Whenever an operative is shooting a friendly VOID-DANCER TROUPE operative, and no attack dice are retained as critical successes, worsen the x of the Piercing weapon rule by 1 (if any). Note that Piercing 1 would therefore be ignored.\nWhenever a friendly VOID-DANCER TROUPE operative is climbing up, you can treat the vertical distance as 2\" (regardless of how far the operative actually moves vertically). Friendly VOID-DANCER TROUPE operatives can move within control range of enemy operatives (they must still start and end the move following all requirements for that move)." },
  { kind: 'strategy', name: "Rising Crescendo", text: "Friendly VOID-DANCER TROUPE operatives can perform the Dash action during the same activation in which they performed the Charge action, but not vice versa (i.e. not Dash then Charge)." },
  { kind: 'strategy', name: "Darting Salvo", text: "Whenever a friendly VOID-DANCER TROUPE operative performs the Reposition action during its activation, it can perform the Shoot action during that action (it must do so in a location it can be placed, and any remaining move distance it had from that Reposition action can be used after it does so)." },
  { kind: 'strategy', name: "Prismatic Blur", text: "Whenever an operative is shooting a friendly VOID-DANCER TROUPE operative that performed an action in which it moved during this turning point, you can re-roll one of your defence dice." },
  { kind: 'strategy', name: "Cegorach’s Jest", text: "Whenever a friendly VOID-DANCER TROUPE operative is fighting or retaliating and your opponent strikes with a normal success, you can roll one D6: if the result is less than the Hit stat of your opponent’s selected weapon, that strike is allocated to block one of your dice instead (ignore the Brutal weapon rule, if relevant) and you cannot use this rule for the rest of the sequence." },
  { kind: 'firefight', name: "The Curtain Falls", text: "Use this firefight ploy when a friendly VOID-DANCER TROUPE operative is fighting, after you strike with a critical success, if the enemy operative isn’t incapacitated. End that sequence (any remaining attack dice are discarded) and immediately perform a free Fall Back action up to 3\" with that operative (then the Fight action ends). That operative can do so even if it’s performed an action that prevents it from performing the Fall Back action." },
  { kind: 'firefight', name: "Murderous Entrance", text: "Use this firefight ploy when a friendly VOID-DANCER TROUPE operative is fighting during an activation in which it performed the Charge action, after you strike. You can immediately resolve another of your normal successes as a strike (before your opponent), or one of your critical successes if there are none." },
  { kind: 'firefight', name: "Elusive Target", text: "Use this firefight ploy during a friendly VOID-DANCER TROUPE operative’s activation. Until the start of its next activation, while that operative has a Conceal order and is in cover, it cannot be selected as a valid target, taking precedence over all other rules (e.g. Seek, Vantage terrain) except being within 2\"." },
  { kind: 'firefight', name: "Domino Field", text: "Use this firefight ploy when an operative is shooting a friendly VOID-DANCER TROUPE operative, during the Resolve Defence Dice step. You can allocate one of your rolled successful dice to block all of your opponent's attack dice with matching results (e.g. one of your successful defence dice results of 5 can be used to block all successful attack dice results of 5)." },
  { kind: 'equipment', name: "Shrieker Toxin Rounds", text: "Once per turning point, when a friendly VOID-DANCER TROUPE operative is performing the Shoot action and you select a shuriken pistol or shrieker cannon (focused), you can use this rule. If you do, until the end of that action, that weapon has the Devastating 1 weapon rule." },
  { kind: 'equipment', name: "Wraithbone Talisman", text: "Once per turning point, when a friendly VOID-DANCER TROUPE operative is shooting, fighting or retaliating, if you roll two or more fails, you can discard one of them to retain another as a normal success instead." },
  { kind: 'equipment', name: "Death Mask", text: "Whenever a friendly VOID-DANCER TROUPE operative that has an ACCOLADE rule is incapacitated, add 1 to your Tragedy tally. When your Tragedy tally reaches 3, you gain 1CP and stop that tally." },
  { kind: 'equipment', name: "Understudy’s Mask", text: "Once per battle, when you activate a friendly VOID-DANCER TROUPE operative, if the friendly operative that has the PIVOTAL ROLE has been incapacitated, you can use this rule. If you do, that activated operative has the PIVOTAL ROLE for the battle." },
]

export const operatives: Operative[] = [
  { id: "voiddancer-troupe:lead-player", name: "Lead Player", apl: 3, move: "7\"", save: "4+", w: 9 },
  { id: "voiddancer-troupe:death-jester", name: "Death Jester", apl: 3, move: "7\"", save: "4+", w: 9 },
  { id: "voiddancer-troupe:player", name: "Player", apl: 3, move: "7\"", save: "4+", w: 8 },
  { id: "voiddancer-troupe:shadowseer", name: "Shadowseer", apl: 3, move: "7\"", save: "4+", w: 9 },
]

export const datacards: Datacard[] = [
  {"name": "Lead Player", "weapons": [{"name": "Fusion pistol", "atk": 4, "hit": "3+", "dmg": "5/3", "wr": "Range 3\", Devastating 3, Piercing 2"}, {"name": "Neuro disruptor", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Piercing 1, Stun"}, {"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Blade", "atk": 5, "hit": "3+", "dmg": "4/6"}, {"name": "Caress", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Rending"}, {"name": "Embrace", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Brutal"}, {"name": "Kiss", "atk": 5, "hit": "3+", "dmg": "3/7"}, {"name": "Power weapon", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Lead the Performance", "text": "Once per battle STRATEGIC GAMBIT. If this operative is in the killzone, change the ALLEGORY you selected for your kill team. Note that the ACCOLADE rule friendly operatives have will also change."}], "actions": [], "keywords": ["VOID-DANCER TROUPE", "AELDARI", "HARLEQUIN", "LEADER", "LEAD PLAYER"], "img": "/ops/voiddancer-troupe/lead-player.webp"},
  {"name": "Death Jester", "weapons": [{"name": "Shrieker cannon (focused)", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Rending, Heavy (Reposition only), Humbling Cruelty*"}, {"name": "Shrieker cannon (sweeping)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Rending, Heavy (Dash only), Torrent 2\", Humbling Cruelty*"}, {"name": "Shrieker blade", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Rending"}], "abilities": [{"name": "Humbling Cruelty", "text": "If the target of this weapon isn’t incapacitated but any of your attack dice inflict damage, the target gains one of your Humbling Cruelty tokens (if it doesn’t already have one). Whenever an enemy operative has one of your Humbling Cruelty tokens, subtract 2\" from its Move stat and worsen the Hit stat of its weapons by 1. This isn’t cumulative with being injured. At the end of that enemy operative’s next activation, remove its Humbling Cruelty token."}], "actions": [], "keywords": ["VOID-DANCER TROUPE", "AELDARI", "HARLEQUIN", "DEATH JESTER"], "img": "/ops/voiddancer-troupe/death-jester.webp"},
  {"name": "Player", "weapons": [{"name": "Fusion pistol", "atk": 4, "hit": "3+", "dmg": "5/3", "wr": "Range 3\", Devastating 3, Piercing 2"}, {"name": "Neuro disruptor", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Piercing 1, Stun"}, {"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Blade", "atk": 5, "hit": "3+", "dmg": "4/6"}, {"name": "Caress", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Rending"}, {"name": "Embrace", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Brutal"}, {"name": "Kiss", "atk": 5, "hit": "3+", "dmg": "3/7"}], "abilities": [{"name": "Luck of the Laughing God", "text": "Once per turning point, you can use this rule. If you do, you can use a firefight ploy for 0CP if this is the specified VOID-DANCER TROUPE operative (including Command Re-roll if the attack or defence dice was rolled for this operative). You cannot select the same firefight ploy for this rule more than once per battle."}], "actions": [], "keywords": ["VOID-DANCER TROUPE", "AELDARI", "HARLEQUIN", "PLAYER"], "img": "/ops/voiddancer-troupe/player.webp"},
  {"name": "Shadowseer", "weapons": [{"name": "Hallucinogen grenade", "atk": 4, "hit": "3+", "dmg": "1/1", "wr": "Range 6\", Blast 2\", Lethal 5+, Seek Light, Silent, Stun"}, {"name": "Neuro disruptor", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Piercing 1, Stun"}, {"name": "Shuriken pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Rending"}, {"name": "Miststave", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Shock"}], "abilities": [], "actions": [{"name": "Mirror of Minds", "ap": 1, "text": "PSYCHIC. Select one enemy operative that’s a valid target for and within 8\" of this operative. Both players roll five D6. Pair your dice with your opponent’s dice based on matching results. For each matching pair, inflict D3 damage on that enemy operative (to a maximum of 8). For example, if you rolled 6, 5, 5, 2, 1 and your opponent rolled 6, 5, 4, 3, 1, you would inflict 3D3 damage on that enemy operative.\nThis operative cannot perform this action while within control range of an enemy operative."}, {"name": "Fog of Dreams", "ap": 1, "text": "PSYCHIC. Select one ready enemy operative visible to this operative and roll one D6. Until the end of the turning point, that enemy operative cannot be activated or perform actions until it’s the last enemy operative to be activated, or until your opponent has activated a number of enemy operatives after this action equal to the result of the D6 (whichever comes first).\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["VOID-DANCER TROUPE", "AELDARI", "HARLEQUIN", "PSYKER", "SHADOWSEER"], "img": "/ops/voiddancer-troupe/shadowseer.webp"},
]
