// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Boons of Tzeentch", text: "Whenever you select a SORCERER operative for the battle, you must select a BOON OF TZEENTCH\n(below) for it to have for the battle. You cannot select each BOON OF TZEENTCH more than once per battle.\nIncorporeal Sight The empyric energies given off by living creatures can be sensed by the Sorcerers of the Thousand Sons.\nThis operative’s ranged weapons have the Saturate weapon rule. Whenever this operative is shooting, enemy operatives cannot be obscured.\nTime-Walk\nThere are few greater boons than mastery over time itself.\nAdd 1\" to this operative’s Move stat." },
  { kind: 'faction', name: "Astartes", text: "During each friendly WARPCOVEN HERETIC ASTARTES operative’s activation, it can perform either two Shoot actions or two Fight actions. If it’s two Shoot actions and a soulreaper cannon or a warpflamer is selected for both, 1 additional AP must be spent for the second action. You cannot select the same PSYCHIC ranged weapon more than once per activation. Each friendly WARPCOVEN HERETIC ASTARTES operative can counteract regardless of its order." },
  { kind: 'strategy', name: "Aetherial Warding", text: "Whenever an operative is shooting a friendly WARPCOVEN operative, weapons with the Piercing 1 weapon rule have the Piercing Crits 1 weapon rule instead." },
  { kind: 'strategy', name: "Fate Itself Is My Weapon", text: "Roll two D6 and reserve them (put them to one side). In the Firefight phase of this turning point, whenever an operative is shooting, fighting or retaliating, after you or your opponent roll their attack dice, but before re-rolls, you can use one of your reserved dice to replace one of the D6 rolled for that sequence (yours or your opponent's); that replacement dice cannot be re-rolled or retained as a success if it’s not, and is discarded at the end of that sequence. Then, if the combined result of both reserved dice was less than 9, discard the other dice. You cannot use more than one reserved dice per sequence. Discard any remaining reserved dice at the end of the turning point." },
  { kind: 'strategy', name: "Savage Herd", text: "Friendly WARPCOVEN TZAANGOR operatives’ melee weapons have the Accurate 1 weapon rule. Whenever a friendly WARPCOVEN TZAANGOR operative is assisted by a friendly WARPCOVEN operative, or is fighting while visible to and within 6\" of a friendly WARPCOVEN SORCERER operative, that friendly WARPCOVEN TZAANGOR operative's melee weapons also have the Severe weapon rule." },
  { kind: 'strategy', name: "Brotherhood of Sorcerers", text: "Friendly WARPCOVEN SORCERER operatives’ PSYCHIC weapons have the Balanced weapon rule, or Ceaseless instead if another friendly WARPCOVEN SORCERER operative is within 9\" of that operative." },
  { kind: 'firefight', name: "All Is Dust", text: "Use this firefight ploy when an attack dice inflicts Normal Dmg on a friendly WARPCOVEN RUBRIC MARINE operative. That attack dice inflicts 1 damage instead." },
  { kind: 'firefight', name: "Capricious Plan", text: "Use this firefight ploy at the end of a friendly WARPCOVEN SORCERER operative’s activation. That friendly operative can immediately perform a free Dash action (even if it’s performed an action that prevents it from performing the Dash action), or you can change its order instead." },
  { kind: 'firefight', name: "Mutant Herd", text: "Use this firefight ploy when a friendly WARPCOVEN TZAANGOR operative is activated. Select one other ready friendly WARPCOVEN TZAANGOR operative visible to and within 2\" of it to activate at the same time. Complete their activations action by action in any order." },
  { kind: 'firefight', name: "Psychic Cabal", text: "Use this firefight ploy when a friendly WARPCOVEN SORCERER operative is activated. Select one other friendly WARPCOVEN SORCERER operative visible to and within 9\" of that operative, then select one of that other friendly operative's PSYCHIC unique actions or PSYCHIC ranged weapons for that first friendly operative to have until the end of its activation. You cannot select a PSYCHIC ranged weapon that has been used by that other friendly operative during this turning point, and that other friendly operative cannot use the selected weapon during this turning point." },
  { kind: 'equipment', name: "Ensorcelled Rounds", text: "Friendly WARPCOVEN operatives’ inferno boltguns, inferno bolt pistols and autopistols have the Devastating 1 weapon rule." },
  { kind: 'equipment', name: "Daemonmaw Weapons", text: "Add 1 to the Atk stat of friendly WARPCOVEN RUBRIC MARINE operatives’ melee weapons. Whenever a friendly WARPCOVEN RUBRIC MARINE operative is retaliating, its melee weapons have the Accurate 1 weapon rule." },
  { kind: 'equipment', name: "Sorcerous Scrolls", text: "Once per battle, when a friendly WARPCOVEN SORCERER operative is activated or counteracts, you can select a different BOON OF TZEENTCH for it to have until the end of the battle (it loses any it previously had). It cannot be the same BOON OF TZEENTCH any other friendly operative has. Note that if you use this rule when a friendly operative counteracts and you select Echoes from the Warp, it can be used immediately to change the operative’s order and perform a free action during that counteraction." },
  { kind: 'equipment', name: "Arcane Robes", text: "Once per turning point, whenever an attack dice would inflict Critical Dmg on a friendly WARPCOVEN SORCERER operative, you can use this rule. If you do, that attack dice inflicts Normal Dmg instead.\nNOTES:" },
]

export const operatives: Operative[] = [
  { id: "warpcoven:sorcerer-of-destiny", name: "Sorcerer of Destiny", apl: 3, move: "6\"", save: "3+", w: 15 },
  { id: "warpcoven:sorcerer-of-tempyrion", name: "Sorcerer of Tempyrion", apl: 3, move: "6\"", save: "3+", w: 15 },
  { id: "warpcoven:sorcerer-of-warpfire", name: "Sorcerer of Warpfire", apl: 3, move: "6\"", save: "3+", w: 15 },
  { id: "warpcoven:rubric-marine-gunner", name: "Rubric Marine Gunner", apl: 3, move: "5\"", save: "2+", w: 14 },
  { id: "warpcoven:rubric-marine-icon-bearer", name: "Rubric Marine Icon Bearer", apl: 3, move: "5\"", save: "2+", w: 14 },
  { id: "warpcoven:rubric-marine-warrior", name: "Rubric Marine Warrior", apl: 3, move: "5\"", save: "2+", w: 14 },
  { id: "warpcoven:tzaangor-champion", name: "Tzaangor Champion", apl: 2, move: "6\"", save: "5+", w: 10 },
  { id: "warpcoven:tzaangor-horn-bearer", name: "Tzaangor Horn Bearer", apl: 2, move: "6\"", save: "5+", w: 9 },
  { id: "warpcoven:tzaangor-icon-bearer", name: "Tzaangor Icon Bearer", apl: 2, move: "6\"", save: "5+", w: 9 },
  { id: "warpcoven:tzaangor-warrior", name: "Tzaangor Warrior", apl: 2, move: "6\"", save: "5+", w: 9 },
]

export const datacards: Datacard[] = [
  {"name": "Sorcerer of Destiny", "weapons": [{"name": "Doombolt", "atk": 4, "hit": "3+", "dmg": "4/2", "wr": "PSYCHIC, Devastating 2, Lethal 5+"}, {"name": "Inferno bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Piercing 1"}, {"name": "Warpflame pistol", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 6\", Piercing 1, Torrent 1\""}, {"name": "Force stave", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "PSYCHIC, Shock"}, {"name": "Prosperine khopesh", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [], "actions": [{"name": "Protected by Fate", "ap": 1, "text": "PSYCHIC. Select one friendly WARPCOVEN operative visible to this operative. Until the start of this operative’s next activation, until it’s incapacitated or until this action is performed again by a friendly operative (whichever comes first), whenever an operative is shooting that selected operative, you can re-roll any of your defence dice.\nThis operative cannot perform this action while within control range of an enemy operative."}, {"name": "Ravage Destiny", "ap": 1, "text": "PSYCHIC. Select one enemy operative visible to and within 9\" of this operative. Until the start of this operative’s next activation, until it's incapacitated or until this action is performed again by a friendly operative (whichever comes first), whenever that enemy operative is shooting, fighting or retaliating, your opponent must re-roll their attack dice results of 6, and whenever determining control of a marker, treat that enemy operative’s APL stat as 1 lower. Note this isn't a change to its APL stat, so any changes are cumulative with this.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["WARPCOVEN", "CHAOS", "HERETIC ASTARTES", "PSYKER", "SORCERER", "DESTINY"]},
  {"name": "Sorcerer of Tempyrion", "weapons": [{"name": "Fluxblast", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "PSYCHIC, Blast 2\", Rending"}, {"name": "Inferno bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Piercing 1"}, {"name": "Warpflame pistol", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 6\", Piercing 1, Torrent 1\""}, {"name": "Force stave", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "PSYCHIC, Shock"}, {"name": "Prosperine khopesh", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [], "actions": [{"name": "Reconstitution Ritual", "ap": 1, "text": "PSYCHIC. Select one friendly WARPCOVEN operative visible to and within 6\" of this operative. That operative regains up to 2D3 lost wounds.\nThis operative cannot perform this action while within control range of an enemy operative, or if a friendly operative has already performed this action during this turning point."}, {"name": "Temporal Flux", "ap": 1, "text": "PSYCHIC. Select one friendly WARPCOVEN operative visible to and within 6\" of this operative and place your Temporal Flux marker within that operative’s control range.\nAt the end of that operative’s next activation, if it hasn’t been incapacitated and is still wholly within 6\" of your Temporal Flux marker, remove that operative from the killzone and set it back up in a location it can be placed; when it's set back up, it must have your Temporal Flux marker within its control range (or as close as possible). Then remove your Temporal Flux marker from the killzone. If that operative isn't wholly within 6\" of your Temporal Flux marker (including if it’s incapacitated), remove that marker from the killzone.\nThis operative cannot perform this action while within control range of an enemy operative, or if your Temporal Flux marker is currently in the killzone."}], "keywords": ["WARPCOVEN", "CHAOS", "HERETIC ASTARTES", "PSYKER", "SORCERER", "TEMPYRION"]},
  {"name": "Sorcerer of Warpfire", "weapons": [{"name": "Firestorm", "atk": 5, "hit": "4+", "dmg": "2/3", "wr": "PSYCHIC, Saturate, Seek Light, Torrent 2\""}, {"name": "Inferno bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\", Piercing 1"}, {"name": "Mindburn", "atk": 5, "hit": "4+", "dmg": "1/1", "wr": "PSYCHIC, Lethal 5+, Saturate, Seek Light,"}], "abilities": [], "actions": [{"name": "Alight", "ap": 1, "text": "PSYCHIC. Select one enemy operative visible to this\noperative. Until the start of this operative’s next activation,\nuntil it's incapacitated or until this action is performed\nagain by a friendly operative (whichever comes first), that\nenemy operative gains one of your Alight tokens (if it doesn’t\nalready have one). Whenever a friendly WARPCOVEN\noperative is shooting against, fighting against or retaliating against an enemy operative that has one of your Alight tokens, that friendly operative’s weapons have the Ceaseless weapon rule.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["WARPCOVEN", "CHAOS", "HERETIC ASTARTES", "PSYKER", "SORCERER", "WARPFIRE"]},
  {"name": "Rubric Marine Gunner", "weapons": [{"name": "Soulreaper cannon (focused)", "atk": 5, "hit": "3+", "dmg": "4/5", "wr": "Piercing 1"}, {"name": "Soulreaper cannon (sweeping)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Piercing 1, Torrent 1\""}, {"name": "Warpflamer", "atk": 4, "hit": "2+", "dmg": "4/4", "wr": "Range 8\", Saturate, Piercing 1, Torrent 2\""}, {"name": "Fists", "atk": 3, "hit": "3+", "dmg": "3/4"}], "abilities": [{"name": "Sorcerous Automata", "text": "Whenever this operative is activated, subtract 1 from its APL stat until the end of that activation, unless a friendly WARPCOVEN SORCERER operative is within 9\" of it."}], "actions": [], "keywords": ["WARPCOVEN", "CHAOS", "HERETIC ASTARTES", "RUBRIC MARINE", "GUNNER"]},
  {"name": "Rubric Marine Icon Bearer", "weapons": [{"name": "Inferno boltgun", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Piercing 1"}, {"name": "Fists", "atk": 3, "hit": "3+", "dmg": "3/4"}], "abilities": [{"name": "Sorcerous Automata", "text": "Whenever this operative is activated, subtract 1 from its APL stat until the end of that activation, unless a friendly WARPCOVEN SORCERER operative is within 9\" of it."}, {"name": "Icon Bearer", "text": "Whenever determining control of a marker, treat this operative’s APL stat as 1 higher. Note this isn’t a change to its APL stat, so any changes are cumulative with this."}], "actions": [], "keywords": ["WARPCOVEN", "CHAOS", "HERETIC ASTARTES", "RUBRIC MARINE", "ICON BEARER"]},
  {"name": "Rubric Marine Warrior", "weapons": [{"name": "Inferno boltgun", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Piercing 1"}, {"name": "Fists", "atk": 3, "hit": "3+", "dmg": "3/4"}], "abilities": [{"name": "Sorcerous Automata", "text": "Whenever this operative is activated, subtract 1 from its APL stat until the end of that activation, unless a friendly WARPCOVEN SORCERER operative is within 9\" of it."}, {"name": "Slow and Purposeful", "text": "Whenever this operative is shooting, if it hasn’t performed the Charge or Reposition action during the activation, or if it's a counteraction, its ranged weapons have the Ceaseless weapon rule. Note this operative isn’t restricted from performing these actions after shooting."}], "actions": [], "keywords": ["WARPCOVEN", "CHAOS", "HERETIC ASTARTES", "RUBRIC MARINE", "WARRIOR"]},
  {"name": "Tzaangor Champion", "weapons": [{"name": "Greataxe", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Brutal, Lethal 5+"}, {"name": "Greatblade", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Lethal 5+, Rending"}], "abilities": [{"name": "Savage Brutality", "text": "The first time this operative performs the Fight action during each of its activations, if it isn’t incapacitated, it can immediately perform a free Fight action afterwards (you don't have to select the same enemy operative to fight against). This takes precedence over action restrictions."}], "actions": [], "keywords": ["WARPCOVEN", "CHAOS", "TZAANGOR", "CHAMPION"]},
  {"name": "Tzaangor Horn Bearer", "weapons": [{"name": "Dagger", "atk": 4, "hit": "4+", "dmg": "3/5"}], "abilities": [], "actions": [{"name": "Brayhorn", "ap": 0, "text": "Until the Ready step of the next Strategy phase, add 1\" to the Move stat of friendly WARPCOVEN TZAANGOR operatives.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["WARPCOVEN", "CHAOS", "TZAANGOR", "HORN BEARER"]},
  {"name": "Tzaangor Icon Bearer", "weapons": [{"name": "Dagger", "atk": 4, "hit": "4+", "dmg": "3/5"}], "abilities": [{"name": "Herd Banner", "text": "Whenever an attack dice inflicts Normal Dmg of 3 or more on a friendly WARPCOVEN TZAANGOR operative that’s visible to and within 3\" of this operative, subtract 1 from that inflicted damage."}, {"name": "Icon Bearer", "text": "Whenever determining control of a marker, treat this operative’s APL stat as 1 higher. Note this isn't a change to its APL stat, so any changes are cumulative with this."}], "actions": [], "keywords": ["WARPCOVEN", "CHAOS", "TZAANGOR", "ICON BEARER"]},
  {"name": "Tzaangor Warrior", "weapons": [{"name": "Autopistol", "atk": 4, "hit": "4+", "dmg": "2/3", "wr": "Range 8\""}, {"name": "Chainsword", "atk": 4, "hit": "4+", "dmg": "4/5"}, {"name": "Tzaangor blade & shield", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Shield*"}, {"name": "Tzaangor blades", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Balanced"}], "abilities": [{"name": "Relic Hunters", "text": "Once per battle, one friendly WARPCOVEN TZAANGOR WARRIOR can perform the Pick Up Marker, Place Marker or a mission action for 1 less AP if that friendly operative is within your opponent's territory.\nNOTES:\nNOTES:\nNOTES:"}], "actions": [], "keywords": ["WARPCOVEN", "CHAOS", "TZAANGOR", "WARRIOR"]},
]
