// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Hunting Astartes", text: "During each friendly WOLF SCOUT operative’s activation, it can perform either two Shoot actions or two Fight actions. If it’s two Shoot actions:\n• 1 additional AP must be spent for the second action if both actions are using a plasma gun or plasma pistol.\n• You cannot select two PSYCHIC ranged weapons. Each friendly WOLF SCOUT operative can counteract regardless of its order. Whenever it does so within your STORM, you can change its order first, or change its order instead of performing an action (for the latter, still treat it as having counteracted this turning point)." },
  { kind: 'faction', name: "Elemental Storm", text: "STRATEGIC GAMBIT. Remove your Storm marker from the killzone (if any), then place it in the killzone. Whenever an operative is wholly within 6\" horizontally of your Storm marker, it’s wholly within your STORM. Each friendly WOLF SCOUT operative can perform the Charge action while it has a Conceal order if it ends that action wholly within your STORM." },
  { kind: 'strategy', name: "Cloaked by the Storm", text: "Whenever an operative is shooting a friendly WOLF SCOUT operative that’s wholly within your STORM, you can re-roll one of your defence dice." },
  { kind: 'strategy', name: "Storm’s Bite", text: "Whenever a friendly WOLF SCOUT operative is fighting against an enemy operative that’s wholly within your STORM, subtract 1 from the Atk stat of that enemy operative’s melee weapons (to a minimum of 3)." },
  { kind: 'strategy', name: "Tempestuous Wrath", text: "Whenever a friendly WOLF SCOUT operative is fighting or retaliating, if it’s wholly within your STORM or was wholly within your STORM at the start of the activation, its melee weapons have the Balanced weapon rule." },
  { kind: 'strategy', name: "Savage Fighters", text: "Whenever a friendly WOLF SCOUT operative finishes retaliating, if it wasn’t incapacitated and is still within control range of the enemy operative in that sequence, you can inflict D3+1 damage on that enemy operative." },
  { kind: 'firefight', name: "Acute Senses", text: "Use this firefight ploy when a friendly WOLF SCOUT operative performs the Shoot action and you’re selecting a valid target. Until the end of that action, that friendly operative’s ranged weapons have the Range 6\" and Seek Light weapon rules and enemy operatives cannot be obscured." },
  { kind: 'firefight', name: "Touched by Lokyar", text: "Use this firefight ploy after rolling your attack dice for a friendly WOLF SCOUT operative (excluding FENRISIAN WOLF), if it’s fighting more than 5\" from other friendly operatives. You can re-roll any of your attack dice." },
  { kind: 'firefight', name: "Counterattack", text: "Use this firefight ploy at the end of an enemy operative’s activation, or after an enemy operative performs the Fight action. One friendly WOLF SCOUT operative can immediately perform a free Fight action, but you cannot select any other enemy operative to fight against during that action." },
  { kind: 'firefight', name: "Transhuman Physiology", text: "Use this firefight ploy when an operative is shooting a friendly WOLF SCOUT operative (excluding FENRISIAN WOLF), in the Roll Defence Dice step. You can retain one of your normal successes as a critical success instead." },
  { kind: 'equipment', name: "Frost Weapons", text: "Whenever a friendly WOLF SCOUT operative is wholly within your STORM, its combat blade (if any) has the Lethal 5+ weapon rule." },
  { kind: 'equipment', name: "Wolfteeth Necklaces", text: "Once per turning point, when a friendly WOLF SCOUT operative (excluding FENRISIAN WOLF) is shooting, fighting or retaliating, if you roll two or more fails, you can discard one of them to retain another as a normal success instead." },
  { kind: 'equipment', name: "Runic Charms", text: "Once per turning point, when an operative is shooting a friendly WOLF SCOUT operative (excluding FENRISIAN WOLF) that’s wholly within your STORM, at the start of the Roll Defence Dice step, you can use this rule. If you do, worsen the x of the Piercing weapon rule by 1 (if any) until the end of that sequence. Note that Piercing 1 would therefore be ignored." },
  { kind: 'equipment', name: "Talismanic Trophies", text: "Whenever a friendly WOLF SCOUT operative\n(excluding FENRISIAN WOLF) that’s wholly within your STORM is fighting or retaliating, in the Resolve Attack Dice step, you can subtract 1 from the damage inflicted on it from one normal success." },
]

export const operatives: Operative[] = [
  { id: "wolf-scouts:wolf-scout-pack-leader", name: "Wolf Scout Pack Leader", apl: 3, move: "7\"", save: "3+", w: 13 },
  { id: "wolf-scouts:wolf-scout-fangbearer", name: "Wolf Scout Fangbearer", apl: 3, move: "7\"", save: "3+", w: 13 },
  { id: "wolf-scouts:wolf-scout-frosteye", name: "Wolf Scout Frosteye", apl: 3, move: "7\"", save: "3+", w: 13 },
  { id: "wolf-scouts:wolf-scout-gunner", name: "Wolf Scout Gunner", apl: 3, move: "7\"", save: "3+", w: 13 },
  { id: "wolf-scouts:wolf-scout-hunter", name: "Wolf Scout Hunter", apl: 3, move: "7\"", save: "3+", w: 13 },
  { id: "wolf-scouts:wolf-scout-rune-priest-skjald", name: "Wolf Scout Rune Priest Skjald", apl: 3, move: "7\"", save: "3+", w: 13 },
  { id: "wolf-scouts:wolf-scout-trapmaster", name: "Wolf Scout Trapmaster", apl: 3, move: "7\"", save: "3+", w: 13 },
  { id: "wolf-scouts:wolf-scout-fenrisian-wolf", name: "Wolf Scout Fenrisian Wolf", apl: 2, move: "8\"", save: "5+", w: 9 },
]

export const datacards: Datacard[] = [
  {"name": "Wolf Scout Pack Leader", "weapons": [{"name": "Plasma pistol (standard)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Piercing 1"}, {"name": "Plasma pistol (supercharge)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Hot, Lethal 5+, Piercing 1"}, {"name": "Power weapon", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Lupine Guile", "text": "Once per battle, after rolling off to decide initiative, if this operative is in the killzone, you can re-roll your dice."}, {"name": "Grizzled Veteran", "text": "The first time this operative would be incapacitated during the battle, it’s not incapacitated, has 1 wound remaining and cannot be incapacitated for the remainder of the action. All remaining attack dice are discarded (including yours if this operative is fighting or retaliating). You cannot use the Counterattack firefight ploy or inflict damage as a result of the Savage Fighters strategy ploy at the end of that action."}], "actions": [], "keywords": ["WOLF SCOUT", "IMPERIUM", "ADEPTUS ASTARTES", "SPACE WOLVES", "PACK", "LEADER"], "img": "/ops/wolf-scouts/wolf-scout-pack-leader.webp"},
  {"name": "Wolf Scout Fangbearer", "weapons": [{"name": "Absolvor bolt pistol", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Piercing Crits 1"}, {"name": "Combat blade", "atk": 5, "hit": "3+", "dmg": "4/5"}], "abilities": [{"name": "Spiritual Chirurgy", "text": "You can ignore any changes to the stats of friendly WOLF SCOUT operatives (excluding FENRISIAN\nWOLF) from being injured (including their weapons’ stats). Note\nthat friendly operatives have this rule if you select this operative for the battle (even if it’s incapacitated later)."}], "actions": [{"name": "Healing Balms", "ap": 1, "text": "Select one friendly WOLF SCOUT operative within this\noperative’s control range to regain up to D3+3 lost wounds.\nThis operative cannot perform this action while within control range of an enemy operative, or more than once per turning point."}], "keywords": ["WOLF SCOUT", "IMPERIUM", "ADEPTUS ASTARTES", "SPACE WOLVES", "FANGBEARER"], "img": "/ops/wolf-scouts/wolf-scout-fangbearer.webp"},
  {"name": "Wolf Scout Frosteye", "weapons": [{"name": "Instigator bolt carbine", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Piercing Crits 1, Silent"}, {"name": "Combat blade", "atk": 4, "hit": "3+", "dmg": "4/5"}], "abilities": [{"name": "Storm-veiled Execution", "text": "Whenever this operative is wholly within your STORM:\n• It can perform the Guard action regardless of the killzone (see close quarters rules, Kill Team Core Book). • It can perform the Guard action while it has a Conceal order."}], "actions": [{"name": "Hunter’s Senses", "ap": 1, "text": "Select one of the following rules for this operative’s instigator bolt carbine to have until the start of its next activation:\n• Severe. • Saturate, and whenever this operative is shooting with that weapon, enemy operatives cannot be obscured.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["WOLF SCOUT", "IMPERIUM", "ADEPTUS ASTARTES", "SPACE WOLVES", "FROSTEYE"], "img": "/ops/wolf-scouts/wolf-scout-frosteye.webp"},
  {"name": "Wolf Scout Gunner", "weapons": [{"name": "Plasma gun (standard)", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Piercing 1"}, {"name": "Plasma gun (supercharge)", "atk": 4, "hit": "3+", "dmg": "5/6", "wr": "Hot, Lethal 5+, Piercing 1"}, {"name": "Combat blade", "atk": 4, "hit": "3+", "dmg": "4/5"}], "abilities": [{"name": "Tempest’s Fury", "text": "Whenever this operative is wholly within your STORM:\n• All profiles of its plasma gun have the Punishing weapon rule. • Its plasma gun (supercharge) doesn’t have the Hot weapon rule."}], "actions": [], "keywords": ["WOLF SCOUT", "IMPERIUM", "ADEPTUS ASTARTES", "SPACE WOLVES", "GUNNER"], "img": "/ops/wolf-scouts/wolf-scout-gunner.webp"},
  {"name": "Wolf Scout Hunter", "weapons": [{"name": "Plasma pistol (standard)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Piercing 1"}, {"name": "Plasma pistol (supercharge)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Hot, Lethal 5+, Piercing 1"}, {"name": "Combat blade", "atk": 5, "hit": "3+", "dmg": "4/5"}], "abilities": [{"name": "Fierce Temperament", "text": "Whenever this operative is wholly within your STORM, its weapons have the Severe weapon rule."}], "actions": [], "keywords": ["WOLF SCOUT", "IMPERIUM", "ADEPTUS ASTARTES", "SPACE WOLVES", "HUNTER"], "img": "/ops/wolf-scouts/wolf-scout-hunter.webp"},
  {"name": "Wolf Scout Rune Priest Skjald", "weapons": [{"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Jaws of the World Wolf", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "PSYCHIC, Blast 2\", Severe"}, {"name": "Thunderclap", "atk": 5, "hit": "2+", "dmg": "2/2", "wr": "PSYCHIC, Range 6\", Saturate, Seek Light, Stun, Torrent 2\""}, {"name": "Runic stave", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "PSYCHIC, Shock"}], "abilities": [{"name": "Cast the Runes", "text": "After selecting this operative, before the battle, roll three D6 and put them to one side. For each result of 1-4, you can use the Command Re-roll firefight ploy for OCP once during the turning point that matches the result. If one or more results are 5-6, you gain 1CP. For example, if you roll 2, 2 and 5, you gain 1CP and twice during the second turning point you can use Command Re-roll for 0CP."}], "actions": [{"name": "Call the Storm", "ap": 1, "text": "PSYCHIC. Remove your Storm marker from the killzone (if any), then place it in the killzone.\nPSYCHIC. Alternatively, instead of resolving the above effect, select one friendly WOLF SCOUT operative. Until the start of this operative’s next activation, until it’s incapacitated or until it performs this action again (whichever comes first), whenever that friendly operative is wholly within your STORM and more than 3\" from the active operative, it’s obscured.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["WOLF SCOUT", "IMPERIUM", "ADEPTUS ASTARTES", "SPACE WOLVES", "PSYKER", "RUNE PRIEST SKJALD"], "img": "/ops/wolf-scouts/wolf-scout-rune-priest-skjald.webp"},
  {"name": "Wolf Scout Trapmaster", "weapons": [{"name": "Plasma pistol (standard)", "atk": 4, "hit": "3+", "dmg": "3/5", "wr": "Range 8\", Piercing 1"}, {"name": "Plasma pistol (supercharge)", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Range 8\", Hot, Lethal 5+, Piercing 1"}, {"name": "Combat blade", "atk": 5, "hit": "3+", "dmg": "4/5"}], "abilities": [{"name": "Haywire Mine", "text": "This operative is carrying your Haywire Mine marker. It can perform the Pick Up Marker action on that marker, but that marker cannot be placed within another operative’s control range (if this operative is incapacitated while carrying that marker and that marker cannot be placed, it’s removed with this operative)."}, {"name": "Proximity Mine", "text": "The first time your Haywire Mine marker is within another operative’s control range, remove that marker, subtract 1 from that operative’s APL stat until the end of its next activation, and inflict 2D3+3 damage on it (or D3+6 if that marker is within 6\" horizontally of your Storm marker); if it isn’t incapacitated, end its action (if any), even if that action’s effects aren’t fulfilled. If it cannot be placed, move it the minimum amount to do so. Note that this operative is ignored for these effects (i.e. it cannot set it off or take damage from that marker)."}], "actions": [], "keywords": ["WOLF SCOUT", "IMPERIUM", "ADEPTUS ASTARTES", "SPACE WOLVES", "TRAPMASTER"], "img": "/ops/wolf-scouts/wolf-scout-trapmaster.webp"},
  {"name": "Wolf Scout Fenrisian Wolf", "weapons": [{"name": "Fangs", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Rending"}], "abilities": [{"name": "Instinctive Predator", "text": "This operative cannot perform any actions other than Charge, Dash, Fall Back, Fight, Guard and Reposition. It cannot use any weapons that aren’t on its datacard. This operative can perform the Charge action while it has a Conceal order.\nWOLF SCOUT , IMPERIUM, ADEPTUS ASTARTES, SPACE WOLVES, FENRISIAN WOLF"}, {"name": "Pounce", "text": "Once per battle STRATEGIC GAMBIT. If this operative’s APL stat is 2 or more, this operative can perform a free Charge, Fall Back or Reposition action. If it does, until the end of its next activation, subtract 1 from its APL stat and it cannot perform any of the aforementioned actions.\n60x35"}], "actions": [], "img": "/ops/wolf-scouts/wolf-scout-fenrisian-wolf.webp"},
]
