// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Familiar Territory", text: "When setting up a WYRMBLADE kill team before the battle, one third of your kill team can be set up in HIDING: place them to one side instead of in the killzone. CULT AGENT operatives cannot be set up in HIDING. In the Firefight phase, friendly WYRMBLADE operatives set up in HIDING are activated as normal. When you do, you can either expend that operative or have it emerge. If it emerges, set it up in the killzone in a location it can be placed as follows (it’s no longer set up in HIDING):\n• Wholly within 6\" of your drop zone.\n• More than 6\" from enemy operatives.\n• With an order of your choice." },
  { kind: 'faction', name: "Cult Agent", text: "Whenever an operative is shooting a friendly WYRMBLADE CULT AGENT operative:\n• Ignore the Piercing and Saturate weapon rules.\n• If you can retain any cover saves, you can retain one additional cover save, or you can retain one cover save as a critical success instead. This isn’t cumulative with improved cover saves from Vantage terrain." },
  { kind: 'strategy', name: "The Day Is at Hand", text: "When the moment is right, the Cult strikes. Swift and brutal ambushes allow for high lethality, even with improvised weapons.\nWhenever a friendly WYRMBLADE operative is activated, if its order is changed from Conceal to Engage, until the end of that activation:\n• Its ranged weapons have the Rending weapon rule.\n• Add 1 to the Atk stat of its melee weapons (to a maximum of 5)." },
  { kind: 'faction', name: "Cult Ambush", text: "When the Day of Ascension arrives, the Cult strike as one, catching their foes unawares with lethal ambushes and surprise assaults. Whenever a friendly WYRMBLADE operative is shooting or fighting during its activation, if its order was changed from Conceal to Engage at the start of that activation, or it wasn’t visible to enemy operatives at the start of that activation, that friendly operative's weapons have the\nCeaseless weapon rule." },
  { kind: 'strategy', name: "Crossfire", text: "Whenever a friendly WYRMBLADE operative is shooting an operative that another friendly WYRMBLADE operative has already shot during this turning point, that first friendly operative's ranged weapons have the Accurate 1 weapon rule." },
  { kind: 'strategy', name: "One with the Shadows", text: "Whenever an operative is shooting a friendly WYRMBLADE operative that has a Conceal order, if Light terrain is intervening, that friendly operative is obscured (unless the intervening Light terrain is within 1\" of either operative)." },
  { kind: 'firefight', name: "Slink Into Darkness", text: "Use this firefight ploy at the end of a friendly WYRMBLADE operative’s activation. If that operative has an Engage order, change it to Conceal. You cannot use this ploy for each friendly operative more than once per battle." },
  { kind: 'strategy', name: "Divert and Disappear", text: "Up to three friendly WYRMBLADE operatives can immediately perform a free Dash or Charge action in an order of your choice (choose separately for each, and for the latter, it cannot move more than 3\"). If a WYRMBLADE CULT AGENT operative is selected for this ploy, it counts as two operatives, and it can perform a free Fall Back action instead (it cannot move more than 3\"); if it does, subtract 1 from its APL stat until the end of its next activation." },
  { kind: 'firefight', name: "Coiled Serpent", text: "When the ambush occurs, it does so with lightning speed and precise coordination, obliterating its targets in a hail of firepower or slashing blades.\nUse this firefight ploy when a friendly WYRMBLADE operative is shooting or fighting, after rolling your attack dice. If that friendly operative’s order was changed from Conceal to Engage at the start of that activation and this is the first time it's performed either the Shoot or Fight action during that activation, you can retain one of your normal successes as a critical success instead. Note this ploy cannot come into effect more than once per activation (you cannot use it during both the Shoot and Fight action in the same activation)." },
  { kind: 'firefight', name: "Unquestioning Loyalty", text: "Use this firefight ploy when a friendly\nWYRMBLADE CULT AGENT or WYRMBLADE LEADER operative is selected as the valid target of a Shoot action or to fight against during the Fight action. Select one other friendly WYRMBLADE NEOPHYTE operative (excluding LEADER) visible to and within 3\" of that first friendly operative to become the valid target or to be fought against (as appropriate) instead (even if it wouldn’t normally be valid for this). If it’s the Fight action, treat that other operative as being within the fighting operative’s control range for the duration of that action. If it’s the Shoot action, that other operative is only in cover or obscured if the original target was. This ploy has no effect if it’s the Shoot action and the ranged weapon has the Blast or Torrent weapon rule." },
  { kind: 'equipment', name: "Blasting Charges", text: "Once per turning point, a friendly WYRMBLADE NEOPHYTE operative can use the following ranged weapon — Blasting charge: ATK 4, HIT 4+, DMG 3/5.\nWR Range 4\", Blast 1\", Saturate" },
  { kind: 'firefight', name: "A Plan Generations in the Making", text: "Use this firefight ploy when a friendly WYRMBLADE NEOPHYTE operative is incapacitated. It can perform a free mission action before it’s removed from the killzone." },
  { kind: 'equipment', name: "Cult Knives", text: "Friendly WYRMBLADE NEOPHYTE operatives have the following melee weapon — Cult knife: ATK 3, HIT 4+, DMG 3/4." },
  { kind: 'equipment', name: "Explosive Traps", text: "You cannot also select that equipment as normal (i.e. to give you three), and friendly WYRMBLADE operatives are ignored for your mines’ effects (i.e. they cannot trigger or take damage from them). This takes precedence over the normal mines rules." },
  { kind: 'equipment', name: "Spotlights", text: "Whenever a friendly WYRMBLADE operative is shooting, the target cannot be obscured if it's visible to and within 6\" of a friendly WYRMBLADE NEOPHYTE operative that isn't within control range of enemy operatives." },
]

export const operatives: Operative[] = [
  { id: "wyrmblade:neophyte-leader", name: "Neophyte Leader", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "wyrmblade:kelermorph", name: "Kelermorph", apl: 3, move: "6\"", save: "4+", w: 9 },
  { id: "wyrmblade:locus", name: "Locus", apl: 3, move: "6\"", save: "4+", w: 9 },
  { id: "wyrmblade:neophyte-gunner", name: "Neophyte Gunner", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "wyrmblade:neophyte-heavy-gunner", name: "Neophyte Heavy Gunner", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "wyrmblade:neophyte-icon-bearer", name: "Neophyte Icon Bearer", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "wyrmblade:sanctus-sniper", name: "Sanctus Sniper", apl: 3, move: "6\"", save: "4+", w: 9 },
  { id: "wyrmblade:sanctus-talon", name: "Sanctus Talon", apl: 3, move: "6\"", save: "4+", w: 9 },
  { id: "wyrmblade:neophyte-warrior", name: "Neophyte Warrior", apl: 2, move: "6\"", save: "5+", w: 7 },
]
