// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Familiar Territory", text: "When setting up a WYRMBLADE kill team before the battle, one third of your kill team can be set up in HIDING: place them to one side instead of in the killzone. CULT AGENT operatives cannot be set up in HIDING. In the Firefight phase, friendly WYRMBLADE operatives set up in HIDING are activated as normal. When you do, you can either expend that operative or have it emerge. If it emerges, set it up in the killzone in a location it can be placed as follows (it’s no longer set up in HIDING):\n• Wholly within 6\" of your drop zone.\n• More than 6\" from enemy operatives.\n• With an order of your choice." },
  { kind: 'faction', name: "Cult Agent", text: "Whenever an operative is shooting a friendly WYRMBLADE CULT AGENT operative:\n• Ignore the Piercing and Saturate weapon rules.\n• If you can retain any cover saves, you can retain one additional cover save, or you can retain one cover save as a critical success instead. This isn’t cumulative with improved cover saves from Vantage terrain." },
  { kind: 'strategy', name: "The Day Is at Hand", text: "When the moment is right, the Cult strikes. Swift and brutal ambushes allow for high lethality, even with improvised weapons.\nWhenever a friendly WYRMBLADE operative is activated, if its order is changed from Conceal to Engage, until the end of that activation:\n• Its ranged weapons have the Rending weapon rule.\n• Add 1 to the Atk stat of its melee weapons (to a maximum of 5)." },
  { kind: 'faction', name: "Cult Ambush", text: "When the Day of Ascension arrives, the Cult strike as one, catching their foes unawares with lethal ambushes and surprise assaults. Whenever a friendly WYRMBLADE operative is shooting or fighting during its activation, if its order was changed from Conceal to Engage at the start of that activation, or it wasn’t visible to enemy operatives at the start of that activation, that friendly operative's weapons have the\nCeaseless weapon rule." },
  { kind: 'strategy', name: "Crossfire", text: "Whenever a friendly WYRMBLADE operative is shooting an operative that another friendly WYRMBLADE operative has already shot during this turning point, that first friendly operative's ranged weapons have the Accurate 1 weapon rule." },
  { kind: 'strategy', name: "One with the Shadows", text: "Whenever an operative is shooting a friendly WYRMBLADE operative that has a Conceal order, if Light terrain is intervening, that friendly operative is obscured (unless the intervening Light terrain is within 1\" of either operative)." },
  { kind: 'firefight', name: "Slink Into Darkness", text: "Use this firefight ploy at the end of a friendly WYRMBLADE operative’s activation. If that operative has an Engage order, change it to Conceal. You cannot use this ploy for each friendly operative more than once per battle." },
  { kind: 'strategy', name: "Divert and Disappear", text: "Up to three friendly WYRMBLADE operatives can immediately perform a free Dash or Charge action in an order of your choice (choose separately for each, and for the latter, it cannot move more than 3\"). If a WYRMBLADE CULT AGENT operative is selected for this ploy, it counts as two operatives, and it can perform a free Fall Back action instead (it cannot move more than 3\"); if it does, subtract 1 from its APL stat until the end of its next activation." },
  { kind: 'firefight', name: "Coiled Serpent", text: "When the ambush occurs, it does so with lightning speed and precise coordination, obliterating its targets in a hail of firepower or slashing blades.\nUse this firefight ploy when a friendly WYRMBLADE operative is shooting or fighting, after rolling your attack dice. If that friendly operative’s order was changed from Conceal to Engage at the start of that activation and this is the first time it's performed either the Shoot or Fight action during that activation, you can retain one of your normal successes as a critical success instead. Note this ploy cannot come into effect more than once per activation (you cannot use it during both the Shoot and Fight action in the same activation)." },
  { kind: 'firefight', name: "Unquestioning Loyalty", text: "Use this firefight ploy when a friendly\nWYRMBLADE CULT AGENT or WYRMBLADE LEADER operative is selected as the valid target of a Shoot action or to fight against during the Fight action. Select one other friendly WYRMBLADE NEOPHYTE operative (excluding LEADER) visible to and within 3\" of that first friendly operative to become the valid target or to be fought against (as appropriate) instead (even if it wouldn’t normally be valid for this). If it’s the Fight action, treat that other operative as being within the fighting operative’s control range for the duration of that action. If it’s the Shoot action, that other operative is only in cover or obscured if the original target was. This ploy has no effect if it’s the Shoot action and the ranged weapon has the Blast or Torrent weapon rule." },
  { kind: 'equipment', name: "Blasting Charges", text: "Once per turning point, a friendly WYRMBLADE NEOPHYTE operative can use the following ranged weapon — Blasting charge: ATK 4, HIT 4+, DMG 3/5.\nWR Range 4\", Blast 1\", Saturate" },
  { kind: 'firefight', name: "A Plan Generations in the Making", text: "Use this firefight ploy when a friendly WYRMBLADE NEOPHYTE operative is incapacitated. It can perform a free mission action before it’s removed from the killzone." },
  { kind: 'equipment', name: "Cult Knives", text: "Friendly WYRMBLADE NEOPHYTE operatives have the following melee weapon — Cult knife: ATK 3, HIT 4+, DMG 3/4." },
  { kind: 'equipment', name: "Explosive Traps", text: "You cannot also select that equipment as normal (i.e. to give you three), and friendly WYRMBLADE operatives are ignored for your mines’ effects (i.e. they cannot trigger or take damage from them). This takes precedence over the normal mines rules." },
  { kind: 'equipment', name: "Spotlights", text: "Whenever a friendly WYRMBLADE operative is shooting, the target cannot be obscured if it's visible to and within 6\" of a friendly WYRMBLADE NEOPHYTE operative that isn't within control range of enemy operatives." },
]

export const operatives: Operative[] = [
  { id: "wyrmblade:neophyte-leader", name: "Neophyte Leader", apl: 2, move: "6\"", save: "5+", w: 8 },
  { id: "wyrmblade:kelermorph", name: "Kelermorph", apl: 3, move: "6\"", save: "4+", w: 9 },
  { id: "wyrmblade:locus", name: "Locus", apl: 3, move: "6\"", save: "4+", w: 9 },
  { id: "wyrmblade:neophyte-gunner", name: "Neophyte Gunner", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "wyrmblade:neophyte-heavy-gunner", name: "Neophyte Heavy Gunner", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "wyrmblade:neophyte-icon-bearer", name: "Neophyte Icon Bearer", apl: 2, move: "6\"", save: "5+", w: 7 },
  { id: "wyrmblade:sanctus-sniper", name: "Sanctus Sniper", apl: 3, move: "6\"", save: "4+", w: 9 },
  { id: "wyrmblade:sanctus-talon", name: "Sanctus Talon", apl: 3, move: "6\"", save: "4+", w: 9 },
  { id: "wyrmblade:neophyte-warrior", name: "Neophyte Warrior", apl: 2, move: "6\"", save: "5+", w: 7 },
]

export const datacards: Datacard[] = [
  {"name": "Neophyte Leader", "weapons": [{"name": "Autogun", "atk": 4, "hit": "3+", "dmg": "2/3"}, {"name": "Bolt pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 8\""}, {"name": "Master-crafted autopistol", "atk": 4, "hit": "3+", "dmg": "2/4", "wr": "Range 8\", Lethal 5+"}, {"name": "Shotgun", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 6\""}, {"name": "Web pistol", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 6\", Severe, Stun"}, {"name": "Chainsword", "atk": 4, "hit": "3+", "dmg": "4/5"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}, {"name": "Power maul", "atk": 4, "hit": "3+", "dmg": "4/6", "wr": "Shock"}, {"name": "Power pick", "atk": 4, "hit": "3+", "dmg": "4/5", "wr": "Rending"}], "abilities": [{"name": "Shadow Vector", "text": "Once per turning point, you can use the Slink Into Darkness or Coiled Serpent firefight ploy for 0CP if the specified friendly WYRMBLADE operative is a NEOPHYTE visible to this operative."}], "actions": [], "keywords": ["WYRMBLADE", "TYRANID", "GENESTEALER CULT", "NEOPHYTE", "LEADER"]},
  {"name": "Kelermorph", "weapons": [], "abilities": [{"name": "Expert Gunslinger", "text": "This operative can perform two Shoot actions during its activation."}, {"name": "Heroic Inspiration", "text": "Whenever a friendly WYRMBLADE NEOPHYTE operative visible to and within 3\" of this operative is shooting, fighting or retaliating, if this operative has incapacitated an enemy operative during this turning point, that friendly operative’s weapons have the Severe weapon rule."}], "actions": [], "keywords": ["WYRMBLADE", "TYRANID", "GENESTEALER CULT", "CULT AGENT", "KELERMORPH"]},
  {"name": "Locus", "weapons": [{"name": "Barbed tail", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 3\", Silent"}, {"name": "Locus blades", "atk": 5, "hit": "3+", "dmg": "4/6", "wr": "Lethal 5+"}], "abilities": [{"name": "Expert Swordsman", "text": "This operative can perform two Fight actions during its activation. Whenever this operative ends the Fight action, if it’s no longer within control range of enemy operatives, it can immediately perform a free Charge action (even if it’s already performed the Charge action during that activation), but it cannot move more than 3\" during that action. Doing so doesn’t prevent it from performing the Dash action afterwards during that activation."}, {"name": "Quicksilver Strike", "text": "Once per turning point, after an enemy operative performs an action in which it moves or is set up, you can interrupt to use this rule. If you do, this operative can immediately perform a free Charge action (you can change its order to do so), but it cannot move more than 3\", and it must end that move within control range of that enemy operative. If this isn’t possible, the interruption is cancelled and this rule hasn’t been used."}, {"name": "Bladed Stance", "text": "Whenever this operative is fighting or retaliating, you can resolve one of your successes before the normal order. If you do, that success must be used to block."}], "actions": [], "keywords": ["WYRMBLADE", "TYRANID", "GENESTEALER CULT", "CULT AGENT", "LOCUS"]},
  {"name": "Neophyte Gunner", "weapons": [{"name": "Flamer", "atk": 4, "hit": "2+", "dmg": "3/3", "wr": "Range 8\", Saturate, Torrent 2\""}, {"name": "Grenade launcher (frag)", "atk": 4, "hit": "4+", "dmg": "2/4", "wr": "Blast 2\""}, {"name": "Grenade launcher (krak)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Piercing 1"}, {"name": "Webber", "atk": 4, "hit": "3+", "dmg": "3/4", "wr": "Range 12\", Severe, Stun"}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [], "actions": [], "keywords": ["WYRMBLADE", "TYRANID", "GENESTEALER CULT", "NEOPHYTE", "GUNNER"]},
  {"name": "Neophyte Heavy Gunner", "weapons": [{"name": "Heavy stubber (focused)", "atk": 5, "hit": "4+", "dmg": "4/5", "wr": "Heavy (Dash only)"}, {"name": "Heavy stubber (sweeping)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Heavy (Dash only), Torrent 1\""}, {"name": "Mining laser", "atk": 5, "hit": "4+", "dmg": "5/6", "wr": "Heavy (Dash only), Piercing 1"}, {"name": "Seismic cannon (long-wave)", "atk": 6, "hit": "4+", "dmg": "2/2", "wr": "Blast 1\", Heavy (Dash only), Stun"}, {"name": "Seismic cannon (short-wave)", "atk": 4, "hit": "3+", "dmg": "4/4", "wr": "Range 6\", Heavy (Dash only), Piercing Crits 1,"}], "abilities": [{"name": "Heavy Weapon Bipod", "text": "Whenever this operative is shooting with a weapon from its datacard, if it hasn’t moved during the activation, or if it’s a counteraction, that weapon has the Ceaseless weapon rule; if the weapon already has that weapon rule (i.e. from the Cult Ambush faction rule), it has the Relentless weapon rule. Note this operative isn’t restricted from moving after shooting."}], "actions": [], "keywords": ["WYRMBLADE", "TYRANID", "GENESTEALER CULT", "NEOPHYTE", "HEAVY GUNNER"]},
  {"name": "Neophyte Icon Bearer", "weapons": [{"name": "Autogun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Shotgun", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Range 6\""}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Icon Bearer", "text": "Whenever determining control of a marker, treat this operative’s APL stat as 1 higher. Note this isn't a change to its APL stat, so any changes are cumulative with this."}, {"name": "Overthrow the Oppressors", "text": "Once per turning point, when a ready friendly WYRMBLADE NEOPHYTE operative is incapacitated while visible to and within 6\" of this operative, you can use this rule. If you do, before that operative is removed from the killzone, it can either perform one free Shoot action (you can change its order to do so), or you can use the A Plan Generations in the Making firefight ploy for 0CP if that incapacitated operative is the specified friendly WYRMBLADE NEOPHYTE operative. It's then removed from the killzone as normal."}], "actions": [], "keywords": ["WYRMBLADE", "TYRANID", "GENESTEALER CULT", "NEOPHYTE", "ICON BEARER"]},
  {"name": "Sanctus Sniper", "weapons": [{"name": "Sanctus sniper rifle (mobile)", "atk": 4, "hit": "3+", "dmg": "3/4"}], "abilities": [], "actions": [{"name": "Target Vulnerability", "ap": 1, "text": "Until the end of this operative’s activation, the stationary profile of its Sanctus sniper rifle has the Lethal 5+ weapon rule.\nThis operative cannot perform this action while within control range of an enemy operative."}, {"name": "Familiar’s Soulsight", "ap": 1, "text": "Select one enemy operative visible to this operative. Until the end of the battle, or until this action is performed again by a friendly operative (whichever comes first), that enemy operative gains one of your Soulsight tokens. Whenever this operative is shooting an enemy operative that has one of your Soulsight tokens, all profiles of this operative's Sanctus sniper rifle have the Saturate weapon rule and that enemy operative cannot be obscured.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["WYRMBLADE", "TYRANID", "GENESTEALER CULT", "CULT AGENT", "SANCTUS", "SNIPER"]},
  {"name": "Sanctus Talon", "weapons": [{"name": "Sanctus bio-dagger", "atk": 4, "hit": "3+", "dmg": "3/6", "wr": "Lethal 4+, Shock"}], "abilities": [{"name": "Creeping Shadow", "text": "This operative can perform the Charge action while it has a Conceal order. Whenever this operative performs the Fight action, it can immediately perform a free Dash or Fall Back action afterwards (for the latter, it cannot move more than 3\"), even if it’s performed an action that prevents it from performing those actions."}], "actions": [{"name": "Assassinate", "ap": 2, "text": "Select one enemy operative this operative isn’t visible to. Perform a free Charge action with this operative, but don't exceed its Move stat (i.e. don't add 2\"), and it must end that move within control range of that enemy operative. Then immediately perform a free Fight action with this operative against that enemy operative. The first time you strike during that action, you can immediately resolve another of your successes as a strike (before your opponent).\nThis operative cannot perform this action while it has an Engage order, or while within control range of an enemy operative."}, {"name": "Familiar’s Soulsight", "ap": 1, "text": "Select one enemy operative visible to this operative. Until the end of the battle, or until this action is performed again by a friendly operative (whichever comes first), that enemy operative gains one of your Soulsight tokens. Whenever this operative is fighting or retaliating against an enemy operative that has one of your Soulsight tokens, its Sanctus bio-dagger has the Brutal and Balanced weapon rules.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["WYRMBLADE", "TYRANID", "GENESTEALER CULT", "CULT AGENT", "SANCTUS", "TALON"]},
  {"name": "Neophyte Warrior", "weapons": [{"name": "Autogun", "atk": 4, "hit": "4+", "dmg": "2/3"}, {"name": "Shotgun", "atk": 4, "hit": "3+", "dmg": "3/3", "wr": "Range 6\""}, {"name": "Gun butt", "atk": 3, "hit": "4+", "dmg": "2/3"}], "abilities": [{"name": "Group Activation", "text": "Whenever this operative is expended, you must then activate one other ready friendly WYRMBLADE WARRIOR operative (if able) before your opponent activates. When that other operative is expended, your opponent then activates as normal (in other words, you cannot activate more than two operatives in succession with this rule).\nNOTES:\nNOTES:"}], "actions": [], "keywords": ["WYRMBLADE", "TYRANID", "GENESTEALER CULT", "NEOPHYTE", "WARRIOR"]},
]
