// Generated from the official team rules PDF. Do not edit by hand — rerun the
// extractor described in CLAUDE.md (‘Where the card data came from’).
import type { Datacard, RefCard } from '../compendium'
import type { Operative } from '../rules'

export const cards: RefCard[] = [
  { kind: 'faction', name: "Stealth Fields", text: "Whenever a friendly XV26 STEALTH BATTLESUIT operative has a Conceal order, it cannot be visible to enemy operatives more than 3\" from it (this takes precedence over all other rules).\nWhenever a friendly XV26 STEALTH BATTLESUIT operative has a Conceal order, it can perform the Fall Back action for 1 less AP." },
  { kind: 'faction', name: "Kauyon", text: "Whenever a friendly XV26 STEALTH BATTLESUIT operative is shooting an enemy operative, its ranged weapons have the Accurate X weapon rule. X is determined by that enemy operative’s location.\nENEMY OPERATIVE LOCATION ACCURATE X\nWithin 3\" of your territory Accurate 1\nWithin your territory Accurate 2\nWithin 3\" of your drop zone Accurate 3" },
  { kind: 'strategy', name: "Patient Hunters", text: "Whenever a friendly XV26 STEALTH BATTLESUIT operative is shooting against or fighting against an expended enemy operative, that friendly operative’s weapons have the Balanced weapon rule and its ranged weapons have the Saturate weapon rule." },
  { kind: 'strategy', name: "Prepare Ambush", text: "Place one of your Ambush markers wholly within your territory and more than 2\" from enemy operatives. Whenever a friendly XV26 STEALTH BATTLESUIT operative is shooting an enemy operative that’s within 2\" of that marker, you can use this rule. If you do, that friendly operative's ranged weapons have the Seek weapon rule until the end of the action. Remove that Ambush marker at the end of that action or in the Ready step of the next turning point (whichever comes first)." },
  { kind: 'strategy', name: "Bonds of Unity", text: "Whenever a friendly XV26 STEALTH BATTLESUIT operative is activated (excluding DRONE), if it's visible to and within 6\" of another friendly XV26 STEALTH BATTLESUIT operative (excluding DRONE), you can ignore any changes to that first friendly operative's APL stat and select one of the following:\n• Ignore any changes to that first friendly operative’s Move stat from being injured until the end of that activation.\n• Ignore any changes to the Hit stat of that first friendly operative’s weapons from being injured until the end of that activation." },
  { kind: 'strategy', name: "Holowave Countermeasures", text: "Whenever an operative is shooting a friendly XV26 STEALTH BATTLESUIT operative more than 6\" from it, in the Roll Attack Dice step, the attacker must discard one of their unresolved normal successes (or one of their critical successes if there are none). This isn’t cumulative with being obscured." },
  { kind: 'firefight', name: "Vectored Retro-thrusters", text: "Use this firefight ploy when an enemy operative ends the Charge action within control range of a friendly XV26 STEALTH BATTLESUIT operative (excluding DRONE). Interrupt that action to use this rule. If you do, that friendly operative can immediately perform a free Fall Back action, but it cannot move more than 3\" during that action. This action cannot be prevented by your opponent’s rules (taking precedence over all such rules). Then, that enemy operative can immediately perform a free Reposition action using any remaining move distance it had from that first Charge action, and can do so even if it’s performed an action that prevents it from performing the Reposition action." },
  { kind: 'firefight', name: "Engage Jet Pack", text: "Use this firefight ploy when a friendly XV26 STEALTH BATTLESUIT operative (excluding DRONE) is activated or counteracts. Until the end of that activation/counteraction, you can ignore the vertical distance it moves during one climb and one drop." },
  { kind: 'firefight', name: "Ghostshroud", text: "Use this firefight ploy at the end of a friendly XV26 STEALTH BATTLESUIT operative’s activation. If that operative has an Engage order, change it to Conceal. You cannot use this ploy for each friendly operative more than once per battle." },
  { kind: 'firefight', name: "Saviour Protocols", text: "Use this firefight ploy when a friendly XV26 STEALTH BATTLESUIT operative (excluding DRONE) is selected as the valid target of a Shoot action. Select one friendly XV26 STEALTH BATTLESUIT DRONE operative visible to and within 3\" of that first friendly operative to become the valid target instead (even if it wouldn’t normally be valid for this). That friendly DRONE operative is only in cover or obscured if the original target was. This ploy has no effect if the ranged weapon has the Blast or Torrent weapon rule." },
  { kind: 'equipment', name: "XV26 Multitrackers", text: "Once per turning point, when a friendly XV26\nSTEALTH BATTLESUIT operative is performing the Shoot action and you select a burst cannon (sweeping), you can use this rule. If you do, select one of the following:\n• Until the end of that action, that weapon has the Torrent 2\" weapon rule.\n• Until the end of that action, that weapon has the Torrent 3\" weapon rule, but you cannot select more than one secondary target." },
  { kind: 'equipment', name: "Advanced Blacksun Filters", text: "Whenever a friendly XV26 STEALTH BATTLESUIT operative is shooting an operative that's obscured, you don't have to discard one success as a result of that rule. All other effects of obscured apply as normal." },
  { kind: 'equipment', name: "Counter-network Jammers", text: "STRATEGIC GAMBIT. Select one objective marker or mission marker. Until the end of the turning point, whenever determining control of that marker, treat the total APL stat of enemy operatives that contest it as 1 lower if at least one of those enemy operatives is within 3\" of friendly XV26 STEALTH BATTLESUIT operatives.\nNote this isn’t a change to the APL stat, so any changes are cumulative with this." },
  { kind: 'equipment', name: "Hardwired Target Locks", text: "Whenever you would counteract, you can do so with one friendly XV26 STEALTH BATTLESUIT operative that has a Conceal order and is more than 3\" from enemy operatives, but before it counteracts, you must change its order to Engage and it cannot perform any actions other than Shoot during that counteraction." },
]

export const operatives: Operative[] = [
  { id: "xv26:xv26-shas-vre", name: "XV26 Shas’vre", apl: 3, move: "6\"", save: "3+", w: 13 },
  { id: "xv26:xv26-designator", name: "XV26 Designator", apl: 3, move: "6\"", save: "3+", w: 12 },
  { id: "xv26:xv26-infiltrator", name: "XV26 Infiltrator", apl: 3, move: "6\"", save: "3+", w: 12 },
  { id: "xv26:xv26-liberator", name: "XV26 Liberator", apl: 3, move: "6\"", save: "3+", w: 12 },
  { id: "xv26:xv26-lodestar", name: "XV26 Lodestar", apl: 3, move: "6\"", save: "3+", w: 12 },
  { id: "xv26:xv26-neutraliser", name: "XV26 Neutraliser", apl: 3, move: "6\"", save: "3+", w: 12 },
  { id: "xv26:mv15-gun-drone", name: "MV15 Gun Drone", apl: 2, move: "6\"", save: "4+", w: 7 },
  { id: "xv26:mv75-marker-drone", name: "MV75 Marker Drone", apl: 2, move: "6\"", save: "4+", w: 7 },
]

export const datacards: Datacard[] = [
  {"name": "XV26 Shas’vre", "weapons": [{"name": "Burst cannon (focused)", "atk": 5, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless"}, {"name": "Burst cannon (sweeping)", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless, Torrent 1\""}, {"name": "Fusion blaster (short range)", "atk": 4, "hit": "4+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Fusion blaster (long range)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Range 12\", Piercing 1"}, {"name": "Pulse pistol (ranged)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Range 8\""}, {"name": "Pulse pistol (point-blank)", "atk": 3, "hit": "4+", "dmg": "4/5", "wr": "Accurate 1"}], "abilities": [{"name": "XV26 Drone Controller", "text": "STRATEGIC GAMBIT whenever this operative is in the killzone. Select one friendly XV26 STEALTH BATTLESUIT DRONE operative in the killzone. Until the end of that operative’s next activation, ignore the first two bullet points of its Drone rule (this takes precedence over that rule)."}, {"name": "For the Greater Good", "text": "Whenever determining the value of Accurate X for the Kauyon faction rule, if this operative is in the killzone, add 1 to the result if 2 or more friendly XV26 STEALTH BATTLESUIT operatives (excluding DRONE) are incapacitated (to a maximum of Accurate 3). Note that you must have a minimum of Accurate 1 to use this rule."}], "actions": [], "keywords": ["XV26 STEALTH BATTLESUIT", "T'AU EMPIRE", "LEADER", "SHAS’VRE"], "img": "/ops/xv26/xv26-shas-vre.webp"},
  {"name": "XV26 Designator", "weapons": [{"name": "Burst cannon (focused)", "atk": 5, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless"}, {"name": "Burst cannon (sweeping)", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless, Torrent 1\""}, {"name": "Fusion blaster (short range)", "atk": 4, "hit": "4+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Fusion blaster (long range)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Range 12\", Piercing 1"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "3/4"}], "abilities": [{"name": "Markerlight", "text": "Whenever an enemy operative is a valid target for this operative, or is visible to this operative and within 2\" of your Ambush marker (see Prepare Ambush strategy ploy), it's marked. Whenever a friendly XV26 STEALTH BATTLESUIT operative is shooting an operative that's marked, that friendly operative’s ranged weapons have the Severe weapon rule. Note that an operative can be a valid target for this operative even if this operative isn't the active operative."}], "actions": [{"name": "Focused Markerlight", "ap": 1, "text": "Select one enemy operative visible to this operative. Once during this turning point, when a friendly XV26 STEALTH BATTLESUIT operative is shooting that enemy operative, you can use this effect. If you do, improve the Hit stat of ranged weapons on that friendly operative’s datacard by 1 until the end of that action.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["XV26 STEALTH BATTLESUIT", "T'AU EMPIRE", "DESIGNATOR"], "img": "/ops/xv26/xv26-designator.webp"},
  {"name": "XV26 Infiltrator", "weapons": [{"name": "Burst cannon (focused)", "atk": 5, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless"}, {"name": "Burst cannon (sweeping)", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless, Torrent 1\""}, {"name": "Fusion blaster (short range)", "atk": 4, "hit": "4+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Fusion blaster (long range)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Range 12\", Piercing 1"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "3/4"}], "abilities": [{"name": "Covert Protocols", "text": "This operative can counteract regardless of its order, but if it has a Conceal order during that counteraction, it cannot perform any actions other than Pick Up Marker, Place Marker or mission actions."}], "actions": [], "keywords": ["XV26 STEALTH BATTLESUIT", "T'AU EMPIRE", "INFILTRATOR"], "img": "/ops/xv26/xv26-infiltrator.webp"},
  {"name": "XV26 Liberator", "weapons": [{"name": "Burst cannon (focused)", "atk": 5, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless"}, {"name": "Burst cannon (sweeping)", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless, Torrent 1\""}, {"name": "EMP bomb", "atk": 5, "hit": "3+", "dmg": "2/2", "wr": "Range 4\", Blast 2\", Devastating 1, Heavy (Reposition only), Lethal 4+, Limited 1, Saturate"}, {"name": "Fusion blaster (short range)", "atk": 4, "hit": "4+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Fusion blaster (long range)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Range 12\", Piercing 1"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "3/4"}], "abilities": [{"name": "Grenadier", "text": "This operative can use frag, krak, smoke and stun grenades (see universal equipment). Doing so doesn’t count towards any limited uses you have (i.e. if you also select those grenades from equipment for other operatives). Whenever this operative is using a frag or krak grenade, improve the Hit stat of that weapon by 1."}], "actions": [], "keywords": ["XV26 STEALTH BATTLESUIT", "T'AU EMPIRE", "LIBERATOR"], "img": "/ops/xv26/xv26-liberator.webp"},
  {"name": "XV26 Lodestar", "weapons": [{"name": "Burst cannon (focused)", "atk": 5, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless"}, {"name": "Burst cannon (sweeping)", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless, Torrent 1\""}, {"name": "Fusion blaster (short range)", "atk": 4, "hit": "4+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Fusion blaster (long range)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Range 12\", Piercing 1"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "3/4"}], "abilities": [{"name": "Electrochaff Launcher", "text": "Once per turning point, when an enemy operative is performing the Shoot action and your opponent selects a valid target (excluding DRONE), you can use this rule, providing this operative isn’t within control range of enemy operatives. If you do, until the end of that action, whenever an enemy operative is shooting a friendly XV26 STEALTH BATTLESUIT operative that’s both visible to and within 3\" of this operative and more than 2\" from that enemy operative:\n• Ignore the Piercing weapon rule. • That friendly operative is obscured."}, {"name": "Homing Beacon", "text": "This operative is carrying your Homing Beacon marker. Operatives (excluding DRONE) can perform the Pick Up Marker action on that marker. The first time an enemy operative performs the Pick Up Marker action on your Homing Beacon marker, discard that marker (remove it from the battle).\nIn the Ready step of each Strategy phase, when you gain CP, if your Homing Beacon marker is placed in the killzone, roll one D6, adding 1 to the result for each objective marker your Homing Beacon marker is within 6\" of. If the result is 5+, you gain 1CP."}], "actions": [], "keywords": ["XV26 STEALTH BATTLESUIT", "T'AU EMPIRE", "LODESTAR"], "img": "/ops/xv26/xv26-lodestar.webp"},
  {"name": "XV26 Neutraliser", "weapons": [{"name": "Burst cannon (focused)", "atk": 5, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless"}, {"name": "Burst cannon (sweeping)", "atk": 4, "hit": "4+", "dmg": "3/4", "wr": "Ceaseless, Torrent 1\""}, {"name": "Fusion blaster (short range)", "atk": 4, "hit": "4+", "dmg": "6/3", "wr": "Range 6\", Devastating 4, Piercing 2"}, {"name": "Fusion blaster (long range)", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Range 12\", Piercing 1"}, {"name": "Fists", "atk": 3, "hit": "4+", "dmg": "3/4"}], "abilities": [{"name": "Multispectrum Sensor Package", "text": "SUPPORT. Once per turning point, when an enemy operative within 8\" of this operative\nis activated, you can use this rule. If you do, each friendly\nXV26 STEALTH BATTLESUIT operative within 3\" of this\noperative can immediately do one of the following:\n• Perform a free Dash action (in an order of your choice). • Change its order.\nEach friendly operative that performs the Dash action cannot end that move within 3\" of an enemy operative. Note that a Comms Device from universal equipment only affects the second distance of this rule."}], "actions": [], "keywords": ["XV26 STEALTH BATTLESUIT", "T'AU EMPIRE", "NEUTRALISER"], "img": "/ops/xv26/xv26-neutraliser.webp"},
  {"name": "MV15 Gun Drone", "weapons": [{"name": "Twin pulse carbine", "atk": 4, "hit": "4+", "dmg": "4/5", "wr": "Ceaseless"}, {"name": "Ram", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [], "actions": [{"name": "Photon Grenade Launcher", "ap": 1, "text": "Select one enemy operative visible to this operative and roll one D6: on a 3+, until the end of that operative’s next activation, subtract 2\" from its Move stat.\nThis operative cannot perform this action while within control range of an enemy operative."}], "keywords": ["XV26 STEALTH BATTLESUIT", "T'AU EMPIRE", "MV15 GUN", "DRONE"], "img": "/ops/xv26/mv15-gun-drone.webp"},
  {"name": "MV75 Marker Drone", "weapons": [{"name": "Ram", "atk": 3, "hit": "5+", "dmg": "2/3"}], "abilities": [{"name": "Markerlight", "text": "Whenever an enemy operative is a valid target for this operative, or is visible to this operative and within 2\" of your Ambush marker (see Prepare Ambush strategy ploy), it’s marked. Whenever a friendly XV26 STEALTH BATTLESUIT operative is shooting an operative that’s marked, that friendly operative’s ranged weapons have the Severe weapon rule. Note that an operative can be a valid target for this operative even if this operative isn’t the active operative."}], "actions": [], "keywords": ["XV26 STEALTH BATTLESUIT", "T'AU EMPIRE", "MV75 MARKER", "DRONE"], "img": "/ops/xv26/mv75-marker-drone.webp"},
]
